### ISSUE TITLE
[Feature request] String ingnore whitespaces strictly

### ISSUE THREAD

**Issue by petromir** [joel-costigliola/assertj-core#1000]
#### Summary
I would like to test if two given string are equal by fully ingnoring all whitespaces.
The current implementation of isEqualToIgnoringWhitespace collapses whitespaces appearing within the strings to a single space before comparison.

#### Example

```java
// Current implementation
String expexted = "ab";
String actual = "a b";
assertThat(actual).isEqualToIgnoringWhitespace(expected) // Returns false

// Can we have another version that does the following
String expexted = "ab";
String actual = "a b";
assertThat(actual).isEqualToIgnoringWhitespaceStrictly(expected) // Returns true
```

**Comment by joel-costigliola** [comment]
[`isEqualToIgnoringWhitespace`](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.8.0-isEqualToIgnoringWhitespace) has changed in 2.8.0/3.8.0, it now does what you expect.
please give it a try and close this issue if you are happy with the behavior.

**Comment by petromir** [comment]
Sorry, I was using 3.6.2. Thanks!
