### ISSUE TITLE
Overload ListAssert varargs methods to take Iterable<ELEMENT>

### ISSUE THREAD

**Issue by Nava2** [joel-costigliola/assertj-core#1001]
#### Summary

Currently, the `ListAssert#containsXXX(...)` methods accept a varargs argument. It would be extremely convenient to accept an `Iterable<? extends ELEMENT>` argument as an overload. 

#### Example

```java
  @Override
  @SafeVarargs
  public final ListAssert<ELEMENT> containsOnly(ELEMENT... values) {
    return super.containsOnly(values);
  }

  @Override
  public final ListAssert<ELEMENT> containsOnly(Iterable<? extends ELEMENT> values) {
    return super.containsOnly(values);
  }
```

#### Java 8 specific ?

NO

**Comment by joel-costigliola** [comment]
It already exists: [containsOnlyElementsOf](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#containsOnlyElementsOf-java.lang.Iterable-).

Maybe we should point this out in the javadoc but I felt that using code completion it would be easy to see `containsOnly` and `containsOnlyElementsOf`.
What do you think  ?

**Comment by Nava2** [comment]
Is there a reason to have the separate naming? I guess I'm used to using things like Hamcrest which have them as overloads. I have no arguments about separate, but adding to the doc would be a great resolution.

**Comment by joel-costigliola** [comment]
the rationale for the naming was that your list does not contain a list but elements.
we will enrich the doc for all flavor of `contains` / `containsElements`

**Comment by joel-costigliola** [comment]
Javadoc enriched.
