### ISSUE TITLE
containsExactlyInAnyOrderElementsOf

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1009]
#### Summary

Variation of `containsExactlyInAnyOrder` with an `Iterable` parameter.
The assertion is named `containsExactlyInAnyOrderElementsOf` for consistency with the API (ex `containsExactlyElementsOf`).

#### Example

```java
// an Iterable is used in the example but it would also work with an array
Iterable<Ring> elvesRings = newArrayList(vilya, nenya, narya, vilya);
Iterable<Ring> elvesRingsSomeMissing = newArrayList(vilya, nenya, narya);
Iterable<Ring> elvesRingsDifferentOrder = newArrayList(nenya, narya, vilya, vilya);

 // assertion will pass
 assertThat(elvesRings).containsExactlyInAnyOrderElementsOf(elvesRingsDifferentOrder);

 // assertion will fail as vilya is contained twice in elvesRings.
 assertThat(elvesRings).containsExactlyInAnyOrderElementsOf(elvesRingsSomeMissing);
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by mkobit** [comment]
Was going to file an issue for this but I glad I found this first. Looking forward to this being in `3.9.0`!
