### ISSUE TITLE
Add CompletionStage assertion

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1010]
#### Summary
AbstractCompletableFutureAssert has methods to run assertions on CompletableFutures.
However, in any given unit test, the given CompletableFuture might not have completed yet, causing the test to be brittle. The exception report can be quite confusing because between the test  failure and the printing of the test error, the future might complete. So even a test asserting isDone() can fail with a message showing a done future.

Coding around this is ugly. Would be real nice if assertj had some waiting (with timeout, with default timeout) function embedded.

Also would be nice if this would work with CompletionStages as well.

Something like
```
CompletionStage<Foo> fooStage = getFoo();
assertThat(fooStage).completesWithin(1000).hasFailedWithThrowableThat()
```

Note: I think the awaitility library could also help, but so far did not use it. Could be this is better solved by using both awaitility and assertj.

**Comment by joel-costigliola** [comment]
@tkruse that is good feedback thanks.

I have created an issue for the confusing error (https://github.com/joel-costigliola/assertj-core/issues/1011) it would be great it you could provide a test case and a better error message if you think it is needed ? 

I think awaitility is great but AssertJ could provide a better future assertions out of the box and leave awaitability for advanced usage.

**Comment by joel-costigliola** [comment]
I have also renamed this issue to focus on `CompletionStage`.

Could you elaborate a bit more on what assertions you would like to see in `CompletionStage` assertions ?

**Comment by tkruse** [comment]
thanks for cleaning up my mess. For CompletionStage, I'd expect the same assertions as for CompletableFuture, I guess, since the latter implements the former. I'll work on reproducing what I see in my project as a PR

**Comment by tkruse** [comment]
In general I would probably change the most current asserts of AbstractCompletableFutureAssert to first check that the future was completed, before asserting anything else. Because most other asserts work on the assumption of completedness.

Then maybe all those methods could be **deprecated**, because developers should never write tests like that (except maybe for isNotDone());

Then I would introduce an intermediate Class CompletedFuture that captures the result of completion after wait. It may contain the result, the exception, or an indication of timeout.

With that, I can imagine a fluent chain like:

```
CompletionStage<Foo> fooStage = getFoo();
CompletedFuture<Foo, Throwable> completed = assertThat(fooStage).completesWithin(1000);
completed.hasFailedWithThrowableThat()
```

Then I would change the interface of most methods to allow for any CompletionStage, and in the asserts starting with something like:
```
if (!actual instanceof CompletedFuture) {
    actual = actual.toCompletedFuture();
}
```
(not literally, consider this psuedo-code).

Note I would also suggest checking how Google Truth does things. I have not checked yet myself.

**Comment by tkruse** [comment]
For google truth, maybe also see this
https://github.com/google/mug/blob/master/core/src/test/java/com/google/mu/util/FutureAssertions.java

**Comment by tkruse** [comment]
Adding one more comment / feedback:


* hasNotFailed() doesn't join so job may not be complete (passes if job is incomplete)
* hasFailedWithThrowableThat() joins so no need to care about unfinished job

Extending the API with wait methods could also include making methods more consistent (or have better naming) about the wait and join behavior

**Comment by PascalSchumacher** [comment]
Implemented in https://github.com/joel-costigliola/assertj-core/commit/5badc3775065ad4041a8b974198b73040d3ad4f6

**Comment by tkruse** [comment]
I'd like this to either be reopened, or for all remaining comments to be settled / moved to own tickets:
* [ ] CompletionStage assertions should provide timeouts such as `assertThat(future).completesWithin(1000)...` to allow testing with multiple threads without uinpredictable race conditions
* [ ] CompletionStage assertions without timeouts such as hasNotFailed() should throw AssertionError when the CompletionStage is not done. Else hasNotFailed() may pass even though the next instant that future fails, causing race conditions and brittle tests.

**Comment by joel-costigliola** [comment]
@tkruse can you create new tickets ? that will make it easier to track

**Comment by tkruse** [comment]
created #1149 and #1150
