### ISSUE TITLE
Some CompletableFuture assertion error message are confusing

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1011]
#### Summary

In any given unit test, the given `Future` might not have completed yet, causing the test to be brittle. The exception report can be quite confusing because between the test failure and the printing of the test error, the future might complete. So even a test asserting `isDone()` can fail with a message showing a done future.

#### Java 8 specific ?

* No : create Pull Request from the `2.x` branch

**Comment by tkruse** [comment]
I created a PR with test to reproduce. Will think on how to improve. 

For the suggested improvement, still thinking. The current report example: 
```
[ERROR]   CompletableFutureAssert_isCompletedExceptionally_Test.should_pass_if_completable_future_will_complete_exceptionally[89] 
Expecting
  <CompletableFuture[Failed: java.lang.RuntimeException]>
to be completed exceptionally
```
should indicate that because this is an assert on a Future, the value shown may be different from the value that failed the assert. And this could include a suggestion to make the test stable by waiting for the async result before asserting.

**Comment by joel-costigliola** [comment]
I think one of the problem here is `StandardRepresentation#toStringOf(CompletableFuture<?> future)` that tries to call `join()` on the future. definitely bad.

I'm thinking that the current assertions check the future at at point in time and the error should represent the future at this same point in time, if that is not possible it should avoid to display the future state later on as it would not be relevant. 

@tkruse thoughts ?

**Comment by tkruse** [comment]
I have not looked at the code causing this yet. Your analysis sounds fine. For the design of the message, I generally think the more information the better, if it can be presented in a non-confusing way.
Not showing the state would hide useful information in most cases. The race condition is an exceptional case.

A workaround would be to call toStringOf() before and after the check, and if the values differ, display them both somehow.

Else a hint that the displayed value might be updated should be good enough.

**Comment by joel-costigliola** [comment]
Interesting, I need to try the workaround to see if it can read nicely, if it does not then adding a warning like "be aware that the description of the future displayed here can different from the one at the moment the assertion was performed" as a the last line of  the end of the error message (if you have a better wording ... mine could certainly be improved)

**Comment by joel-costigliola** [comment]
I don't think it is possible to capture the future description and evaluate it atomically so the best that we can do is to add a warning in the error messages pertaining to future assertions.

**Comment by tkruse** [comment]
I'd prefer the information and a warning / hint.

**Comment by joel-costigliola** [comment]
I'm going with `Be aware that the state of the future in this message might not reflect the one when the assertion was performed as it is evaluated later on`
