### ISSUE TITLE
isSameAs fails incorrectly

### ISSUE THREAD

**Issue by petteyg** [joel-costigliola/assertj-core#1013]
public class Thing {
        private @Interned String name;
        public Thing(@NonNull String name) { this.name = name.intern(); }
        public @Interned String getName() { return name; }
    }

    public class ThingTest {
        private Thing a;
        public void beforeTest() {
             a = new Thing("name");
        }
        public void testName() {
             LoggerFactory.getLogger("logger").info("{}", a.getName() == "name");
             assertThat(a.getName()).isSameAs("name");
        }
    }

The log message "true" appears, but the test fails.

Using TestNG 6.11, assertj 3.6.2

**Comment by petteyg** [comment]
Might be a hardware problem on my end. I can't reliably reproduce it myself.

**Comment by joel-costigliola** [comment]
I'm closing the issue since `isSameAs` is really only performing a `==` comparison.
Please comment on this if you find AssertJ is behaving suspiciously and I'll reopen the issue.
