### ISSUE TITLE
Provide a way to plugin a custom toStringOf

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1016]
#### Summary
I know that one can provide a custom representation and I know about `Assertions#registerFormatterForType(Class, Function)`. However, for both of them one has to manually set them statically in each test.

Wouldn't it be good to have some sort of Service Provider Interface (SPI) that the users can implement and AssertJ can pick it up?

That way one can use something like [`ReflectionToStringBuilder`](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/ReflectionToStringBuilder.html) from `commons-lang`
Maybe there is some way to do it globally, but I have missed it.

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I agree it would be great to have a way to let AssertJ discover formatters (through a SPI), is that possible in plain java without any framework dependency or major plumbery ?

**Comment by filiphr** [comment]
The Java [`ServiceLoader`](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html) should be used for this. 

Discovery looks like this:

```java
Iterator<AssertJCustomFormatter> iterator = ServiceLoader.load(AssertJCustomFormatter.class/*, optionally ClassLoader*/).iterator();
```

The users will only have to define a file named `org.assertj.api.AssertJCustomFormatter` and save it in `META-INF/services` and in the file they need to write the FQN of their implementation(s). 


This can be a different issue as well, but theoretically there can be an SPI for all the configuration options within AssertJ.

**Comment by joel-costigliola** [comment]
Let's try that ! I agree we should provide service loader for other global registration (comparators, filtering stack traces, custom date formats, lenient date parsing, ...) anyhing
