### ISSUE TITLE
Annotate vararg methods using generics with @SafeVarargs

### ISSUE THREAD

**Issue by mihhail-lapushkin** [joel-costigliola/assertj-core#1017]
Otherwise compiler emits warnings:
```
uses unchecked or unsafe operations
```
Compiling with `Xlint` explains the warning:
```
unchecked generic array creation for varargs parameter of type java.util.Map.Entry<? extends java.lang.Object,? extends java.lang.Object>[]
```

For example when calling this method:
`AbstractMapAssert`
```java
  public SELF contains(@SuppressWarnings("unchecked") Map.Entry<? extends K, ? extends V>... entries) {
    maps.assertContains(info, actual, entries);
    return myself;
  }
```
Note: `@SafeVarargs` can be used starting from Java 7

**Comment by joel-costigliola** [comment]
`SafeVarargs` is already used in 2.8.0/3.8.0, see https://github.com/joel-costigliola/assertj-core/blob/d7469cb5dabe8820a797fbb1fb8f7358aa120ff9/src/main/java/org/assertj/core/api/MapAssert.java#L39.

**Comment by mihhail-lapushkin** [comment]
OK, I see. My original problem was with this method:
https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/json/JsonContentAssert.java#L969

I guess they are just using the wrong return type, since `assertThat` returns `MapAssert`.

**Comment by joel-costigliola** [comment]
Yes, `SafeVarargs` works only for final method (sigh), that's why they are not defined in `AbstractMapAssert` which was introduced to let users subclass it.

**Comment by mihhail-lapushkin** [comment]
Got it! Thanks for the help!
I'll close this.
