### ISSUE TITLE
OptionalAssert should have all the methods that the AbstractObjectAssert has

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1021]
#### Summary
It would be good if I can do assertions on the internal value of an `Optional` in the same way as we are doing assertions for objects.

Possible solutions:
* Provide a method that checks if a value is present and returns an `AbstractObjectAssert` back
* Copy all the methods from `AbstractObjectAssert` with names that would make meaningful for `Optional`
* Make sure that `AbstractOptionalAssert` extends `AbstractObjectAssert` and override all methods with a new implementation
* Extract an interface for all the "interesting" methods and make sure that the `AbstractObjectAssert` and `AbstractOptionalAssert` implement the interface. 

#### Example

```java
Optional<MyObject> myObject = new MyObject();

Assertions.assertThat(myObject).isEqualToComparingFieldByField(new MyObject());
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
I think it's confusing to blur the optional assertion with the object assertions, so option 1 is the only valid IMO.
Maybe adding a simple `get()` is enough:
```java
Optional<MyObject> myObject = ...;
assertThat(myObject).get().isEqualToComparingFieldByField(new MyObject());
```
