### ISSUE TITLE
Idea: Make it easier to compare zipped Lists

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1022]
#### Summary
I find myself writing tests for Bean mappers, mapping e.g CustomerOrderDTO to CustomerOrder and similar. Regularly this involves comparing collections. While this can be done with Comparators, comparators have several disadvantages, they only return a number, and they do not make use of fluent APIs (unless someone knows a fluentAPI to create Comparators?).

#### Example

```java
List<AdressDTO> source = generateAdressDTOs();
List<Adress> target = convert(source);
assertThat(source).comparedToOtherSatisfies(target, (AdressDTO dto, Adress adress) -> {
   assertThat(dto.getZipcode() + ' ' + dto.getCity()).isEqualTo(adress.getCityLine())
});
```

Maps would probably also be useful. Not sure what else.

I assume the above can also be achieved using a Comparator<Object> that casts, and returns 0 or throws AssertionException. But that's somewhat ugly...

#### Java 8 specific ?

Not sure if that makes much sense without lambdas...

**Comment by joel-costigliola** [comment]
That is interesting because it is really possible in AssertJ.
I was thinking that  the suggested assertions is actually a matching element by element, I would name the assertion like this (thinking out loud):
```java
assertThat(source).matches(target, (AdressDTO dto, Adress adress) -> {
   assertThat(dto.getZipcode() + ' ' + dto.getCity()).isEqualTo(adress.getCityLine())
});
```

**Comment by tkruse** [comment]
I have no strong opinion about the name, I have not used assertj enough to know what name would fit will in the overall picture. I am amazed how many convenience functions there are already in assertj, sometimes I feel overwhelmed finding the one I need. I cannot yet promise when I will find time to do a PR.

**Comment by tkruse** [comment]
I find that I prefer the satisfies(...) method to the matches(...) methods.
So I would suggest this:
```
@Override
  public <OTHER_ELEMENT> SELF allSatisfy(Iterable<OTHER_ELEMENT> other, BiConsumer<? super ELEMENT, OTHER_ELEMENT> consumer) {
    Iterator<? extends ELEMENT> i1 = actual.iterator();
    Iterator<OTHER_ELEMENT> i2 = other.iterator();
    while (i1.hasNext()) {
      assertThat(i2.hasNext()).isTrue(); // TODO add useful message
      consumer.accept(i1.next(), i2.next());
    }
    assertThat(i2.hasNext()).isFalse(); // TODO add useful message
    return myself;
  }
```

Usage:
```
 @Test
  public void testAllSatisfy() {
    Employee yoda = new Employee(1L, new Name("Yoda"), 800);
    Employee obiwan = new Employee(2L, new Name("Obi"), 800);
    List<Employee> employees = newArrayList(yoda, obiwan);

    EmployeeDTO yodaDTO = new EmployeeDTO("Yoda", 800);
    EmployeeDTO obiwanDTO = new EmployeeDTO("Obi", 800);
    List<EmployeeDTO> employeeDTOs = newArrayList(yodaDTO, obiwanDTO);

    assertThat(employees).allSatisfy(employeeDTOs, (employee, employeeDTO) -> {
      assertThat(employee.getAge()).isEqualTo(employeeDTO.age);
      assertThat(employee.getName().getFirst()).isEqualTo(employeeDTO.name);
    });
  }

  private static class EmployeeDTO {
    public String name;
    public int age;

    public EmployeeDTO(String name, int age) {
      this.name = name;
      this.age = age;
    }
  }
```

**Comment by tkruse** [comment]
And the same for maps, via:
```
public <K2, V2> SELF allSatisfy(Function<K, K2> keyMapper, Map<K2, V2> other, BiConsumer<V, V2> requirements) {
    actual.forEach((k, v) ->
      requirements.accept(v, other.get(keyMapper.apply(k))));
    return myself;
  }

  public <V2> SELF allSatisfy(Map<K, V2> other, BiConsumer<V, V2> requirements) {
    actual.forEach((k, v) ->
            requirements.accept(v, other.get(k)));
    return myself;
  }
```

**Comment by joel-costigliola** [comment]
@tkruse what about `zipSatisfy`?

**Comment by tkruse** [comment]
it's creative and descriptive. Whether users will easily find it (via search or tab completion) I don't know. I think I might type 'satisfy' first and browse through the candidates of my IDE, but that might be just me.

**Comment by joel-costigliola** [comment]
fortunately IDEs are able to show `zipSatisfy` when code completing with `satis...`
