### ISSUE TITLE
Use a more relevant floating point number comparator algorithm

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1025]
#### Summary

http://floating-point-gui.de/errors/comparison/ describes a better way of comparing floating point numbers, Double and Float comparators each have a `complexCloseEnough` method that implements it but they are not yet used.

Let's introduce `DoubleComparator` or `FloatComparator` constructors without parameters to follow the new algorithm but keep `epsilon` with `DoubleComparator(epsilon)` or `FloatComparator(epsilon)` in that case we use the existing algorithm assuming users want to set the comparison precision themselves.

Last point is adding tests as in http://floating-point-gui.de/errors/NearlyEqualsTest.java.

Note that this is a breaking change (a small one thought)

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
:+1: 

What do you think about doing #637 (another small breaking change related to floating point numbers) in the same release?

**Comment by joel-costigliola** [comment]
already done in d251f2c22ee6aecfb1cf9d81066e0247dc34e47b   :flushed:

**Comment by joel-costigliola** [comment]
Well the algorithm does not work for x, y, epsilon where x=0 and y=epsilon which is a bit too unexpected IMO.

Guava [fuzzyCompare](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/math/DoubleMath.html#fuzzyCompare(double,%20double,%20double)) may be an option but it is not transitive and then not suitable for use in `Object.equals(java.lang.Object)` implementations according to Guava authors.

At this point I'm not sure if there is any possible good enough default implementation and it might really be that the only option is to let users come with their own implementation.

**Comment by joel-costigliola** [comment]
I'm closing this issue because there is no obvious solution to compare floats or doubles, this is not an easy topic and if such an algorithm existed it would have implemented already. 

Although  http://floating-point-gui.de/errors/comparison/ propose an interesting algorithm, it is not simple for users to decide how to set `epsilon`.

As a conclusion we leave users implement the float/double comparator algorithm that suits best their own use cases.

**Comment by joel-costigliola** [comment]
I have kept my exploration in `better-real-numbers-comparators` in case of we want to follow up on the topic.
