### ISSUE TITLE
Assertions#byLessThan bug?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#1028]
I expected:

```java
assertThat(10.1).isCloseTo(10.0, byLessThan(0.1));
```
but it succeeds.

**Comment by joel-costigliola** [comment]
it passes for me :thinking: ... is that a floating precision issue ?

**Comment by PascalSchumacher** [comment]
Well it passes for me, but I think that is the problem. I expected `byLessThan` to be exclusive, e.g. fail if the offset is the specified value.

**Comment by joel-costigliola** [comment]
That's a fair point, `byLessThan` being an alias of `offset` and `within` it shares their behavior but to be consistent with `isLessThan` assertion I think it should be a strict comparison (moreover there is no way to perform strict comparisons currently).
It is a breaking change but an acceptable one  as it is small users can switch to `within/offset` if they wan to keep the old behavior.

**Comment by joel-costigliola** [comment]
this was more javadoc work than I expected !

**Comment by PascalSchumacher** [comment]
fixed by Joel in https://github.com/joel-costigliola/assertj-core/commit/e23f664b2deb27a862ab18aed3e6a1e6022c05d2
