### ISSUE TITLE
Idea: allSatisfy for Maps

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1030]
Provide MapAsserts.allSatisfy()

I believe currently this is missing for assertions like:
```
Employee emperor = new Employee(2L, new Name("Sheev", "Palpatine"), 26);
Map<String, Company> customerMap = Maps.newHashMap("imperium",
            new Company(Arrays.asList(emperor), "imperium", null));

    assertThat(customerMap)
            .allSatisfy((name, customer) -> {
              assertThat(name).isNotBlank();
              assertThat(customer.getEmployees())
                                      .allSatisfy(e -> assertThat(e.getAge()).isBetween(20, 30)));
            });
```
IterableAsserts already has something similar.

The alternative using the entry set has the slight disadvantage of not showing the types / semantics of the map entries:
```
assertThat(customerMap.entrySet())
            .allSatisfy(entry -> {
              assertThat(entry.getKey()).isNotBlank();
              assertThat(entry.getValue().getEmployees())
                                      .allSatisfy(e -> assertThat(e.getAge()).isBetween(20, 30)));
            });
```

I mean `map.allSatisfy((name, customer) -> { assertThat(customer)` is easier to read than `map.entrySet().allSatisfy(entry -> {assertThat(entry.getValue())`

**Comment by joel-costigliola** [comment]
I am definitely in favor of the first option where a pair of parameters is passed.

**Comment by joel-costigliola** [comment]
I'm not sure to get the `fieldSatisfies` part though.

**Comment by tkruse** [comment]
sorry, the fieldSatisfies was just a personal experiment. It did not bring sufficient benefit though. I forgot it was in the examples. Removing it.
