### ISSUE TITLE
add flatExtracting for map

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1034]
#### Summary

`Iterable` assertions provide `flatMap` extraction but map assertions don't, it was suggested in:
https://stackoverflow.com/questions/45081542/assertj-flatmap-list-of-lists-after-calling-extracting

#### Example

```java
Map<String, List<String>> testMap  = new HashMap<>();
List<String> nameList = newArrayList("Dave", "Jeff");
List<String> jobList = newArrayList("Plumber", "Builder");
List<String> cityList = newArrayList("Dover", "Boston");

testMap.put("name", nameList);
testMap.put("job", jobList);
testMap.put("city", cityList);

assertThat(testMap)
        .flatExtracting("name", "city", "job")
        .contains("Dave", "Jeff", "Plumber", "Builder", "Dover", "Boston");
```

#### Java 8 specific ?

* YES : to lambda part (PR on master)
* NO  : when extracting by keys (PR on 2.x)

**Comment by dafenix** [comment]
Hello there,

i am looking at this.

**Comment by Vidit-Gupta** [comment]
@joel-costigliola This looks pretty sweet. However this would not let you check all unique elements if I understand correctly, no?
For example if I have
```
class A {
 List<Name> names()
}
A[] = {new A("foo", "bar"), new A("foo")}
```
then applying flatExtracting on A::names I cannot check that it contains exactly ["foo", "bar"] can I?

**Comment by PascalSchumacher** [comment]
`flatExtracting` returns an `AbstractObjectArrayAssert`. You can use all methods provided by this assertion, e.g. `containsExactly`, see: https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectArrayAssert.html#containsExactly-ELEMENT...-

**Comment by Vidit-Gupta** [comment]
@PascalSchumacher `assertThat(ImmutableList.of("a", "a", "b")).containsExactly("a", "b")` will fail.
What I'm saying is flatExtracting gives me back that list with duplicates (["a", "a", "b"]) hence I cannot use it

**Comment by PascalSchumacher** [comment]
Not sure if I'm understand you correctly, but if you want to check all unique elements you can use:

```java
String[] abc = {"a", "a", "b"};
assertThat(abc).containsOnly("a", "b")
```

If you also want to check the order of unique elements you can use:

```java
 String[] abc = {"a", "a", "b"};
 assertThat(abc).containsOnly("a", "b").containsSubsequence("a", "b");
```
