### ISSUE TITLE
AbstractSoftAssertions.errorsCollected() modifies error list

### ISSUE THREAD

**Issue by nebehr** [joel-costigliola/assertj-core#1036]
The code in the public method AbstractSoftAssertions.errorsCollected() (https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractSoftAssertions.java#L104) modifies error list by changing their messages, even though the list itself is immutable.

**Comment by joel-costigliola** [comment]
@nebehr it does modify the elements in the list but not the list itself, have you encountered a problem because of that ?

**Comment by nebehr** [comment]
Yes, I am trying to find a way to perform some additional actions on soft assertion failure. One of the methods I thought might help was errorsCollected(), but it turns out that it prepends extra line to each error on each call, which renders it unusable, especially since it is a public method.

**Comment by joel-costigliola** [comment]
what type of action ?

**Comment by nebehr** [comment]
Basically, a screenshot for every soft failure, which would then be associated with corresponding throwable. There is actually no straightforward way to achieve it with current architecture but it is irrelevant to this here issue.

**Comment by joel-costigliola** [comment]
I believe you can use reflection to access the `proxies` field and then invoke `errorsCollected()`.
Otherwise I don't mind exposing a raw `errorsCollected()` if that is a condition to your happiness :wink:

**Comment by nebehr** [comment]
Well, a lot of things can be achieved via reflection and package spoofing but would it be a good practice? :) In the end I don't think ```errorsCollected()``` will help me in my particular case, it's just that it was unexpected and kind of contradictory that a "getter" method should mangle the data it retrieves.

**Comment by joel-costigliola** [comment]
well getters are not forced to exactly represent the field they are exposing but I guess that's a matter of opinion.
ok for me to close this issue ?

**Comment by nebehr** [comment]
This is true, getters may provide a modified view of the field as long as they do not *actually* modify that field. In other words, two subsequent calls to the same getter should give exactly the same result (if this field has not been changed by some other agent in the meantime). Which is not the case here. If, for whatever reason, this "getter" is called ten times (and there is nothing to prevent it since it is part of public API) you end up with ten similar error messages attached to each stacktrace. In my opinion this is a serious design flaw but YMMV.

**Comment by joel-costigliola** [comment]
I agree, I did not realize that the field was changed, I'll see if we can change that.
