### ISSUE TITLE
Misleading Javadoc comment for Strings.assertBlank

### ISSUE THREAD

**Issue by christoph-schneegans** [joel-costigliola/assertj-core#1037]
#### Summary
In AssertJ 3.8.0, the Javadoc comment for the method org.assertj.core.internal.Strings.assertBlank(AssertionInfo, CharSequence) reads as follows:

`Asserts that the given {@code CharSequence} is {@code Null}, empty or contains only whitespace.`

This comment does not reflect the actual behavior of the method. The Javadoc comment should rather read as follows:

`Asserts that the given {@code CharSequence} consists of one or more whitespace characters.`

Likewise, the Javadoc comment for the method org.assertj.core.internal.Strings.assertNotBlank(AssertionInfo, CharSequence) is misleading as well. It should read as follows:

`Asserts that the given {@code CharSequence}  is {@code Null}, empty or contains at least one non-whitespace character.`

**Comment by PascalSchumacher** [comment]
Thanks for reporting. :+1: 

This will be fixed in 2.9.0/3.9.0.
