### ISSUE TITLE
NullPointerException in assertThat.extracting when actual object is null

### ISSUE THREAD

**Issue by rherrmann** [joel-costigliola/assertj-core#1041]
#### Summary
When using `assertThat` followed by `extracting` and the actual array or collection is null, AssertJ throws a NullPointerException.

```
java.lang.NullPointerException
	at org.assertj.core.groups.FieldsOrPropertiesExtractor.extract(FieldsOrPropertiesExtractor.java:54)
	at org.assertj.core.groups.FieldsOrPropertiesExtractor.extract(FieldsOrPropertiesExtractor.java:44)
	at org.assertj.core.api.AbstractObjectArrayAssert.extracting(AbstractObjectArrayAssert.java:1225)
        ...
```
While I think this is not a major issue because the assertion would fail anyway, it is inconsistent compared to using `assertThat` without extracting. In this case, an AssertionError "Expecting actual not to be null" is raised.

#### Example
```java
  class Foo {
    Object bar;
  }

  @Test
  public void testAssertThatExctractedContains() {
    Foo expectedFoo = new Foo();
    Foo[] actualFoos = null;
    assertThat( actualFoos ).contains( expectedFoo );
  }
```

#### Java 8 specific ?
No

**Comment by joel-costigliola** [comment]
I agree, it is nicer to have an `AssertionError` instead of an NPE.
Thanks for the nicely reported issue !

**Comment by joel-costigliola** [comment]
Fix thanks to @mle-enso.
