### ISSUE TITLE
Refactor primitive array tests

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1043]
#### Summary

Primitive array tests can simplified, there is quite a bit of duplication that can be removed. 

#### Example

Let's take `IntArrays_assertContains_Test`, instead of verifying that `IntArrays` delegates to `Arrays` it tests all the possible `assertContains` use cases, these tests  should be moved to `Arrays` tests as it actually implement `assertContains` assertion logic.

The duplication comes from `LongArrays_assertContains_Test`, `FloatArrays_assertContains_Test` that do the same thing testing `assertContains` assertion logic  again and again.

A better approach is the one taken with `IntArrays_assertContainsAnyOf_Test` where the assertion logic tests are written in `Arrays_containsAnyOf_Test`, the only test in `IntArrays_assertContainsAnyOf_Test` being `should_delegate_to_internal_Arrays`

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
done in https://github.com/joel-costigliola/assertj-core/pull/1055
