### ISSUE TITLE
Ambiguous assertThat with custom type

### ISSUE THREAD

**Issue by jolivares** [joel-costigliola/assertj-core#1045]
#### Summary
I cannot use `Assertions.assertThat` with my custom ID class. It complains about ambiguous method: _The method assertThat(IDTest.ID) is ambiguous for the type Assertions_

#### Example

```java
import org.assertj.core.api.Assertions;
import org.junit.Test;

public class IDTest {

	public static class ID implements CharSequence, Comparable<ID> {

		@Override
		public int compareTo(ID o) {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public int length() {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public char charAt(int index) {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public CharSequence subSequence(int start, int end) {
			// TODO Auto-generated method stub
			return null;
		}
	}

	@Test
	public void test() {
		ID id = new ID();

		Assertions.assertThat(id); // The method assertThat(IDTest.ID) is ambiguous for the type Assertions
	}
}
```

The only way to workaround it is by casting the id to something like Object, CharSequence, ... which is kind of dirty hack:
```
Assertions.assertThat((Object) id).isEqualTo(id);
```
Any idea how to fix it?

#### Java 8 specific ?
NO

**Comment by joel-costigliola** [comment]
No elegant way unfortunately it's one of these rare case when a class inherit two types that AssertJ provides assertions for.
You could try to create a custom assertion `IDAssert` class with an `assertThat` factory method, I think it would be picked up in place of the ambiguous `Assertions.assertThat` (but not 100% sure as I haven't tried).

**Comment by joel-costigliola** [comment]
@jolivares feel free to ask to reopen the issue it you find a better approach to this issue.
