### ISSUE TITLE
return type of `extracting` seems to be wrong in the presense of wildcard generics

### ISSUE THREAD

**Issue by schauder** [joel-costigliola/assertj-core#1056]
This 

```java
List<Object> numbers = Arrays.asList("String", 23);
assertThat(numbers).extracting(n -> n.getClass()).containsExactly(String.class, Integer.class);
```
does not compile, although I think it should:

    no suitable method found for containsExactly(java.lang.Class<java.lang.String>,java.lang.Class<java.lang.Integer>)
     method org.assertj.core.api.ObjectEnumerableAssert.containsExactly(java.lang.Class<capture#1 of ? extends java.lang.Object>...) is not applicable
       (varargs mismatch; java.lang.Class<java.lang.String> cannot be converted to java.lang.Class<capture#1 of ? extends java.lang.Object>)
     method org.assertj.core.api.AbstractIterableAssert.containsExactly(java.lang.Class<capture#1 of ? extends java.lang.Object>...) is not applicable
       (varargs mismatch; java.lang.Class<java.lang.String> cannot be converted to java.lang.Class<capture#1 of ? extends java.lang.Object>)

The following does work and qualifies as a workaround: 

```java
assertThat(numbers).extracting(n -> (Class)n.getClass()).containsExactly(String.class, Integer.class);
````

**Comment by joel-costigliola** [comment]
I don't have a clean solution for that, your workaround is ok.
The only way to solve this issue would be to remove generics in `containsExactly` but I'm not sure users are ok with that.

**Comment by schauder** [comment]
I came to the same conclusion :-/

I guess closing the issue as `won't fix` is fine.

**Comment by joel-costigliola** [comment]
I will do a poll at some point to see if users are ok to get rid of generics, we had a few other issues like yours.
