### ISSUE TITLE
New feature request -  .withFailMethod() to run a method if the test fails

### ISSUE THREAD

**Issue by prrk47002** [joel-costigliola/assertj-core#1057]
#### Summary
We are trying to move to using assertJ for our automated tests and integrate it cleanly with ExtentReports.  What is needed is a way to call a method when an assertion fails, similar to the .withFailMessage().

#### Example

```java
public void myMethod(Method m){
    report = new ExtentReports("filename");     
    test = report.startTest("testName");

   String actual = "sssssss";
   String expected = "xxxxxxxx";

    // what I can do with AssertJ id have a nice readable test
    assertThat(actual).isEqualTo(expected).withFailMessage("BOINK!");

    // what I can do with ExtentReports
    if (!actual.equals(expected)) test.log(LogStatus.FAIL, "BOINK");

    // what I want to extend assertJ to do
    assertThat(actual).isEqualTo(expected).extentLog(test, LogStatus.FAIL, "BOINK");
}
```

#### Java 8 specific ?
Yes. we are coding automation tests in Java 8
* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

Thank you Joe for your response on StackOverflow.
I'll put this in as an enhancement request.

**Comment by joel-costigliola** [comment]
It is not possible to implement your enhancement because as soon as you have an assertion error the next chained call is not performed due to the thrown `AssertionError`.

**Comment by joel-costigliola** [comment]
@prrk47002 would https://github.com/joel-costigliola/assertj-core/issues/1040 work for you ?

**Comment by prrk47002** [comment]
Joel:  
    Thanks for the quick response, I'm new to assertJ, and see I had the assertions out of order.

I'll take a look at #1040 as soon as I can, but that probably won't be after vacation (2+ weeks in Europe).

**Comment by joel-costigliola** [comment]
Closing this issue but happy to reopen it after additional feedback is provided.
