### ISSUE TITLE
Comparing equal binary files fails with java.nio.charset.MalformedInputException

### ISSUE THREAD

**Issue by michael-schnell** [joel-costigliola/assertj-core#1059]
Comparing equal binary files fails with a "java.nio.charset.MalformedInputException: Input length = 1" exception. Method that fails: "FileAssert.hasSameContentAs(java.io.File)".

This is actually caused by a wrong 'fall back' in the 'org.assertj.core.internal.Files' class:
```Java
BinaryDiffResult binaryDiffResult = binaryDiff.diff(actual, readAllBytes(expected.toPath()));
if (binaryDiffResult.hasNoDiff()) {
    // fall back to the RuntimeIOException : not throwing an error is wrong as there was one in the first place.
   throw e;
}
```
In fact this only means the both files are binary qual and it should be:
```Java
BinaryDiffResult binaryDiffResult = binaryDiff.diff(actual, readAllBytes(expected.toPath()));
if (binaryDiffResult.hasNoDiff()) {
   // Both files are binary equal
   return;
}
```
I added a [pull request](https://github.com/joel-costigliola/assertj-core/pull/1060) with the fix and added a test.

**Comment by joel-costigliola** [comment]
This case was meant to address the rare case when you have identical files you can't read with the given charset which is why the Travis CI build failed on your PR: 
```
[ERROR]   Files_assertSameContentAs_Test.should_throw_an_error_if_files_cant_be_compared_with_the_given_charsets_even_if_binary_identical Expected test to throw (an instance of org.assertj.core.api.exception.RuntimeIOException and exception with message a string starting with "Unable to compare contents of files")
```
Your issue is relevant, I think the correct solution here is to introduce a binary file comparison that would directly perform a binary diff, I would name the assertion: `hasSameBinaryContentAs`

If you agree with and have the time to do so, can you modify your PR to introduce such a method ?

**Comment by michael-schnell** [comment]
Maybe a better check would be something like file ".hasCharSet(Charset)". 

The test case method "should_throw_an_error_if_files_cant_be_compared_with_the_given_charsets_even_if_binary_identical()" already states exactly that it's about looking for a char set and not if the files are identical.

So basically "assertSameContent(File)" means "Are the files are identical?" and not "Do they have charset X?'.

The problem is also that one of the last changes lead to that error. Before the method worked fine also for binary files. This stopped working when the charset stuff was introduced.

**Comment by joel-costigliola** [comment]
> Maybe a better check would be something like file ".hasCharSet(Charset)".

I'm not sure to understand, can you clarify ?  with an example maybe.

> `assertSameContent(File)` means "Are the files are identical?" 

You can have files with same textual content encoded in different charset, in that case they are not binary equals / identical but their logical contents are the same. Conversely it is possible (but unlikely) to have binary equals files with different textual content.

I'm ok not to rethrow the exception but only  if the charset were the same.

I think though it would be valuable to have an `hasSameBinaryContentAs` assertion as it would be explicit that the comparison  does not involve charsets.

**Comment by michael-schnell** [comment]
Hmmm... Maybe it's best to deprecate the "assertSameContent(File)" method in favor of two new methods:

- assertSameTextContentsAs(File) - As already suggested in [pull request 574](https://github.com/joel-costigliola/assertj-core/pull/574)
- hasSameBinaryContentAs(File)

The deprecated "assertSameContent(File)" method will stay the same and will simply be delegated to the new "assertSameTextContentsAs(File)".

What do you think?

**Comment by joel-costigliola** [comment]
I agree with deprecating `hasSameContentAs` for `hasSameTextualContentAs` and adding `hasSameBinaryContentAs` - no ambiguity !

**Comment by ngeor** [comment]
Hello, I was going over some old issues to see if I can help with something and this looked like a low hanging fruit. I pushed a commit on my branch without tests/docs yet. If this is still needed, I can continue.

**Comment by joel-costigliola** [comment]
@ngeor yes this is still relevant, thanks

**Comment by ngeor** [comment]
One Travis job failed with:

```
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk13" --workspace "/home/travis/.cache/install-jdk" --feature "13" --license "GPL" --cacerts" failed and exited with 7 during .
```

can you maybe help me with that? Other than that the PR is open and waiting for your feedback :)

**Comment by joel-costigliola** [comment]
Don't worry about it, we have regular errors with that script, it is usually temporary, I'm restarting the build right now

**Comment by joel-costigliola** [comment]
ok I can't restart the build for PR :(
