### ISSUE TITLE
API changes review for AssertJ Core

### ISSUE THREAD

**Issue by lvc** [joel-costigliola/assertj-core#1061]
The report on API changes/backward compatibility for the AssertJ Core library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/assertj-core/

The report is updated 3 times a week (Mon, Wed, Fri). Hope it will be helpful for users and maintainers of the library.

The report is generated by https://github.com/lvc/japi-compliance-checker and https://github.com/lvc/japi-tracker tools.

Thank you.

![assertj-1](https://user-images.githubusercontent.com/1517837/29508926-787cceec-8667-11e7-8c16-4a57420374c9.png)
![assertj-2](https://user-images.githubusercontent.com/1517837/29508937-7e520080-8667-11e7-82f7-0a4d2617a878.png)

**Comment by filiphr** [comment]
This is really interesting. However, by looking at the report I would say that it is wrong. 

First of all the comparison between 2.x and 3.x releases should be done by comparing 2.x with 3.x. For example 2.1.0 and 3.1.0. The reason for that is that the 3.x release track is everything from the 2.x plus Java 8. Also 2.8.0 is newer than 3.7.0 for example. You can also see that trend on the graphic as well.

I also think that the checks are wrong. If you see some of the removed methods, you'll see that the only difference in the is the name of the generic parameter. That is not an incompatibility, you already have https://github.com/lvc/japi-compliance-checker/issues/38 for it

**Comment by lvc** [comment]
Removed 2.x from the report. Started working on https://github.com/lvc/japi-compliance-checker/issues/38.

Thank you!

**Comment by lvc** [comment]
The issue with generic parameters has been fixed in master of the https://github.com/lvc/japi-compliance-checker tool. Reports have been regenerated: https://abi-laboratory.pro/java/tracker/timeline/assertj-core/

Thank you.

![assertj-core-3](https://user-images.githubusercontent.com/1517837/29634120-cf2a2cdc-8859-11e7-8907-0075b09175d0.png)
![assertj-core-4](https://user-images.githubusercontent.com/1517837/29634124-d343631a-8859-11e7-85c7-9162e6f0647c.png)

**Comment by joel-costigliola** [comment]
That looks nice ! :+1:  
Is there a way to drill down to see what the incompatible changes are ?

**Comment by lvc** [comment]
@joel-costigliola, just click on the interested links in the report: https://abi-laboratory.pro/java/tracker/timeline/assertj-core/

See https://wiki.eclipse.org/Evolving_Java-based_APIs_2 for more info.

**Comment by joel-costigliola** [comment]
Thanks for the report.
