### ISSUE TITLE
Check for list containing only null values

### ISSUE THREAD

**Issue by bobmarks** [joel-costigliola/assertj-core#1062]
#### Summary

Would be nice to have the ability to check a list / collection for only `null` values

Based from stackoverflow article (https://stackoverflow.com/questions/45795956/assertj-check-list-contains-x-items-but-are-all-null)

#### Example

```java
List<String> items= Arrays.asList(null, null, null);
assertThat(items).hasSize(3).containsOnlyNulls();
```
> **Note** - `containsOnlyNulls` (or something suitably named) doesn't currently exist!

#### Java 8 specific ?

Don't think so.

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Thanks for reporting this @bobmarks.

**Comment by BillyYccc** [comment]
Great Idea! I'm trying to work on it.

**Comment by bobmarks** [comment]
Awesome stuff guys!

**Comment by AndreiYu** [comment]
Is there an option to assert that list contains "not only" specific value (for ex. null, "",0 ) but any other values

**Comment by joel-costigliola** [comment]
can you give a concrete example ?

**Comment by PascalSchumacher** [comment]
@AndreiYu you can use ` assertThat(Arrays.asList("1")).doesNotContain("", "0").isNotEmpty();`

**Comment by onacit** [comment]
Did we have a discussion for failing when the list is empty? I just started on via #2595.
