### ISSUE TITLE
Rename String containsSequence to containsSubsequence and add a proper containsSequence

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1064]
#### Summary

[String containsSequence](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractCharSequenceAssert.html#containsSequence(java.lang.CharSequence...)) should be renamed to  `containsSubsequence` since its behaviour is actually `containsSubsequence` and add a proper `containsSequence`

#### PR

Since there is nothing specific to Java 8, the Pull Request should be created from the `2.x` branch

**Comment by BillyYccc** [comment]
I will take a look at this.
