### ISSUE TITLE
Add isEqualToIgnoringNewLines

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1067]
#### Summary
I want to compare 2 strings by ignoring the new lines.

#### Example

```java
String actual = "Some text\nWith new lines";
String expected = "Some textWith new lines";
String notExpected = "Some text With new lines";

// should pass
assertThat(actual).isEqualToIgnoringNewLines(expected);

// should fail
assertThat(actual).isEqualToIgnoringNewLines(notExpected);
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by dafenix** [comment]
Hello there,
i will look at this.

**Comment by joel-costigliola** [comment]
@dafenix  @filiphr I think we also ignore new lines in the expected value to be consistent with `isEqualToNormalizingNewlines`, thoughts ?

**Comment by filiphr** [comment]
@joel-costigliola yes that would be the expectation. I think we need something like `String.replace("\r?\n", "")` on both the actual and expected (normalizing is done on both sides I think).

**Comment by dafenix** [comment]
If i get right normalizing like in `isEqualToNormalizingNewlines` is not sufficient. The main difference vs  `isEqualToIgnoringNewLines` and `assertIsEqualToNormalizingNewlines` lies in test case `should_fail_if_newlines_are_different_in_both_strings`. In case of `isEqualToIgnoringNewLines` this test should pass. @joel-costigliola I will change the code as you have suggested.

**Comment by joel-costigliola** [comment]
@dafenix are you working on this?

**Comment by dafenix** [comment]
@joel-costigliola sorry i think i missed to reference the issue id when i commited my changes. 

See 
https://github.com/joel-costigliola/assertj-core/pull/1089/files `src/main/java/org/assertj/core/internal/Strings.java` lines 894-895 and  901-902.

`Strings_assertEqualsToIgnoringNewLines_Test.java` test case `should_pass_if_both_texts_contain_new_lines_of_any_kind`

Did you mean this?

**Comment by joel-costigliola** [comment]
Yes, my bad :man_facepalming: :smile:
