### ISSUE TITLE
usingComparatorForFields doesn't work in combination with isEqualToComparingFieldByFieldRecursively

### ISSUE THREAD

**Issue by DavidRigglemanININ** [joel-costigliola/assertj-core#1092]
#### Summary
Maybe my expectations of how this should work are incorrect, but if I am declaring to compare properties recursively, then I would have expected that specifying a comparator should work for all properties at any level. If this functionality is not supported, is there any way workaround.

#### Example

```java
class Foo {
    Bar bar;

    Foo(Bar bar) {
        this.bar = bar;
    }
}

class Bar {
    String id;
     int value;

    Bar(String id, int value) {
        this.id = id;
        this.value = value;
    }
}

@Test
public void testEquality() {
    Foo foo1 = new Foo(new Bar("1", 1));
    Foo foo2 = new Foo(new Bar("2", 1));
    Comparator<String> comparator = (String o1, String o2) -> 0;
    assertThat(foo1)
        .usingComparatorForFields(comparator, "id")
        .isEqualToComparingFieldByFieldRecursively(foo2);

    // expecting assert to succeed, but currently fails
}
```

**Comment by joel-costigliola** [comment]
It fails because fields need to be declared from the root object, i.e. `"bar.id"`, something that is missing in the javadoc.

**Comment by DavidRigglemanININ** [comment]
That makes sense. I tried it in my actual more complicated example and it solved my problem. Thanks for the quick response

**Comment by joel-costigliola** [comment]
happy to help :) I'm closing this issue and will update the javadoc to clarify that point.
