### ISSUE TITLE
Suggestion: reformat LICENSE in file header

### ISSUE THREAD

**Issue by BillyYccc** [joel-costigliola/assertj-core#1094]
#### Summary
As I create new files in assertj-core, and when I add the LICENSE in file header I find the LICENSE at present is like 
 /**
\*   LICENSE Content
 */
which is the form of Javadoc?
I use IntelliJ IDEA LICENSE template to generate LICENSE Header like this:
/\*
 \*     LICENSE Content
  */
this way is more convenient and maybe this form is the right one?

Do you think there is any necessity to reformat LICENSE in file header? @joel-costigliola 

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
I believe the merge of https://github.com/joel-costigliola/assertj-maven-parent-pom/pull/21 would result in the change described above.

**Comment by joel-costigliola** [comment]
Will merge the PR soonish

**Comment by PascalSchumacher** [comment]
done be Joel in https://github.com/joel-costigliola/assertj-core/commit/cc178abc5871bc34525113550373ffd90e303034
