### ISSUE TITLE
Tests for custom assertions

### ISSUE THREAD

**Issue by ltennstedt** [joel-costigliola/assertj-core#1098]
Hello,

maybe I missed it or this is not the right place to ask my question.

Can someone give me a hint how unit tests for custom assertions could be written?

Thanks in advance for your time!

Greetings
Lars

**Comment by joel-costigliola** [comment]
I suggest to look at the documentation: http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html and the [assertj-examples tests](https://github.com/joel-costigliola/assertj-examples/tree/master/assertions-examples/src/test/java/org/assertj/examples).

Hope it helps

**Comment by joel-costigliola** [comment]
@ltennstedt  comment or ask the mailing list if you need more help
