### ISSUE TITLE
Add `isUpperCase()` and `isLowerCase` to `AbstractCharSequenceAssert`

### ISSUE THREAD

**Issue by marceloverdijk** [joel-costigliola/assertj-core#1106]
#### Summary

Add `isUpperCase()` and `isLowerCase` to `AbstractCharSequenceAssert`.
Just like `AbstractCharacterAssert ` also has these.

#### Example

```java
assertThat("ABC").isUpperCase(); // --> currently not possible

assertThat('A').isUpperCase(); // --> currently already possible
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Sure no problem.
Do you want to contribute ?

**Comment by marceloverdijk** [comment]
Yes fine, I will create a PR later.

**Comment by marceloverdijk** [comment]
ShouldI take the `master` branch as basis?

**Comment by marceloverdijk** [comment]
I created PR #1107 for this.
