### ISSUE TITLE
Introduce XPath like assertions

### ISSUE THREAD

**Issue by gualtierotesta** [joel-costigliola/assertj-core#111]
It would quite useful to have XPath like assertions (similar to what it is available in XMLUnit but with a fluent interface of course :-) )

For example:

    String mySolarSystemXML = "<solar-system><planet name='Earth' position='3' supportsLife='yes'/><planet name='Venus' position='4'/></solar-system>";

    assertXpathExists("//planet[@name='Earth']", mySolarSystemXML);

    assertXpathNotExists("//star[@name='alpha centauri']",
                         mySolarSystemXML);

    assertXpathsEqual("//planet[@name='Earth']",
                      "//planet[@position='3']", mySolarSystemXML);

    assertXpathsNotEqual("//planet[@name='Venus']",
                         "//planet[@supportsLife='yes']",
                         mySolarSystemXML);

[Example from http://xmlunit.sourceforge.net/userguide/html/index.html#Xpath%20Tests ]

**Comment by j-maly** [comment]
My own take on XML validation: https://github.com/j-maly/SchematronAssert (based on AssertJ).

**Comment by PascalSchumacher** [comment]
There is also xmlunit2: https://github.com/xmlunit/xmlunit

@joel-costigliola You closed the pull request for this issue with: 

>I'm closing this issue but I might reconsider if a contributor wants to spend time on it.

I guess you also meant close this issue?

**Comment by joel-costigliola** [comment]
yes, main reason is because XML Unit 2 is actively developed and it's a "full time" project to get XML assertions, I just don't have time to do it properly.

**Comment by PascalSchumacher** [comment]
For reference there is a pull request to add AssertJ support to XMLUnit 2: https://github.com/xmlunit/xmlunit/pull/120

**Comment by bodewig** [comment]
we've just released XMLUnit 2.6.1 with the new xmlunit-assertj module provided

**Comment by joel-costigliola** [comment]
I created https://github.com/assertj/doc/issues/11 to reference XMLUnit
