### ISSUE TITLE
assertThat in an optional of String gives a wrong result.

### ISSUE THREAD

**Issue by sobngwi** [joel-costigliola/assertj-core#1110]
#### Summary
I tried to test the equals on a an Optional of String and a string. The result is alwas true.
However while runnning the test in debug mode . The instruction inside parenthesis if evaluate to false,
but the final assertThat evaluation is true.

#### Example
``` java
    @Test
    public void assertOptionalString_is_not_equals_to_string() {
         final String aString="alain";
         final Optional<String> anOptionalOfString =  Optional.of("alain");
         org.assertj.core.api.Assertions.assertThat(anOptionalOfString.equals(aString)); // pass ?
         org.assertj.core.api.Assertions.assertThat(anOptionalOfString.get().equals(aString)); // pass
         Assert.assertTrue(anOptionalOfString.equals(aString)); // fail
    }
```

**Comment by joel-costigliola** [comment]
you are misusing the API, `assertThat(anOptionalOfString.equals(aString))` does nothing, you should do either of these:
```java
assertThat(anOptionalOfString.get()).isEqualTo(aString);
// better
assertThat(anOptionalOfString).contains(aString);
```

See 
- http://joel-costigliola.github.io/assertj/assertj-core.html#faq-incorrect-api-usage
- http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractOptionalAssert.html#contains-VALUE-

**Comment by sobngwi** [comment]
Thanks mister.
This will solve a lot of bad assertions i  saw in severals code.
I wondering if it is not possible to not authorize such instructions, or make tests fails ( which a special message ) ,  or throws runtime exceptions while running tests containing such instructions.
regards,
Alain

**Comment by PascalSchumacher** [comment]
You can use static code analysis tools like findbugs or error-prone to check for these errors.
