### ISSUE TITLE
isNull assertion broken in Kotlin when calling a Java class

### ISSUE THREAD

**Issue by DavidRigglemanININ** [joel-costigliola/assertj-core#1115]
#### Summary
If you have a java class with a object property and try to assert that the property is null from kotlin, then the isNull assertion is not usable due to an exception being thrown first that null cannot be converted to not null. So instead of assertThat(foo).isNull(), I end up having to do assertThat(foo == null).isTrue()

#### Example

java
```java
public class Test {
    public Integer foo;
}
```

kotlin
```kotlin
Test t = Test()
assertThat(t.foo).isNull() // is broken and doesn't work
assertThat(t.foo == null).isTrue() // works as expected
```

**Comment by joel-costigliola** [comment]
I have just checked it in java and it works fine.

I don't know Kotlin but could it be that it tries to convert your `Integer` into an `int` ?
What does `assertThat(t.foo)` resolves to ? In my IDE it's resolving to  `public static AbstractIntegerAssert<?> assertThat(Integer actual)` which does not try to do any conversion to `int`.

I'm using assertj core  .8.0

**Comment by DavidRigglemanININ** [comment]
So when I step into the assertThat from Kotlin into the decompiled assertJ core code, here's what I see:
```
@CheckReturnValue
    public static AbstractIntegerAssert<?> assertThat(int actual) {
        return AssertionsForClassTypes.assertThat(actual);
    }
```
So it's that int type that's coercing the null value and causing problems. Also for reference, I'm using 3.8

**Comment by joel-costigliola** [comment]
It looks like a Kotlin pb :thinking:, does Kotlin have this "feature" of converting `Integer` to `int` and is it possible to control it ?

**Comment by DavidRigglemanININ** [comment]
So I just tried converting as assertThat(t.foo as Int?).isNull() and that does work, although I get a warning saying the cast is unnecessary. I did look more through the source code and found just a few lines below
```
@CheckReturnValue
    public static AbstractIntegerAssert<?> assertThat(Integer actual) {
        return new IntegerAssert(actual);
    }
```
So it seems that maybe there is two overloads and Kotlin can't figure out which one to use. I'll submit a ticket with them

**Comment by joel-costigliola** [comment]
I'm closing this, but feel free to add a comment if you think something needs to be done in AssertJ.

**Comment by leosprikryl** [comment]
Here is the Kotlin issue reported by David: https://youtrack.jetbrains.com/issue/KT-21285.
