### ISSUE TITLE
Allow passing a comparator description

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1116]
#### Summary

Allow to pass a comparator description with `usingComparator`  or `usingElementComparator` so that it is clear what was the comparison strategy used in the assertion error message.

#### Example

```java
Comparator<TolkienCharacter> raceComparator = 
                 (tc1, tc2) -> tc1.getRace().compareTo(tc2.getRace());

assertThat(frodo).usingComparator(raceComparator, "Race comparator")
		 .isEqualTo(legolas);
```
without description:
```
Expecting:
 <Frodo 33 years old Hobbit>
to be equal to:
 <Legolas 1000 years old Elf>
when comparing values using 'AssertionsDemo$$Lambda$1/1355316001' but was not.
```
with description
```
Expecting:
 <Frodo 33 years old Hobbit>
to be equal to:
 <Legolas 1000 years old Elf>
when comparing values using 'Race comparator' but was not.
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by johnkillmer** [comment]
Hi Joel,

I think having the ability to pass in a description would be very helpful. I use custom comparators frequently and so I wanted to try and make this improvement in the code. 

Question about contributors. 

Do I commit and push my changes directly to the 2.x branch then create a pull request to merge them to master?
or
Do I have a separate branch created, commit and push, then create a pull request to 2.x?

Thanks
-John

**Comment by filiphr** [comment]
@johnkillmer have a look at the [contributing](https://github.com/joel-costigliola/assertj-core/blob/master/CONTRIBUTING.md) section of the code.

You will need to create e fork of this projects and base your changes from the `2.x` branch. If I were you I would create a branch based on `2.x` commit your changes there and open a pull request from that branch to the `2.x` branch in this project.

**Comment by joel-costigliola** [comment]
@johnkillmer if your comparators are extracted to a class then the simple class name is used except or `toString()` if you have overridden it.

**Comment by nach-o-man** [comment]
created #1191 for this

**Comment by joel-costigliola** [comment]
@nach-o-man will review it this we, thanks.

**Comment by joel-costigliola** [comment]
Fixed vy @nach-o-man, thanks!
