### ISSUE TITLE
assertThatCode( () -> {}).doesNotThrowAnyException() should print stack trace information

### ISSUE THREAD

**Issue by mkobit** [joel-costigliola/assertj-core#1118]
#### Summary

`doesNotThrowAnyException()` should print full stacktraces to make debugging these tests easier.

Similar request as https://github.com/joel-costigliola/assertj-core/issues/791

#### Example

```java
class Mkobit {

  @Test
  void assertjExample() {
    assertThatCode(() -> new ExampleClass().doThing()).doesNotThrowAnyException();
  }

  private static class ExampleClass {
    void doThing() {
      throw new RuntimeException("Inside thing");
    }
  }
}
```

Prints out:

```
java.lang.AssertionError: 
Expecting code not to raise a throwable but caught a
  <java.lang.RuntimeException>
with message :
  "Inside thing"
```

It is preferable to get the origin of the exception that was thrown for debugging purposes. In general, I think most of the `Throwable` assert-style things should print out more of the stack trace when the exception is not the expected one. `assertThatCode` is the most frequent one I run into, but it might be present in other exception asserting APIs.

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Fair enough

**Comment by mkobit** [comment]
Hah, alright! Thanks for quick response - I'll try and throw a PR for it sometime this week.
