### ISSUE TITLE
isEqualTo should not check for null if using a custom comparator

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1121]
#### Summary

`isEqualTo` should not check that the object under test is null when a custom comparators is used since it is the custom comparator to evaluate the equality.

#### Example

https://stackoverflow.com/questions/47471469/how-to-check-for-equality-or-both-blank-in-assertj

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by eximius313** [comment]
will it go for milestone 2.9.0 as it is `breaking change`?

**Comment by joel-costigliola** [comment]
Yes I think we will do that, it is a minor breaking change which is easy to fix in the custom comparator itself or by calling `isNotNull()` before `isEqualTo`

**Comment by eximius313** [comment]
@joel-costigliola when do you plan to release 2.9.0?

**Comment by joel-costigliola** [comment]
Yes (as suggested by the milestone).

**Comment by eximius313** [comment]
But it says "[No due date](https://github.com/joel-costigliola/assertj-core/milestone/35)"

**Comment by joel-costigliola** [comment]
because there is no date yet for 2.9.0/3.9.0 although I'm trying to do it by the end of the year.

**Comment by eximius313** [comment]
Ok. I just asked "when do you plan to release 2.9.0" and you answered "as suggested by the milestone" so I thought that I'll find the answer there.
Anyway - thanks for the information
