### ISSUE TITLE
Must AbstractAssert#equals  throw UnsupportedOperationException

### ISSUE THREAD

**Issue by guenhter** [joel-costigliola/assertj-core#1128]
#### Summary
@joel-costigliola Is it necessary for the `AbstractAssert#equals` to throw the `UnsupportedOperationException`?
This is against the contract of `Object#equals` and brakes other libraries which are not handling this. I know that it should be the deal of the libraries, if they can handle this error but this situation is absolutely not obvious. Is is possible, to change this?

In fact, currently it breaks the coroutines of Kotlin.

#### Example

```java
org.assertj.core.api.AbstractAssert

  /**
   * {@inheritDoc}
   *
   * @deprecated use {@link #isEqualTo} instead
   *
   * @throws UnsupportedOperationException if this method is called.
   */
  @Override
  @Deprecated
  public boolean equals(Object obj) {
    throw new UnsupportedOperationException("'equals' is not supported...maybe you intended to call 'isEqualTo'");
  }

```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
This is done to avoid misusing the API like that: 
```java
// BAD
assertThat(actual).equals(expected);

// GOOD
assertThat(actual).isEqualTo(expected);
``` 
`*Assert` are not meant to be compared, what is the concrete use case for that ? is it Kotlin specific ?

**Comment by guenhter** [comment]
Ok, I understand the reason you added the exception to the class. From this point of view it is useful to prevent the user to use the `equals`-method unintentionally.

The problem itself is in a kotlin library. When a lambda is used like the following

```
doSomething {
    assertThat(foo).isNull()
}
```

the `isNull` itself returns again the `...AbstractAsserter`. When the lambda can handle return values, this `....AbstractAsserter` is returned to the caller. 
In this case, the `coroutines` library does some magic under the hood. One step in the magic is to compare the result with the last result `thisone.equals(lastone)` and here the problem happens, because the equals throws an exception which the library doesn't handles.
I know that this is the problem of the library, but as I said, IMO breaking the contract of `equals` isn't the best way to do.
