### ISSUE TITLE
containsExactlyElementsOf should display the diff when the size differ

### ISSUE THREAD

**Issue by reitzmichnicht** [joel-costigliola/assertj-core#1132]
Using containsExactlyElementsOf for a list with more than 1000 entries does not show the missing elements if they have an index > 1000 because the error message truncates after 1000 element entries with ...

```java
assertThat(List<String> a).containsExactlyElementsOf(List<String> b);
```

**Comment by joel-costigliola** [comment]
That was a deliberate decision but maybe not a good one or we could bump to 10 000 elements

**Comment by reitzmichnicht** [comment]
I think it would be better to only show the none matching elements of actual and expected for containsExactlyElementsOf. That would require to skip the internal different size check.

**Comment by filiphr** [comment]
One can configure this via `Assertion.setMaxElementsForPrinting(xxx)`. However, this would be only for a single test.

@joel-costigliola maybe we can add an SPI like we did for the representation for this configuration (and some others as well).

**Comment by joel-costigliola** [comment]
Changing the number of elements with `Assertion.setMaxElementsForPrinting(xxx)` would be for the following tests also (it's a static field in `StandardRepresentation`).

**Comment by filiphr** [comment]
Yes you are right @joel-costigliola. What I wanted to say that it would not affect the entire execution of all tests, i.e. it will be used for all tests after the one setting it

**Comment by reitzmichnicht** [comment]
Setting setMaxElementsForPrinting is a first aid workaround, but as noted it would be much better to not dump the whole list, but instead only the differences of the lists.

Actually it is not really comfortable to diff two lists of 1600 entries per copy paste in a diff tool just to find out why the test is failing.

**Comment by filiphr** [comment]
Now I get it, what you are looking for at the moment is only displayed when the sizes of the lists are the same.

**Comment by reitzmichnicht** [comment]
@filiphr yes if the sizes of the lists are not the same, the output of the assertion is not really helpful

**Comment by joel-costigliola** [comment]
I agree this would be better
