### ISSUE TITLE
Add "yyyy-MM-dd'T'HH:mm:ssX" timezone aware format to default ones. 

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1133]
#### Summary

Add "yyyy-MM-dd'T'HH:mm:ssX" to the default date formats to support TZ comparison.

#### Example

```java
Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
cal.clear();
cal.set(2017, Calendar.NOVEMBER, 27, 20, 13, 24);
Date date = cal.getTime();

assertThat(date)
    .isEqualTo("2017-11-27T20:13:24+00:00");
```

See #1123

**Comment by pswiatowski** [comment]
Hi! I use assertJ on daily basis and I would like to contribute to it. I created a pull request and I will be grateful for review.

**Comment by joel-costigliola** [comment]
Hi @pswiatowski, I'll review your PR this week, thanks for the contribution!
