### ISSUE TITLE
Tests not running through Maven

### ISSUE THREAD

**Issue by wama2** [joel-costigliola/assertj-core#1135]
#### Summary
Running (mvn package ) gives me :
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.7.9:check (default-check) on project assertj-core: Coverage checks have not been met. See log for details. -> [Help 1]

also before : 
[ERROR] Failed to execute goal  org.apache.maven.plugins:maven-surefire-plugin:2.20:test:check (default-check) on project assertj-core: Coverage checks have not been met. See log for details. -> [Help 1]

Thanks

#### Example

```java
<add example here>
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Thanks for reporting this ! That's a bit weird, I'll try it and see how it goes.

**Comment by PascalSchumacher** [comment]
@joel-costigliola I can not replicate this (with current master) and it also works on travis. I think we close this issue.
