### ISSUE TITLE
org.assertj.core.util.introspection.FieldSupport.readSimpleField causes ExceptionInInitializerError for private primitive fields where generateAssertionsForAllFields is set true

### ISSUE THREAD

**Issue by skiaheliou** [joel-costigliola/assertj-core#1141]
#### Summary

I use the **assertj-assertions-generator-maven-plugin** with `<generateAssertionsForAllFields>true</generateAssertionsForAllFields>` for my project, as one of my objects has a private primitive field (`int`). When I run that object's `Assert`'s `has` method, `org.assertj.core.util.introspection.FieldSupport.readSimpleField(FieldSupport.java:193)` sparks an `ExceptionInInitializerError`. Before that, it throws and catches a `ClassCastException`:  `java.lang.ClassCastException: Cannot cast java.lang.Integer to int`.

On further inspection, any primitive type except boolean causes this problem.

#### Example

Please see attached:
[ReadSimpleFieldExceptionInInitializerErrorSample.zip](https://github.com/joel-costigliola/assertj-core/files/1585116/ReadSimpleFieldExceptionInInitializerErrorSample.zip)

#### Java 8 specific ?
Untested, but I hypothesize not.

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Good catch ! We will try to ship it in 2.9.0 that should be released really soon.
