### ISSUE TITLE
NPe in ShouldBeEqualByComparingFieldByFieldRecursively.describeField since AssertJ 3.9.0

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1151]
#### Summary

In 3.9.0, NPE vulnerability introduced via this commit:
https://github.com/joel-costigliola/assertj-core/commit/fb9f9522f7ab

See my comment there. replace() Should have nullcheck.

#### Example

```java
<add example here>
```

**Comment by joel-costigliola** [comment]
duplicate of #1145
