### ISSUE TITLE
SoftAssertions do not work with `asList`, `asString`, `first`, etc.

### ISSUE THREAD

**Issue by robfletcher** [joel-costigliola/assertj-core#1156]
When down-casting a soft assertion using `asList` or `asString` the assertion returned does not work within the context of the existing soft assertions. The same also applies to `first` when used on a `SoftAssertionsListAssert`. It looks like any proxies need to be applied to the new assertions those methods return.

**Comment by joel-costigliola** [comment]
Good catch, we have forgotten about these ones :(

**Comment by robfletcher** [comment]
I noticed when I tried to create some similar methods (for example `asMap`) as Kotlin extension functions. I'm concerned that it wouldn't be possible to access the in-scope proxies in order to do that.

**Comment by joel-costigliola** [comment]
yeah that would be a problem as you need to proxy these methods in a special way, for example when calling `asString` we need to proxy the new StringAssert returned by `asString`, same goes for `asMap` but if AssertJ does not know about `asMap` it can't apply the proper proxying. 

Not sure I'm super clear

**Comment by robfletcher** [comment]
Yeah, I understand. I'll hold on and see how you implement a fix for this issue. If I can't access the proxies I'll maybe submit a pull request to add an `asMap`.

**Comment by joel-costigliola** [comment]
Fixed
