### ISSUE TITLE
Add isEqualTo(long) for IntegerAssert 

### ISSUE THREAD

**Issue by lqc** [joel-costigliola/assertj-core#1162]
#### Summary

Add ```isEqualTo(int)``` method to ```AbstractLongAssert``` and a ```@Deprecated``` override of ```isEqualTo(Object)``` to avoid use by mistake.

#### Rationale

I may be missing something obvious, but I can't understand why there is no isEqualTo(long) overload in assertions for ```int``` type like there are for BigInteger.

A typical pitfall I see is:
```java
assertThat(foo.getBar()).isEqualTo(5L)
```

If ```getBar()``` returns ```long``` or ```BigInteger``` with a numeric value of 5, then this passes as expected. But if the return type is ```int``` that it will fail as the generic ```isEqualTo(Object)``` will be chosen (which will never succeed if the passed object is not an instance of Integer, but than isEqualTo(int) would be used so you never want to call it).

####

**Comment by joel-costigliola** [comment]
This works fine in my environment:
```java
// GIVEN
final long longValue = 5;
final int intValue = 5;
// THEN
assertThat(longValue).isEqualTo(longValue);
assertThat(longValue).isEqualTo(intValue);
```
the second `isEqualTo` assertion is resolved to `public SELF isEqualTo(long expected)` in 3.9.0.

Can you create a test case that fails in order to show the problem ?

**Comment by lqc** [comment]
Ah, sorry I reverted the types when writing the issue:

```
public class Test {

    static int INT = 1;
    static long LONG = 1L;

    public static void main(String[] args) {
        int x = 1;
        assertThat(x).isEqualTo(INT);
        assertThat(x).isEqualTo(LONG);
    }
}
```

I think it should work both ways as long as the argument for ```isEqualTo()``` can be converted to int without rounding, etc.

**Comment by joel-costigliola** [comment]
Agreed

**Comment by joel-costigliola** [comment]
Fixed thanks to @epeee.
