### ISSUE TITLE
AbstractZonedDateTimeAssert.isEqualTo(ZonedDateTime expected) throws NPE

### ISSUE THREAD

**Issue by sindremehus** [joel-costigliola/assertj-core#1164]
#### Summary
Asserting equality between two ZonedDateTime instances that are null throws NullPointerException. This does not happen, for instance, with LocalDateTime.

#### Example

```java
        ZonedDateTime a = null;
        ZonedDateTime b = null;
        assertThat(a).isEqualTo(b);  // throws NPE
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this ! we will look at it for 3.9.1

**Comment by pswiatowski** [comment]
Also, NPE is thrown when only the actual value is null or only the expected value is null.

isEqualTo Override method on ZoneDateTime checks zone on the instances before asserting null.

**Comment by pswiatowski** [comment]
Also, isNotEqual method throws NPE. @joel-costigliola  Should we create another issue or fix in this one?

**Comment by joel-costigliola** [comment]
@pswiatowski  let's fix both, thanks!

**Comment by pswiatowski** [comment]
@joel-costigliola  I updated both methods and it is ready for code review.

**Comment by joel-costigliola** [comment]
Thanks! I'll look at it this we.
