### ISSUE TITLE
Illegal reflective access warnings with SoftAssertions and Java 9+

### ISSUE THREAD

**Issue by triceo** [joel-costigliola/assertj-core#1165]
Using AssertJ 3.9.0 and JUnit 5 with Maven Surefire 2.19, I get the classic Java 9 warning:

    WARNING: An illegal reflective access operation has occurred
    WARNING: Illegal reflective access by org.assertj.core.internal.cglib.core.ReflectUtils$1 (file:.../org/assertj/assertj-core/3.9.0/assertj-core-3.9.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
    WARNING: Please consider reporting this to the maintainers of org.assertj.core.internal.cglib.core.ReflectUtils$1
    WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    WARNING: All illegal access operations will be denied in a future release

When I use `Assertions` instead of `SoftAssertions`, the warning doesn't show.

My environment:

    $ java -version
    openjdk version "9.0.1"
    OpenJDK Runtime Environment (build 9.0.1+11)
    OpenJDK 64-Bit Server VM (build 9.0.1+11, mixed mode)
    $ uname -a
    Linux sagan 4.15.0-0.rc8.git0.1.fc28.x86_64 #1 SMP Mon Jan 15 17:04:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I have a suspicion that this is somehow related to either JUnit 5 or Maven Surefire 2.19. When I used JUnit 4 with Maven Surefire 2.20, AssertJ threw no warnings.

**Comment by joel-costigliola** [comment]
Thanks for reporting this ! We are replacing cglib by byte-buddy, we'll see if we get the same warning (I'm expecting to).

**Comment by PascalSchumacher** [comment]
@triceo It would be great, if you could give AssertJ `3.9.1` (which replaces `cglib` with `byte-buddy`) a try and check if the warnings still occur.

**Comment by triceo** [comment]
@PascalSchumacher Most of the warnings are indeed gone. I still occasionally get the following, though:

    WARNING: Illegal reflective access by org.assertj.core.api.AbstractSoftAssertions (file:/home/lpetrovi/.m2/repository/org/assertj/assertj-core/3.9.1/assertj-core-3.9.1.jar) to field java.lang.Throwable.detailMessage
    WARNING: Please consider reporting this to the maintainers of org.assertj.core.api.AbstractSoftAssertions
    ...

The interesting bit is that it doesn't show up in the tests themselves. It shows up when the tests are being re-run with PITest (https://github.com/hcoles/pitest).

**Comment by triceo** [comment]
@PascalSchumacher The issue you reference has been closed, yet the warning is still there. Not sure what the next steps are here.

**Comment by PascalSchumacher** [comment]
@triceo Sorry for the late response. #1036 did not remove access to the private field `Throwable#detailMessage` in https://github.com/joel-costigliola/assertj-core/blob/4946b0461fb240d437dd756b162dbf64c8402642/src/main/java/org/assertj/core/api/AbstractSoftAssertions.java#L176

As long as this is not fixed the warning `Illegal reflective access by org.assertj.core.api.AbstractSoftAssertions to field java.lang.Throwable.detailMessage` will continue to occur.

**Comment by joel-costigliola** [comment]
@PascalSchumacher is that something we can address ?

**Comment by PascalSchumacher** [comment]
The easy solution would be to drop the line number feature of `SoftAssertions`.

There is no clean way to update the message of a `Throwable` and I am not aware of any other clean way to solve this this problem.

**Comment by triceo** [comment]
I'm not familiar with the full codebase, but from looking at the codebase, couldn't `decorateErrorsCollected(...)` "rethrow" the errors, adding the line into the message of the newly created error?

**Comment by joel-costigliola** [comment]
@triceo that's something to try, I'm not too sure if you can keep the original stack trace though.

**Comment by scaphoid** [comment]
Can't you replace the original exception with a new one and use Throwable#setStackTrace to add the original stack trace?

**Comment by joel-costigliola** [comment]
@PascalSchumacher would you have time to look into this ?

**Comment by joel-costigliola** [comment]
@scaphoid  @triceo I have just merged @PascalSchumacher fix for this but somehow I was not able to get the warning before the fix, could you try build assertj-core from master and give it a try ? 
building assertj-core is as simple as running `mvn install -Dmaven.test.skip=true`

**Comment by triceo** [comment]
I'm no longer seeing this issue with today's master. My environment is as follows:

- OpenJDK 11
- JUnit 5.5
- Surefire 3.0.0-M3

Thanks for the fix!

**Comment by scaphoid** [comment]
Build fails for me; sorry I have no clue how to get around this:

[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ assertj-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 629 source files to C:\Projects\AssertJ\assertj-core\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.761 s
[INFO] Finished at: 2019-07-16T08:46:59-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project assertj-core: Fatal error compiling: invalid flag: --release -> [Help 1]

**Comment by scaphoid** [comment]
Latest master works for me with Corretto 11.0.3_7 and JUnit 5.5.0

**Comment by PascalSchumacher** [comment]
@triceo @scaphoid Thanks for testing the fix! 👍
