### ISSUE TITLE
CompletionStage should print stacktrace on failed assertion with failed-future

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1167]
#### Summary

When asserting non exception result about CompletionStage / Future like isNotDone or isCompleted, assertJ reports something like this:

```
Expecting
  <CompletableFuture[Failed: java.lang.NullPointerException]>
not to be done
```

In such cases, it would be useful for the Exception Stacktrace to be printed, IMO, as a good start for debugging the cause of the test failure.

**Comment by pswiatowski** [comment]
I can work on this.

**Comment by pswiatowski** [comment]
@joel-costigliola do we want to add StackTrace to the AssertJ report

```
Expecting
  <CompletableFuture[Failed: java.lang.NullPointerException]
   [StackTrace]>
not to be done
```

or only print it?

**Comment by joel-costigliola** [comment]
@pswiatowski I would put it in the AssertJ report

**Comment by pswiatowski** [comment]
Okay, there will be a small problem in unit test because actual stacktrace is different than expected.

**Comment by pswiatowski** [comment]
@joel-costigliola thank you for CR. I updated after reworks.
