### ISSUE TITLE
Replace RuntimeIOException with UncheckedIOException?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#1175]
Should we replace the AssertJ specific `RuntimeIOException` with `UncheckedIOException` which was added in Java 8?

**Comment by pswiatowski** [comment]
I can work on this 👍

**Comment by pswiatowski** [comment]
@joel-costigliola  what should we do with the missing constructors in UncheckedIOException?
e.g. RuntimeIOException(String message)

UncheckedIOException Constructors:

UncheckedIOException(IOException cause)
UncheckedIOException(String message, IOException cause)

**Comment by joel-costigliola** [comment]
can't we use `UncheckedIOException(String message, IOException cause)` ? 
if not it means it wasn't an IOException in the first place, then a simple `RuntimeException` should do the job

**Comment by pswiatowski** [comment]
Yes, you are right. Will fix wrong usage of RuntimeIOException with RuntimeException. Thanks!

**Comment by pswiatowski** [comment]
@joel-costigliola ready for code review.
