### ISSUE TITLE
assertIsNotIn should allow empty iterable

### ISSUE THREAD

**Issue by tkruse** [joel-costigliola/assertj-core#1180]
#### Summary
Currently isNotIn(Iterable<?> values) starts with

    checkIsNotNullAndNotEmpty(values);

However it should only check IsNotNull().

#### Example

```java
Set<> keys = new HashSet();
for (Thing thing: things) {
    assertThat(thing.key()).isNotIn(keys);
    keys.add(thing.key());
}
```

Or maybe this test should be written in a different way?
I can write

```java
Set<> keys = new HashSet();
for (Thing thing: things) {
    assertThat(keys).doesNotContain(thing.key());
    keys.add(thing.key());
}
```
But it feels like this violates assertj philosophy of putting the thing under test into the assert method.

**Comment by joel-costigliola** [comment]
IMO, it does not make a lot of sense to have an empty set of values as an argument of `isNotIn` (or `isIn`).
Using the vararg, what would you say `assertThat(value).isNotIn();` means?  I find this to be confusing so the check was made to avoid this possible confusion.

Just curious, is it correct in your context to have an empty set of values in the first place ?

**Comment by tkruse** [comment]
In my context, I want to make sure that a collection of things do not have duplicate values in one of their fields. Accessing that fields is a bit involved (I am checking values from configuration files), so I use a loop. The way I wrote my example, I start with an empty Set, and check contains each time. So on the first iteration, the empty set is correct in that sense.

**Comment by tkruse** [comment]
Hm, so I assume the philosophy is that the expectation that comes after an  assert should be static, so by using a dynamically changing set I already go against assertj (or testing) principles. It's more validation than testing, maybe. So maybe no need to change the method for my case, close if you wish.

**Comment by joel-costigliola** [comment]
yeah, it seems to be a use case for [doesNotHaveDuplicates](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#doesNotHaveDuplicates--)

**Comment by joel-costigliola** [comment]
@tkruse I'm closing this one but feel free to continue commenting and we might reopen it.

**Comment by janbols** [comment]
Hi @joel-costigliola ,

I want to test a repository implementation. The repository has a method that returns a list of users. It also has a method to add a user.
I want to test that you cannot add the same user twice.
```
val userToAdd = "newUser"
assertThat(userToAdd).isNotIn(myRepo.getUsers())
myRepo.add(userToAdd)
assertThat(userToAdd).isIn(myRepo.getUsers())
```

The above code does not go against any sort of testing principle I assume.
However, the first assertion will fail b/c the returned list of users is empty in the beginning.

**Comment by joel-costigliola** [comment]
I still don't like `assertThat(value).isNotIn();` but I guess that if you explicitly pass an empty group of values then the assertion should pass all the time. So `assertThat(userToAdd).isNotIn(myRepo.getUsers())` should pass if `myRepo.getUsers()` is empty.

**Comment by joel-costigliola** [comment]
I have also changed `isIn` to accept an empty iterable, in that case the assertion always fails
