### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Skiv1989** [joel-costigliola/assertj-core#1183]
#### Summary
code at org.assertj.core.error.ShoulBeEqualByComparingFieldByFieldRecursevly class in the describeDifference method will fail with NPE if difference object has actual or other field as null.

**Comment by joel-costigliola** [comment]
duplicate of https://github.com/joel-costigliola/assertj-core/issues/1145 ?

**Comment by Skiv1989** [comment]
Yes, sorry haven't saw it.
