### ISSUE TITLE
filteredOn operation does not play well with factory

### ISSUE THREAD

**Issue by dalewking** [joel-costigliola/assertj-core#1186]
#### Summary
Trying to write assertion on a list of objects where I have a custom assertion for the type of the objects contained within it. I have created a factory instance for the custom assertion class for the type.

assertThat has a nice overload that takes an iterable and a factory. But the filteredOn iterator ignores the factory and returns an assert instance using just ObjectAssert<ELEMENT> so you lose the type safe support.

#### Example
So assuming TolkeinCharacter and TolkeinCharacterAssert as in the docs:

```java
    public static AssertFactory<TolkeinCharacter, TolkeinCharacterAssert> FACTORY =
            new AssertFactory<TolkeinCharacter, TolkeinCharacterAssert>()
            {
                @Override
                public TolkeinCharacterAssert createAssert(TolkeinCharacter character)
                {
                    return TolkeinCharacterAssert.assertThat(character);
                }
            };
```

This allows you to do this which will work assuming that frodo is first:

```java
     assertThat(fellowshipOfTheRing, factory)
         .first()
         .hasAge(33);
```
However this does not compile:

```java
     assertThat(fellowshipOfTheRing, factory)
         .filteredOn("name", "Frodo")
         .first()
         .hasAge(33);
```

**Comment by dalewking** [comment]
The same would also be true using the class based version:

     assertThat(fellowshipOfTheRing, TolkeinCharacterAssert.class)

**Comment by joel-costigliola** [comment]
Yes true, thanks for reporting this.

**Comment by pswiatowski** [comment]
I can work on this.
