### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by duclet** [joel-costigliola/assertj-core#1190]
#### Summary
Upgrading from 3.9.0 to 3.9.1 cause the following error for my tests:

java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/lang/Object;)Lorg/assertj/core/api/AbstractObjectAssert;

#### Example

```java
assertThat(actual).as(description).isNotNull();
```

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

What is the type of `actual`?

I'm asking because e.g.:

```
Object actual = new Object();
assertThat(actual).as("description").isNotNull();
```

works for me.

Did you recompile your tests or just replace assertj library? `3.9.1` is is not binary compatible to `3.9.0` due to https://github.com/joel-costigliola/assertj-core/issues/839.

Thanks in advance,
Pascal

**Comment by duclet** [comment]
@PascalSchumacher - The tests were recompiled. I think this might be suffering from something similar because it does have to do with a generic. I have a small utility function that sets the description and make the calling code above. In this case, the actual type of the object is a POJO.

```
public static <T> AbstractObjectAssert<?, T> assertNotNull(final T actual) {
    final String description = ....;

    return assertThat(actual).as(description).isNotNull();
}
```

**Comment by duclet** [comment]
So after looking at the code changes, changing my function signature to the following fixes the issue:

```
public static <T> ObjectAssert<T> assertNotNull(final T actual)
```
