### ISSUE TITLE
3.9.0 -> 3.9.1 breaks backward compatibility

### ISSUE THREAD

**Issue by pkoenig10** [joel-costigliola/assertj-core#1194]
Upgraded from 3.9.0 -> 3.9.1. A testing dependency uses 3.6.2. When attempting to run tests that use this dependency, I am getting a no such method error:
`java.lang.NoSuchMethodError:org.assertj.core.api.Assertions.assertThat(Ljava/lang/Object;)Lorg/assertj/core/api/AbstractObjectAssert;`

Looks like the brekaing change was in this commit: https://github.com/joel-costigliola/assertj-core/commit/fabeac7a2beb73497acdd61fdb446debb8fdbe01

**Comment by PascalSchumacher** [comment]
Thanks for reporting and sorry for breaking you code.

AssertJ does not guarantee binary compatibility, there are also other binary incompatible changes, e.g. https://github.com/joel-costigliola/assertj-core/commit/43c3c6b67e40047691521b8935a82afed509c8e9

**Comment by joel-costigliola** [comment]
@pkoenig10 this is indeed an API breaking change that I forget to mention in the release notes (my bad). It was done to address a warning when using generics vararg parameters (sigh).

@pkoenig10 is the error like #1190 ? if not can you give us more context ? a test case would be ideal.

As @PascalSchumacher said we don't guarantee binary compatibility but we try to avoid breaking it as much as possible.

**Comment by pkoenig10** [comment]
@joel-costigliola yes this is the same error as in #1190.

We have solved the problem by upgrading to 3.9.1.

**Comment by joel-costigliola** [comment]
@pkoenig10 thanks for checking.
