### ISSUE TITLE
Built-in comparator not used for SortedSet implementations

### ISSUE THREAD

**Issue by tommcdo** [joel-costigliola/assertj-core#1202]
#### Summary

Assertions on implementations of `SortedSet` (like `TreeSet`) do not use the comparator used to construct the instance.

#### Example

If I wanted to create a class that returned a set of strings which allowed testing for case-insensitive inclusion, I'd use a `TreeSet` with a custom comparator. The following code example is greatly simplified, but demonstrates the basic mechanics (in a real example, the creation of the set would be encapsulated within the class under test).

```java
TreeSet<String> mySet = new TreeSet<>(Comparator.comparing(String::toUpperCase));
mySet.add("FOO");
assertThat(mySet.contains("foo")).isTrue(); // passes
assertThat(mySet).contains("foo"); // fails
```

I found it surprising that the assertion didn't really call `mySet.contains()`, but looking into the AssertJ codebase I found that it was highly abstracted.

I can work around it by passing in an element comparator, like this:

```java
assertThat(mySet).usingElementComparator(mySet.comparator()).contains("foo")
```

However, in a real application, the set would probably have come from a method just returning `Set<String>`, so accessing its comparator is mostly out of the question. And even if I did, it just wouldn't feel like I was actually testing that my class returned a case-insensitive set.

**Comment by filiphr** [comment]
@tommcdo I think that this issue is the same as #1104

**Comment by nach-o-man** [comment]
@tommcdo this is really interesting situation you have.
I encountered the same for a few times and was also surprised.

But what if you look at it this way:
- by testing `assertThat(mySet.contains("foo"))` you test the concrete implementation of `contains` method of the given object
- by testing `assertThat(mySet).contains("foo")` you test that given object contains exactly specific object.
as said in javadoc 
>  Verifies that the actual group contains the given values, in any order

@filiphr I think it is slightly different

**Comment by joel-costigliola** [comment]
At first sight, the issue is in `StandardComparisonStrategy#iterableContains`: 
```
  public boolean iterableContains(Iterable<?> iterable, Object value) {
    if (iterable == null) {
      return false;
    }
    for (Object next : iterable) {
      if (areEqual(next, value)) {
        return true;
      }
    }
    return false;
  }
```
It checks values one by one with `areEqual` instead of using the iterable `contains` method, this was made to be able to override `areEqual` to use a different comparison strategy.

I think this should be changed so that collection accepting a Comparator are correctly honored (mainly `TreeSet`).

**Comment by tommcdo** [comment]
It looks most general interface where a custom comparator can be supplied is [`SortedSet`](https://docs.oracle.com/javase/7/docs/api/java/util/SortedSet.html).

Would it be too naive to simply overload `Assertions.assertThat(SortedSet)`?

```java
public static <ELEMENT> IterableAssert<ELEMENT> assertThat(SortedSet<? extends ELEMENT> actual) {                                                                                
  return new IterableAssert<>(actual).usingElementComparator(actual.comparator());                                                                                                                                          
}
```

**Comment by joel-costigliola** [comment]
@tommcdo that is a nicely short possibility, I think the only drawback is that if your `SortedSet` is declared as a `Set` that won't work, it would select `assertThat(Iterable<? extends ELEMENT> actual)` instead of `assertThat(SortedSet<? extends ELEMENT> actual)`.

**Comment by tommcdo** [comment]
@joel-costigliola Good call, that would be non-ideal.

**Comment by joel-costigliola** [comment]
We might get away with the limitation I mentioned by checking if the runtime type of actual is a `SortedSet`.
