### ISSUE TITLE
AbstractListAssert allow chainable assertions at specific index

### ISSUE THREAD

**Issue by airborn** [joel-costigliola/assertj-core#1205]
#### Summary
I'd like to propose a new assertion for `AbstractListAssert` that would allow chainable assertions on different elements of collection. This would match various `satisfy` assertions that are already present in other assertion classes.

#### Example

```java
List<String> actual = newArrayList("Leia", "Luke", "Yoda")

assertThat(actal)
    .satisfiesAt(str -> assertThat(str).isEqualTo("Luke"), atIndex(1))
    .satisfiesAt(
        str -> {
            assertThat(str)
                .isNotEmpty()
                .endsWith("da")
        }
        , atIndex(2))
```

**Comment by joel-costigliola** [comment]
Good idea!

For consistency with [`contains(object, index)`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractListAssert.html#contains-ELEMENT-org.assertj.core.data.Index-), let's remove `At`, rewriting your example:
```java
List<String> actual = newArrayList("Leia", "Luke", "Yoda")

assertThat(actal)
    .satisfies(str -> assertThat(str).isEqualTo("Luke"), atIndex(1))
    .satisfies(
        str -> {
            assertThat(str)
                .isNotEmpty()
                .endsWith("da")
        }
        , atIndex(2))
```

**Comment by airborn** [comment]
I have renamed the metod and add required javadoc, guess everything should be in right now.
