### ISSUE TITLE
Make constructor of ThrowableAssertAlternative public

### ISSUE THREAD

**Issue by ddidier** [joel-costigliola/assertj-core#1207]
#### Summary

The constructor of `org.assertj.core.api.ThrowableAssertAlternative` is currently package protected. I'd like to create a class named `MyExceptionAssertAlternative` with some more methods dealing with the fields of `MyException`. It would be used like this:

```
assertThatMyException().isThrownBy(() -> { throw new MyException("boom!", 123); })
                          .withMessage("%s!", "boom")
                          .withMessageContaining("boom")
                          .withNoCause()
                          .withStatus(123);
```

If there is an alternative, I'd like to hear it.

I could make a PR but as this is a really simple one, is it necessary? Thanks.

**Comment by ddidier** [comment]
That's a little more complicated than expected:

The constructor of `org.assertj.core.api.ThrowableTypeAssert` must be public too and its fields protected.

**Comment by joel-costigliola** [comment]
sure, no problem

**Comment by joel-costigliola** [comment]
Fixed in https://github.com/joel-costigliola/assertj-core/commit/bd44eabb7380aba5916a36cc6a66de6a857f0a31, let me know if you that is sufficient.
