### ISSUE TITLE
Add PathAssert#hasDigest(MessageDigest, byte[])

### ISSUE THREAD

**Issue by valery1707** [joel-costigliola/assertj-core#1210]
#### Summary
I think this methods can be very useful for `PathAssert`, `FileAssert` and `InputStreamAssert`:
* `hasDigest(MessageDigest digest, byte[] expected)`
* `hasDigest(MessageDigest digest, String expected)`
* `hasDigest(String algorithm, byte[] expected)`
* `hasDigest(String algorithm, String expected)`
* `hasDigest(String algorithm, String provider, byte[] expected)`
* `hasDigest(String algorithm, String provider, String expected)`

#### Example

```java
URL source = new URL("https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/2.9.0/assertj-core-2.9.0.jar");
assertThat(source.openStream()).hasDigest("SHA1", "5c5ae45b58f12023817abe492447cdc7912c1a2c");
```

P.S.
I can create PR if you approve such methods.

**Comment by valery1707** [comment]
Digest expected variants:
* `byte[]` - this variant maybe useful for some cases when digest calculated within tests.
* `String` - But digest in string-representation is more useful for cases when developer already know digest in this form (hex).

Digest algorithms:
* `MessageDigest` - core variant, all other variant will call this variant. And it's most powerful - developer can create what he want and what they need
* `String algorithm` - more simple variant when used some basic digest algorithms (`SHA1`, `MD5`, e.t.c.): `hasDigest("SHA1", "...")` vs `hasDigest(MessageDigest.getInstance("SHA1"), "...")`
* `String algorithm` + `String provider` - this less useful over all variants because it's only simplify `hasDigest(MessageDigest.getInstance("SHA1", "provider?"), "...")` into `hasDigest("SHA1", "provider?", "...")`

I think what 
* 4 variants [(`MessageDigest` | `String`) x (`byte[]` | `String`)] will be very useful and need implemented
* 2 variants [(`String, String`) x (`byte[]` | `String`)] - can be eliminated

**Comment by joel-costigliola** [comment]
Sweet, let's go with the 4 variants first then if users ask for it we can always the two remaining ones.

**Comment by valery1707** [comment]
Good.
I started preparing PR

**Comment by valery1707** [comment]
This changes does not Java 8 specific but in 3406fc62cb20a5fb906584cbd7deaa97d7c2b8a3 you decide to stop work under [branch 2.x](https://github.com/joel-costigliola/assertj-core/tree/2.x).
Because of this I make PR from master branch.
