### ISSUE TITLE
Add support AbstractIterableAssert::noneStatisfy(Consumer consumer)

### ISSUE THREAD

**Issue by bfarka** [joel-costigliola/assertj-core#1215]
#### Summary
if you want to assert some complex things that non eelement of an Iterable contains something it would be create to have something an nonSatisfy like we there is currently an anySatisfy and an allSatisfy method

#### Example

```java
 assertThat(collection).nonSatisfy(item ->
            assertThat(item).startsWith("foo")
        );
```

**Comment by joel-costigliola** [comment]
I'll be happy if we rename that to `noneSatisfy` to be consistent with [`noneMatch`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#noneMatch-java.util.function.Predicate-).

**Comment by bfarka** [comment]
@joel-costigliola: 

what about having both:
As far as i understand the API all *Match method take an Predicate as arguement, all *Satisfy take a Consumer..

of course having both methods would be consistent...

what do you think?

**Comment by joel-costigliola** [comment]
Not sure if I understand you correctly but `noneMatch` already exists so we just need to add `noneSatisfy(Consumer)`.

**Comment by bfarka** [comment]
ahhh sure, so of course I'll can implement noneSatisfy(Consumer)
