### ISSUE TITLE
Provide a withPredicate check for exception handling

### ISSUE THREAD

**Issue by hgschwibbe** [joel-costigliola/assertj-core#1219]
#### Summary
We have a custom business exception class which transports an error code from the backend to the frontend. It would be great to have a predicate check where we can access the additonal error code.

Please provide a withPredicate check for exception handling. 

#### Example
```
        assertThatExceptionOfType(BusinessException.class).isThrownBy(() -> {
             throw new BusinessException(ErrorCodeEnum.INVALID_EMAIL_FORMAT)
        }).withPredicate(ex -> ex.getErrorCode()  == ErrorCodeEnum.INVALID_EMAIL_FORMAT);
```

**Comment by nach-o-man** [comment]
it is possible in latest version (3.9.1) with *matches* method
```java
assertThatExceptionOfType(BusinessException.class).isThrownBy(() -> {
             throw new BusinessException(ErrorCodeEnum.INVALID_EMAIL_FORMAT)
        }).matches(ex -> ex.getErrorCode()  == ErrorCodeEnum.INVALID_EMAIL_FORMAT);
```

**Comment by joel-costigliola** [comment]
@hgschwibbe Have you something to add ? can we close this issue?
