### ISSUE TITLE
AssertJ Core Does Not Define an Automatic Module Name

### ISSUE THREAD

**Issue by andrewauclair** [joel-costigliola/assertj-core#1220]
#### Summary
Currently when compiling a project that uses assertj-core as a dependency in Java 9+ I receive the following warning from maven-compiler-plugin.
> Required filename-based automodules detected. Please don't publish this project to a public artifact repository!

The following should be added to the assertj-core pom.xml to generate an automatic module name in the Manifest file for maven to use.

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-jar-plugin</artifactId>
  <configuration>
    <archive>
      <manifestEntries>
        <Automatic-Module-Name>assertj-core</Automatic-Module-Name>
      </manifestEntries>
    </archive>
  </configuration>
</plugin>
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this !
