### ISSUE TITLE
Checkreturnvalue wrong on withFailMessage

### ISSUE THREAD

**Issue by reitzmichnicht** [joel-costigliola/assertj-core#1227]
#### Summary
Using the error prone compiler results in a failed build because withFailMessage does specify checkreturnvalue annotation, but that does not make sense.

#### Example
```java
assertThat(result4).hasSize(1).withFailMessage("searched for: {}", searchStr);
```

No return value needed here.

**Comment by PascalSchumacher** [comment]
`withFailMessage` has to be used before the assertion, otherwise it has not effect.

**Comment by reitzmichnicht** [comment]
Ok that was not obvious for me, there is no example in the documentation.
So the correct assertion would be:
```java
assertThat(result4).withFailMessage("searched for: {}", searchStr).hasSize(1);
```

**Comment by PascalSchumacher** [comment]
Javadoc and website updated.

Thanks for reporting! 👍
