### ISSUE TITLE
SoftAssertion doesn't proxy AssertExceptions from the IterableComparator

### ISSUE THREAD

**Issue by ASaunin** [joel-costigliola/assertj-core#1228]
AssertJ version: 3.9.1
Java: 8
When SoftAssertion is used with Iterable proxy, it doesn't handle AssertException, thrown by IterableComparator.
Please, check the code below. This test should pass, there is no softly.assertAll() calling at the end of the test. But unfortunately test fails cause of the internal implementation bug.

```java
public class CustomSoftAssertions {

    private final SoftAssertions softly = new SoftAssertions();

    public <T> IterableAssert assertThat(Iterable<T> actual) {
        return softly.proxy(IterableAssert.class, Iterable.class, actual);
    }

    public void assertAll() {
        softly.assertAll();
    }

}

public class IterableSoftAssertTest {

    private final CustomSoftAssertions softly = new CustomSoftAssertions();

    @Test
    public void shouldProxySoftAssertions() {
        final List<String> actual = Collections.singletonList("john");
        final List<String> expected = Collections.singletonList("doe");

        final Comparator<String> comparator = Comparator.comparing(Function.identity());

        //noinspection unchecked
        softly.assertThat(actual)
                .usingElementComparator(comparator)
                .containsExactlyInAnyOrder(expected.toArray());

        System.out.println("This message should be printed, but unfortunately not!" +
                "Soft assert has not proxied AssertException!");
    }

}
```

**Comment by joel-costigliola** [comment]
Your test does not work because `containsExactlyInAnyOrder` in `IterableAssert` is declared as `final` (in order to use `@SafeVarargs`), soft assertions work by dynamically proxying assert classes but this can't work for `final` method as they can't be overridden (the proxy is a subclass of the assert class).

Try with `ProxyableIterableAssert` and it should work fine.

I'm closing this issue but feel free to comment and I'll reopen it if necessary.

**Comment by ASaunin** [comment]
@joel-costigliola, thanks for the detailed answer. I've checked and it works fine with `ProxyableIterableAssert`. 
I just want to notice, that for the earlier AssertJ version SoftAssertions also worked fine with the pure proxyed `IterableAssert`. 
Maybe it makes sense to throw an exception if the proxying class is declared as `final` or to mention this feature at the documentation here: http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html#custom-soft-assertions. 
What do you think?

**Comment by joel-costigliola** [comment]
Not sure about the exception, AssertJ relies on the proxying library (byte buddy) and they don't throw one.
But yes we should state that final method don't work with soft assertions.
