### ISSUE TITLE
ShouldHaveMessage should use same assertion error as ShouldBeEqual

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1231]
#### Summary
When asserting message of a throwable a normal `AssertionError` is thrown. However, it is possible to use JUnit 4 or JUnit Jupiter specific assertion error in order to benefit from the IDEs features

#### Example

```java
assertThatThrownBy(() -> {
            throw new IllegalArgumentException("testing");
        })
            .hasMessage("Test");
```

results in:

```
java.lang.AssertionError: 
Expecting message:
 <"Test">
but was:
 <"testing">
```

It should be:

```
org.opentest4j.AssertionFailedError: 
Expecting message:
 <"testing">
to be equal to:
 <"Test">
but was not
```

**Comment by joel-costigliola** [comment]
Fixed in 1e40b3814a32bc93910bbe03aa8057617e6a770b
