### ISSUE TITLE
minor doc change suggestion for gradle

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1235]
change

```
testCompile 'org.assertj:assertj-core:3.9.0'
```

to
```
    testCompile( "org.assertj:assertj-core:3.9.0")
```

the difference being is that the latter is valid in kotlin, and groovy, but are supported by new versions of gradle, and would facilitate my lazy copy and paste issues.

**Comment by joel-costigliola** [comment]
Updated
