### ISSUE TITLE
Contains subsequence assertion on list of strings fails on valid subsequence

### ISSUE THREAD

**Issue by Juvat** [joel-costigliola/assertj-core#1241]
#### Summary
When a valid sub-sequence in a list of strings is asserted then the assertion will fail even though the sequence is present.

#### Example
This is a slightly reworked example from assertj-core-examples repo:

```java
    @Test
    public void longerString() {
        final List<String> list = Arrays.asList("Batman is weaker", "than Superman", "but he is", "less", "annoying");
        assertThat(list).containsSubsequence("Batman is"); // Fails
    }
```

**Comment by joel-costigliola** [comment]
The described behavior is actually correct, in your example [`containsSubsequence`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#containsSubsequence-ELEMENT...-) is a collection assertion that will look at **elements** (sub)sequence but `"Batman is"` is not an element of `list` thus the failure.

I guess you were thinking of the String [`containsSequence`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractCharSequenceAssert.html#containsSubsequence-java.lang.CharSequence...-) assertion, which you could achieve by concatenating all the String from your list into a single one.

I'm closing this issue as `work as expected` but feel free to continue discussing it if you want to.

**Comment by GregYeo** [comment]
> you could achieve by concatenating all the strings from your list into a single one.

I solved this problem by the way. But it loses index of the list. It is kind of unpleasant during debug.
Of course, we can add prefix or suffix for it but the we would be happy if there is native way for this case as long as assertThat is accepting collection.
