### ISSUE TITLE
Add assertion to determine that a String doesNotContainWhitespace

### ISSUE THREAD

**Issue by garethmok** [joel-costigliola/assertj-core#1245]
#### Summary

I have a scenario where I am aggregating String values and reducing it down to a single comma separated value for an external service, one of the requisites is that the submitted value does not contain whitespaces. Currently there does not appear to be a nice way to assert on this type of output.

#### Example

```java
String aggregatedValue = new Values("val1", "val2", "val3").asAggregate(); // aggregatedValue == "val1,val2,val3"
assertThat(aggregatedValue).doesNotContainWhitespace();
```

**Comment by PascalSchumacher** [comment]
Currently you can use:

`assertThat("val1,val2").doesNotContainPattern("\\s");`

**Comment by garethmok** [comment]
Excellent, thank you. In the end I opted for a combination of Apache commons' `StringUtils.containsWhitespace` :

`assertThat(containsWhitespace("val1,val2")).isFalse();`

I believe there is still value in adding this feature, language associated with pattern matching feels like it would normally be reserved for more complex patterns from a clean code standpoint. We have devs at all levels in our company, it makes sense for us to opt for the readable approach.

Although as I write this, I realise that this could also be remedied by isolating this into a single test with an appropriate test name.

**Comment by joel-costigliola** [comment]
I'm not against adding `doesNotContainWhitespace` if someone is keen to contribute it.

**Comment by garethmok** [comment]
Awesome, I'd be happy to have a look at this tonight 👍
