### ISSUE TITLE
Converting your JUnit assertions to AssertJ fails in some cases

### ISSUE THREAD

**Issue by romanlinhard** [joel-costigliola/assertj-core#1248]
Hello,
I've converted my JUnit test code  with your  convert-junit-assertions-to-assertj.sh script.
In most cases I have no problems and got a very good result. But at some tests I got into trouble (no compile any more ...) . As example here are some git diff's between JUnit code and now after the conversion.
Can you explain, what going wrong with that?

Here are two examples for successful conversion:
-    assertEquals("'ABcDe ='", StringHandling.addSingleQuotes("ABcDe ="));
+    assertThat(StringHandling.addSingleQuotes("ABcDe =")).isEqualTo("'ABcDe ='");

-    assertEquals("\"ABcDe =\"", StringHandling.addDoubleQuotes("ABcDe ="));
+    assertThat(StringHandling.addDoubleQuotes("ABcDe =")).isEqualTo("\"ABcDe =\"");

And here two example blocks which goes wrong:
-    assertEquals("12.34", StringHandling.fixFPNumberFormat("12.34"));
-    assertEquals("34.34", StringHandling.fixFPNumberFormat("34,34"));
-    assertEquals("1234.34", StringHandling.fixFPNumberFormat("1,234.34"));
-    assertEquals("1234.34", StringHandling.fixFPNumberFormat("1.234,34"));
-    assertEquals("1234567.34", StringHandling.fixFPNumberFormat("1,234,567.34"));
-    assertEquals("1234567.34", StringHandling.fixFPNumberFormat("1.234.567,34"));
+    assertThat(StringHandling.fixFPNumberFormat("0")).isEqualTo("0");
+    assertThat(StringHandling.fixFPNumberFormat("12.34")).isEqualTo("12.34");
+    assertThat(34")).as("34.34").isEqualTo(StringHandling.fixFPNumberFormat("34);
+    assertThat(234.34")).as("1234.34").isEqualTo(StringHandling.fixFPNumberFormat("1);
+    assertThat(34")).as("1234.34").isEqualTo(StringHandling.fixFPNumberFormat("1.234);
+    assertThat(234).as("1234567.34").isCloseTo(StringHandling.fixFPNumberFormat("1, within(567.34")));
+    assertThat(34")).as("1234567.34").isEqualTo(StringHandling.fixFPNumberFormat("1.234.567);

-    assertEquals("/home/linhrowe/Source/java/JCompPosition/examples/test_gencadpanel.cad", StringHandling.changeFileExtension("/home/linhrowe/Source/java/JCompPosition/examples/test_gencadpanel.pnl", "cad"));
+    assertThat(StringHandling.changeFileExtension("/home/linhrowe/Source/java/JCompPosition/examples/test_gencadpanel.pnl","cad").isEqualTo("/home/linhrowe/Source/java/JCompPosition/examples/test_gencadpanel.cad"));

If you need further informations, please contact me.

Bye
Roman

**Comment by joel-costigliola** [comment]
Thanks for reporting this, we know the script is not 100% bullet proof but if the conversion is 90% right then it is worth it.

We will improve it based on your feedback.

**Comment by juliodias** [comment]
Hi guys! Is this issue still open? I can help with it :D

**Comment by joel-costigliola** [comment]
@juliodias it is, awesome if you can help!

**Comment by juliodias** [comment]
Thanks @joel-costigliola, I'll do my best! If I have any questions I ask you

**Comment by joel-costigliola** [comment]
Sure, don't hesitate to ask!

**Comment by ulises-lara** [comment]
Hello! I would also like to help with this issue, if I may.
I will look into it and let you know if I have a question, is that okay @joel-costigliola ?

**Comment by ulises-lara** [comment]
Hey @juliodias !
Have you had any luck with this?
Please let me know if you need a helping hand with something.

**Comment by Eveneko** [comment]
Hello! Is this issue still open? I saw @juliodias wants to contribute to this issue. Is ok now? Or can I work on it?

**Comment by joel-costigliola** [comment]
@Eveneko  @ulises-lara thanks! 
There had been some improvements in the scripts since [3.13.0](https://assertj.github.io/doc/#assertj-core-3-13-0-release-notes) it would be good to test whether this issue is still relevant.
If you could look at that and let us know that would be great.

**Comment by romanlinhard** [comment]
Hello  @joel-costigliola ,

I tried today with the same JUNIT commands from my first comment.
I grab the actual JUNIT migrations scripts and by the way also version 3.15.0 of assert-core  from your page.

Sorry, but , the result was the same as in 2018, it fails in all belongings.

If there are new news, keep me informed.

Bye
Roman

**Comment by joel-costigliola** [comment]
The issue is still relevant then and needs some work @Eveneko  or @ulises-lara  ;-)

**Comment by Eveneko** [comment]
OK, I work on it now :-P

**Comment by Eveneko** [comment]
@joel-costigliola @romanlinhard  **Good test cases**

The error is the incorrect match for `,` in regular expressions.

`,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)` can match well, but `sed` don't support `(?=pattern)`. So I can't solve it by using `sed`.

Are there  other shell commands that can solve this problem? Or can we use `python` or `java` to solve it?

And I found that there is no test for the convert scripts, do we need to add it? (Actually I have written one for checking)

**Comment by joel-costigliola** [comment]
I'd rather keep shell scripting if possible as it is widely available (python is available be default in all major OS). Are you saying it can't be done with regular shell scripting? 

Having tests would be great indeed, we can start with @romanlinhard initial list of assertions.

**Comment by Eveneko** [comment]
> Are you saying it can't be done with regular shell scripting?

Yes, at least `sed` is unable to complete this task. But I will try to use other shell commands. And the python version will be developed synchronously. I try my best :-)

**Comment by Eveneko** [comment]
@joel-costigliola Done. Please review the code. Thx :-)
