### ISSUE TITLE
Typed equalTo alternative

### ISSUE THREAD

**Issue by Phil-Ba** [joel-costigliola/assertj-core#1249]
#### Summary
I'd like if there was a typed alternative to the current _isEqualTo_ method. While there is nothing wrong with the current _isEqualTo_ I often find myself wishing for IDE auto-completion support. But because the _isEqualTo_ method takes an Object, the IDE is not able to provide any meaningful assistance.
I'm sorry if this has been discussed before, but I wasn't able to find anything.

#### Example
```java
  public SELF isEqualToTyped(<? super ACTUAL> expected) {
    objects.assertEqual(info, actual, expected);
    return myself;
  }
```

**Comment by joel-costigliola** [comment]
Ideally we would add `public SELF isEqualTo(ACTUAL expected)` but this does not compile as it conflicts with the current `public SELF isEqualTo(Object expected)`.

I would not be opposed to add `isEqualToTyped`, but before I want to make sure it adds enough benefits to outmatch the API additional bloating.

@PascalSchumacher thoughts ? 
Any feedback appreciated.

**Comment by PascalSchumacher** [comment]
`isEqualToTyped` may safe one or two keystrokes for auto-completion, but in my opinion it is not very readable as the `Typed` part is pure noise when read.

As code is more often read than written I'm not in favor of adding this.

Sorry!

**Comment by Phil-Ba** [comment]
`isEqualToTyped` was only a first idea for the name, `isAkinTo` would be something that seems more elegant. 
But @joel-costigliola made a good point about the API being cluttered already. I thought about adding something liked `AbstractTypedAssert`, but in the very least this would lead to lots of duplicate code to maintain.
@PascalSchumacher Well, normally it safes more than 2 strokes, especially in the edge case of enum names clashing ;) But yeah, normally the IDE should prefer locally declared variables for auto completion, so you can get by with little typing if you declared the expected value somewhere in your method or class .

**Comment by joel-costigliola** [comment]
@Phil-Ba thanks for taking the time to share your thoughts (and closing the issue).
