### ISSUE TITLE
Missing OSGI Import-Package

### ISSUE THREAD

**Issue by Glirox** [joel-costigliola/assertj-core#1250]
#### Summary

Import-Package are missing in OSGI.

```java
 <Import-Package>!org.assertj.core.*</Import-Package>
```

 should probably be changed to :

```java
  <Import-Package>!org.assertj.core.*, *</Import-Package>
```
in the pom.xml (*maven-bundle-plugin*)

#### Example
Several Assertions cannot be used, for example:
```java
 assertThat("<test>testValue</test>").isXmlEqualTo("<test>testValue</test>");
```
throw
```java
java.lang.ClassNotFoundException: org.w3c.dom.Node cannot be found by org.assertj.core_3.10.0 
```
in an OSGI environment

**Comment by joel-costigliola** [comment]
Thanks for reporting this !

**Comment by joel-costigliola** [comment]
@Glirox I have pushed the commit with your fix suggestion, can you give it a try and see it correctly addresses the issue ? (jut build assertj-core with `mvn install` and use 3.11.0-SNAPSHOT in your dependency).

**Comment by Glirox** [comment]
It works ! Thx
