### ISSUE TITLE
Add alias meets(Condition) to has(Condtion)

### ISSUE THREAD

**Issue by rpost** [joel-costigliola/assertj-core#1255]
#### Summary

Can we add handy alias for `org.assertj.core.api.ExtensionPoints.has(Condition condition)` ? It would increase human readability when using "Condition" suffix as in example 

#### Example

```java
Assertions.assertThat(myObject).meets(new IsAwesomeCondition()); // or
Assertions.assertThat(myObject).meets(isAwesomeCondition);
```

**Comment by PascalSchumacher** [comment]
What about using the existing method `is(Condition)`, e.g.:

``` java
assertThat(myObject).is(new Awesome());
assertThat(myObject).is(awesome);
```
?

Related issue: https://github.com/joel-costigliola/assertj-core/issues/938

**Comment by rpost** [comment]
I'm aware of `is`. There are two issues with `is` imo:
1. I don't like naming classes with non-nouns (`Awesome` vs `(Is)AwesomeCondition`)
2. Sometimes my `Condition` instance comes as argument (in some bigger own custom assertion method for example) and then really there is no better name for that instance than `condtion` - this reads bad with `assertThat(myObject).is(condition)` or  `assertThat(myObject).has(condition)`

This boils down to the fact that `meets(Condition)` reads naturally in English while `is/has(Condition)` not.

#938 confirms my feeling.

**Comment by joel-costigliola** [comment]
If we add something I would go for `satisfies` as we already have a version of it when expressing [requirements as `Consumer`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractAssert.html#satisfies-java.util.function.Consumer-).

**Comment by rpost** [comment]
`satisfies` is as good as `meets` :+1: . We can close this issue in favor of #938.
