### ISSUE TITLE
assertThatThrownBy() findbugs problem

### ISSUE THREAD

**Issue by luengnat** [joel-costigliola/assertj-core#1268]
#### Summary
assertThatThrownBy() actually checks whether the lambda throws an exception. Therefore, assertThatThrownBy() can be used alone without having to check the return value. error-prone and findbugs, therefore, identifies a lot of false positives on this. Currently, the way to do is to add `.isNotNull()`. Do you think it makes sense to add another method that is more meaningful to assert that?

#### Example

```java
Assertions.assertThatThrownBy(() -> {
   throw new RuntimeException();
});
```

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

I guess we should remove `@CheckReturnValue` from `assertThatThrownBy`.

Instead of  `.isNotNull()` you could check the type of the thrown exception with `isInstanceOf(ExceptionClass.class)` and/or the message with `hasMessage...()`.
