### ISSUE TITLE
assertThat(String) is not touching ComparableAssert

### ISSUE THREAD

**Issue by karayv** [joel-costigliola/assertj-core#1269]
#### Summary
Using assertj library I cannot check an order of strings.

#### Example
This is possible
```java
assertThat(10).isBetween(9, 11);
```
But such a thing is impossible at the moment
```java
assertThat("ab").isBetween("aa", "ac");
```

**Comment by PascalSchumacher** [comment]
It is possible, but you have use an (ugly) cast:
```java
assertThat((Comparable) "ab").isBetween("aa", "ac");
```

**Comment by joel-costigliola** [comment]
let's try to add `isBetween` to AbstratCharSequenceAssert, I think that should solve the problem.

**Comment by joel-costigliola** [comment]
I'm actually making `StringAssert` implementing [`ComparableAssert`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/ComparableAssert.html) (can't do it for `AbstractCharSequenceAssert` as a CharSequence does not implement `Comparable`).
