### ISSUE TITLE
Why framework not has doesNotContainAnyWhitespaces

### ISSUE THREAD

**Issue by ardmn** [joel-costigliola/assertj-core#1274]
#### Summary
I found method doesNotContainOnlyWhitespaces but what about doesNotContainAnyWhitespaces
I think it is helpful when in code user use String.trim method ? Or May be I can check it by assertj using another way ? Thanks.

**Comment by joel-costigliola** [comment]
Because nobody has contributed it ;-)

**Comment by ardmn** [comment]
@joel-costigliola If you think that it is not bad idea then I want contributed it :)

**Comment by joel-costigliola** [comment]
I think it's not a bad idea :)

**Comment by ardmn** [comment]
I had hope to contribute but the framework already has this method(since 3.11.0) :) 
```AbstractCharSequenceAssert.doesNotContainAnyWhitespaces()```

**Comment by joel-costigliola** [comment]
Ah ah! my bad :smile:
