### ISSUE TITLE
[ComponentLookupException: Unable to find component using matcher] while Component is not visible

### ISSUE THREAD

**Issue by StefanDraeger** [joel-costigliola/assertj-core#1275]
#### Summary
Hello,

i've got a error.
I've got a simple Swing GUI like this

JLabel testLbl = new JLabel("Hallo Welt!");
testLbl.setName("testLbl");
testLbl.setForeground(Color.RED);
testLbl.setVisible(false);
System.out.println(testLbl.toString());
this.add(testLbl);

I want to test this label if it is visible or not.
At the start Time of the application this label is not visible but this label is added to the frame.

In the stacktrace the label is listed

org.assertj.swing.exception.ComponentLookupException: Unable to find component using matcher org.assertj.swing.core.NameMatcher[name='testLbl', type=javax.swing.JLabel, requireShowing=true].

Component hierarchy:
       ....
        javax.swing.JLabel[name='testLbl', text='Hallo Welt!', enabled=true, visible=false, showing=false]
       ....

#### Example

```java
 JLabelFixture label = window.label("testLbl");
 label.requireNotVisible();
```

Thanks for your help.

Best Regards,

Stefan Draeger

**Comment by joel-costigliola** [comment]
This issue should be raised in https://github.com/joel-costigliola/assertj-swing, thanks!
