### ISSUE TITLE
use Predicate's where  Conditions are allowed

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1278]
working on replacing this hamcrest code
```
        assertThat( organizationDtos.size(), is( 1 ) );
        assertThat( organizationDtos.get( 0 ).getName(), is( lab.getName() ) );
```
with
```
        assertThat( organizationDtos ).hasSize( 1 ).has( dto -> true, 0 );
```
I realized that `Condition` can't be implemented as a lambda, however it should be pretty simple to have the system internally create a Condition object that delegates to a `Predicate` wherever a `Condition` is found in the API.

my result is this

```
        assertThat( organizationDtos )
            .hasSize( 1 )
            .have( MyConditions.of( Predicates.extractAndTest( Nameable::getName, Predicate.isEqual( lab.getName() ) ) ) );
```

**Comment by joel-costigliola** [comment]
You actually can build Condition with a lambda but you need to give a description:
```java
Condition<String> jediPower = new Condition<>(JEDIS::contains, "jedi power");
```

**Comment by xenoterracide** [comment]
yeah, I noticed that, I just think that doing that inline when writing is a bit cludgier than it has to be ... I think the nicest solution would be to have the api's directly take the Predicate in a method Overload. Maybe the second nices would be to have an overloaded static factory constructor. Though given my other ticket... I don't need conditions at all I guess... still if I wanted to use them I found this to be unintuitive.

**Comment by joel-costigliola** [comment]
like [`allMatch`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#allMatch-java.util.function.Predicate-) ?

**Comment by xenoterracide** [comment]
yes, or anymatch... ugh... more proof that I shouldn't be doing that while tired.... though this leaves some credence to making a `map` synonym for extracting, since anymatch/allmatch are stream methods, and being streamlike would allow one to think about those...

**Comment by xenoterracide** [comment]
also given OptionalAssert has map, so the apis seem somewhat inconsistent (I get legacy reasons)

**Comment by joel-costigliola** [comment]
Indeed, `extracting` was introduced way before java 8 map ...
