### ISSUE TITLE
Improve Collections matching for simple properties

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1279]
related to #1278 

        assertThat( organizationDtos )
            .hasSize( 1 )
            .have( MyConditions.of( Predicates.extractAndTest( Nameable::getName, Predicate.isEqual( lab.getName() ) ) ) );

is an exceptional amount of code...

I'd much rather write
```
assertThat( dtos ).hasSize(1).haveMapped( Nameable::getName, Predicate.isEqual( lab.getName() );
```
or maybe
```
assertThat( dtos ).hasSize(1).extracting( Nameable::getName ).isEqualTo( lab.getName() );
```
or streamlike
```
assertThat( dtos ).hasSize(1).map( Nameable::getName ).anyMatch( Predicate.isEqual( lab.getName() ));
```

i've managed to simplify my code this way

```
public interface Conditions {

    static <T> Condition<T> of( Predicate<T> predicate ) {
        return new Condition<>( predicate, null );
    }

    static <I,T> Condition<I> extract( Function<I,T> extract, Predicate<T> predicate ) {
        return new Condition<>( i -> predicate.test( extract.apply( i )), null );
    }

}
```

        assertThat( organizationDtos )
            .hasSize( 1 )
            .have( Conditions.extract(  Nameable::getName, Predicate.isEqual( lab.getName() ) ) );

**Comment by joel-costigliola** [comment]
why not simply:
```
 assertThat(organizationDtos).extracting(Nameable::getName)
                             .containsExactly(lab.getName());
```

**Comment by xenoterracide** [comment]
I would also say that having `.map` would seem more natural for some things... but not sure it provides any significant advantage

**Comment by joel-costigliola** [comment]
I would have used `map` but `extracting` was added before java 8 and it also supports extracting by property name.

you can use `extracting` after `hasSize` but in my example `containsExactly` also indirectly checks the size as you have to exactly give all the elements of the collection.

**Comment by joel-costigliola** [comment]
BTW that example you gave,  `isEqualTo` is going to check a collection of Name (with one element only) against lab.getName() which is likely not what you want:
```
assertThat( dtos ).hasSize(1).extracting( Nameable::getName ).isEqualTo( lab.getName() );
```

**Comment by xenoterracide** [comment]
I must have been at the computer too long... I should put it up. Thanks.
