### ISSUE TITLE
AbstractInputStreamAssert should assert isEmpty, isNotEmpty

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1284]
#### Example

```
       static Supplier<InputStream> getDocumentDataById( long id ) {...}

        assertThat(  DocumentRepository.getDocumentDataById( 0 ).get() )
            .hasSameContentAs( new ByteArrayInputStream( new byte[0] ) );
```
thinking it'd be nice to write

```
        assertThat(  DocumentRepository.getDocumentDataById( 0 ).get() ).isEmpty();
```
also looking at verifying that contents of some things aren't empty or maybe `contentIsSize( int size )`

also, I don't appear to get at `hasSameContentAs` when running in list context.

        assertThat( ids )
            .extracting( DocumentRepository::getDocumentDataById )
            .extracting( Supplier::get )
            .doesNotContain( bais )
            .isNotNull();

also maybe a 

```
.hasSize( bytes )
```

**Comment by xenoterracide** [comment]
hmm... thinking a little further on it, may also be worth thinking about simply having a way to delegate an InputStream to a StringAssert/ListAssert (list of lines)
```
assertThat(  DocumentRepository.getDocumentDataById( 0 ).get() ).string( UTF8 ).contains( "foo" )
```

```
assertThat(  DocumentRepository.getDocumentDataById( 0 ).get() ).lines( UTF8 ).hasSize( 32)
```

**Comment by joel-costigliola** [comment]
@xenoterracide why not, can you open a new issue as this is a different topic ? I would go with `asString()` and `toLines()` but let's discuss it in the new issue.
