### ISSUE TITLE
Files#temporaryFolder() will fail if System temporary folder does not exist

### ISSUE THREAD

**Issue by GencoreOperative** [joel-costigliola/assertj-core#1289]
#### Summary

We noticed this issue when working on a docker based build. We found that the Java defined property for `java.io.tmpdir` was defined but the folder did _not exist_. This caused calls to Files#temporaryFolder to fail with the exception:

`org.assertj.core.api.exception.RuntimeIOException: Unable to find temporary directory`

#### Example

```java
    public static void main(String ... args) {
        System.setProperty("java.io.tmpdir", "badger");
        assertThat(new File(System.getProperty("java.io.tmpdir"))).doesNotExist();
        Files.temporaryFolder(); // Will fail
    }
```

The following code sample would resolve this issue. I am happy to raise this as a pull request if this issue is considered valid.

```java
    public static File temporaryFolder() {
        File temp = new File(Files.temporaryFolderPath());
        if (!temp.isDirectory()) {
            throw new RuntimeIOException("Unable to find temporary directory");
        }
        if (!temp.exists() && !temp.mkdirs()) {
            throw new RuntimeIOException("Failed to create temporary directory");
        }
        return temp;
    }
```

**Comment by Sunt-ing** [comment]
If no one is working on this issue, I'd like to work on it. @joel-costigliola

**Comment by joel-costigliola** [comment]
Sure, go for it @Sunt-ing

**Comment by Sunt-ing** [comment]
So when we only set the property for `java.io.tmpdir` like `System.setProperty("java.io.tmpdir", "badger");`,  although there is no temporary folder, we don't want `Files.temporaryFolder();` to fail, right?

**Comment by joel-costigliola** [comment]
What needs to be done here is trying to create the directory if it does not exist

**Comment by scordio** [comment]
This seems to be an old feature which probably doesn't make sense anymore, considering that for example JUnit 4 and 5 have already good support for temporary directories.

I'd propose not to spend effort on it and to deprecate this api.

**Comment by Sunt-ing** [comment]
It seems that we should close this issue now.

**Comment by joel-costigliola** [comment]
let's juts deprecate it and then we can close it

**Comment by Sunt-ing** [comment]
Should I add an annotation `@depracated` before the method `File temporaryFolder()` and then create a PR?

**Comment by joel-costigliola** [comment]
Sure, also add in javadoc a deprected annotation and explain the alternatives (JUnit 5 + JUnit 4)

**Comment by Sunt-ing** [comment]
OK. Please check this simple PR first: [#1851](https://github.com/joel-costigliola/assertj-core/pull/1851)
