### ISSUE TITLE
Missing OSGi Import-Package for dynamically loaded classes - Assumptions failing

### ISSUE THREAD

**Issue by kriegfrj** [joel-costigliola/assertj-core#1290]
#### Summary

#1250 fixed the issue of most of the missing imports when used in an OSGi environment. However, there are a number of other packages that are dynamically accessed by AssertJ at run time using `Class.forName()`. Bnd is not able to automatically determine these references and so they must be explicitly specified in the Import-Package Bnd instruction.

The specific example I ran into was with Assumptions - which sequentially tries to load the assumption classes of JUnit, OpenTest4J and TestNG (in that order). In an OSGi environment, these load attempts will fail unless they are (optionally) imported by the bundle. This issue will only trigger if an assumption fails (as the assumptions only lazily try to load the assumption exception class).

The fix is fairly straightforward, and I have already tested this in my local directory. I hope to submit a PR with the fix shortly.

This and a few other recent OSGi-related bugs that have come up recently (eg, #1250, #1160 and #1181) also perhaps highlights that it would be nice for some kind of integration test in the continuous build process that exercises the OSGi aspects of the implementation.

**Comment by joel-costigliola** [comment]
I do agree it would be nice to validate the OSGi integration, how complicated would that be ?

**Comment by kriegfrj** [comment]
I'm still trying to get my head around OSGi, OSGi testing, and building OSGi using Maven. :smile: I think for someone who had the know-how it would be doable using tycho-surefire-plugin, or perhaps more fully leveraging bnd/bndtools. I don't think I'm quite there yet, sorry. But it might be worth raising as a separate issue for someone else to work on if they have the time, know-how and the desire to scratch this itch.

**Comment by joel-costigliola** [comment]
I was secretly hoping you were that person @kriegfrj :smile:

**Comment by kriegfrj** [comment]
Sorry! Don't get me wrong - I do have the desire to scratch itches like this and I think I could acquire the know-how. It's just that last criteria where I am a bit deficient...

**Comment by joel-costigliola** [comment]
No problem @kriegfrj, all good.
