### ISSUE TITLE
 Create test class without extending AssertJSwingJUnitTestCase class

### ISSUE THREAD

**Issue by widura** [joel-costigliola/assertj-core#1292]
There is a requirement that need to implement AssertJSwingJUnitTestCase class features in our own class hierarchy, But there is a constraints for extending AssertJSwingJUnitTestCase  class. Is it recommended to implement setup Robot and handle FailOnThreadViolationRepaintManager in our own class level.

**Comment by PascalSchumacher** [comment]
Thanks for reporting!

Please report `assertj-swing` issues at https://github.com/joel-costigliola/assertj-swing, this repo is only for `assertj-core`.

Thanks!

**Comment by widura** [comment]
Thanks for the information.
