### ISSUE TITLE
Assertions.fail is causing problems due to @CheckReturnValue

### ISSUE THREAD

**Issue by epeee** [joel-costigliola/assertj-core#1298]
#### Summary
It looks like `Assertions.fail` is no longer `void` starting from AssertJ 3.11.0 (#1294). Since `Assertions` is annotated with `@CheckReturnValue` quite some projects out there might run into troubles.

#### Example

```java
import org.assertj.core.api.Assertions;
import org.junit.Test;

public class AssertionsFailTest {

    @Test
    public void test() {
        Assertions.fail("failing this test on purpose");
    }
}

```

Using this example and errorprone every project which is using `Assertions.fail` will fail now with something like:

```
error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
        Assertions.fail("failing this test on purpose");
```

**Comment by joel-costigliola** [comment]
good point, we will disable it for fail.
I'm away for a few weeks but I'll try to do a service pack for it.
