### ISSUE TITLE
installation instructions ?

### ISSUE THREAD

**Issue by fmorriso** [joel-costigliola/assertj-core#1308]
#### Summary
Nowhere in the FAQ or other documentation can I find anything that tells me how to download and install AssertJ.  Please add that to the home page or in a WiKi page.

#### Example

```java
<add example here>
```

**Comment by joel-costigliola** [comment]
It's in the quickstart section: http://joel-costigliola.github.io/assertj/assertj-core-quick-start.html

**Comment by fmorriso** [comment]
I already looked there and did not find what I was looking for, which is what caused me to open this issue in the first place.

I am using plain, simple, Eclipse Oxygen.3 (March 2018) on a small, Java SE project, trying to use AssertJ for unit testing and having no success at all.

For example, where is the JAR file that I need to reference in order for the import to work properly?  

Am I supposed to use the Eclipse Marketplace to find AssertJ or should I manually reference the (what is its full name?) JAR file for my small little project?

**Comment by PascalSchumacher** [comment]
Hi Fred,

you can download the jar from https://search.maven.org/remotecontent?filepath=org/assertj/assertj-core/3.11.0/assertj-core-3.11.0.jar and reference it in Eclipse.
