### ISSUE TITLE
Additional file assertions?

### ISSUE THREAD

**Issue by ketan** [joel-costigliola/assertj-core#1311]
#### Summary

I'd like to contribute some additional file assertions to core (to check the mode/ownership and other file attributes) if that's something that the core team finds useful.

I'm happy to submit a PR if this is something you find useful.

#### Example

```java
assertThat(someFile)
  .hasMode(....)
  .isExecutable()
  .isReadOnly()
```

**Comment by haruntuncay** [comment]
Hello @ketan,
How are you currently doing on this issue ? I would like to help implement it as well and wanted to ask if you are actively working on it or not so that I won't be stepping on your toes. Please inform me and thanks in advance.

**Comment by ketan** [comment]
I have not started on this, since I did not receive any confirmation if this might be something the core team would accept.

**Comment by haruntuncay** [comment]
Well, I believe the issue being tagged indicates that they are interested.

**Comment by ketan** [comment]
> Well, I believe the issue being tagged indicates that they are interested.

I'm sorry, I did not receive any notification about this. I'm happy to submit a PR. Will likely happen later next week, though.

**Comment by joel-costigliola** [comment]
@haruntuncay if by any chance you have frontend skills (unlike me) could you have a look at https://github.com/joel-costigliola/assertj-core/issues/1485 ? No problem if you can't/don't.

**Comment by haruntuncay** [comment]
@joel-costigliola Unfortunately I can't say I have frontend skills. By the way, I was working on #1238 if that's okay ?

**Comment by tarioch** [comment]
It would be great if there were also some assertions around file size. e.g. hasAtLeastSize() asAtMostSize().

**Comment by joel-costigliola** [comment]
@ketan are you still interested in contributing more file assertions ?
In that case I would prefer to have one PR per assertion as big PRs take too much time to review.

**Comment by joel-costigliola** [comment]
@tarioch sure, do you have a concrete example ? how would the expected size be expressed ?

**Comment by tarioch** [comment]
I would probably keep it simple and keep size as an long in bytes (as specified by https://docs.oracle.com/javase/7/docs/api/java/io/File.html#length()). 
The use case I have it is where we have some report generation and we want to check that at least some file with some content was generated.

**Comment by joel-costigliola** [comment]
Sounds good to me.

**Comment by joel-costigliola** [comment]
I'm reviewing #1614 and I wonder if we should rename the assertion `hasSize` to `hasSizeInBytes` ? thoughts ?

**Comment by ketan** [comment]
I'd suppose `bytes` is implicit, so just having `hasSize` seems pretty clear (to me, at least)

**Comment by joel-costigliola** [comment]
@PascalSchumacher  @scordio @epeee thoughts ?

**Comment by scordio** [comment]
Not sure if it's too late for the following reasoning.

Is it worth to deviate from the original `length` name from `java.io.File`? There are already other examples in `AbstractFileAssert` having one-to-one mapping to the `File` api, like `canRead` and `canWrite`.

Clearly, `File` is not the best example of clarity and assertj could fill the gap, but on the other hand I would expect that `File` will be more and more superseded by the [NIO2 `Path` alternative](https://www.oracle.com/technetwork/articles/javase/nio-139333.html#1).

Sticking to the original naming, a parameter which implicitly expects `bytes` would be totally acceptable to me.
