### ISSUE TITLE
assertThat(

### ISSUE THREAD

**Issue by novaterata** [joel-costigliola/assertj-core#1318]
This worked in 3.10, but not in 3.11.1
I have a generic `List<Log>` where Log is an interface type
I call:

    assertThat(aLogList).contains(aLog)

And I get the following AssertionException:

Expecting:
  <[com.foo.$Impl_Log@24a35978]>
to contain sequence:
  <[com.foo.$Impl_Log@24a35978]>

As you can see, the list contains the exact same object as the expected.

**Comment by novaterata** [comment]
So the log is a jmockit `@Mocked` jmockit is notoriously chaotic with this kind of thing, so it's probably not something you can control, but if you do want to try to fix it, then use a jmockit Mocked field

**Comment by novaterata** [comment]
Nevermind, I just replaced it with my own anonymous inner class so jmockit is not the culprit.

**Comment by novaterata** [comment]
I replaced the anonymous inner class with a named class with equals / hashcode override and it still failed

**Comment by novaterata** [comment]
Ok, so it IS a jmockit issue. It's the list being returned by a `@Mocked` object. After replacing all the `@Mocked` with `@Injectable` the contains works as expected. Closing

**Comment by joel-costigliola** [comment]
Happy you could solve it!
