### ISSUE TITLE
how to verify Descending order with assertJ assertions?

### ISSUE THREAD

**Issue by siva90144** [joel-costigliola/assertj-core#1326]
Hi,

I have a scenario as below.
arrayList countryList =new arrayList();
I have taken arrayList and added all countries to it . Now I need to verify those are in ascending/Descending order or not.
//working fine for Ascending  order.
assertThat(sortAscending(countryList)).as("Ascending Sorted order is: "+countryList).isSorted();

is there is a way to verify for Descending  order with assertJ. I have seen "isSortedAccordingTo" . it is using comparator. But in my implementation there is no comparator(it is not required for me to implement comparator). 

is any other assert will verfiy Descending  order? any example with it ?

Thanks in advance for your help.

**Comment by joel-costigliola** [comment]
is that the same issue as https://github.com/joel-costigliola/assertj-examples/issues/43 ?

**Comment by siva90144** [comment]
Yes Joel. Its extension to that

**Comment by joel-costigliola** [comment]
the only option at the moment is to use `isSortedAccordingTo` and define your reverse comparator.
