### ISSUE TITLE
usingElementComparatorIgnoringFields does not work for nested objects

### ISSUE THREAD

**Issue by maximilianschreiber** [joel-costigliola/assertj-core#1333]
#### Summary
Assertions fail for Lists with **.containsExactly** (and other variations) when using **.usingElementComparatorIgnoringFields** on e.g. and ID when nested objects are used, that
also have an ID that should be ignored for comparison.

#### Example
Simple test in Kotlin to demonstrate the behaviour:

```kotlin
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomTest {

    class CustomDTO(val id : Long, val name: String, var nested : CustomDTO?)

    private var myDTO = CustomDTO(id = 12, name="test123", nested=null)
    private var myDTO2 = CustomDTO(id = 123, name="test123", nested=null)


    @Test
    fun testsDTOListContainsIgnoringID(){
        
        //success
        val myDTOList = listOf(myDTO)
        assertThat(myDTOList)
                .usingElementComparatorIgnoringFields("id")
                .containsExactly(myDTO2)

    }

    @Test
    fun testNestedDTOWithExplicitNameComparator(){
        myDTO.nested = myDTO2
        myDTO2.nested = myDTO

        //success (even for nested objects) since just names are compared
        val myNestedDTOList = listOf(myDTO)
        assertThat(myNestedDTOList)
                .usingElementComparatorOnFields("name")
                .containsExactly(myDTO2)

    }

    @Test
    fun testNestedDTOWithIgnoringId(){
        myDTO.nested = myDTO2
        myDTO2.nested = myDTO

        //fails
        val myNestedDTOList = listOf(myDTO)
        assertThat(myNestedDTOList)
                .usingElementComparatorIgnoringFields("id")
                .containsExactly(myDTO2)

    }
}
```

**Comment by joel-costigliola** [comment]
It is the current behavior as documented in the [javadoc](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#usingElementComparatorIgnoringFields-java.lang.String...-):
> Note that the comparison is not recursive, if one of the fields/properties is an Object, it will be compared to the other field/property using its equals method. 

A new recursive comparison api (#1002) is going to address this issue and more flexibility on  expressing how to compare objects recursively.
