### ISSUE TITLE
Introspection error on public final fields of parent classes

### ISSUE THREAD

**Issue by Gregoriz** [joel-costigliola/assertj-core#1337]
IsEqualToComparingFieldByField and IsEqualToComparingFieldByFieldRecursivly are failing to access parent classes public final properties.

Example:

```
class A {
    public final AnObject someProp;

    public A(AnObject someProp) {
        someProp = someProp
    }
} 
```

```
class B extends class A { ... }
```
```
assertThat(new B(toto).isEqualToComparingFieldByFieldRecursivly(new B(toto));
```

will throw an IntrospectionError.

Sorry, I can't give you the full stack as it's on my working station and access to GitHub is disabled.

I'll try to come back during the weekend with a more detailed stack if needed.

**Comment by Gregoriz** [comment]
Sorry for formatting. I'm on mobile and GitHub works horribly. I can't edit my message :/

**Comment by joel-costigliola** [comment]
Hi @Gregoriz, could you give a full example so that I can easily reproduce the bug ?
Thanks in advance!

**Comment by Gregoriz** [comment]
It can't reproduce it at the moment. I close the issue and will check again at work on monday.
