### ISSUE TITLE
collection on entity matching issue, no way to flatMap?

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1339]
#### Summary

So my colleague was asking how to simplify this... and I've realized I can't quite figure it out either

#### Example

```java
     SessionSearchCriteria found = repo.findById( ssc.getId() ).get();
        assertThat( found.getSearchCategories() ).containsExactlyInAnyOrder( sc1, sc2 ); # works
 
       assertThat( found ) # I think this should be the same as above
            .extracting( SessionSearchCriteria::getSearchCategories ).hasSize( 2 ) # can't flatExtracting
            .containsExactlyInAnyOrder(  sc1,  sc2  );
```
```
java.lang.AssertionError: 
Expected size:<2> but was:<1> in:
<[[SearchCategory{id=13}, SearchCategory{id=14}]]>
```

i'm betting Set.of( sc1, sc2 ) would work in java 11... but, is there another way? I tried a few more things than this, and can't seem to get it because of the singular to plural

something like this
```java
class A {
     public boolean equals( Object o ) { return o instanceof A }
}
class B {
    Collection<A> getAs() { return Arrays.asList( new A() ); }
}
assertThat( new B() ).extracting(B::getAs)>containsExactlyInAnyOrder(new A() )
```

**Comment by joel-costigliola** [comment]
Before 3.11.0 extracting for Object was taking a vararg so even if you were extracting one value only you would end up with a singleton list, in your case it turns out that this single value is also a List.

In 3.11.0 AssertJ learnt to extract single value as an Object (and not a singleton List of the extract value) as described here: http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.11.0-extracting

I'm guessing you are not using 3.11.0, am I right ?

**Comment by xenoterracide** [comment]
yeah looks like we're using 3.9.1, though, I don't know why spring boot doesn't upgrade the 3.x line more rapidly...

**Comment by filiphr** [comment]
As far as I know the policy of the Spring Boot team is to only update patch versions within a patch update.

Meaning that Spring Boot 2.0.x will only update 3.9.x series of AssertJ. The update to a next minor version will occur only in the 2.1.x release. 

What we are doing is just to update it ourselves by using `<assertj.version>3.10.0</assertj.version>`

**Comment by xenoterracide** [comment]
yes, that's the policy-ish but I think it depends on the specific upstream stuff too, but yes

**Comment by xenoterracide** [comment]
I'm gonna go ahead and close this as needs to be upgraded on our side
