### ISSUE TITLE
Assertions#assertThatThrownBy` without chained assertions should not cause static code analysis error

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#1345]
```java
Assertions.assertThatThrownBy(() -> new Exception());
```

causes the following error prone error:

`[CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue`

but this is a valid use-case because:

```java
Assertions.assertThatThrownBy(() -> {});
```

fails with:

`java.lang.AssertionError: Expecting code to raise a throwable.`

**Comment by lukaszrek** [comment]
`assertThatThrownBy` has no longer `@CheckReturnValues`  annotation, however `Assertions` class does have it. So this issue is still valid. Can it be reopened or should I create new one?
