### ISSUE TITLE
Replace Extractor with Function

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1348]
#### Summary
Now that the base supported version of AssertJ is Java 8. Won't it make sense to deprecate `Extractor` (make it extend `Function`) and use `Function` everywhere instead of `Extractor`.

I found one inconsistence (in my opinion) that could be resolved with this.

In `AbstractIterableAssert`

```
public AbstractListAssert<?, List<? extends Tuple>, Tuple, ObjectAssert<Tuple>> extracting(@SuppressWarnings("unchecked") Function<ELEMENT, ?>... extractors)
```

```
public <V> AbstractListAssert<?, List<? extends V>, V, ObjectAssert<V>> extracting(Extractor<? super ELEMENT, V> extractor)
```

The first one returns `Tuple` (which is fine as it is a varargs) and the second one return a normal object assert of the extractor result. On top of that one can't use the functions with wildcards in actual.

If you are interested I can try to provide a PR that cleans this up

**Comment by joel-costigliola** [comment]
I agree to deprecate `Extractor` in favor of `Function`.

I'm not sure what your are suggesting we do with `extracting(Extractor<? super ELEMENT, V> extractor)` but it  shouldn't be replaced by `extracting(@SuppressWarnings("unchecked") Function<ELEMENT, ?>... extractors)` because when you have only one value to extract, I does not make sense to force users to use tuples of one value.

**Comment by filiphr** [comment]
I know that it doesn't make sense to have a single tuple. I even noticed that in one of our tests I had to use a `Tuple` for a single value and I was wondering why that happened (I didn't investigate that further).

What I am proposing is to make the `Extractor` extend the `Function` and then:

* Replace `extracting(Extractor<? super ELEMENT, V> extractor)` with `extracting(Function<? super ELEMENT, V> extractor)`

* Replace `extracting(@SuppressWarnings("unchecked") Function<ELEMENT, ?>... extractors)` with `extracting(@SuppressWarnings("unchecked") Function<? super ELEMENT, ?>... extractors)`

If you agree I can prepare a PR for this

**Comment by joel-costigliola** [comment]
I'm happy with that.
