### ISSUE TITLE
add migration script from JUnit5 to AssertJ

### ISSUE THREAD

**Issue by tomekkaczanowski** [joel-costigliola/assertj-core#1350]
#### Summary
There is Junit4 to AssertJ script available http://joel-costigliola.github.io/assertj/assertj-core-converting-junit-assertions-to-assertj.html. Unfortunately, the script is uselesess for JUnit5, mostly due to change in order of message part of assertion.

I already have the script (see http://testinglikeaboss.com/tips-tricks/migrating-from-junit-5-assertions-to-assertj/) but need to add it to assertj-core. I will do it.

**Comment by joel-costigliola** [comment]
fixed by https://github.com/joel-costigliola/assertj/issues/89.
