### ISSUE TITLE
ObjectArrays#assertHasOnlyElementsOfType throws NPE for arrays containing null

### ISSUE THREAD

**Issue by yrodiere** [joel-costigliola/assertj-core#1356]
#### Summary

`ObjectArrays#assertHasOnlyElementsOfType` throws a NullPointerException when passed an array containing a null element.

PR coming.

#### Example

```java
Assertions.assertThat(Arrays.array(null, "notNull")).hasOnlyElementsOfType(String.class)
```

=> NullPointerException

**Comment by joel-costigliola** [comment]
Thanks @yrodiere  for reporting this and providing a PR!

**Comment by yrodiere** [comment]
No problem, it will help me too :)
Thanks for all the good work!

**Comment by joel-costigliola** [comment]
Fixed by https://github.com/joel-costigliola/assertj-core/pull/1357
