### ISSUE TITLE
Clean way to have assertions on properties of custom exception types?

### ISSUE THREAD

**Issue by davidmichaelkarr** [joel-costigliola/assertj-core#1358]
I like to use "catchThrowable()" to perform assertions on exceptions, but it gets a little messy when I have to perform assertions on properties of custom exceptions, which requires a cast to get access to the custom type, so I can then perform the assertion on the casted object.

Is there a cleaner way to do this that isn't described in the documentation?

**Comment by davidmichaelkarr** [comment]
I'm guessing the answer is "catchThrowableOfType".  Am I missing a link for a full API reference that would show me these things?

**Comment by joel-costigliola** [comment]
documentation completed: https://assertj.github.io/doc/#assertj-core-exception-assertions-bdd-strongly-typed-style
