### ISSUE TITLE
Expose all AssertJ global configuration through ConfigurationProvider

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1361]
#### Summary

Follow the same approach for [global Representation configuration ](https://assertj.github.io/doc/#assertj-core-custom-representation-default-global-scope) with [ConfigurationProvider](https://github.com/joel-costigliola/assertj-core/blob/0b623f70bbe9de4d4785b7b3317528595d898c78/src/main/java/org/assertj/core/configuration/ConfigurationProvider.java) for:

- accessing or not private fields
- lenient date parsing
- registering custom `DateFormat`
- the maximum elements that would be printed from one iterable/array/map
- the maximum length for an iterable/array to be displayed on one line

**Comment by filiphr** [comment]
Thanks for creating this @joel-costigliola. Just my 2 cents about this.

Not everything needs to have an SPI. Maybe for some of the properties a single `SettingsProvider` or whatever the name would be enough as then people can override that and provide their own changes. In any case I think everything you mentioned into this fits into a single SPI (in my opinion)

**Comment by joel-costigliola** [comment]
This issue should likely be split, one important configuration to support is related to https://github.com/joel-costigliola/assertj-core/pull/1360#issuecomment-470299508

**Comment by joel-costigliola** [comment]
Here's what users will see if they registered their configuration:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.assertj.configuration.example.CustomConfigurationTest

AssertJ has found and applied the following registered configuration: org.assertj.configuration.example.MyConfiguration
- representation .................................. = BinaryRepresentation
- comparingPrivateFieldsEnabled ................... = false
- extractingPrivateFieldsEnabled .................. = false
- bareNamePropertyExtractionEnabled ............... = false
- lenientDateParsingEnabled ....................... = true
- additionnal date formats ........................ = [yyyy_MM_dd, yyyy|MM|dd]
- maxLengthForSingleLineDescription ............... = 81
- maxElementsForPrinting .......................... = 1001
- removeAssertJRelatedElementsFromStackTraceEnabled = false

Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.305 sec
```
