### ISSUE TITLE
Assertion to check that a map contains exactly all entries of another map

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1367]
#### Summary

Assert that a map contains exactly all entries of another map. 

Basically an alternative to `containsExactly` with another `Map` instead of varargs

#### Example

```java

Map<Ring, TolkienCharacter> ringBearers = new HashMap<>();
ringBearers.put(nenya, galadriel);
ringBearers.put(narya, gandalf);
ringBearers.put(vilya, elrond);
ringBearers.put(oneRing, frodo);

Map<Ring, TolkienCharacter> elvesRingBearers = new HashMap<>();
elvesRingBearers.put(nenya, galadriel);
elvesRingBearers.put(narya, gandalf);
elvesRingBearers.put(vilya, elrond);

// assertion will succeed
assertThat(ringBearers).containsExactlyAllEntriesOf(ringBearers);

// assertion will fail
assertThat(ringBearers).containsExactlyAllEntriesOf(elvesRingBearers);
```

**Comment by joel-costigliola** [comment]
Agreed!

**Comment by filiphr** [comment]
Realised that I don't really need this one. In any case I created a PR with the feature implementation

**Comment by filiphr** [comment]
@joel-costigliola thanks for accepting my PR #1368. Now that it is merged we can close this I think? I am not closing it on purpose in order to leave it up to you to mark with the appropriate milestone
