### ISSUE TITLE
Extracting function from entries for Map

### ISSUE THREAD

**Issue by ebundy** [joel-costigliola/assertj-core#1370]
#### Summary
I like very much the extracting function feature of AssertJ.  
With `Iterable` objects, it is really fine as that is defined in the base class : 
 `AbstractIterableAssert.extracting(Function<? super ELEMENT, ?>... extractors)`.

But for `Map` objects, that is not possible.
I didn't find any way to extract data from the Map entries as we could do from List elements and that is really annoying because it forces me to rely on `equals()` method of the asserted objects in an undesirable way.  And that is an anti pattern.

#### Here is a simple unit test of what I want to do (`extractingFromEntry()` is the introduced method): 

```
void findNbEmployeeByManager() {
	Map<Manager, Integer> nbEmployeeByManager = company.findNbEmployeeByManager();
	Assertions.assertThat(nbEmployeeByManager)
			  .hasSize(2)
			  .extractingFromEntry(e -> e.getKey().getName(),
					    	            e -> e.getKey().getLastName(),
							    e -> e.getValue())
			  .containsExactlyInAnyOrder(Tuple.tuple("scoubi", "shis", 1), Tuple.tuple("scoubi", "doe", 2));
}
```
In this way no need to override` Manager.equals()` to do assertion on its fields.  

As said, I didn't find a way to do that.
So I implemented it.

If currently this feature doesn't exist, would it be possible to integrate that ?

#### Code change in AbstractMapAssert
```  
 @CheckReturnValue
 public AbstractListAssert<?, List<? extends Tuple>, Tuple, ObjectAssert<Tuple>> extractingFromEntry(@SuppressWarnings("unchecked") Function<? super Map.Entry<K,V>, ?>... extractors) {
    // combine all extractors into one function
  Function<Map.Entry<K, V>, Tuple> tupleExtractor = objectToExtractValueFrom -> new Tuple(Stream.of(extractors)
                                                                                        .map(extractor -> extractor.apply(objectToExtractValueFrom))
                                                                                        .toArray());
    List<Tuple> tuples = stream(actual.entrySet().spliterator(), false).map(tupleExtractor)
                                                                       .collect(toList());
    return newListAssertInstanceForMethodsChangingElementType(tuples);
 }
```

**Comment by ebundy** [comment]
Thanks for this way.  
I think that it is still worth. This option has too much technical/boiler plate code.
I find personally my way already too much verbose. The `e.getKey()/getValue().getFoo()` pattern is terrible... that is not very fluent.

Something like that I find more fluent would be (suppose we assert a  `Map<Foo,Bar>)`: 
````
.extractingFromKey(Foo::getValue, Foo::getOtherValue)
.extractingFromValue(Bar:getValue, Bar::getOtherValue)
.contains(tuple("foo", "otherFoo", "bar", "otherBar"));
````

**Comment by joel-costigliola** [comment]
You can't chain `extractingFromKey` with `extractingFromValue` because after `extractingFromKey` you don't have the initial map at your disposal but a list of tuple.

The best we can do is:
```
assertThat(nbEmployeeByManager).extracting(e -> e.getKey().getName(),
                                           e -> e.getKey().getLastName(),
                                           e -> e.getValue())
	                       .contains(tuple("scoubi", "shis", 1));
```

**Comment by ebundy** [comment]
I get it. So, I will implement the initial proposition with the `extracting()` overload you propose. It is already not bad at all.

**Comment by joel-costigliola** [comment]
Need to think about it but at the moment `extractingFromEntries` would work or defining several `extracting` methods taking 1 parameter, 2 parameters, 3 parameters,  ... up to 6 should be alright.

I'll probably go with `extractingFromEntries` to avoid bloating the api but vararg comes with a nasty price, to avoid the heap pollution warning, you need to use the `SafeVararg` annnotation and set the method as final which then breaks soft assertions and assumptions. This solution has already been implemented but quite a bit of work unfortunately.

**Comment by ebundy** [comment]
I understand. Take your time and if you get a good idea tell me. 
About bloating the API I agree. For some AssertJ client classes, when I am looking for an unusual method it is sometimes hard to find it even with auto-completion.
Concerning the var-args limitation against soft assertions, does the fact that `extractingFromEntries()` is designed to extract multiple things to perform multiple assertions should not be considered like a feature which the need for soft assertions is less important ?  

What do you mean by : 

> This solution has already been implemented but quite a bit of work unfortunately.

**Comment by joel-costigliola** [comment]
Soft assertions are important, they should work for all assertions out of the box. It would not be easy for users to understand why some work and some don't.

Your last suggestion is already covered by the vararg option where you only pass one `Function<Entry, Tuple>`, I would prefer going the vararg since it is a bit lighter for users.

You can follow the same implementation as `AbstractObjectAssert#extracting`, see:
- https://github.com/joel-costigliola/assertj-core/blob/d39568abf3e33a37216a3fa68f51bc8b4386596c/src/main/java/org/assertj/core/api/AbstractObjectAssert.java#L638
- https://github.com/joel-costigliola/assertj-core/blob/0b623f70bbe9de4d4785b7b3317528595d898c78/src/main/java/org/assertj/core/api/ObjectAssert.java#L46
- https://github.com/joel-costigliola/assertj-core/blob/0b623f70bbe9de4d4785b7b3317528595d898c78/src/main/java/org/assertj/core/api/ProxyableObjectAssert.java

Don't worry too much about the var-arg implementation, I'll help you along the way when you need it.

**Comment by ebundy** [comment]
Agreed for soft assertions. Clearest is better.
Thanks for the pointers. I will check that.   

**Issue solving in progress...**

**Comment by ebundy** [comment]
Hello @joel-costigliola

I progressed on the feature. However I have some doubts on what the test class [Map_special_assertion_methods_in_assumptions_Test](https://github.com/joel-costigliola/assertj-core/blob/master/src/test/java/org/assertj/core/api/assumptions/Map_special_assertion_methods_in_assumptions_Test.java) actually asserts. 
The javadoc says "verify that assertions final methods or methods changing the object under test in {@link MapAssert} work with assumptions 
 * (i.e. that they are proxied correctly in {@link ProxyableMapAssert})."
So I would add my test case here too but by reading the test code I notice that it tests methods that are proxified and others that are not. It tests final methods but not only.  
 Besides, ok `assumeThat()` returns a proxy as a `Map` is passed but `ProxifyMethodChangingTheObjectUnderTest` doesn't seem required here. Passing by the `ProxyableMapAssert` proxy should be enough and that seems to be guaranteed by `assumeThat(Map<K, V> actual)` and `newListAssertInstance(List<? extends E> newActual)` overrided  as required in `ProxyableMapAssert`

 I don't like the idea to add tests to add tests. So could you explain the purpose of these tests  ? 
Thanks and have a nice week end.

**Comment by joel-costigliola** [comment]
Some of the methods have simply vararg generic parameters which were overridden in `MapAssert` and annotated with `@SafeVarargs` and made `final`.

`ProxifyMethodChangingTheObjectUnderTest` is required for `extractingFromEntries` since we need to proxy the resulting tuples list as in `AbstractMapAssert.extracting`. You will need to add `extractingFromEntries` to `SoftProxies.METHODS_NOT_TO_PROXY` otherwise it won't be picked up by `ProxifyMethodChangingTheObjectUnderTest`.

The purpose of this class is just to make sure Map assumptions work as expected, if we fail to proxy the list of tuples got from `extractingFromEntries` then assumptions won't work correctly. 

`Map_special_assertion_methods_in_assumptions_Test`  has tests for `extracting` and `flatExtracting`.

**Comment by joel-costigliola** [comment]
I think we should add an overloaded variation of the new assertion taking only one parameter and returning a list of value instead of a list of tuple.

Ex:
```java
assertThat(nbEmployeeByManager).extractingFromEntries(entry -> entry.getKey().getName())
                               .contains("foo", "bar", "baz"));
```
The rationale is if we don't add it, even if you extract one value you still have to use a list of tuple (of one value in that case). It is not user friendly to ask users to build tuples for one value.

```java
// without the oveloaded variation
assertThat(nbEmployeeByManager).extractingFromEntries(entry -> entry.getKey().getName())
                               .contains(tuple("foo"), tuple("bar"), tuple("baz")));
```

**Comment by ebundy** [comment]
I probably was not clear enough. 

>  You will need to add extractingFromEntries to SoftProxies.METHODS_NOT_TO_PROXY otherwise it won't be picked up by ProxifyMethodChangingTheObjectUnderTest.

Are you sure ? I added the method name to `SoftProxies.METHODS_CHANGING_THE_OBJECT_UNDER_TEST` and in this way it is picked up by ProxifyMethodChangingTheObjectUnderTest in the intercept() method.
In this way, soft assertion appeared working.   

Actually, I don't need to add "extracting" or "flatExtracting" in `SoftProxies` referenced methods to make  `Map_special_assertion_methods_in_assumptions_Test` successful. That's why I asked about the role of all these tested method.  
According to my understanding, for assumptions, we pass systematically by `AssumptionMethodInterceptor`. So it doesn't matter if the current Assert object changes the object under test because the interceptor will recreate for us the proxy.    
To illustrate things,  I commited and pushed a part of my work : https://github.com/ebundy/assertj-core/tree/issue-1370 and to illustrate my proposes I removed temporarily the method names referenced in `SoftProxies`.    
It doesn't prevent this test to succeed : 

```` 
mvn clean test -Dtest=Map_special_assertion_methods_in_assumptions_Test

**Comment by ebundy** [comment]
Concerning the overload, I absolutely agreed.

**Comment by joel-costigliola** [comment]
@ebundy you are actually right! For assumptions you don't need to change `SoftProxies.METHODS_NOT_TO_PROXY` it is needed for  soft assertions only.

If you want feedback, you can submit a PR even if you haven't completed everything.

**Comment by ebundy** [comment]
All right. It is not completely finished but it is close. Probably some tests should be added in `BDDSoftAssertionsTest`.  About the `SoftProxies` class and more particularly `METHODS_NOT_TO_PROXY` I think that it should be really be reviewed because either some parts of it are not tested or some parts are not useful. I completely removed it and all tests pass. As explained earlier only `METHODS_CHANGING_THE_OBJECT_UNDER_TEST` matters to make soft assertion working. Besides I am not sure at all that all referenced methods in be required. 
I do the pull request with this change. No because I am sure that this part to be removed but because if it turns out that is is necessary it a serious problem that no automatic test may detect that.
