### ISSUE TITLE
MapAssert.containsOnlyKeys() with Iterable overload

### ISSUE THREAD

**Issue by ebundy** [joel-costigliola/assertj-core#1371]
#### Summary
`MapAssert.containsOnlyKeys()` accepts a var-args but doesn't have an overload with `Iterable<>`, contrary to `IterableAssert`.

#### Example

```java 

void findEmployeesByCountry(Company company) {
        List<Country> countries = ...;
	Map<Country, List<Employee>> employeesByCountry = company.findEmployeesByCountry(countries);
	Assertions.assertThat(employeesByCountry)
			 .containsOnlyKeys(countries.stream().toArray(Country[]::new));         

	Assertions.assertThat(employeesByCountry.get())
}
```

That 

```java 
.containsOnlyKeys(countries.stream().toArray(Country[]::new));         
```
or  

```java 
.containsOnlyKeys(countries.toArray(new Country[countries.length]));         
```

should be just :

```java 
.containsOnlyKeys(countries);  
```

**Comment by joel-costigliola** [comment]
Sure.

**Comment by bastikempken** [comment]
I am working on this issue, and will provide a pull request soon.

**Comment by bastikempken** [comment]
@joel-costigliola  I've implemented a possible solution on https://github.com/joel-costigliola/assertj-core/pull/1373
@ebundy It's my first participation, too and and i already worked on it. but i would really appreciate your feedback

**Comment by ebundy** [comment]
@bastikempken The next time, out of courtesy for the person that asked the question, please wait for that he/she tells whether he/she would implement that.  
About the implementation : not bad but it could be much dry.  You created new methods in each layer to perform the same thing. You don't need because the single variation is `K[]` becomes `Iterable<K>`. Passing from the one to the other is straight simple. 
After I think that that is the kind of thing that deserves some discussions with the API owner and its collaborators.  
I would do things in this way  or in the other way : 
```` JAVA
public <K, V> void assertContainsOnlyKeys(AssertionInfo info, Map<K, V> actual,
                                            @SuppressWarnings("unchecked") K... keys) {
    assertContainsOnlyKeys(info, actual, java.util.Arrays.asList(keys));
}


public <K, V> void assertContainsOnlyKeys(AssertionInfo info, Map<K, V> actual,
                                             Iterable<K> keys) {
    assertNotNull(info, actual);
    failIfNull(keys);
    int sizeOfKeys = sizeOf(keys);
    if (actual.isEmpty() && sizeOfKeys == 0) {
      return;
    }
    failIfEmpty(sizeOfKeys);

    Set<K> notFound = new LinkedHashSet<>();
    Set<K> notExpected = new LinkedHashSet<>();

    compareActualMapAndExpectedKeys(actual, keys, notExpected, notFound);

    if (!notFound.isEmpty() || !notExpected.isEmpty())
      throw failures.failure(info, shouldContainOnlyKeys(actual, keys, notFound, notExpected));

}
```` 

With some minor changes in the helper methods and that's all.

**Comment by ebundy** [comment]
@bastikempken Really no problem. Thanks for that.  

I think you refer to the `failIfEmpty(int keysize)` invocation. 
You could keep the two distinct error messages (which is rather good)  by allowing each distinct method to supply the error message : a `Supplier<String> errorMsgIfKeyObjectEmpty` parameter could do the job. In this case,  I think that define a third method with the Supplier as parameter could make sense.

In this way : 

````java
public <K, V> void assertContainsOnlyKeys(AssertionInfo info, Map<K, V> actual,
                                            @SuppressWarnings("unchecked") K... keys) {
    assertContainsOnlyKeys(info, actual, java.util.Arrays.asList(keys), ()-> "The array of keys to look for should not be empty");
}

public <K, V> void assertContainsOnlyKeys(AssertionInfo info, Map<K, V> actual,
                                             Iterable<K> keys) {
    assertContainsOnlyKeys(info, actual, keys, ()-> "The keys Iterable to look for should not be empty");
}

private <K, V> void assertContainsOnlyKeys(AssertionInfo info, Map<K, V> actual,
                                             Iterable<K> keys, Supplier<String> errorMsgIfKeyObjectEmpty) {
    assertNotNull(info, actual);
    failIfNull(keys);
    int sizeOfKeys = sizeOf(keys);
    if (actual.isEmpty() && sizeOfKeys == 0) {
      return;
    }
    failIfEmpty(sizeOfKeys);

    Set<K> notFound = new LinkedHashSet<>();
    Set<K> notExpected = new LinkedHashSet<>();

    compareActualMapAndExpectedKeys(actual, keys, notExpected, notFound);

    if (!notFound.isEmpty() || !notExpected.isEmpty())
      throw failures.failure(info, shouldContainOnlyKeys(actual, keys, notFound, notExpected));

}
````

**Comment by ebundy** [comment]
@bastikempken It seems very good things. The supplier didn't make really sense here. I didn't remember why I proposed that. See you on other issues :)
