### ISSUE TITLE
Add anysatisfy  for Map

### ISSUE THREAD

**Issue by almondtools** [joel-costigliola/assertj-core#1377]
#### Summary

Allow to verify a bunch of assertions for any key-value pairs of a Map. This would serve the symmetry of the map assert. See #1030 (allSatisfy for Maps) and #889 (anySatisfy for Iterables).

#### Example

```java

class Person {
  public String firstName;
  public String lastName;

  public Person(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }
}

Person max = new Person("Max","Mustermann");
Person min = new Person("Min","Mustermann");
Map<Person, Person> knows = new HashMap<Person, Person>();
knows.put(max, min);
knows.put(max, max);
assertThat(knows).anySatisfy((key, value) -> {
  assertThat(key.firstName).isEqualTo("Max");
  assertThat(key.lastName).isEqualTo("Mustermann");
  assertThat(value.firstName).isEqualTo("Min");
  assertThat(value.lastName).isEqualTo("Mustermann");
});```

**Comment by joel-costigliola** [comment]
I agree, @almondtools would you like to contribute it?

**Comment by almondtools** [comment]
I can try, yet I have a question:

I tried to understand the actual code for `assertAllSatisfy` in `Maps` and it diverges from the `assertAllSatisfy` and `assertAnySatisfy` in `Iterables` (the latter aggregates the Information, the former simply fails with the delegated assertion). 

```java
actual.entrySet().stream()
          .forEach(entry -> entryRequirements.accept(entry.getKey(), entry.getValue()));
```

`assertAnySatisfy` for `Maps` cannot be implemented similar to `assertAllSatisfy` in `Maps` since the method should return succesful if only one assertion is succesful (swallowing all failed assertions). So I would prefer also to touch `assertAllSatisfy` in Maps such that `all` and `any` look similar after the contribution. Is this ok for you?

**Comment by joel-costigliola** [comment]
There was an improvement done for `assertAllSatisfy` in `Iterables` to gather all elements not satisfying the requirements. It's an improvement we want to also for maps (I have just created https://github.com/joel-costigliola/assertj-core/issues/1379 to track that).

**Comment by almondtools** [comment]
The code for #1379 was already written as your answer arrived me. Fortunately I kept both changes separately. I think you can review this one.

The Javadoc does yet not contain version information, I am not certain whether to add a hard version or whether there is a variable that is updated at the next release time. So if you do not want to adjust it yourself, give me a hint.

**Comment by almondtools** [comment]
Notify me if I should package a pull request.

**Comment by joel-costigliola** [comment]
You can create a PR when you feel the code is ready to be reviewed or want some feedback even if the implementation is partial.
