### ISSUE TITLE
Make constructor of ListAssert that takes a Stream public

### ISSUE THREAD

**Issue by korthout** [joel-costigliola/assertj-core#1380]
#### Summary
The constructor `ListAssert(java.util.stream.Stream<? extends ELEMENT> actual)` is currently protected. Due to constraints of [Qulice](https://www.qulice.com/) and [Elegant Objects](https://www.elegantobjects.org/#principles) (i.e. no static methods allowed), I'd like to be able to use the constructors. Their visibility must be public in order for them to be used anywhere. Please make these constructors public.

#### Example

```java
new ListAssert<>(
    new ArrayList<>().stream()
).isEmpty();
```

**Comment by joel-costigliola** [comment]
Done.

**Comment by korthout** [comment]
Wow you're quick! 🥇 Thanks!
