### ISSUE TITLE
ZippedElementsShouldSatisfy not escaping elements 

### ISSUE THREAD

**Issue by AHeise** [joel-costigliola/assertj-core#1387]
#### Summary

The failure string constructed by ZippedElementsShouldSatisfy does not properly escape formatting symbols leading to extra formatting args.

```java
super("%n" +
          "Expecting zipped elements of:%n" +
          "  <%s>%n" +
          "and:%n" +
          "  <%s>%n" +
          "to satisfy given requirements but these zipped elements did not:" + describe(zipSatisfyErrors),
          actual, other);
```

#### Example

```java
    @Test
    void showFormatIssue() {
        assertThat(List.of("%s")).zipSatisfy(List.of("%d"), (a, e) -> assertThat(a).isEqualTo(e));
    }
```

```
java.util.MissingFormatArgumentException: Format specifier '%s'

	at java.base/java.util.Formatter.format(Formatter.java:2672)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:86)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:62)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:109)
	at org.assertj.core.internal.Failures.failure(Failures.java:120)
	at org.assertj.core.internal.Iterables.assertZipSatisfy(Iterables.java:1054)
	at org.assertj.core.api.AbstractIterableAssert.zipSatisfy(AbstractIterableAssert.java:2490)
```

Expected output
```
Expecting zipped elements of:
  <["%s"]>
and:
  <["%d"]>
to satisfy given requirements but these zipped elements did not:

- (%s, %d) error: 
Expecting:
 <"%s">
to be equal to:
 <"%d">
but was not.
```

I can contribute if you need help, but would need a pointer on how escaping of '%' is usually done.

**Comment by joel-costigliola** [comment]
Thanks for reporting this and wanting to contribute !

I thin the error is in `private static String describe(List<ZipSatisfyError> zipSatisfyErrors)` that should escape the result with `org.assertj.core.util.Strings.escapePercent`.

Can you try the suggested fix ?

**Comment by AHeise** [comment]
Sure, I'll look into it. Thanks for the pointers.

**Comment by joel-costigliola** [comment]
No that fast ;-) I actually fixed a similar issue in `ElementsShouldSatisfy`, I can fix it too in `ZippedElementsShouldSatisfy` if you don't have the time to contribute it. Up to you, really.

**Comment by AHeise** [comment]
I'd really like to contribute, so I'm working on it now ;)

**Comment by AHeise** [comment]
Please review https://github.com/joel-costigliola/assertj-core/pull/1392
I very much reused stuff from your previous commit.
