### ISSUE TITLE
Support for actual object type in IterableAssert

### ISSUE THREAD

**Issue by AHeise** [joel-costigliola/assertj-core#1388]
#### Summary

While implementing tests for Json Trees using jackson's JsonNode, I stumbled upon a non-trivial issue: I would like to compare JsonNodes as objects with ObjectAssert, however since they implement Iterable, the overloaded assertThat is giving me an IterableAssert and the actual type information of the node is lost. 

I could force the object overload with an explicit object cast, but that would also erase type information.

Currently, I create an ObjectAssert directly, but that doesn't seem like it fits the DSL of assertj.

Options to explore:
* Add an explicit assertThatAsObject(...) (fast to implement but not so nice)
* Capture the actual type in assertThat(Iterable) and pass that to the respective functions. (a larger refactoring, especially if we also want to have it for lists, maps, etc.).

#### Example

```java
           JsonNode actual = ...;
           assertThat(actual)
                    .matches(actualArray -> ((JsonNode) actualArray).isArray()); // <-- cast is necessary!
```

I can contribute.

**Comment by filiphr** [comment]
Not entirely related to this issue, but I have to share https://github.com/lukas-krecan/JsonUnit. It is a really good library (it has AssertJ support as well) for testing JSON strings. It also works with just passing `JsonNode`

**Comment by AHeise** [comment]
I tried a quick and dirty refactoring to get the type information ACTUAL to IterableAssert.

You'd need to introduce a fifth type parameter in the AbstractIterableAssert hierarchy that captures the SELF type with Iterable<? extends ELEMENT> as ACTUAL to be returned by newAbstractIterableAssert (for all selective assertions).

But that assumes that all subclasses only take Iterable<? extends ELEMENT> in newAbstractIterableAssert, which is not true for the ConcreteIterableAssert class in the test packages. To support that case, you'd need to introduce a sixth type parameter for capturing the ACTUAL to be returned by newAbstractIterableAssert.

All-in-all this sounds like way to much work and complexity to support my edge case.

So it would be much easier to support additional entry assertion statements, but that probably blows the concise API...

**Comment by joel-costigliola** [comment]
I would not mind having an `assertThatObject`, it is just one more method.

**Comment by AHeise** [comment]
Okay, then I'll put in a proposal with javadoc and tests at the beginning of next week.

**Comment by AHeise** [comment]
Added a PR that should NOT be used for merging. 

Currently, it's a proposal for the issue. If it's acceptable, I'd bring the new method also to SoftAssertions etc.
