### ISSUE TITLE
isEqualToComparingFieldByField does not deal with Infinity

### ISSUE THREAD

**Issue by champialex** [joel-costigliola/assertj-core#1390]
#### Summary
When using isEqualToComparingFieldByField, if two fields have the same Infinity value the objects are not considered equal. This does not seem to be the expected behaviour. 
This is due to Infinity not being handled in the DoubleComparator.
NaN are not handled either, but I can see why this would be more controversial.

#### Example

```java
       class A {
           double a = Double.POSITIVE_INFINITY;
       }

        assertThat(new A()).isEqualToComparingFieldByField(new A());
```

#### Proposed fix
In both DoubleComparator and FloatComparator, closeEnough could be changed to:
```java
    private static boolean closeEnough(Double x, Double y, double epsilon) {
        if (x.doubleValue() == y.doubleValue()) {
            return true;
        } else if (Double.isNaN(x) && Double.isNaN(y)) {
            return true;
        } else {
            return Math.abs(x - y) <= epsilon;
        }
    }
```

**Comment by joel-costigliola** [comment]
I agree with `x.doubleValue() == y.doubleValue()` but I indeed think it should not compare NaN, users can always register their own double comparator to get that specific behaviour.

Would you like to contribute this improvement?
