### ISSUE TITLE
Boolean Assert Is for truth tables

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1393]
#### Summary

I'd like to be able to write `assertThat( boolean ).is( boolean )` so that code snippets like the following could be written as a junit 5 parameterized test with a truth table like supplier

#### Example

```java
        for ( final PlanType planType : PlanType.values() ) {
            final boolean test2Result = mockOrganizationService.isPlanDescriptionMutable( planType );
            
            if ( planType.isOther() ) {
                assertThat( test2Result ).isTrue();
            }
            else {
                assertThat( test2Result ).isFalse();
            }
        }
```
can give a result example if desired

**Comment by xenoterracide** [comment]
one of the reasons I thought `is` is that it could enforce non null by taking the primitive, where I would expect `isEqualTo` to take `Object`

**Comment by joel-costigliola** [comment]
`isEqualTo` can take primitive that are going to boxed into their object wrapper counterpart.

**Comment by xenoterracide** [comment]
there was an additional reason... I had this problem a while back and encountered it by proxy again today...

oh I think it was because messaging... failures on `isEqualTo` weren't greatly descriptive, but moreso I think I wanted a log of the original object, e.g. `assertThat( person ).extracting( Person::isCool ).is( boolean )` a failure would include a `toString` of `person`; so that the message was better than `true is false`. I *think* that was my issue, I may need to take some time tonight thinking on this to see if there were other reasons (code readability/length primitives were also reasons).

**Comment by joel-costigliola** [comment]
@xenoterracide should this issue be closed ? I'm not too sure what to think about it.

**Comment by xenoterracide** [comment]
I'll close it for now, and re-open or whatever if I come up with the better use case again. I'm sure I had one but...
