### ISSUE TITLE
Verifying size of Set in List<Set<>> fails with FormatFlagsConversionMismatchException

### ISSUE THREAD

**Issue by imavroukakis** [joel-costigliola/assertj-core#1394]
#### Summary
I'm attempting to verify the size of all Sets in a List<Set<>> and I'm getting the following exception

```
java.util.FormatFlagsConversionMismatchException: Conversion = b, Flags =  

	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4298)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:2997)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:2955)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2725)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:86)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:62)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:109)
	at org.assertj.core.internal.Failures.failure(Failures.java:120)
	at org.assertj.core.internal.Iterables.assertAllSatisfy(Iterables.java:1027)
	at org.assertj.core.api.AbstractIterableAssert.allSatisfy(AbstractIterableAssert.java:2450)
```

#### Example

This assertion fails with exception
```java
List<Set<Integer>> lists = Application.generateProductBatches(INTEGER_SET, BATCH_SIZE);

//fails with exception
assertThat(lists)
			.as("Verify product batch size is approximate to batch size selection")
			.allSatisfy(batch -> {
				assertThat(batch.size()).isCloseTo(BATCH_SIZE, Percentage.withPercentage(5));
			}); 
```

This assertion succeeds but looks ugly/wrong
```java
List<Integer> count = lists.stream()
			.map(Collection::size)
			.collect(Collectors.toList());
assertThat(count)
			.satisfies(size -> {
				assertThat(size.get(0)).isCloseTo(BATCH_SIZE, Percentage.withPercentage(5));
			});
```

Is there a better way of doing this or have I hit a genuine bug?

**Comment by joel-costigliola** [comment]
You might be hitting a bug that has been fixed recently in https://github.com/joel-costigliola/assertj-core/commit/20669674ceb08c9f9e33fd8dcb4ad6a39eba86e9, could you join a complete test case to make sure the fix covers your scenario ?

**Comment by imavroukakis** [comment]
Thanks, @joel-costigliola will do. Doesn't that bug though apply to `String` representations that contain `%`? Mine contains only `Integer`.

**Comment by imavroukakis** [comment]
Try this (with Guava as a dependency)

```
Set<Integer> integerSet = IntStream.rangeClosed(1, 2_531_503).boxed().collect(Collectors.toSet());
Iterable<List<Integer>> iterable = Iterables.partition(integerSet, 1000);
assertThat(iterable)
			.as("Verify product batch size is approximate to batch size selection")
			.allSatisfy(batch -> {
				assertThat(batch.size()).isCloseTo(1000, Percentage.withPercentage(5));
			});
```

**Comment by joel-costigliola** [comment]
I tried and the test failed with a regular assertion error ending with:
```
<not printing the whole collection>
Expecting:
  <503>
to be close to:
  <1000>
by less than 5% but difference was 49.7%.
```
running the almost killed my IDE btw!

**Comment by imavroukakis** [comment]
I may have figured it out. It certainly looks like https://github.com/joel-costigliola/assertj-core/commit/20669674ceb08c9f9e33fd8dcb4ad6a39eba86e9 as when I escape `%` as in https://repl.it/repls/CalculatingLightcyanRouter it works fine.

**Comment by joel-costigliola** [comment]
I believe that should indeed fix your issue, to be 100% sure of that, could you build the current assertj-core master version, run your test with it and confirm it runs without the exception?

Executing `mvn install` is all you need to build assertj-core.

**Comment by imavroukakis** [comment]
on it, I'll let you know ASAP.

**Comment by imavroukakis** [comment]
yup all good!

**Comment by imavroukakis** [comment]
On a, somewhat related note, how does one go about testing that all the elements in a List, satisfy a particular condition with the exception of a single one, which should satisfy another?

**Comment by joel-costigliola** [comment]
I agree using `filteredOn` + `hasSize` was the best option.
