### ISSUE TITLE
Add hasBinaryContent for InputStream

### ISSUE THREAD

**Issue by ralfstx** [joel-costigliola/assertj-core#1395]
I would like to assert that a given input string returns a given binary content.
Since `InputStream` contains bytes, I'd suggest to provide the method `hasBinaryContent` that is also available for `File`. I'm currently using `hasSameContentAs` as a workaround, but that's not optimal.

```java
byte[] expected = TEST_CONTENT;

InputStream inputStream = storage.getDownloadStream(TEST_URI);

// currently not supported:
assertThat(inputStream).hasBinaryContent(expected);
// workaround:
assertThat(inputStream).hasSameContentAs(new ByteArrayInputStream(expected));
```

**Comment by joel-costigliola** [comment]
I agree, it looks to be useful.

Would you like to contribute it ?

**Comment by ralfstx** [comment]
Sure. I had some trouble with the PR, but #1413 should be ready for review now.

**Comment by joel-costigliola** [comment]
thanks @ralfstx I'll look at it shortly

**Comment by joel-costigliola** [comment]
@ralfstx sorry, I haven't had the time to look at it but not I have more time.
