### ISSUE TITLE
no assertions should fail

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1398]
#### Summary

So, we're refactoring some code and in review I told my colleague to use `isEmpty`, here's what he came up with

#### Example

```
-        assertThat( null != test3Result && test3Result.isEmpty() ).isTrue();
+        assertThat( test3Result.isEmpty() );
```

I think that `assertThat` without any assertions should default to `fail()`

**Comment by joel-costigliola** [comment]
I'm not sure this is technically possible, at the moment the best course of actions is to use static code analysis, see https://assertj.github.io/doc/#assertj-core-incorrect-usage

**Comment by xenoterracide** [comment]
in theory it should be possible to pass the current state down (kind of like the Stream api), or a stack/state machine kind of tracker. I guess its technical possibility depends on how the assertions are built...

**Comment by joel-costigliola** [comment]
but when do you evaluate it ? you can't do it in `asserThat(object)` call because you don't know at this point if there is an assertions chained after it.

This is an issue with any fluent api (i.e. builders, stream) that needs a termination call

**Comment by xenoterracide** [comment]
good point

**Comment by joel-costigliola** [comment]
using spotbugs is usually enough to avoid these kind of errors.

I'm closing this issue since there is nothing we can do on it but feel free to continue the discussion.

**Comment by joel-costigliola** [comment]
I'm not sure to get your second point, can you elaborate ?
