### ISSUE TITLE
isEqualToComparingFieldByFieldRecursively is ignoring a custom comparator if a fields exists only at one side

### ISSUE THREAD

**Issue by merlin-hst** [joel-costigliola/assertj-core#1410]
#### Summary
Because isEqualToComparingFieldByFieldRecursively doesn't support ignoring fields the suggestest [workaround ](https://stackoverflow.com/questions/43316133/how-to-compare-recursively-ignoring-given-fields-using-assertj) is to use a custom comparator. But such a comparator is not called when the field to ignore is only available at one side.

#### Example

```java
class A {

 private String name;
 private boolean ready;

//getter / setter here
}

class B {

 private String name;

//getter / setter here
}

A a = ...
B b = ...
assertThat(a).usingComparatorForFields((x, y) -> 0, "ready").isEqualToComparingFieldByFieldRecursively(b);

```
This gives the following result:

```java
java.lang.AssertionError: 
Expecting:
  <A@3b7dd173>
to be equal to:
  <B@6ddc817f>
when recursively comparing field by field, but found the following difference(s):

Path to difference: <>
- actual  : <A@3b7dd173>
- expected: <B@6ddc817f>
- reason  : A can't be compared to B as B does not declare all A fields, it lacks these:[ready]
	
```

As shown B doesn't have the 'ready' property. I've seen [1002](https://github.com/joel-costigliola/assertj-core/issues/1002) but as I understand there's currently no release date planned yet. 

Testest with 3.11.1

**Comment by joel-costigliola** [comment]
I have made good progress on #1002 (at least 80% of the thing I wanted to implement), it means I can release 3.12 in the next 2/3 weeks. Be patient ;-) 

You can try the new recursive on this branch if you are keen to : https://github.com/joel-costigliola/assertj-core/tree/recursive-api (I always appreciate feedback).

**Comment by merlin-hst** [comment]
Thank you for answer. Is it possible to deploy that version as a SNAPSHOT release to maven central ?

**Comment by joel-costigliola** [comment]
We don't deploy snapshot and moreover the work is not yet in master but you can simply build it with `mvn install`
