### ISSUE TITLE
java.lang.NoClassDefFoundError: org/assertj/core/api/ProxyableObjectAssert exception when AssertJ declared with test scope in maven pom.xml

### ISSUE THREAD

**Issue by ava1ar** [joel-costigliola/assertj-core#1417]
#### Summary
When AssertJ is declared with `test` scope in project pom.xml, during test execution following exception is thrown when ```assertThat``` method is used:
```
java.lang.NoClassDefFoundError: org/assertj/core/api/ProxyableObjectAssert
	at ... 
	at ... 
Caused by: java.lang.ClassNotFoundException: org.assertj.core.api.ProxyableObjectAssert
	at ...
	at ...
```

Test is invoking following method:
```java
  public <T> ProxyableObjectAssert<T> assertThat(T actual) {
    return proxy(ProxyableObjectAssert.class, Object.class, actual);
  }
```

Removing `test` scope for assertJ dependency resolves the issue.

**Comment by joel-costigliola** [comment]
@ava1ar can you provide a sample project to reproduce that issue ? 
Your error can happen of you use assertj in your main code (src/main/java) while declaring it with a test scope

**Comment by joel-costigliola** [comment]
@ava1ar I'm closing the issue but I'm happy to reopen it if you can provide a way to reproduce it.
