### ISSUE TITLE
add isEqualTo(String string, Objects... param) to String assertion

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1423]
#### Summary

When comparing strings, it would be nice to have String.format baked in the expected string so instead of writing:

```java
assertThat(actualString).isEqualTo(String.format("%s is before %s", date1, date2)); 
```

one can simply write:

```java
assertThat(actualString).isEqualTo("%s is before %s", date1, date2); 
```

**Comment by j-kitch** [comment]
Hi, would I be ok to tackle this and submit a PR?  Seems like a good problem for a first contribution :smiley:

**Comment by dev-priporov** [comment]
@j-kitch hi, I'm sorry but I close to complete PR, I don't want to you may spend your time on that

**Comment by joel-costigliola** [comment]
@dev-priporov thanks. Next time you start working on an issue, can you comment on the issue to let everybody know about it (like @j-kitch).

**Comment by joel-costigliola** [comment]
@j-kitch if you are keen to contribute (which would be great, this https://github.com/joel-costigliola/assertj-core/issues/1422 can be a good one to tackle).

**Comment by dev-priporov** [comment]
@joel-costigliola ok, sure, I will comment

**Comment by j-kitch** [comment]
No problem @dev-priporov, I'll take a look at #1422
