### ISSUE TITLE
get rid of CGLIB and use dynamic proxy

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#143]
This will need to use interface instead of class in *Assert, this a breaking change but not a serious one.

**Comment by joel-costigliola** [comment]
I have tried to follow your work, made some changes (see [remove-cglib](https://github.com/joel-costigliola/assertj-core/tree/remove-cglib) branch) , the problem of my approach is that each interface needs to (re)define all the methods to return the interface type.

Example:
```java
// compile error: The method isEqualTo(int) is undefined for the type Descriptable
softly.assertThat(7).as("Living Guests").isEqualTo(7);
```
To make this code compile `as("description")` must be redefined in `Descriptable`, that would lead to a lot of redefinition and a maintenance hell.

I need to think to a different approach that would avoid to redefine methods.

**Comment by AlexBischof** [comment]
Hello Joel,

sorry for absence the last couple of weeks. I had vacation and a little bit of stress in others projects.

I haven’t look at your changes so far but i also came to the conclusion that my way of removing cglib will not work or to be more precise will blow up the abstract classes and interfaces and therefor is not advisable. But i wonder if that way could work with java8 considering a "refactoring of the abstract classes“  to java8 default interfaces.

Kind regards
-------------------------------------------------- 
Alexander Bischof
Germany 

twitter: https://twitter.com/A_Bischof @A_Bischof
mailto:alexanderxbischof@gmail.com 
web: www.rapidpm.org
xing: https://www.xing.com/profiles/Alex_Bischof
linkedin: https://www.linkedin.com/in/alexbischof

Am 14.01.2015 um 10:25 schrieb Joel Costigliola <notifications@github.com>:

**Comment by joel-costigliola** [comment]
No problem Alex, we all have personal life and work, it is normal not to be available.

The conclusion of this issue/investigation is that it is too much work but I agree we might give it a shot in java 8 (although not super prioritary).

**Comment by joel-costigliola** [comment]
I'm closing this issue in favour of #339.
