### ISSUE TITLE
catchThrowableOfType - stack trace of the original exception is lost

### ISSUE THREAD

**Issue by ptomaszek** [joel-costigliola/assertj-core#1432]
#### Summary
When `catchThrowableOfType` fails because caught exception does not match the expected one, it would be helpful to see stack trace showing the place where the unexpected exception was thrown. Easier than debug.

#### Example
What I see:

`java.lang.AssertionError: Expecting code to throw <class com.example.AppException> but threw <class java.lang.UnsupportedOperationException> instead`

What I'd like to see:
```
java.lang.AssertionError: 
Expecting:
  <java.lang.UnsupportedOperationException>
to be an instance of:
  <com.example.AppException>
but was:
  <"java.lang.UnsupportedOperationException
	at com.example.GameServiceImpl.readGameState(GameServiceImpl.java:22)
	at com.example.GameServiceTests.lambda$failToReadStateByNotJoinedPlayer$14(GameServiceTests.java:44)
    ...
```

Similar to #791.

**Comment by joel-costigliola** [comment]
Fair enough.

**Comment by ssmyth2** [comment]
Hey do you mind if I work on this one?

**Comment by joel-costigliola** [comment]
Sure, thanks!
