### ISSUE TITLE
UnknownFormatConversionException when asserting String with `%` sign

### ISSUE THREAD

**Issue by asolntsev** [joel-costigliola/assertj-core#1441]
#### Summary
I have a test written in Kotlin. It throws `UnknownFormatConversionException` when I try to assert a String containing `%` character. The same test in Java works properly. 

  > A hint: Java test calls method `org.assertj.core.api.AbstractAssert#isEqualTo`, while Kotlin test calls `org.assertj.core.api.AbstractStringAssert#isEqualTo` (which is buggie when there is no args). 

#### Example

1. Test in Java - works:

```java
import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;

public class AssertJTest {
  @Test
  public void assertJ12() {
    assertThat("foo %").isEqualTo("foo %");
  }
}
```

2. The same test in Kotlin - fails:

```kotlin
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test

class AssertJTest {
  @Test
  fun assertJ12() {
    assertThat("foo %").isEqualTo("foo %")
  }
}
```

Failure message is:

```java
java.util.UnknownFormatConversionException: Conversion = '%'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:310)
	at controllers.api.AssertJTest.assertJ12(AssertJTest.kt:9)
```

**Comment by joel-costigliola** [comment]
@asolntsev  Although your fix looks like to address the immediate issue, I wonder why is kotlin resolving `isEqualTo(String template, Object... args)` instead of `isEqualTo(Object expected)` ?

**Comment by joel-costigliola** [comment]
This issue is I believe the same as https://github.com/joel-costigliola/assertj-core/issues/1440#issuecomment-465032464

**Comment by asolntsev** [comment]
> @asolntsev Although your fix looks like to address the immediate issue, I wonder why is kotlin resolving `isEqualTo(String template, Object... args)` instead of `isEqualTo(Object expected)` ?

Good question. I don't know. It's some specific of Kotlin. 
Kotlin has a lot of surprises, you know :) Interoperability with Java is not as good as it should be :(

**Comment by maximusKon** [comment]
I guess Kotlin prefer to use function with more specific argument type.

**Comment by MayaGardeva** [comment]
Hi, I have the same issue with `^` when calling `isEqualTo("abc^d")`

java.util.UnknownFormatConversionException: Conversion = '^'

**Comment by joel-costigliola** [comment]
@asolntsev @maximusKon As suggested by @epeee, would adding the following overload method to `AbstractStringAssert` solve the issue for kotlin users ?
```java
public SELF isEqualTo(String s) {
  return super.isEqualTo(s);
}
```

**Comment by asolntsev** [comment]
Probably. I need to check it.

**Comment by asolntsev** [comment]
@joel-costigliola @maximusKon @epeee 
Yes, it also works! 

I prepared an alternative PR for the same issue. Probably you find it better:
https://github.com/joel-costigliola/assertj-core/pull/1465

**Comment by kevcodez** [comment]
When do you plan to release this fix?

**Comment by joel-costigliola** [comment]
@kevcodez in a few weeks hopefully
