### ISSUE TITLE
anySatisfy: do not continue evaluating elements once we found a match 

### ISSUE THREAD

**Issue by epeee** [joel-costigliola/assertj-core#1445]
#### Summary
In #1400 we added support for reporting all failing elements.
While doing so we changed the implementation in a case that we always evaluate all elements.

Let's optimize this and only evaluate as many elements as needed. E.g. once a element matches, we can stop evaluating all remaining elements.

I can provide a pr for this one soon.

**Comment by joel-costigliola** [comment]
Sounds good, thanks Erhard!
