### ISSUE TITLE
No contains* in IteratorAssert anymore

### ISSUE THREAD

**Issue by uhafner** [joel-costigliola/assertj-core#1451]
#### Summary

I'm using the `contains` methods in `IteratorAssert` to check if there are all elements present in an `Iterator`. This worked quite well with 3.11.1 but not with 3.12.0. The class `IteratorAssert` is now almost empty. I'm not sure if this is intended, I did not find anything in the documentation.
 
#### References

See
- [broken PR](https://github.com/jenkinsci/analysis-model/pull/94)  to bump AssertJ 3.11.1 to 3.12.0 in my plugin
- [test code](https://github.com/jenkinsci/analysis-model/blob/master/src/test/java/edu/hm/hafner/analysis/ReportTest.java#L602) that does not compile anymore
- [broken build](https://travis-ci.org/jenkinsci/analysis-model/builds/498892690#L1348) with 3.12.0.

**Comment by PascalSchumacher** [comment]
With 3.12.0 you have to add a `IteratorAssert#toIterable` call (similar to the changes done in https://github.com/jdbi/jdbi/pull/1466/files).

**Comment by uhafner** [comment]
I see. I fixed it in the [same way](https://github.com/jenkinsci/analysis-model/commit/ff01e9de041c176cd19b3dc08d5f4bba9039da18), thanks for the hint.

**Comment by joel-costigliola** [comment]
@uhafner it was intended the [release notes](https://assertj.github.io/doc/#assertj-core-3-12-0-release-notes) is a bit confusing though so I'll clarify them and suggest using `IteratorAssert#toIterable` as Pascal said.

**Comment by filiphr** [comment]
I noticed this as well. Why not add those methods to the `IteratorAssert` and call `toIterable` in them?

**Comment by joel-costigliola** [comment]
That's what we used to do with some lazy conversion to iterable but it was an hacky implementation that was sometimes tricky for users, we thought it was best to stick with the Iterator API.

**Comment by joel-costigliola** [comment]
I have (hopefully) clarified the release notes: https://assertj.github.io/doc/#assertj-core-3-12-0-release-notes

**Comment by bjhargrave** [comment]
I think the readme text has `Iterator` and `Iterable` transposed.

Is says:

```
Introduce first class Iterator assertions.
* This removes previously supported assertions for Iterable
```

but should say

```
Introduce first class Iterable assertions.
* This removes previously supported assertions for Iterator
```

**Comment by joel-costigliola** [comment]
updated
