### ISSUE TITLE
Wrong assertion in EqualsHashCodeContractAssert

### ISSUE THREAD

**Issue by ghostd** [joel-costigliola/assertj-core#1455]
Hi,

I read the class `EqualsHashCodeContractAssert`, and since `equals` returns a boolean, i think 

```java
public static void assertIsNotEqualToNull(Object obj) {
    assertThat(obj.equals(null)).isNull();
}
```
should be 
```java
public static void assertIsNotEqualToNull(Object obj) {
    assertThat(obj.equals(null)).isFalse();
}
```
If you didn't spot the bug, i guess this is dead code.

Regards

**Comment by ghostd** [comment]
By the way, did you consider expose those assertions in the public API to check the `equals` contract?

**Comment by joel-costigliola** [comment]
Good catch! The code is dead code indeed, it was written in Fest Assert which AssertJ is a fork of.

I think it is better to use https://jqno.nl/equalsverifier/ to test equals and hashcode, no plan in the roadmap to support this.

**Comment by ghostd** [comment]
Ok, thanks for the pointer.
