### ISSUE TITLE
Ignore static methods when introspecting properties

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1458]
#### Summary

See the discussion starting here: https://github.com/joel-costigliola/assertj-core/pull/1360#issuecomment-470200904

**Comment by stevenschlansker** [comment]
You might consider "ignore static methods when introspecting *any* property" as a static method is not a property of an instance with or without the `get` prefix, and having different visibility rules based on the method name could be confusing.
