### ISSUE TITLE
Is it possible somehow use AssertJ in WebDriver waits or waiting in general?

### ISSUE THREAD

**Issue by mtravnicek** [joel-costigliola/assertj-core#1462]
#### Summary
I want to use AssertJ capabilities, namely List/Iterable functions like **containsOnly** etc
in WebDriver wait or generally in some cycle which waits until condition is satisfied.
I know that assertThat does not return boolean and terminates code in case of failure.....
What about something along the lines of SoftAssertions?
Or can you hint some Java library with functions like containsOnly etc.?
#### Example

```java
new WebDriverWait(driver, 5).until(new Predicate<WebDriver>() {
        public boolean apply(WebDriver d) {
// when return line (boolean) is satisfied, wait ends, else it throws timeout after some time...
            return d.findElement(By.id("your id")).isDisplayed();
//i need something like .... not working code
//           return assertThat(someUpdatedValues).containsOnly(statusGreen);
        }
    });
```

**Comment by epeee** [comment]
Hi,
sounds like [awaitility](https://github.com/awaitility/awaitility/) might help you, e.g. see https://github.com/awaitility/awaitility/wiki/Usage#example-8---using-assertj-or-fest-assert

**Comment by joel-costigliola** [comment]
I concur wirh @epeee, awaitability is great for this kind of use cases

**Comment by mtravnicek** [comment]
thanks for prompt reply... `await().untilAsserted` works good, but my problem shifts to  #1466
