### ISSUE TITLE
AbstractOptionalAssert::contains() fails on substring.

### ISSUE THREAD

**Issue by torsten-github** [joel-costigliola/assertj-core#1472]
#### Summary
using contains on Optional<String> fails with substring.

#### Example

```java
// fails
 assertThat(Optional.of("abc")).contains("a"); 

// passes
assertThat("abc").contains("a");
```

**Comment by joel-costigliola** [comment]
This works as expected as per http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractOptionalAssert.html#contains-VALUE- `contains` for `Optional` checks the content, it's not a String assertion.

We will update the code examples, to make it clear that  `assertThat("abc").contains("a");`
