### ISSUE TITLE
assertThat(CustomException) casts to Throwable

### ISSUE THREAD

**Issue by krzyk** [joel-costigliola/assertj-core#1479]
#### Summary
I have a custom exception class that I want to do assertions on, but I'm unable because instead of matching to assertThat(T) there is a method assertThat(Throwable) and I'm able to match only methods that exist in Throwable.

#### Example

```java
class CustomException extends RuntimeException {
public int count() { return 123;}

....
CustomException ex = new CustomException();
Assertions.assertThat(ex).matches(p -> p.count() == 123);
```

The above fails because `p` is of type `Throwable`.

**Comment by joel-costigliola** [comment]
Try [`assertThatObject`](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/Assertions.html#assertThatObject-T-), it forces calling `assertThat(T) `.

**Comment by krzyk** [comment]
Yes, indeed that solves the issue, thanks.
