### ISSUE TITLE
yyyy-MM-dd'T'HH:mm:ss.SSSX is not supported in time parsing.

### ISSUE THREAD

**Issue by matejdro** [joel-costigliola/assertj-core#1487]
#### Summary

Related to #1133. Time parsing supports either milliseconds OR timezone, it does not work when both are specified.

#### Example
 ```java
 Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
 cal.clear();
 cal.set(2017, Calendar.NOVEMBER, 27, 20, 13, 24);
 Date date = cal.getTime();
 
 assertThat(date)
     .isEqualTo("2017-11-27T20:13:24.000+00:00");
 ```

Above test fails if target machine's default tiemzone is any other than UTC.

**Comment by joel-costigliola** [comment]
Fair enough, @matejdro are you keen to contribute this one ? 

In the meantime it is always possible to register this date format but you have to do it explicitly, see [withDateFormat](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/AbstractDateAssert.html#withDateFormat-java.lang.String-) or [registerCustomDateFormat](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/AbstractDateAssert.html#registerCustomDateFormat-java.lang.String-)

**Comment by matejdro** [comment]
I have created new PR.

**Comment by joel-costigliola** [comment]
Integrated thanks @matejdro!
