### ISSUE TITLE
Support ignoring collection order in Recursive comparison API

### ISSUE THREAD

**Issue by zeljko-mirovic** [joel-costigliola/assertj-core#1494]
It will be nice to be able to ignore collection order with Recursive comparison API.
Instead of writing something like:
```java
assertThat(actual).usingRecursiveComparison()
                  .ignoringFields("unorderedCollection")
                  .isEqualTo(expected);
assertThat(actual.getUnorderedCollection()).hasSameElementsAs(expected.getUnorderedCollection());
```
to have option to ignore collection order like this:
```java
assertThat(actual).usingRecursiveComparison()
                  .ignoringCollectionOrderInFields("unorderedCollection")
                  .isEqualTo(expected);
```

**Comment by joel-costigliola** [comment]
Sure, I had a bullet point in #1002 for it.

**Comment by joel-costigliola** [comment]
@zeljko-mirovic do you have a use case where specifying fields is necessary ? 
I was at first considering a global option `ignoringCollectionOrder()` for all collections.

**Comment by zeljko-mirovic** [comment]
Yes I do.
I am asserting complex DTO generated by maven plugin. All collections in DTO are Lists but some of them are backed up by entities using Lists and some by entities using Sets.

**Comment by joel-costigliola** [comment]
alright fair enough.
