### ISSUE TITLE
Use var-args with ThrowableAssertAlternative.withMessageContaining

### ISSUE THREAD

**Issue by philwebb** [joel-costigliola/assertj-core#1501]
#### Summary
I currently often find myself calling `withMessageContaining` multiple times on an exception assertions. It would be more convenient if I could roll these up into a single line, similar to the way that String assertions support `contains(CharSequence... values)`.

#### Example
The following current code:

```java
assertThatExceptionOfType(BeanCreationException.class).isThrownBy(lbf::preInstantiateSingletons)
	.withMessageContaining("Circular")
	.withMessageContaining("'tb3'")
	.withMessageContaining("'tb1'");
```

could become:

```java
assertThatExceptionOfType(BeanCreationException.class).isThrownBy(lbf::preInstantiateSingletons)
	.withMessageContaining("Circular", "'tb3'", "'tb1'");
```

**Comment by joel-costigliola** [comment]
Fair enough, would you mind contributing it (if you have time) ?

**Comment by philwebb** [comment]
I'm working on a PR to submit shortly.
