### ISSUE TITLE
Support formatting overloads in more AbstractThrowableAssert methods

### ISSUE THREAD

**Issue by antoniomacri** [joel-costigliola/assertj-core#1502]
#### Summary
In particular, I'd use `hasMessageContaining(String message, Object... parameters)`.

#### Example
Instead of:
```java
assertThat(thrown).hasMessageContaining(String.format("My %s format string", "beautiful"));
```
write
```java
assertThat(thrown).hasMessageContaining("My %s format string", "beautiful");
```
just like:
```java
assertThat(thrown).hasMessage("My %s format string", "beautiful");
```

**Comment by joel-costigliola** [comment]
Interestingly #1501 goes in a different way unfortunately incompatible with your suggestion.

I totally get why you ask for it but I think allowing multiple string to be checked is more useful than supporting `String.format` syntax. 

@antoniomacri have you got a compelling argument for your suggestion that I have missed ?

**Comment by antoniomacri** [comment]
No, it's just convenience.

But instead of adding varargs to `withMessageContaining` a new `withMessageContainingAll` could be defined?

What do you think?

**Comment by joel-costigliola** [comment]
Good idea, we'll make the change to `withMessageContainingAll` / `hasMessageContainingAll`.

@antoniomacri are you keen to contribute this improvement ? If so I suggest to wait for #1501 to be resolved to avoid merge conflicts.

**Comment by joel-costigliola** [comment]
Actually for consistency with collection assertions `contains`, I suggest we change the existing `with/hasMessageContaining(String)` to  `with/hasMessageContainingFormattedMessage(String, Object...)` .

It will make it obvious what the difference is and with #1501, we are backward compatible so all good.

comments ?

**Comment by antoniomacri** [comment]
Since we are checking exception messages, the consistency with collections is probably not a big problem.

`hasMessageContainingFormattedMessage` seems ugly to me (maybe better `hasMessageContainingFormattedString`) and is longer than `String.format`, therefore I'd probably keep using the last. 😄 ...no ok maybe not, just to avoid the extra parenthesis.

`containsFormattedMessage` (as suggested by Phil [here](https://github.com/joel-costigliola/assertj-core/pull/1503#issuecomment-491558079)) has a subtle difference in its name, since it refers not to the exception itself but actually to its `getMessage` result, that's why `hasMessage...`/`has...` methods are clearer to me.

**Comment by joel-costigliola** [comment]
Good point for `hasMessageContainingFormattedMessage`, having `message` twice is not great.

 `hasMessageContainingFormattedString` is not super elegant, so I'm back to prefer `with/hasMessageContainingAll(String...)` and `with/hasMessageContaining(String, Object...)`.

**Comment by joel-costigliola** [comment]
@antoniomacri are you keen to contribute `with/hasMessageContaining(String, Object...)` ?
