### ISSUE TITLE
Typo in AbstractDateAssert#isBeforeOrEqualsTo method name?

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1506]
#### Summary
`AbstractDateAssert#isBeforeOrEqualsTo` has a trailing 's' in 'Equals' and it looks like a typo compared to java 8 time assertions (same for `AbstractDateAssert#isAfterOrEqualsTo`). It is just a style issue and fixing it would be a backwards incompatible change.

Also `org.assertj.core.error.ShouldBeBeforeOrEqualsTo` and `org.assertj.core.error.ShouldBeAfterOrEqualsTo` have the same flaw.

#### Example

```java
assertThat(new Date).isBeforeOrEqualsTo(anotherDate)
assertThat(Instant.now()).isBeforeOrEqualTo(anotherInstant)
```

**Comment by joel-costigliola** [comment]
Yeah, good catch :man_facepalming: .

The way to go is is deprecate `isBeforeOrEqualsTo` / `isAfterOrEqualsTo` and add  `isBeforeOrEqualTo` / `isAfterOrEqualTo`. For the other typos a rename refactoring will do.
