### ISSUE TITLE
Add hasSuperclass(Class<?>) to AbstractClassAssert

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1512]
#### Summary
Sometimes I feel the lack of `isNotAssignableFrom()` in `AbstractClassAssert`.
Recently I needed a defensive test to enforce an exception class staying "checked" (i.e., not inheriting from `RuntimeException`). To do that, I created a custom condition:

```java
private static Condition<Class<?>> runtimeException = new Condition<>(RuntimeException.class::isAssignableFrom, RuntimeException.class.getSimpleName());
```
used in this way:
```java
assertThat(MyException.class).isNot(runtimeException);
```

#### Example
Following the behavior of the existing `isAssignableFrom(Class<?>...)`, a new api could check that `actual` is not assignable from any of the `others`:
```java
public SELF isNotAssignableFrom(Class<?>... others)
```
With it, my example would not require a custom condition:
```java
assertThat(RuntimeException.class).isNotAssignableFrom(MyException.class);
```

Would this new api make sense?

#### Additional Thoughts
Would it make sense to have some assertions for `Throwable` classes, for example to verify if the class is inheriting from `Error`/`Exception`/`RuntimeException`? It would address the ugly backwards readability of `isAssignableFrom` :-)
Maybe a new `AbstractThrowableClassAssert` inheriting from `AbstractClassAssert` could to the job.

**Comment by joel-costigliola** [comment]
I'm ok with `isNotAssignableFrom` as the opposite of `isNotAssignableFrom`.

Having said that, I have always found the (JDK) `isAssignableFrom` method to be highly unclear, I often find myself wondering which class should inherit from the other one.

It would be great to find a better name for the `isAssignableFrom` assertion (and `isNotAssignableFrom`) that would not be ambiguous, maybe `isA/isAn` and `isNotA/isNotAn`? 

```java
assertThat(MyException.class).isAn(Error.class);
assertThat(MyException.class).isNotA(RuntimeException.class);
```

I don't see adding `AbstractThrowableClassAssert` to be  valuable enough at this point, were you thinking having assertions like `isRuntimeException()` ?

**Comment by scordio** [comment]
Yes, I was thinking about something like `isRuntimeException()` just because of the JDK `isAssignableFrom` unclearness! But you're right, there would be no need for an `AbstractThrowableClassAssert` having a better name for `isAssignableFrom`.

To avoid the `isA`/`isAn` duplication, what do you think about `isInheritingFrom()`? There could also be a `isBeingInheritedFrom()` for the superclass use case.

I was also thinking about the pair `hasSuperclass()` / `hasSubclass()` but it's probably too close to [Class#getSuperclass()](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getSuperclass--) and it could create confusion since the `Class` method has less flexibility.

**Comment by scordio** [comment]
@joel-costigliola let's try again on this topic, but this time simpler :-)

What about having `isAssignableTo(Class<?>)`?

**Comment by scordio** [comment]
@joel-costigliola one more try 🙂 

What about `hasSuperclass(Class<?>)` which is backed by [`getSuperclass()`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getSuperclass--) from the JDK?

Not flexible as the previous one as it doesn't match implemented interfaces but it's good enough for my purpose and doesn't deviate from JDK api.

**Comment by joel-costigliola** [comment]
Works for me! :)

**Comment by perlun** [comment]
(Also, adding negation forms for both the existing one - `isNotAssignableFrom` - and the suggested new method - `isNotAssignableTo` - would be incredibly useful. Right now, I'm doing a workaround on the form `assertThat( ParentClass.class ).matches( cls -> !cls.isAssignableFrom( ChildClass.class ) ))`, but it's a bit rough. :slightly_smiling_face:)

**Comment by scordio** [comment]
Thanks for the feedback, @perlun. #2570 is now the best place to discuss further enhancements.

**Comment by perlun** [comment]
Thanks for pointing me there @scordio and also for copying my comment into that thread, greatly appreciated. :pray:
