### ISSUE TITLE
Feature Request: assertThat(date).isCloseToUtcNow()

### ISSUE THREAD

**Issue by ngeor** [joel-costigliola/assertj-core#1519]
#### Summary

It is common that we have some code that creates a date-time (e.g. `LocalDateTime`) based on the current time, in UTC time zone.

We have a custom assertion for that, but it would be perhaps nice if assertJ had this out of the box.

This is our class:

```java
public final class DateAssertions {

    private static final int DELTA = 750;

    private DateAssertions() {}

    public static void assertNow(OffsetDateTime dateTime) {
        assertThat(dateTime).isCloseTo(OffsetDateTime.now(), within(DELTA, ChronoUnit.MILLIS));
    }

    public static void assertNow(LocalDateTime dateTime) {
        assertThat(dateTime).isCloseTo(LocalDateTime.now(Clock.systemUTC()), within(DELTA, ChronoUnit.MILLIS));
    }
}
```

We'd like to have the same functionality out of the box, e.g.

```java
assertThat(dateTime).isCloseToUtcNow();
```

perhaps with some overloads like:

```java
assertThat(dateTime).isCloseToUtcNow(DIFFERENT_DELTA, ChronoUnit.MILLIS);
```

If you also find this useful, I would be happy to create a PR for it.

**Comment by joel-costigliola** [comment]
I have mixed feeling on this, it feels a bit too specific but why not.

One thing I'm sure of is that `isCloseToUtcNow()` is not obvious enough as we have no idea what delta was used. I think it is preferable to be explicit, so I would go for something like:

```
assertThat(dateTime).isCloseToUtcNow(within(10, MILLIS));
```

@ngeor WDYT ?

**Comment by ngeor** [comment]
The use case I have in mind is about storing a value in the db (like a creation timestamp). By the time the assertion runs, some milliseconds have passed, which depending on the speed of the machine can go up to 500 or even more, but almost within the second.

I agree that a default value might be good for my use case but not for others.

I would still go for both overloads, because I'm assuming `within(1, SECOND)` might be a good enough default. Maybe there's a way to ask the community to vote for a default? Or maybe there's a way to indicate that API is not stable yet?

But in any case I could start a PR just for the overload with the explicit parameter, if that is okay.

**Comment by joel-costigliola** [comment]
I'm still not convinced about a default value because it is really dependent on what you are testing, if people really want it, they can easily write a static wrapper method that would call `isCloseToUtcNow` with their own default value.

If you are keen to start working on the  overload with the explicit parameter, that would be great!

**Comment by ngeor** [comment]
@joel-costigliola I have pushed some first draft in order to get your feedback.

I didn't create a PR because it didn't finish all the tests and I didn't add the javadoc comments.

https://github.com/joel-costigliola/assertj-core/compare/master...ngeor:1519?expand=1

I would really appreciate any early feedback in case I'm doing it completely wrong :-)

One thing I found strange is that `AbstractLocalDateTimeAssert` is throwing `IllegalArgumentException` if I pass in a `null` (which is correct in my opinion) but its parent class, `AbstractTemporalAssert`, is throwing a `NullPointerException`. Should I change that as well, I wonder, or would that be a breaking change.

But other than that, my idea was to add my methods in `AbstractLocalDateTimeAssert` and `AbstractOffsetDateTimeAssert`, add the unit tests, add the javadoc, create a PR, live happily ever after :-)

**Comment by joel-costigliola** [comment]
Hi @ngeor,
You can raise a PR even if it is early stage, it is easier for me to review and make comments.
Don't worry too much about the exception discrepancies, I prefer `IllegalArgumentException` too, if can change that, great. It is a breaking change but a minor one so it's ok.

**Comment by ngeor** [comment]
Hi @joel-costigliola ,
thanks, I opened up a PR. The build failed on `openjdk-ea` on some tests related to paths, e.g. `Paths_assertIsDirectoryContaining_Predicate_Test`. It passed on the other versions of Java. Is this perhaps a known issue or do I need to do something about it? Looking forward to your feedback.

https://github.com/joel-costigliola/assertj-core/pull/1528

**Comment by scordio** [comment]
> Hi @joel-costigliola ,
> thanks, I opened up a PR. The build failed on `openjdk-ea` on some tests related to paths, e.g. `Paths_assertIsDirectoryContaining_Predicate_Test`. It passed on the other versions of Java. Is this perhaps a known issue or do I need to do something about it? Looking forward to your feedback.
> 
> #1528

That should be fixed now. Unless you push something else, someone with write access would need to trigger a new build for your PR or you can close and reopen your PR to trigger Travis again.

**Comment by ngeor** [comment]
Thanks @scordio I pushed a change in `.editorconfig` (changed a URL to https) and the build is indeed green.

**Comment by joel-costigliola** [comment]
@ngeor I'll look at it in the next few days, thanks.
