### ISSUE TITLE
Allow return values of WithAssertions#fail* methods to be ignored

### ISSUE THREAD

**Issue by jiri-pejchal** [joel-costigliola/assertj-core#1533]
#### Summary
`WithAssertions#fail` methods don't return void (from #1294). This causes violations in static analysis tools because the class `WithAssertions` is annotated with `@CheckReturnValue`. 

`WithAssertions#fail` methods  should be annotated with `@CanIgnoreReturnValue`.
The similar fix has been made for `Assertions#fail` in #1298.

**Comment by joel-costigliola** [comment]
Good catch thanks!
