### ISSUE TITLE
junit-platform-testkit includes assertj-core as a transitive dependency

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1550]
It seems `junit-platform-testkit` is providing `assertj-core` as a transitive dependency:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ assertj-core ---
[INFO] org.assertj:assertj-core:bundle:3.13.0-SNAPSHOT
[INFO] \- org.junit.platform:junit-platform-testkit:jar:1.5.0:test
[INFO]    \- org.assertj:assertj-core:jar:3.12.2:test
```

I guess either `assertj-core` should be excluded explicitly or `junit-platform-testkit` could declare it as an optional depedency (Gradle feature variants?)

@sbrannen what would you suggest?

**Comment by joel-costigliola** [comment]
I think we should simply exclude it to avoid any confusion and be explicit.

**Comment by sbrannen** [comment]
> I think we should simply exclude it to avoid any confusion and be explicit.

I agree
