### ISSUE TITLE
`isEqualTo` for strings fail if expected string contains a '%'

### ISSUE THREAD

**Issue by rsertelon** [joel-costigliola/assertj-core#1556]
We've updated AssertJ from 3.10.0 to 3.12.2, and one of our tests now fails, due to this update.

We test a percentage formatter method, and use `isEqualTo("12.3 %") ` which throws an exception.

Indeed, it seems that in `AbstractStringAssert` there is now a `String.format` call on the expected value.

`java.util.Formatter` considers `%` to be an invalid character, and throws a `java.util.UnknownFormatConversionException: Conversion = '%'`

Change seem to be in https://github.com/joel-costigliola/assertj-core/commit/37eacd11b0d4ef43c13d7d6c96dc7970ff2f5ffb#diff-70bfdc17bd413d92ab36c8ed02695a1fR310

**Comment by joel-costigliola** [comment]
Thanks for reporting this, it is already fixed in the next version 3.13.0 to be released soonish.

I have just pushed to make it sure your case worked https://github.com/joel-costigliola/assertj-core/commit/c9a8618d8cd5ec1bc9c81eb03123035051e6332c
