### ISSUE TITLE
AbstractObjectAssert.hasFieldOrPropertyWithValue documentation example wrong

### ISSUE THREAD

**Issue by LinaSchad** [joel-costigliola/assertj-core#1558]
#### Summary

The example of the hasFieldOrPropertyWithValue documentation shows hasFieldOrProperty in the code, but it should be hasFieldOrPropertyWithValue instead.

See [https://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectAssert.html#hasFieldOrPropertyWithValue-java.lang.String-java.lang.Object-](url) 
`// assertions will pass :
 assertThat(frodo).hasFieldOrProperty("name", "Frodo");
 assertThat(frodo).hasFieldOrProperty("age", 33);
 assertThat(noname).hasFieldOrProperty("name", null);` 

These assertions won't pass, because they cannot compile.

**Comment by joel-costigliola** [comment]
I missed this one :man_facepalming: , will be in the next release.
