### ISSUE TITLE
AssertJ 3.13.0 requires OpenTest4J (java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError)

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#1563]
If the classpath does not contain OpenTest4J (e.g. you use JUnit 4 instead of JUnit 5) AssertJ `3.13.0` fails with:

`java.lang.NoClassDefFoundError: org/opentest4j/MultipleFailuresError`

A sample project to reproduce this issue: https://github.com/PascalSchumacher/assertj-3.13.0-requires-junit5-bug

**Comment by PascalSchumacher** [comment]
The dependency on OpenTest4J  was introduced with this commit: https://github.com/joel-costigliola/assertj-core/commit/d79423dedfbc1a5645bce9fa2b61580620860493#diff-4df7ee848542cb94166b422c1c3b05bd

**Comment by joel-costigliola** [comment]
my bad :( 
this is not too serious IMO as people usually have opentest4j in their dependencies but let's try to fix that (if that's possible)

**Comment by joel-costigliola** [comment]
AssertJ Core 3.13.1 is released with this fix.
