### ISSUE TITLE
Javadoc anchor links don't work (Java 11)

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1570]
#### Summary

This works : https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html

This works when the link is clicked from the page: https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html#method.summary but open the same link in a new tab and it won't show the method summary, just the beginning of the page https://static.javadoc.io/org.assertj/assertj-core/3.13.1/org/assertj/core/api/AbstractInstantAssert.html

This is pretty annoying when you want to share a link to a specific section of a page.

**Comment by joel-costigliola** [comment]
@scordio @PascalSchumacher @epeee if you have any ideas on this one, that would be great, I have no clue why this is not working :(

**Comment by scordio** [comment]
I noticed that when opening the link in a new tab it moves very quickly to the method summary and then comes back to the beginning of the page

**Comment by scordio** [comment]
Again 🤦 will take another look

**Comment by joel-costigliola** [comment]
sorry @scordio links work, what does not is search https://github.com/joel-costigliola/assertj-core/issues/1657
