### ISSUE TITLE
Add an Instant assertion for OffsetDateTime

### ISSUE THREAD

**Issue by raynicho** [joel-costigliola/assertj-core#1571]
#### Summary
The `AbstractOffsetDateTimeAssert` only offers a `isEqualTo(String dateTimeAsString)`. The other option to compare `OffsetDateTime` objects is `isEqualTo(Object)`. The ladder is not sufficient as the following test fails:

```java
@Test
void testIsEqualTo() {
  final String dateTime = "2011-12-03T10:15:30.45+01:00";
  final OffsetDateTime actual =
      OffsetDateTime.parse(dateTime).withOffsetSameInstant(ZoneOffset.ofHours(0));
  final OffsetDateTime expected =
      OffsetDateTime.now()
          .withYear(2011)
          .withMonth(12)
          .withDayOfMonth(3)
          .withHour(10)
          .withMinute(15)
          .withSecond(30)
          .withNano(450000000)
          .withOffsetSameLocal(ZoneOffset.ofHours(1));

  assertThat(actual).isNotNull();
  assertThat(actual).isEqualTo(expected);
}
```

With the following error message:

```
org.opentest4j.AssertionFailedError: 
Expecting:
 <2011-12-03T09:15:30.450Z>
to be equal to:
 <2011-12-03T10:15:30.450+01:00>
but was not.
Expected :2011-12-03T10:15:30.450+01:00
Actual   :2011-12-03T09:15:30.450Z
```

Utilizing [OffsetDateTime.html#isEqual](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#isEqual-java.time.OffsetDateTime-), the test passes:

```java
@Test
void testIsEqualTo() {
  final String dateTime = "2011-12-03T10:15:30.45+01:00";
  final OffsetDateTime actual =
      OffsetDateTime.parse(dateTime).withOffsetSameInstant(ZoneOffset.ofHours(0));
  final OffsetDateTime expected =
      OffsetDateTime.now()
          .withYear(2011)
          .withMonth(12)
          .withDayOfMonth(3)
          .withHour(10)
          .withMinute(15)
          .withSecond(30)
          .withNano(450000000)
          .withOffsetSameLocal(ZoneOffset.ofHours(1));

  assertThat(actual).isNotNull();
  assertThat(actual.isEqual(expected)).isTrue();
}
```

#### Example
```java
final OffsetDateTime now = OffsetDateTime.now();
assertThat(now).isEqualTo(now.withOffsetSameInstant(ZoneOffset.ofHours(10)));
```

**Comment by raynicho** [comment]
As the `OffsetDateTime` documentation mentions, 

> This method differs from the comparison in compareTo(java.time.OffsetDateTime) and equals(java.lang.Object) in that it only compares the instant of the date-time. This is equivalent to using dateTime1.toInstant().equals(dateTime2.toInstant());.

it might be better to introduce a method like `isEqualTo(Instant other)`.

**Comment by joel-costigliola** [comment]
This one is a bit tricky, AssertJ `isEqualTo` is meant to use `equals` but `OffsetDateTime`  has an `isEqualTo` method! 

I think AssertJ could provide a `isEqualToInstant` or `isInstant` to make it clear it is comparing `Instant` as I'm sure most of the people don't realize the difference between `OffsetDateTime`  `isEqualTo`  and `equals` methods (I did not until https://github.com/joel-costigliola/assertj-core/issues/1452#issuecomment-478306220)

**Comment by raynicho** [comment]
@joel-costigliola Thanks for the reply. I agree that the assertion method should make it clear that it is comparing the `Instant` and not the actual `Object`. I like the suggestions you posted, but I was hoping to add a fluent assertion comparing two `OffsetDateTime` objects, without having to call `toInstant()` and without having to set the `ZoneOffset` for each `OffsetDateTime` to 0. What do you think about the following, naming the assertion `hasSameInstantAs`?

```java
final OffsetDateTime now = OffsetDateTime.now();
assertThat(now).hasSameInstantAs(now.withOffsetSameInstant(ZoneOffset.ofHours(10)));
```

**Comment by raynicho** [comment]
Also, I was hoping to give this a shot. I'll put a PR up whenever I get a chance.
