### ISSUE TITLE
add Path assertions

### ISSUE THREAD

**Issue by SylvainJuge** [joel-costigliola/assertj-core#158]
The only file-related assertions I could find are for pre-java7 API, thus [using the File class](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/FileAssert.html) .

Allowing assertion (or create a new one) that allows to use Path would be useful, however that may break pre-java7 compatibility, thus requiring a dedicated module like "assertj-core-java7".

**Comment by joel-costigliola** [comment]
FYI, this issue is being addressed by https://github.com/joel-costigliola/assertj-core/pull/303.
