### ISSUE TITLE
The assertion assertThat().HasSizeBetween() does not work with strings

### ISSUE THREAD

**Issue by geoffreyarthaud** [joel-costigliola/assertj-core#1586]
#### Summary

The assertion assertThat().hasSizeBetween() with strings does not work, assertj-core seems to confuse string lengths between actual, min and max.

#### Example

```java
assertThat("Test1").hasSizeBetween(4, 11);
```
throws a confusing exception :
java.lang.IllegalArgumentException: The higher boundary <4> must be greater than the lower boundary <5>.

Tested on assertj_core 3.13.2 and AdoptOpenJDK 11

**Comment by joel-costigliola** [comment]
Thanks for reporting this ! it's a bit embarrassing 🤦‍♂

**Comment by geoffreyarthaud** [comment]
As a workaround, this code works : 

```java
assertThat("Test1").hasSizeGreaterThan(3).hasSizeLessThan(12)
```
