### ISSUE TITLE
HamcrestCondition matcher generic is too strict

### ISSUE THREAD

**Issue by carterkozak** [joel-costigliola/assertj-core#1607]
#### Summary

I'm working on an ErrorProne check which produces 'suggested fixes' that can be automatically applied to migrate from junit asserts to AssertJ. `assertThat(Object, Matcher)` is more difficult than other methods, so for the time being, I've simply fallen back to using `assertThat(actual).is(new HamcrestCondition<>(ORIGINAL_HAMCREST_MATCHER)`.
Unfortunately there are many cases where this doesn't compile!

#### Example

```java
Collection<String> value = ImmutableList.of();
assertThat(value).is(new HamcrestCondition<>(not(hasItems("one", "two"))));
﻿                                          ﻿﻿^ 🌶 Cannot infer arguments 🌶 (I hope the spaces align!)
```

#### Recommendation

We should loosen the Matcher to `Matcher<? extends T>` rather than `T`.

Aforementioned ErrorProne migration is [here](https://github.com/palantir/gradle-baseline/blob/develop/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferAssertj.java) if you're interested. The [test](https://github.com/palantir/gradle-baseline/blob/develop/baseline-error-prone/src/test/java/com/palantir/baseline/errorprone/PreferAssertjTests.java) are probably the most interesting place to start.

**Comment by joel-costigliola** [comment]
Thanks for reporting this issue and the PR! I agree the generic should have been looser.
