### ISSUE TITLE
Add 'given' method for BDD assumptions

### ISSUE THREAD

**Issue by gmullerb** [joel-costigliola/assertj-core#1613]
#### Summary

Just as there is an [`org.assertj.core.api.BDDAssertions`](https://assertj.github.io/doc/#alternative-entry-points) that provides an equivalent BDD approach to `org.assertj.core.api.Assertions` (`org.assertj.core.api.BDDAssertions` supplies the method `then`, an entrypoint for a BDD assertion), A **`org.assertj.core.api.BDDAssumptions`** (equivalent to [`org.assertj.core.api.Assumptions`](https://assertj.github.io/doc/#assertj-core-assumptions)) **could be introduced to provide the method `given`, an entrypoint for a BDD assumption**.

#### Example

```java
@Test
public void when_all_assumptions_are_met_the_test_is_run_normally() {
  // since this assumption is true ...
  given(frodo.getRace()).isEqualTo(HOBBIT);
  // ... this assertion is performed
  then(fellowshipOfTheRing).doesNotContain(sauron);
}
```

**Comment by joel-costigliola** [comment]
I wonder why I haven't thought about it, great idea, love the fluency @gmullerb !

**Comment by joel-costigliola** [comment]
Go for it!

**Comment by gmullerb** [comment]
Superb! Thank You!
