### ISSUE TITLE
filteredOn with Function for arrays and iterables 

### ISSUE THREAD

**Issue by mgrafl** [joel-costigliola/assertj-core#1620]
#### Summary

Extend the fluent filter API for arrays and iterables with a method to filter based on a `Function<? super ELEMENT, T>` parameter (e.g., a method reference to a getter) and a `T` parameter (for matching). 

The approach is similar to the `extracting(Function<? super ELEMENT, V>)` method. It will allow a save filtering without introspection.

#### Example

```java
assertThat(fellowshipOfTheRing).filteredOn(TolkienCharacter::getRace, HOBBIT)
                                   .containsOnly(sam, frodo, pippin, merry);

assertThat(fellowshipOfTheRing).filteredOn(character -> character.getRace().getName(), "Hobbit")
                                   .containsOnly(sam, frodo, pippin, merry);
```

**Comment by mgrafl** [comment]
Additionally, the `filterOn` method could accept a `FilterOperator<T>` as second parameter. 

#### Example

```java
assertThat(employees).filteredOn(Employee::getAge, not(800))
                      .containsOnly(luke);
```

**Comment by joel-costigliola** [comment]
Have you tried using a `Predicate` ? as in:
```java
assertThat(employees).filteredOn(employee -> employee.getAge() != 800)
                     .containsOnly(luke);
```

**Comment by mgrafl** [comment]
Yes, but at least for simple equality matching, it appears to me clearer to write 
```java
filteredOn(TolkienCharacter::getRace, value)
``` 
instead of 
```java
filteredOn(character -> Objects.equals(character.getRace(), value))
```

**Comment by joel-costigliola** [comment]
Yes but I'm not sure it is worth having another overload for `filteredOn`, it feels more like syntactic sugar.

**Comment by mgrafl** [comment]
It probably is nothing more than syntactic sugar (but so are lambdas in Java). 

Filtering on the value of a certain property is the most common use of `filterOn` in my unit tests. The `filteredOn(String propertyOrFieldName, Object expectedValue)` method just doesn't feel right in these cases because it lacks type safety and IDE tooling support (e.g., for refactoring).

**Comment by joel-costigliola** [comment]
Alright, I agree it can be added
