### ISSUE TITLE
Add containsOnlyElementsOfOnce

### ISSUE THREAD

**Issue by leventov** [joel-costigliola/assertj-core#1632]
#### Summary
Would be nice to have this method for completeness, in addition to `containsOnlyElementsOf()` and `containsOnlyOnce()`.

#### Example

```java
assertThat(myColl).containsOnlyElementsOfOnce(referenceColl);
```

**Comment by joel-costigliola** [comment]
can you show a concrete example, it's not clear to me what `containsOnlyElementsOfOnce` is supposed to do.

**Comment by leventov** [comment]
It's exact equivalent to `containsOnlyOnce(referenceColl.toArray(new MyElementType[0]))`.

Maybe `containsOnceOnlyElementsOf()` would be a better name.

**Comment by Cal027** [comment]
Any progress or plan? I can try working on this issue.

**Comment by joel-costigliola** [comment]
Sorry for the late feedback, I'm still not sure what is the use case of this is, @leventov @Cal027  do you have a real life example?

**Comment by Cal027** [comment]
I think `containsOnlyElementsOfOnce()` should have the same semantics as `containsOnlyOnce()`, just like the existing `containsOnlyElementsOf()` is same as `containsOnly()`. This feature is only for completeness.

**Comment by joel-costigliola** [comment]
Got it, let's  rename the assertion to `containsOnlyOnceElementsOf` though.
