### ISSUE TITLE
Add 'and' method for BDD assertions

### ISSUE THREAD

**Issue by gmullerb** [joel-costigliola/assertj-core#1640]
#### Summary

When mixing `BDDAssertions` with `BDDMockito`, a classic class import for one of them must be used, i.e. `import org.mockito.BDDMockito` or `import org.mockito.BDDAssertions`, in consequence, the code may look like:

```java
import org.assertj.core.api.BDDMockito;
import static org.mockito.BDDAssertions.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    BDDMockito.then(someMock)
      .should()
      .someMethod1()
    BDDMockito.then(someMock)
      .should()
      .someMethodN()
    then(someField1)
      .isNotEqualTo(false);
    then(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
or vice versa:

```java
import org.assertj.core.api.BDDAssertions;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod1()
    then(someMock)
      .should()
      .someMethodN()
    BDDAssertions.then(someField)
      .isNotEqualTo(false);
    BDDAssertions.then(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
Then a decrease of the readability of the test code arises.

---

#### Approach 1

**`BDDAssertions` can provided a method `and` that will allow to easily avoid this name clash.**

#### Example

```java
import static org.assertj.core.api.BDDAssertions.and;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    and().then(someField1)
      .isNotEqualTo(false);
    and().then(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
(This approach is one of the more maintainable and keeps the spirit of functions for accessing the api, but require internal instantiation).

---

#### Approach 2

**`BDDAssertions` can provided a field `and` that will allow to easily avoid this name clash.**

#### Example

```java
import static org.assertj.core.api.BDDAssertions.and;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    and.then(someField1)
      .isNotEqualTo(false);
    and.then(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
(This approach is the most maintainable, but require internal instantiation).

---

#### Approach 3

**`BDDAssertions` can provided a method `andThen` that will allow to easily avoid this name clash.**

#### Example

```java
import static org.assertj.core.api.BDDAssertions.andThen;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    andThen(someField1)
      .isNotEqualTo(false);
    andThen(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
(This approach is the least maintainable and instantiation is not required).

---

#### Approach 4

 A new class **`BDDAndAssertions` (basically a clone of `BDDAssertions`, to avoid overpopulating `BDDAssertions`) can provided a method `andThen` that will allow to easily avoid this name clash.**

#### Example

```java
import static org.assertj.core.api.BDDAndAssertions.andThen;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    andThen(someField1)
      .isNotEqualTo(false);
    andThen(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
(This approach is one of the less maintainable, but sync tests should do the trick).

---

#### Approach 5

 A new class **`BDDAndAssertions` (basically a clone of `BDDAssertions`, to avoid overpopulating `BDDAssertions`) can provided a method `and` that will allow to easily avoid this name clash.**

#### Example

```java
import static org.assertj.core.api.BDDAndAssertions.andThen;
import static org.mockito.BDDMockito.then;

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    and(someField1)
      .isNotEqualTo(false);
    and(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```
(This approach is one of the less maintainable, but sync tests should do the trick).

---

#### Note

In the meantime (or if the proposal is not viable ), in order to keep readability of test code, the following approach can be use:

```java
import org.assertj.core.api.BDDAssertions;
import static org.mockito.BDDMockito.then;

\\ ...

  // Can be extracted to tests' utility if desired
  public static final BDDAssertions and = new BDDAssertions();

\\ ...
  
  @Test
  public void someTest() {
    \\ ...
    then(someMock)
      .should()
      .someMethod()
    then(someMock)
      .should()
      .someMethodN()
    and.then(someField1)
      .isNotEqualTo(false);
    and.then(someFieldM)
      .isEqualTo(1L);
  }

\\ ...
```

**Comment by joel-costigliola** [comment]
As I commented in the PR, I believe the `and` field should be enough IMO.
