### ISSUE TITLE
Add assertThat for java.time.Duration

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#1650]
#### Summary

It would be good if there is support for `java.time.Duration`

#### Example

```java
Duration duration = Duration.ofMinutes(65);
assertThat(duration)
    .hasMinutes(10)
    .hasHours(1);
//...
```

Some of the options would be the following assertion methods:

* `isZero()`
* `isNegative()`
* `isPositive()`
* `hasDays(long)`
* `hasHours(long)`
* `hasMinutes(long)`
* `hasSeconds(long)`
* `hasMillis(long)`
* `hasNanos(long)`

Not 100% sure whether the `hasXXX` is a good name, couldn't think of something else.

There are also the the variants ending with `Part` but not sure how useful that would be

**Comment by joel-costigliola** [comment]
I agree!

**Comment by scordio** [comment]
> Not 100% sure whether the `hasXXX` is a good name, couldn't think of something else.

What if we use the same approach like `AbstractMapAssert.size()`? This means having `toDays()`, `toHours()`, etc. methods (or even without `to`) which provide a new assertion instance extending `AbstractLongAssert`, similarly to `AbstractMapSizeAssert`.

Not sure if it's too much.

**Comment by filiphr** [comment]
That is interesting, I didn't know that this exists (`AbstractMapAssert#size`). 

I think that the error messages would be a bit easier to do if we do it directly on the potential new `AbstractDurationMapAssert`. 

Having something similar to the `AbstractMapSizeAssert` is also OK to me, but I would like to have something directly so I can chain it easier, without the need to go back and forth.

The error message that I had in mind was something like `expected that <PT1H5M> to have 2 hours, but it had 1` (a bit more aligned with the other errors, but you get the idea). The `PT1H5M` comes from the `Duration#toString`
