### ISSUE TITLE
Regression: allOf(Iterable) and anyOf(Iterable) no longer track descriptions

### ISSUE THREAD

**Issue by sbrannen** [joel-costigliola/assertj-core#1658]
When multiple conditions are supplied as an `Iterable` instead of as an array, the individual descriptions are lost.

The fix in 0640d1d7133bb8253d6c4da336220f6e6d77c677 only addressed multiple conditions provided as an array to `allOf()` or `anyOf()`.

The underlying cause is that `org.assertj.core.condition.Join.Join(Condition<? super T>...)` tracks descriptions; whereas, `org.assertj.core.condition.Join.Join(Iterable<? extends Condition<? super T>>)` does not track descriptions.

See also the workaround I introduced in JUnit 5: https://github.com/junit-team/junit5/commit/b3b21bde93f370aa121128a1fb59aa35cc178e49

**Comment by joel-costigliola** [comment]
🤦‍♂ we'll fix it in the next release, thanks for the quick feedback

**Comment by sbrannen** [comment]
Thanks for the quick turnaround! 👍
