### ISSUE TITLE
Root cause assertions assume exception wrapping

### ISSUE THREAD

**Issue by akroy** [joel-costigliola/assertj-core#1659]
#### Summary
Assertions about root cause exceptions do not work if the root cause exception is not wrapped.

My expectation is that root cause assertion is so that you can declare things about the root cause without worrying about how many times the root cause is wrapped. As is, it only works if it's wrapped 1 or more times. That is, if the root cause exception is not wrapped, the root cause will not be found, despite just being the exception itself.

#### Example
I would expect this to work:
```java
assertThat(new RuntimeException("Message")).hasRootCauseMessage("Message");
```
but you get:
```
java.lang.AssertionError: 
Expecting a root cause with message:
  <"Message">
but actual had no root cause.
```

Does this seem like a fair expectation?/Would a change be accepted?

**Comment by joel-costigliola** [comment]
I get your point but the Java `Throwable.getCause()` documentation states that it will return null if it does not have a cause, what you are suggesting is to consider a simple exception to be its own root cause in contrast to Java. 
Since AssertJ tries to be consistent with Java I think its current behavior is correct.

> Returns the cause of this throwable or null if the cause is nonexistent or unknown. (The cause is the throwable that caused this throwable to get thrown.)

If you can't or don't want to check whether your exception has a cause or not, you can always use [`hasStackTraceContaining`](https://www.javadoc.io/static/org.assertj/assertj-core/3.14.0/org/assertj/core/api/AbstractThrowableAssert.html#hasStackTraceContaining(java.lang.String,java.lang.Object...)).

**Comment by scordio** [comment]
If you tried to debug and see inside a non wrapped `Throwable`, you probably saw a self reference in the `cause` field. But as mentioned by @joel-costigliola the `getCause()` contract is giving back `null` if there is no external reference. The OpenJDK source code also helps for this:

https://github.com/openjdk/jdk/blob/843fe9eb03ef33692edba925666e0214ae6934e6/src/java.base/share/classes/java/lang/Throwable.java#L421-L423

Which I read as "a throwable is not the cause of itself".

**Comment by akroy** [comment]
Hmm, I would suggest that one interpretation is that cause and root cause are different. Not all throwables have direct causes, consistent with core Java, but from the intuitive meaning of the idea of a "root cause", it seems like every exception has a root cause, even if that's just itself. (in this reading, core Java is making a claim about direct causes, not root causes)

That said, I totally understand if you don't read it the same way.

It does seem very useful to be able make assertions about whatever cause is at the root; not sure if there's a better term we might use, even as a different method?

**Comment by joel-costigliola** [comment]
If we followed your suggestion then this we could write:
```java
assertThat(new RuntimeException("Message")).hasNoCause()
                                           .hasRootCauseMessage("Message");
```
which is quite confusing, that's another reason to keep the existing behavior as it is.

**Comment by akroy** [comment]
That's fair. Thanks for taking the time to consider this!

**Comment by akroy** [comment]
For anyone else that comes across this, both Guava and Apache use the semantics I propose, so you can easily workaround by using them instead of the AssertJ method:
https://guava.dev/releases/23.0/api/docs/com/google/common/base/Throwables.html#getRootCause-java.lang.Throwable-
https://commons.apache.org/proper/commons-lang/javadocs/api-3.4/org/apache/commons/lang3/exception/ExceptionUtils.html#getRootCause(java.lang.Throwable)
