### ISSUE TITLE
Nested test classes in BDDAssumptionsTest result in class file collisions

### ISSUE THREAD

**Issue by sbrannen** [joel-costigliola/assertj-core#1662]
The `@Nested` test classes in `BDDAssumptionsTest` result in class file collisions on Microsoft Windows. In addition, Eclipse IDE fails to compile the classes even when not on Windows.

For example:

> Class file collision: A resource exists with a different case: '/assertj-core/target/test-classes/org/assertj/core/api/assumptions/BDDAssumptionsTest$BDDAssumptions_given_boolean_Test.class'.

The clash in the above example is between `Boolean` and `boolean`, and clashes occur for `byte`, `double`, `float`, `long`, and `short` as well.

I suggest renaming classes such as `BDDAssumptions_given_boolean_Test` to `BDDAssumptions_given_boolean_primitive_Test` and `BDDAssumptions_given_boolean_wrapper_Test` for the wrapper.

**Comment by joel-costigliola** [comment]
Will change that, did not notice it as I'm using on linux.

**Comment by joel-costigliola** [comment]
Should be fixed with https://github.com/joel-costigliola/assertj-core/commit/5d715eacc1b1882cbc632d04a226cdc35482eec8 but I need to run a build on windows to be sure (sigh).

**Comment by filiphr** [comment]
@joel-costigliola, not sure if you have access to the GitHub actions (they are coming out of beta anyways in a week or so). If you are interested I could rey and wrap something up. They also have support for building on Windows

**Comment by sbrannen** [comment]
> Should be fixed with [5d715ea](https://github.com/joel-costigliola/assertj-core/commit/5d715eacc1b1882cbc632d04a226cdc35482eec8) but I need to run a build on windows to be sure (sigh).

I can confirm that it's fixed for Eclipse. So one can assume it works on Windows as well (though somebody should actually check it for completeness).

As @filiphr recommended, it would be a good idea to have a build matrix covering Linux, Mac OS, and Windows going forward, since that would help the AssertJ team to catch such errors on the CI server.

**Comment by joel-costigliola** [comment]
yep, I think we are going to have a look at github actions.
thanks

**Comment by joel-costigliola** [comment]
yep, I think we are going to have a look at github actions. @filiphr yes we are interested ;-)
thanks

**Comment by joel-costigliola** [comment]
We have Github actions running windows build (and Mac OS too) :)
