### ISSUE TITLE
Create Assistant issues me an error

### ISSUE THREAD

**Issue by sriketh16** [joel-costigliola/assertj-core#1684]
#### Summary
I have followed the instructions outlined on how to create an assistant after installing the auto-pilot CLI.  Installation was successful.  
After the installation, I entered "ta create" to use the existing assistant template.  After I chose the template, it is giving me the following error:

#### Example? List of templates you can chose Airline Reservations
×  Initializing Twilio Autopilot project from the chosen template...
ERROR: Error: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```java
<add example here>
```

**Comment by sriketh16** [comment]
What do I need to do to fix the above error?

**Comment by joel-costigliola** [comment]
this has nothing with assertj

**Comment by sriketh16** [comment]
I am not sure why the issue is closed. I am new and wondering if a solution or recommendation to fix can be provided

**Comment by joel-costigliola** [comment]
As I have said your issue is not related to this project.
