### ISSUE TITLE
Missing assertion with a timeout

### ISSUE THREAD

**Issue by Sam-Kruglov** [joel-costigliola/assertj-core#1688]
#### Summary
I want to execute something asynchronously and then execute my assertion every second for 15 seconds at max to verify the thing is done.

#### Example

```kotlin
whenOtherServiceEmitsUpdate()

Probe(
        Timeout(15, TimeUnit.SECONDS),
        1000,
        { entityRepo.findById(blockedEntity.id).lastStatus },
        { it == State.ACTIVE }
).check()
```

Where I had to manually implement the `Probe` util like this:
```kotlin
class Probe<R>(
        val timeout: Timeout,
        val backoffTimeMs: Long,
        val sampler: () -> R,
        val expectedCondition: (R) -> Boolean) {

    var result: R? = null

    fun check() {
        result = sampler.invoke()
        while (!expectedCondition.invoke(result!!)) {
            if (timeout.hasTimedOut()) {
                assertThat(false)
                        .describedAs("The sampler didn't get result within $timeout!")
                        .isTrue()
            }
            Thread.sleep(backoffTimeMs)
            result = sampler.invoke()
        }
    }
}
```

I wish there was something like that in the library

**Comment by epeee** [comment]
Hi,
sounds like [awaitility](https://github.com/awaitility/awaitility) might help in your case, see https://github.com/awaitility/awaitility/wiki/Usage#using-assertj-or-fest-assert

**Comment by Sam-Kruglov** [comment]
Thanks a lot, @epeee, that does sound exactly like what I need!
In that case, don't really see a point of reimplementing this here
