### ISSUE TITLE
weird messaging for enum when testing isPublic

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#1692]
#### Summary

the messaging here is weird, I'm not sure it's a bug, or really whether it must be fixed

#### Example

```
Expecting:
  <com.potreromed.phg.entity.RoleName>
to be a "public" class but was "final".
```

```java
enum RoleName { // in my own file
    MONITOR
}

   @ParameterizedTest
    @ArgumentsSource( EntityClassProvider.class)
    void publicClass( Class<?> clazz ) {
        assertThat(clazz).isPublic();
    }

static class EntityClassProvider implements ArgumentsProvider {

        @Override
        public Stream<? extends Arguments> provideArguments( ExtensionContext context ) throws Exception {
            return Stream.of(
                Arguments.of( RoleName.class )
            );
        }
    }
```

**Comment by joel-costigliola** [comment]
We'll look into it, thanks for reporting this.

**Comment by scordio** [comment]
According to the example, `RoleName` is package-private (i.e., no modifiers).

Also, from [JLS section 8.9](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9):

> An enum declaration is implicitly final unless it contains at least one enum constant that has a class body

Overall the message seems OK!

Maybe it could be improved either mentioning what is implicit or printing the values of all possible flags.

**Comment by xenoterracide** [comment]
yeah, I just thought it was weird that I'm checking for public and get back it's final, my thought was ok, what does one have to do with the other. obviously I knew it was because they were modifiers. I also thought package private was confusing because it just comes out as "", but not too hard to figure out. printing them all might be better, I'll leave it up to you, as I don't really have a better suggestion.

**Comment by scordio** [comment]
Since a13f73bd73ad94e648bc74bbc72dbe2a0c300a18, `AbstractClassAssert#isPackagePrivate` is available and gives the following output in case of error:
```
Expecting:
  <java.lang.String>
to be a "package-private" class but was "public final".
```
For completeness, we could support a `package-private` output value in the `ClassModifierShouldBe` error message factory. As `ClassModifierShouldBe` relies on `java.lang.reflect.Modifier#toString`, we would need to enhance the outcome with an additional `package-private` string if relevant for the error.

@joel-costigliola thoughts?

**Comment by joel-costigliola** [comment]
the new error message adds `package-private`, it looks like:
```
[TEST] 
Expecting:
  <org.assertj.core.error.ClassModifierShouldBe_create_Test.PackagePrivate>
to be a "public" class but was "package-private static final".
```
