### ISSUE TITLE
isPackagePrivate() missing from AbstractClassAssert

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1700]
#### Summary
Currently `AbstractClassAssert` provides `isPublic()` and `isProtected()` methods to assert access level modifiers. I would also add `isPackagePrivate()` for completeness.

#### Current solution
```java
Condition<Class<?>> packagePrivate = new Condition<>(clazz -> {
	int mod = clazz.getModifiers();
	return !(Modifier.isPublic(mod) || Modifier.isProtected(mod) || Modifier.isPrivate(mod));
}, "package-private");

assertThat(MyClass.class).is(packagePrivate);
```

#### Improvement
```java
assertThat(MyClass.class).isPackagePrivate();
```

I was also thinking if `isPrivate()` would make sense but probably there is no real use case for it as the class should be declared inside the test class itself.

**Comment by mwajcht** [comment]
I can take it

**Comment by scordio** [comment]
Thank you @mwajcht, go for it!
