### ISSUE TITLE
How to check if a list of objects has an element with a String property matching a regex pattern

### ISSUE THREAD

**Issue by laskybontiagmail** [joel-costigliola/assertj-core#1709]
#### Summary
Given a list of objects with a String field or getter method returning a String, is there a way in assertj to check if out from the list an object contains a string based from a "Regular Expression Pattern"?

Kindly see example below for more details.

#### Example

```java
class MyObject {
    private String theValue;
    
    public String getValue() {
       return theValue;
    }
    public void setValue(String newValue) {
        this.theValue = newValue;
    }
    
}

List<MyObject> listOfMyObjects = new ArrayList<MyObject>();

// populate the list here...

assertThat(listOfMyObjects).extracting("value").containsAnElementWith("some regular expressions here...");

```

**Comment by scordio** [comment]
You could use [`extracting(Function)`](https://www.javadoc.io/static/org.assertj/assertj-core/3.14.0/org/assertj/core/api/AbstractIterableAssert.html#extracting(java.util.function.Function)) together with [`anyMatch`](https://www.javadoc.io/static/org.assertj/assertj-core/3.14.0/org/assertj/core/api/AbstractIterableAssert.html#anyMatch(java.util.function.Predicate)) or [`anySatisfy`](https://www.javadoc.io/static/org.assertj/assertj-core/3.14.0/org/assertj/core/api/AbstractIterableAssert.html#anySatisfy(java.util.function.Consumer)):

```java
MyObject foo = new MyObject();
foo.setValue("foo");
MyObject aaa = new MyObject();
aaa.setValue("aaa");
List<MyObject> listOfMyObjects = Arrays.asList(foo, aaa);

assertThat(listOfMyObjects)
  .extracting(MyObject::getValue)
  .anyMatch(value -> value.matches("a*")) // shorter with java.lang.String#matches
  .anySatisfy(value -> assertThat(value).matches("a*")); // nicer error message with StringAssert
```

**Comment by joel-costigliola** [comment]
@laskybontiagmail I'm closing the issue, feel free to comment if you need more help and we will reopne it.
