### ISSUE TITLE
Feature to compare two JSON strings?

### ISSUE THREAD

**Issue by Pezhin** [joel-costigliola/assertj-core#1722]
#### Summary
Does assertj have function to compare if two JSON strings are equal? By equal, I mean the key-value mapping are the same but the order might be different. I found project like https://github.com/skyscreamer/JSONassert provides such functionalities. Does assertj already have something like this? 

If not, are contributions like introducing JSONassert as dependency and add new assert methods so that `assertThat(jsonA).isSameJsonAs(jsonB)`

#### Example

```java
assertThat("{a : {a : 2}, b : 2}").isSameJsonAs("{b : 2, a : {a : 2}}"); // pass
```

**Comment by joel-costigliola** [comment]
nope we recpmmand JSONAssert or https://github.com/lukas-krecan/JsonUnit

**Comment by filiphr** [comment]
JsonUnit also have AssertJ support https://github.com/lukas-krecan/JsonUnit#assertj-integration. So it is a really good fit for AssertJ users.
