### ISSUE TITLE
[Android 6] IllegalArgumentException: Unknown pattern character 'X'

### ISSUE THREAD

**Issue by valeriyo** [joel-costigliola/assertj-core#1730]
#### Summary
On Android 6.0 (API 23) asserting Dates for equality fails with "java.lang.IllegalArgumentException: Unknown pattern character 'X'" - because apparently "X" wasn't supported.

#### Example

```kotlin
assertThat(Date(123)).isEqualTo(Date(123))
```

Repros with latest `assertj-core` 3.14.0

**Comment by joel-costigliola** [comment]
Unfortunately we won't revert the changes that provided the `X` date format character support as this is standard java, AssertJ tries to be Android compatible but not at the expense of standard java.

If you know the date format in use, you can register it as a custom date format as they take precedence over the default ones.

I realized the javadoc is missing two of the supported default date format, we will add that and document the workaround for android users.

**Comment by joel-costigliola** [comment]
Addressed in https://github.com/joel-costigliola/assertj-core/commit/f4c95bfa4de071f1357c3c438f3f8fa825064f6d
