### ISSUE TITLE
org.assertj.core.api.junit.jupiter not exported in module-info

### ISSUE THREAD

**Issue by jftsunami** [joel-costigliola/assertj-core#1735]
The package `org.assertj.core.api.junit.jupiter` should be added to the module-info exports.

**Comment by joel-costigliola** [comment]
@scordio looks related to https://github.com/joel-costigliola/assertj-core/pull/1717 WDYT?

**Comment by scordio** [comment]
@joel-costigliola I think so, although it's not clear (to me) yet which direction we want to take about modular testing. My feeling is that we need first to revise if the current package is correctly built to satisfy both java 8 and modular java 9+ apps, then we can understand the gaps to cover with automated testing.

Anyway, in preparation for the 3.15 release, I would suggest to add the missing statements to `module-info.java`, like the one reported here, the one from #1656 and the others detected in #1713 

If you agree, I can tackle those cases.

**Comment by joel-costigliola** [comment]
that would be great thanks!

**Comment by jftsunami** [comment]
Thank you.
