### ISSUE TITLE
Quick start refers to older version

### ISSUE THREAD

**Issue by frankbenoit** [joel-costigliola/assertj-core#1738]
#### Summary
https://joel-costigliola.github.io/assertj/assertj-core-quick-start.html
Here the maven+gradle dependency shown refers to 3.11.1, but the current version is higher.
The page should be updated.

**Comment by frankbenoit** [comment]
... and for Gradle 5+, `testCompile` shall be replaced with `testImplementation`

**Comment by frankbenoit** [comment]
.. dead link
https://joel-costigliola.github.io/assertj/assertj-core-news.html
Add Assumptions for Java 8 types to skip tests when preconditions are not satisfied.
Points to https://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.9.0-assumptions
which is not reachable.

**Comment by frankbenoit** [comment]
.. "JavaDoc (3.x)" links to 3.12.0 API, not the current 3.14.

**Comment by joel-costigliola** [comment]
Hi @frankbenoit, this is the old site, the new one has moved to https://assertj.github.io/doc/ as per https://joel-costigliola.github.io/assertj/index.html ;-)

**Comment by joel-costigliola** [comment]
If you find things to improve in the new site, please raise an issue in https://github.com/assertj/doc and even better address them with a PR, the new site is asciidoc which is much nicer to write.

**Comment by frankbenoit** [comment]
@joel-costigliola right, it is pretty bold in the first page.

However, the old page is still first hit in google.
I navigate there, and directly hit "quick start" without reading the front page, because i knew from earlier where to find the needed info.

I guess it would be good in the old page to have the big blinking "old page, go there" on each subpage.

**Comment by joel-costigliola** [comment]
yeah, until people goes to the new site and google stop making it a the first it.
