### ISSUE TITLE
How is isDirectoryContaining supposed to work?

### ISSUE THREAD

**Issue by LorenzoBettini** [joel-costigliola/assertj-core#1740]
#### Summary

I don't understand how org.assertj.core.api.AbstractFileAssert.isDirectoryContaining(String) is supposed to work (or is its Javadoc wrong?): According to its Javadoc

```
Verify that the actual File is a directory containing at least one file matching the given String interpreted as a path matcher (as per FileSystem.getPathMatcher(String)).

Note that the actual File must exist and be a directory.

Given the following directory structure:

 /root/
 /root/sub-dir-1/
 /root/sub-dir-1/file-1.ext
 /root/sub-dir-1/file-2.ext
 /root/sub-file-1.ext
 /root/sub-file-2.ext
Here are some assertions examples:
 File root = new File("root");

 // The following assertions succeed:
 assertThat(root).isDirectoryContaining("glob:**sub-dir*")
                 .isDirectoryContaining("glob:**sub-file*")
                 .isDirectoryContaining("glob:**.ext")
                 .isDirectoryContaining("regex:.*ext")
                 .isDirectoryContaining("glob:**.{ext,bin");

 // The following assertions fail:
 assertThat(root).isDirectoryContaining("glob:**dir");
 assertThat(root).isDirectoryContaining("glob:**.bin");
 assertThat(root).isDirectoryContaining("glob:**.{java,class}"); 
```

If I have a directory "root/com/example/Example.java", then this assertion should succeed (where outputDirectory is "root"):

```
assertThat(outputDirectory)
			.isDirectoryContaining("glob:**.java");
```

But it fails saying that the directory contents is "com".

**Comment by joel-costigliola** [comment]
The javadoc indicates the syntax follows https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystem.html#getPathMatcher-java.lang.String- which is not straightforward I do agree hence the other assertions with a `Predicate` where you can programmatically expresses the filter.

It looks like the `**` syntax is not traversing sub-directories but only look at the directory first level content, I need more time to confirm if it's a bug.

**Comment by LorenzoBettini** [comment]
Indeed I was expecting a recursive traverse assertion

**Comment by joel-costigliola** [comment]
Just confirming it's not a bug and that the only the given directory is inspected. 

Having said that, there is room for similar assertions with a recursive traversal of all subdirectories.
Possible syntax:
```java
//  - 1
boolean recursively = true;
assertThat(outputDirectory).isDirectoryContaining("glob:**.java", recursively);
// - 2 
assertThat(outputDirectory).isDirectoryOrSubdirectoriesContaining("glob:**.java");
// - 3 
assertThat(outputDirectory).isDirectoryRecursivelyContaining("glob:**.java");
```
@LorenzoBettini WDYT? any better naming?

**Comment by joel-costigliola** [comment]
@scordio any naming suggestion for the recursive assertion?

**Comment by LorenzoBettini** [comment]
I would tend to avoid the boolean parameter (solution 1) and to prefer 3; the name in 2 does not sound correct in English but I'm not a native speaker ;)

**Comment by ebundy** [comment]
@joel-costigliola 
Hello,

If not implemented yet, I can work on it.

**Comment by joel-costigliola** [comment]
Thanks @ebundy, let's  implement no3:
```java
assertThat(outputDirectory).isDirectoryRecursivelyContaining("glob:**.java");
````

**Comment by ebundy** [comment]
Hello,

> Thanks @ebundy, let's implement no3:
> 
> ```java
> assertThat(outputDirectory).isDirectoryRecursivelyContaining("glob:**.java");
> ```

You are welcome. I have just examined the current API around `isDirectoryContaining()`. 
To be consistent and symmetric with the current API we should define 4 API methods both for `FileAssert`. WDYT?
If the approach suits correct for you, I will do the job for these 4 methods ofp `FileAssert`  : 
```
- isDirectoryRecursivelyContaining(String syntaxAndPattern)
- isDirectoryRecursivelyNotContaining(String syntaxAndPattern)
- isDirectoryRecursivelyContaining(Predicate<File> filter)
- isDirectoryRecursivelyNotContaining(Predicate<File> filter)
```

And just for the record, it seems that `PathAssert` the Path counterpart of `FileAssert` should probably be enriched with these new methods to keep the two Assert API consistent. Let' see that later.

**Comment by ebundy** [comment]
In `org.assertj.core.internal.Files`,  is there any reason to not use the Java 7 Path API to perform the processings ? 

In assert methods I will add, for example  `assertIsDirectoryRecursivelyContaining()`,  in order to prevent iterate files more than required and to keep the code simple, I would like to favor `Files.walk(inputFile.toPath())` to some recursive call to `File.listFiles(FileFilter)` +  such as : 

      boolean isAnyMatch = java.nio.file.Files.walk(actual.toPath())
                                     .map(Path::toFile)
                                     .anyMatch(filter);

**Comment by joel-costigliola** [comment]
> I will do the job for these 4 methods ofp FileAssert :

The 4 methods are needed for consistency, yes.
They should also be added to path assertions but in another PR to keep the PR to a reasonable size.
One thing you can do is implement one of the method and notify me when it is done, I can then review it. This will give guidance for the remaining methods to write and less work for both of us (general review comments won't have to be addressed four times, once the first is right and then do the others the same way)

> In assert methods I will add, for example `assertIsDirectoryRecursivelyContaining()`, in order to prevent iterate files more than required and to keep the code simple, I would like to favor `Files.walk(actual.toPath())` to some recursive call to `File.listFiles(FileFilter)`

I'm fine with that and like the functional style of the example!

**Comment by ebundy** [comment]
Agreed. Let's go.

**Comment by ebundy** [comment]
@joel-costigliola

You probably didn't see my edit. Sorry, the next time I would add another comment instead of.

**Comment by joel-costigliola** [comment]
I indeed missed it! I'll think about it and get back to you. (ping me if I don't by the end of the week)

**Comment by ebundy** [comment]
Ok, thanks !

**Comment by joel-costigliola** [comment]
@ebundy sorry for the late reply, about the testing approach could we simply create directory on the fly as needed by our tests? Although experimental we can leverage JUnit 5 [TempDir extension](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/io/TempDir.html). 
WDYT?

**Comment by ebundy** [comment]
@joel-costigliola  No problem. I think that I like very much the idea. 
Thanks for your feedback.
