### ISSUE TITLE
Recursive assertions fail for nested enum types

### ISSUE THREAD

**Issue by wujek-srujek** [joel-costigliola/assertj-core#1741]
#### Summary

I have two types, an entity and a DTO, and they have a field called 'status', which are of different types but otherwise have identical constants. When using:

    assertThat(entity)
            .usingRecursiveComparison()
            .ignoringAllOverriddenEquals()
            .isEqualTo(dto)

differences between the enum fields are not reported. I debugged a bit and turns out the 'equals' method is ignored for the fields (correctly, as I used 'ignoringAllOverriddenEquals') and they are attempted to be compared recursively again (i.e. their fields). There are no fields in these enums, so the difference is not reported at all.

Ignoring equals is not taken into account for Java types (https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration.java#L361)

Maybe a similar exception should be made for enums, i.e. enums should be compared by using their name? Even if there are custom fields in the enums, the name check should be enough?

**Comment by joel-costigliola** [comment]
looks like https://github.com/joel-costigliola/assertj-core/issues/1691, right?

**Comment by wujek-srujek** [comment]
Seems like it, with the only exception being that I compare two different types, and the enums are also different (one mirrors the other, but one has just the constants and the other a few other methods) so using == will not work. Here is a workaround I came up with based on the other issue (Kotlin code):

    .withComparatorForType({ entityStatus: Enum<*>, dtoStatus: Enum<*> -> entityStatus.name.compareTo(dtoStatus.name) }, Enum::class.java)

**Comment by joel-costigliola** [comment]
Using a specific comparator is one way to go if the enum are different types.

I think we should actually change the current implementation that uses `==` to compare enums, this is fine if the `strictTypeChecking` flag is `true` but if not (and by default it's not) we should not care about the type and just compare the enums according to their `name()` which is what you did.

**Comment by wujek-srujek** [comment]
Does this mean that, once this improvement is implemented, a custom comparatorForType similar to what I did will not be needed any more, even for non-strict type checking (i.e. different enum types)?

**Comment by joel-costigliola** [comment]
With this improvement, you will only need a comparator if you have enable the `strictTypeChecking`.
