### ISSUE TITLE
Chained HasNoNullFieldsOrPropertiesExcept should have the same effect as using it once

### ISSUE THREAD

**Issue by x80486** [joel-costigliola/assertj-core#1747]
## Summary

`hasNoNullFieldsOrPropertiesExcept` can be chained, hence, it looks like it should account for all the values on the different places where it is used before stating the result(s).

### Example

```java
@Test
void instantiate() {
  // Actor inherits id, createdOn, updatedOn, and version
  // filmActors is a member of Actor
  final Actor actor = new Actor("first-name", "last-name");
  Assertions.assertThat(actor)
      .hasNoNullFieldsOrPropertiesExcept("id", "createdOn", "updatedOn", "version")
      .hasNoNullFieldsOrPropertiesExcept("filmActors")
      .satisfies(it -> {
        Assertions.assertThat(it.firstName).isEqualTo("first-name");
        Assertions.assertThat(it.lastName).isEqualTo("last-name");
        // ...inherited fields
      });
}
```

> If `filmActors` is placed on the first `hasNoNullFieldsOrPropertiesExcept` everything is fine.

**Comment by joel-costigliola** [comment]
By default AssertJ stops at the first failing assertion, to get a report will all failed assertions you have to use soft assertions https://assertj.github.io/doc/#assertj-core-soft-assertions.

Is that what you are looking for?

**Comment by joel-costigliola** [comment]
@x80486 I'm closing this issue but happy to reopen it if my answer did not address it.
