### ISSUE TITLE
Recursive comparison that ignore fields by types

### ISSUE THREAD

**Issue by tommysitu** [joel-costigliola/assertj-core#1749]
`.usingRecursiveComparison()` is really useful for objects that don't override equals and hashcode.

In order to assert an object with fields that has random values, like id, uuid or datetime, I'll need to ignore them using this method:
https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/RecursiveComparisonAssert.java#L251

```
RecursiveComparisonConfiguration ignoreIdConfig = new RecursiveComparisonConfiguration();
ignoreIdConfig.ignoreFields("idFieldName");
assertThat(actual)
        .usingRecursiveComparison(ignoreIdConfig)
        .isEqualTo(expected);
```

It works like a charm, but supplying the field name with a string is not type-safe, I wonder if it's possible to add a method that can take field type as arguments like this: 

```
ignoreIdConfig.ignoreFields(ZonedDateTime.class, UUID.class);
```

So it will match and ignore any fields with the given types.

**Comment by joel-costigliola** [comment]
We certainly add that, something like `ignoreFieldsForTypes(Class<?>... typesToIgnore)`

**Comment by tommysitu** [comment]
I can try raising a PR for that :)

**Comment by joel-costigliola** [comment]
closed with https://github.com/joel-costigliola/assertj-core/commit/5afe94e73776e1c24f2bafaf5a5cdbeb9f7ad85d
