### ISSUE TITLE
Is it possible to provide RecursiveComparisonConfiguration for usingRecursiveFieldByFieldElementComparator()

### ISSUE THREAD

**Issue by tommysitu** [joel-costigliola/assertj-core#1750]
I can pass a `RecursiveComparisonConfiguration`  to `usingRecursiveComparison()` for ignoring certain fields, but it's not possible when asserting collection types  with `usingRecursiveFieldByFieldElementComparator()`.

**Comment by joel-costigliola** [comment]
Indeed it is not possible, that's why we added `usingRecursiveComparison()` and the new recursive comparison API.
There is no plan to to retrofit but in 3.15.0 at the moment.

**Comment by tommysitu** [comment]
ok, will check out the new recursive comparison API 👍 

I have been doing this with v3.14.0
```
assertThat(list)
        .anySatisfy(actual -> assertThat(actual).usingRecursiveComparison(config)
            .isEqualTo(expected));
```
