### ISSUE TITLE
Detailed assertion error if the field is an object itself with many fields

### ISSUE THREAD

**Issue by aleks-oracle** [joel-costigliola/assertj-core#1757]
#### Summary
Hello! We faced the problem that if the field in comparing objects is an object itself and there are assertion errors, assertJ does not print in the error message exact fields from these objects which do not equal, only the message that fields do not equal.
It is a huge problem when object contains 100+ fields.

#### Example
java.lang.AssertionError: 
Expecting: ...
to be equal to:...
...
when recursively comparing field by field, but found the following difference:

field/property 'insuranceContract' differ:
- actual value   :
   print an actual insuranceContract object with all its 100+ fields
- expected value :
  print an expected insuranceContract object with all its 100+ fields

"insuranceContract" is one of the fields of comparing objects.
So, to find the real differences in two insurance contracts, we have to copy the error message and compare results in some text editor.

Use use 3.14 and construction:
```java
assertThat(actualObject).usingRecursiveComparison().isEqualTo(expectedObject);
```

Is there any possibility to print exact nested fields which do not equal?

**Comment by joel-costigliola** [comment]
AssertJ recursive comparison compares fields and prints their differences, fields are compared with their `equals` method if the latter has been overridden (so no sub-recursive comparison in that case), I suspect that the huge display comes from fields that have overridden `equals`.

You can ignore `equals`, see https://assertj.github.io/doc/#assertj-core-recursive-comparison-ignoring-equals.

If that does not work, can you provide a test case reproducing the behavior?

**Comment by aleks-oracle** [comment]
Omg, it did help!
We actually have implicit overridden 'equals' by Lombok's @Data annotation.
So, we added 'ignoringAllOverriddenEquals()' and  got the desired result:

field/property 'insuranceContract.insurerId' differ:
- actual value   : "38681792"
- expected value : "rerefer"

Thank you so much!

P.S. Also, let me thank you for this amazing assertJ library.
We moved to it from testNG's assertions and discovered many advantages which help us every day.

**Comment by joel-costigliola** [comment]
Glad it helped and thanks for the kind words :)

**Comment by hauler** [comment]
I guess this does not help in case of Objects inside of Collections inside of Objects and so on... when ignoring collection order. See the test:
```
import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Objects;

import org.junit.jupiter.api.Test;

public class ListMatcherTest {

	@Test
	void test() {
		final ClassWithList expected = new ClassWithList("wow", List.of(
				new ClassWithList("aaa"),
				new ClassWithList("bbb", List.of(new ClassWithList("111 diff"), new ClassWithList("222"))),
				new ClassWithList("ccc")));
		final ClassWithList actual = new ClassWithList("wow", List.of(
				new ClassWithList("aaa"),
				new ClassWithList("ccc"),
				new ClassWithList("bbb", List.of(new ClassWithList("222"), new ClassWithList("111")))
		));

		assertThat(actual)
				.usingRecursiveComparison()
				.ignoringCollectionOrder()
				.ignoringAllOverriddenEquals()
				.isEqualTo(expected);
	}

	public static class ClassWithList {
		private final String name;
		private final List<ClassWithList> list;

		public ClassWithList(String name) {
			this.name = name;
			this.list = null;
		}

		public ClassWithList(String name, List<ClassWithList> list) {
			this.name = name;
			this.list = list;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o)
				return true;
			if (o == null || getClass() != o.getClass())
				return false;
			ClassWithList that = (ClassWithList) o;
			return name.equals(that.name) && Objects.equals(list, that.list);
		}

		@Override
		public int hashCode() {
			return Objects.hash(name, list);
		}

		@Override
		public String toString() {
			return "ClassWithList{" +
					"name='" + name + '\'' +
					", list=" + list +
					'}';
		}
	}
}

```
