### ISSUE TITLE
Using a custom comparator for a type not working

### ISSUE THREAD

**Issue by blackat** [joel-costigliola/assertj-core#1765]
#### Summary
I would like to extract from each element in the list only certain properties.
One of them is an Object with id and name, but the test fails.

In debug mode the comparator is not even called, so the default equals is called. Any of the objects contains equals.

Could you please advise me on how to set and use the custom comparator?

#### Example

```java
ModelDTO m1 = new ModelDTO();
m1.setName("model1");
m1.setModelOwner(new MinimalDTO(1L, "user1"));

ModelDTO m2 = new ModelDTO();
m2.setName("model2");
m2.setModelOwner(new MinimalDTO(2L, "user2"));

ModelDTO[] models = {m1, m2};

// fail
assertThat(asList(models))
    .extracting(ModelDTO::getName, ModelDTO::getModelOwner)
    .usingComparatorForElementFieldsWithType(new MinimalDTOComparator(), MinimalDTO.class)
    .containsAnyOf(tuple("model1", new MinimalDTO(1L, "user1")));
```

This is the exception I obtain
```java
java.lang.AssertionError: 
Expecting:
 <[("model1", MinimalDTO{id=1, name=user1}),
    ("model2", MinimalDTO{id=2, name=user2})]>
to contain:
 <[("model1", MinimalDTO{id=1, name=user1})]>
but could not find:
 <[("model1", MinimalDTO{id=1, name=user1})]>
```

If I then add `.usingElementComparatorOnFields("modelOwner")` I get this exception
```java
java.lang.AssertionError: 
Expecting:
 <[("model1", MinimalDTO{id=1, name=user1}),
    ("model2", MinimalDTO{id=2, name=user2})]>
to contain:
 <[("model1", MinimalDTO{id=1, name=user1})]>
but could not find:
 <[("model1", MinimalDTO{id=1, name=user1})]>
when comparing values using single field/property comparator on field/property "modelOwner"
Comparators used:
- for elements fields (by type): {MinimalDTO -> com.frsglobal.riskpro.testingplan.comparator.MinimalDTOComparator@74d1dc36, Double -> DoubleComparator[precision=1.0E-15], Float -> FloatComparator[precision=1.0E-6]}
- for elements (by type): {Double -> DoubleComparator[precision=1.0E-15], Float -> FloatComparator[precision=1.0E-6]}
```

Finally, the assertion passes if I use ` .usingRecursiveFieldByFieldElementComparator()`:
```java
// pass
 assertThat(asList(models))
                .extracting(ModelAdminDTO::getName, ModelAdminDTO::getModelOwner)
                .usingComparatorForElementFieldsWithType(new MinimalDTOComparator(), MinimalDTO.class)
                .usingRecursiveFieldByFieldElementComparator()
                .contains(tuple("model1", new MinimalDTO(1L, "user1")));
```

**Comment by joel-costigliola** [comment]
The [javadoc](https://www.javadoc.io/static/org.assertj/assertj-core/3.14.0/org/assertj/core/api/AbstractIterableAssert.html#usingComparatorForElementFieldsWithType(java.util.Comparator,java.lang.Class)) states that 

> To be used, comparators need to be specified by this method before calling any of:
> -  usingFieldByFieldElementComparator()
>  - usingElementComparatorOnFields(java.lang.String...)
>  - usingElementComparatorIgnoringFields(java.lang.String...)
>   - usingRecursiveFieldByFieldElementComparator()

You should give a try to new recursive API which gives better report and more control over the comparison

**Comment by joel-costigliola** [comment]
@blackat I'm closing that issue but feel free to comment if you need more information

**Comment by blackat** [comment]
Thanks a lot @joel-costigliola I will go on experimenting/testing :-)
