### ISSUE TITLE
Version 3.15.0 not available via Maven Central et al

### ISSUE THREAD

**Issue by sormuras** [joel-costigliola/assertj-core#1766]
#### Summary

It looks like version `3.15.0` was released today:

- https://github.com/joel-costigliola/assertj-core/releases/tag/assertj-core-3.15.0
- https://twitter.com/JoCosti/status/1222091408346992642

> AssertJ Core 3.15.0 is available! check the release notes https://assertj.github.io/doc/#assertj-core-3-15-0-release-notes
Thanks to the AssertJ team: Stefano Cordio, Pascal Schumacher and Erhard Pointl.
Happy assertions!

But it is not available from various places:

- [x] https://search.maven.org/artifact/org.assertj/assertj-core
- [ ] https://repo1.maven.org/maven2/org/assertj/assertj-core/ (partly)
- [x] https://bintray.com/bintray/jcenter/org.assertj:assertj-core

Am I too early? Is the upload still in progress?

**Comment by scordio** [comment]
It should appear soon as it's already available in the [OSS Nexus](https://oss.sonatype.org/content/groups/public/org/assertj/assertj-core/3.15.0/).

**Comment by sormuras** [comment]
Updated initial description as search and bintray are providing the version.

**Comment by joel-costigliola** [comment]
https://repo1.maven.org/maven2/org/assertj/assertj-core/3.15.0/ is good although 3.15.0 does not show up in https://repo1.maven.org/maven2/org/assertj/assertj-core/ but I guess it's juts a matter of time

**Comment by joel-costigliola** [comment]
https://repo1.maven.org/maven2/org/assertj/assertj-core/ is good now, closing the issue
