### ISSUE TITLE
Add "Remove duplication for Descriptable implementations" to braking changes of 3.15.0

### ISSUE THREAD

**Issue by lukas-krecan** [joel-costigliola/assertj-core#1774]
#### Summary

This commit https://github.com/joel-costigliola/assertj-core/commit/618609cc0a05414ef1a117cf616621310cd062ee#diff-c0ecfbb7e9c4271683c9c00215303ca9 moved method implementations from an abstract class to interface default method. While it it source compatible change, it breaks libraries that were compiled with older version. (see for example https://github.com/lukas-krecan/JsonUnit/issues/216). I did not have time to dive into details, but I assume that the bytecode for the method call differs.

Please add it to breaking changes in release notes and ideally do not do such changes in future minor releases.

**Comment by joel-costigliola** [comment]
I'll add it to the release notes breaking changes.

**Comment by scordio** [comment]
Done in [18ecd0c](https://github.com/assertj/doc/commit/18ecd0c131fe34c2dcc23c62cf1668309390e704).
