### ISSUE TITLE
ImprovementRequest: please add the ability to display successful asserts as well

### ISSUE THREAD

**Issue by SebastianStavar** [joel-costigliola/assertj-core#1777]
It would be wonderful if we would have the ability to display the test description when it passes as well. Like overload as() to have a boolean parameter which when set to true would display the description when the test passes as well.

**Comment by SebastianStavar** [comment]
Looks like I'm not the only one wanting this. https://stackoverflow.com/questions/56436541/assertj-log-all-passing-and-failing-assertions contains a case why this would be useful.

**Comment by joel-costigliola** [comment]
Where does the description should be displayed? console output? a report of some sort?
Writing on the console should be starightforward, having a report is not, that will likely require some kind of global state (which usually rings alarms to my ears)

I would rather add a parameter in assertj global configuration to control that over overloading as.

**Comment by SebastianStavar** [comment]
To be honest in my case console output is fine. The reason I mentioned the overload is because this way you could decide which asserts you do want to see even when they pass and which ones you don't. At the same time I do see your point of having a global config that you can just switch on/off and then all asserts behave the same and I think that is the more probable case.

**Comment by joel-costigliola** [comment]
What is your use case exactly, debugging tests? or having a report of what went well?

**Comment by SebastianStavar** [comment]
Debug in my case. As part of the logs I also have a highly verbose output from the console of a device, so it would be nice to be able to see the asserts happening as the test progresses while also monitoring what the device is outputting. It would be easier to follow the tests progressing to the point of failure.
But to be honest I perfectly see a case where as part of a bdd approach I don't only say "THEN I verify the box is happy" but I also output what the actual checks were. Would be useful for both live documentation, supervision of tests, learning when new to the domain, deep reporting, etc.

**Comment by joel-costigliola** [comment]
I'll go for displaying the assertion description to the console. 
@SebastianStavar I was thinking to a global configuration property to control whether descriptions are displayed or not, is that too broad? do you need control per assertion?

**Comment by SebastianStavar** [comment]
Hi,

Thanks for considering adding this. 

I would think that a global config property should be good enough. Normally I would like to see them all displayed as the test progresses. In my case there was no way I would have liked to see some assertions, but not others. More options are good (well not from a testing/maintenance point of view), but since this is a new feature, get it going and if people come and say this is awesome but you know what would make it more awesome, having this amount of control, then you can probably add it then.

And yes, imho a log consumer will definitely be preferred to straight sysout.
