### ISSUE TITLE
Feature request: isEqualToComparingFieldByField - recursive

### ISSUE THREAD

**Issue by j-maly** [joel-costigliola/assertj-core#178]
I like the idea of isEqualToComparingFieldByField, but it is of limited use when some of the fields are objects without Equals being overriden. 

I would like to have an option to use isEqualToComparingFieldByField recursively, instead of falling back to org.assertj.core.util.Objects.areEqual.

**Comment by mefi** [comment]
Hello, I vote for this feature. Thanks!

**Comment by PascalSchumacher** [comment]
I guess it should be possible to adapt a Apache 2 licensed implementation of deepEquals for AssertJ, e.g.: https://github.com/jdereg/java-util/blob/master/src/main/java/com/cedarsoftware/util/DeepEquals.java 

@joel-costigliola I could give it a try, if you are o.k. with this approach?

**Comment by joel-costigliola** [comment]
Agrred, let's not reinvent a recursive comparison.

**Comment by xp-vit** [comment]
I'm also waiting for this feature it will make tests even more neat.

**Comment by jenzz** [comment]
Exactly 2 years since this was requested today.

Any chance of getting it merged to master?

**Comment by joel-costigliola** [comment]
It is planned for 2.4/3.4, I haven't had the time to review the PR yet but it is definitely on my todo list.

**Comment by joel-costigliola** [comment]
Done

**Comment by fd8s0** [comment]
I have a case of a very big object (which I'm testing when serialising and de-serialising). In some attribute there's a collection of an object which overrides equals. The new recursive feature seems to be favoring the usage of that, which seems to be against the concept of isEqualFieldByField assertj is trying to use. I realise this is the behaviour of deepEquals library (which checks if equals method is defined and uses that) after reading that code, but I think this is not what this method is supposed to do. @joel-costigliola what do you think?

**Comment by PascalSchumacher** [comment]
@fd8s0 to quote Joel (see above):

>I agree that if fields override equals then is should be used and otherwise fall back to field by field comparison.

I think this behaviour preferable most of the time. Of course having the option to do a deep comparison which ignores all `equals` overrides would also be helpful.

**Comment by joel-costigliola** [comment]
What we could do is provide a `Comparator` that would perform the recursive field by field comparison without using `equals` method.

**Comment by Fadelis** [comment]
Is this feature not implemented yet? Currently doing recursive FieldByField comparison checks if there are customEquals methods, where you'd think it would also check field by field is the customEquals is true.
