### ISSUE TITLE
usingFieldByFieldValueComparator() fails for Optional

### ISSUE THREAD

**Issue by ASarco** [joel-costigliola/assertj-core#1791]
#### Summary
When I try to use usingFieldByFieldValueComparator() to compare the fields of the value of an Optional with another objects, it fails because is actually using equals on the objects.
Using version 3.15.0 or 3.14.0

#### Example

```java
    @Test
    public void testOptional() {
        Optional<Starship> enterpriseOptional = Optional.of(new Starship("Enterprise", "NCC-1701", new Officer("James T. Kirk", CAPTAIN), 8f));
        Starship enterprise = new Starship("Enterprise", "NCC-1701", new Officer("James T. Kirk", CAPTAIN), 8f);
        assertThat(enterpriseOptional)
                .isPresent()
                .usingFieldByFieldValueComparator()
                .contains(enterprise);
    }
```
fails with:

org.opentest4j.AssertionFailedError: 
Expecting:
  <Optional[uk.co.landbay.assertj_presentation.entities.Starship@64c87930]>
to contain:
  <uk.co.landbay.assertj_presentation.entities.Starship@400cff1a>
but did not.
Expected :uk.co.landbay.assertj_presentation.entities.Starship@400cff1a
Actual   :uk.co.landbay.assertj_presentation.entities.Starship@64c87930

**Comment by joel-costigliola** [comment]
try using the new recursive api, it supports Optional. look for
usingRecursiveComparison in the new website

**Comment by joel-costigliola** [comment]
@ASarco  closing this issue but happy to reopen it if you have want.
