### ISSUE TITLE
convert from Hamcrest to AssertJ assertion

### ISSUE THREAD

**Issue by dstoianov** [joel-costigliola/assertj-core#1792]
#### Summary
Can someone suggest how to write code down below using `AsserJ`

#### Example

```java
assertThat(Arrays.asList("foo", "bar", "baz", "raisin"), 
                 hasItems(endsWith("z"), containsString("isin")));
```

**Comment by joel-costigliola** [comment]
Try [anySatisfy](https://www.javadoc.io/static/org.assertj/assertj-core/3.15.0/org/assertj/core/api/AbstractIterableAssert.html#anySatisfy(java.util.function.Consumer))

```java
assertThat(myIcelanderFriends).anySatisfy(person -> {
                                  assertThat(person.getCountry()).isEqualTo("Iceland");
                                  assertThat(person.getSurname()).endsWith("son");
                                });
```

**Comment by dstoianov** [comment]
thank you for your answer, it is good, i want to use it in a bit another context

this will work only with 100% match, do we have in assertj `containsString` matcher
```java
 assertThat(Arrays.asList("foo", "bar", "baz", "raisin", "162,33 EURO", "assertj"))
                .containsSubsequence(Arrays.asList("baz","raisin", "162,33"));
```

**Comment by joel-costigliola** [comment]
I'm not sure to understand what assertion you want to do, can you clarify?

**Comment by joel-costigliola** [comment]
@dstoianov I'm closing this issue but happy to reopen if you need more help.
