### ISSUE TITLE
Improvement Request: ignoringExpectedNullFields

### ISSUE THREAD

**Issue by aleks-oracle** [joel-costigliola/assertj-core#1793]
#### Summary
Hello! Let me thank the creators of this wonderful framework once again.

At the moment we have the option "ignoringActualNullFields/isEqualToIgnoringNullFields (for null actuals too)".
In addition to this, it would be nice to have the same option for Expected Null fields.

#### Example
It is an often case to fill some fields only during the test.
For example, entity ID - it is created dynamically.
I send an object with null ID and during the test it gets some value. And there could me many such dynamic-filled fields.
So, I would like to compare expected and actual objects and exclude all that fields, which were null before the test, from comparison, so that [expected = null & actual = not null] would be ignored. 

Is it possible? We would be very grateful!

**Comment by joel-costigliola** [comment]
Would the new recursive comparison work for you?
Thanks for the kind words!
In the new recursive comparison api, you can ignore fields by regexes so it should be easy to ignore all the id fields: https://assertj.github.io/doc/#assertj-core-recursive-comparison-ignoring-fields.

let me know if that works for you

**Comment by aleks-oracle** [comment]
Hi, Joel! Thanks for response.
Yes, this will work.
The question was, there could be many such expected null-fields, not only ID.
And the possibility to ignore them all at once would be more convenient.

**Comment by joel-costigliola** [comment]
Alright fair enough!
