### ISSUE TITLE
Problem with AbstractAssert.overridingErrorMessage when no arg is provided

### ISSUE THREAD

**Issue by xgouchet** [joel-costigliola/assertj-core#1795]
#### Summary

This is an old issue (#35) that was fixed in commit [44648c3d](https://github.com/joel-costigliola/assertj-core/commit/44648c3d95ac678dc977ebca3866b96c63a1cb08), but broken again with the commit [932339d2](https://github.com/joel-costigliola/assertj-core/commit/932339d2166ed776d0d7e375a3f8358e88d833f8#diff-b524f46f2b3f708cdd6ef17afbae1916) fixing #312 : 

Even though the overriding message has no arguments, it might contain `%` character that will be interpreted as a specifier marker, and will break the message. 

#### Example

```java
assertThat(true)
    .overridingErrorMessage("This will break 100% of the time")
    .isFalse();
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this! will be fixed in 3.16.0

**Comment by joel-costigliola** [comment]
@xgouchet which version are you using? your example fails as expected in master with:
```
java.lang.AssertionError: This will break 100% of the time
	at org.assertj.core.internal.Failures.failure(Failures.java:164)
	at org.assertj.core.internal.Failures.failureIfErrorMessageIsOverridden(Failures.java:150)
	at org.assertj.core.internal.Failures.failure(Failures.java:102)
```
what is the behaviour you are experiencing?

**Comment by joel-costigliola** [comment]
@xgouchet closing this issue but happy to reopen it if you give us more details.
