### ISSUE TITLE
allow more than three arguments for satisfiesAnyOf()

### ISSUE THREAD

**Issue by Jakzi666** [joel-costigliola/assertj-core#1803]
#### Summary
In my context I would like to use four arguments in a satisfiesAnyOf() statement which is not supported even though there is a private method which seems to be able to handle this scenario.
Is there a reason why this is so, or could you implement this?

#### Example

```java
<add example here>
```

**Comment by joel-costigliola** [comment]
Nope, except that we felt at the time that having more than 3 conditions were an unlikely use case, I guess we were wrong ;-)

Do you want to contribute it?

**Comment by Jakzi666** [comment]
Sure.

**Comment by joel-costigliola** [comment]
Fixed by #1804

**Comment by Jakzi666** [comment]
Thank you! Do you have any estimate on when the new milestone will be released?

**Comment by joel-costigliola** [comment]
no plan yet but something like in a month
