### ISSUE TITLE
Consider adding isEven/isOdd to AbstractByteAssert, AbstractShortAssert, AbstractIntegerAssert and AbstractLongAssert

### ISSUE THREAD

**Issue by fbiville** [joel-costigliola/assertj-core#1807]
#### Summary
It is currently not possible to directly assert whether integers are odd or even.

#### Example

```java
assertThat(someInteger).isEven();
assertThat(someInteger).isOdd();
```

**Comment by scordio** [comment]
Wouldn't the `isEven()`/`isOdd()` pair be enough?

**Comment by joel-costigliola** [comment]
yes, if it's not even then it's odd 😄

**Comment by fbiville** [comment]
> Wouldn't the `isEven()`/`isOdd()` pair be enough?

It could, but I imagine in some contexts, you want to express the negation. Maybe not worth keeping though. No strong opinions :)

**Comment by scordio** [comment]
> It could, but I imagine in some contexts, you want to express the negation.

That would be odd! (sorry, I couldn't resist 😄)

**Comment by joel-costigliola** [comment]
Let's keep it simple, no negative assertion.

**Comment by fbiville** [comment]
I assume we also want this for Byte, Short, Long and maybe even Character?

**Comment by joel-costigliola** [comment]
yes but I'm not sure we need it for character (how likely is somebody going to use that?)

**Comment by scordio** [comment]
> I assume we also want this for Byte, Short, Long and maybe even Character?

I think we should add this to `NumberAssert`, which would trigger some children classes so it's probably not going to be a small change.

I guess these new assertions should appear wherever `isZero` is available:

![Screenshot 2020-03-21 at 16 48 45](https://user-images.githubusercontent.com/26772046/77230383-17644300-6b94-11ea-8aad-a7ca6b8e39ad.png)

**Comment by fbiville** [comment]
The problem is that `FloatingPointNumberAssert` extends `NumberAssert` and you would end up with odd/even assertions for numbers other than integers.

**Comment by scordio** [comment]
Fair point, that would be wrong.

**Comment by joel-costigliola** [comment]
> Probably BigInteger should also be part of the group, what do you think?

yes but if that is too much work, happy to create another issue for that

**Comment by scordio** [comment]
We could go with the four in the title, later with `BigInteger` and then decide if the common interface is needed. For example, `LongAdderAssert` in #1812 could belong to the family being a `java.lang.Number`.

**Comment by piefel** [comment]
> Fair point, that would be wrong. […]

Well, floating point number _can_ be integral (and even exactly so), so they can be odd or even. Only that many number are neither.

**Comment by scordio** [comment]
> Well, floating point number _can_ be integral (and even exactly so), so they can be odd or even. Only that many number are neither.

I'm far from being a mathematician, but the topic seems a bit more complicated when we move to rational numbers (i.e., floating point numbers), e.g. from [Math StackExchange](https://math.stackexchange.com/questions/3013028/generalized-definition-of-parity)

> The notion of parity can be extended to many rings - but certainly not all rings, since if 2 has an inverse 𝑢 then 2𝑢=1 ⇒2∣1∣𝑥 so everything is "even". So we can't extend it to all rationals, but if we restrict to the subring of rationals with odd denominator then integer parity has a unique extension: the parity of 𝑚/(2𝑛+1) is the parity of 𝑚, by mod2: (2𝑛+1)−1≡1−1≡1.

Also, from [Wikipedia](https://en.wikipedia.org/wiki/Talk%3AParity_(mathematics)#Parity_of_any_rational_number_can_be_determined):

> A fraction is even if the numerator is, therefore all rational numbers have parity.

IMHO I would keep floating point types out for now and we can always change it if the community sees the benefit of those assertions also there.
