### ISSUE TITLE
Add functionality similar to isEqualToIgnoringNullFields for Optional.empty() 

### ISSUE THREAD

**Issue by malovitsinm** [joel-costigliola/assertj-core#1809]
#### Summary
I am really digging the ability to ignore null fields in the _actual_ based on null fields of the _expected_ since it provides a very flexible way to build highly reusable tests in our BDD framework. It would be really nice if this functionality was extended to include Optional.empty() as well.
Hope it could land as another part of the #1002.
#### Example

```java
class Animal {
    String nickName;
    Integer tailCount;

    Animal(String nickName, Integer tailCount) {
        this.nickName = nickName;
        this.tailCount = tailCount;
   }

    Optional<Integer> getTailCount() {
        Optional.ofNullable(tailCount);
    }

    Optional<String > getNickname() {
        Optional.ofNullable(tailCount);
    }
}
```
And such assertion would pass:
```java
assertThat(new Animal("Fluffers", 9) 
    .usingRecursiveComparison()
    .ignoringActualNullFields()
    .isEqualTo("Fluffers", null) ;

**Comment by joel-costigliola** [comment]
It would better to add `ignoringEmptyOptional`, WDYT?

**Comment by malovitsinm** [comment]
Yeah, you're right. It makes more sense semantically to add it as a separate option. Shouldn't "Actual" be included in naming thought? I thinks it may sound a bit confusing as it is.

**Comment by joel-costigliola** [comment]
yes it should, good point!

**Comment by joel-costigliola** [comment]
For consistency with other configuration parameter, I'll go with `ignoringAllActualEmptyOptional`

**Comment by joel-costigliola** [comment]
for consistency with the existing api, we will go with `ignoringActualOptionalEmptyFields`

**Comment by joel-costigliola** [comment]
oh and also going to ignore `OptionalInt`, `OptionalLong` and `OptionalDouble`
