### ISSUE TITLE
SoftAssertionExtension to support custom soft assertions

### ISSUE THREAD

**Issue by kriegfrj** [joel-costigliola/assertj-core#1819]
#### Summary

The current implementation of `SoftAssertionExtension` is hardcoded to support `SoftAssertions` and `BDDSoftAssertions`. If you have your own custom soft assertions entry point (with your own custom assertions), then you're out of luck.

#### Example

```java
class MySoftAssertions extends SoftAssertions {
  public CustomAssert assertThat(Custom actual) {
    return proxy(CustomAssert.class, Custom.class, actual);
  }
}
@ExtendWith(SoftAssertionsExtension.class)
public class MyTest {
  @Test 
  void my_test_method(MySoftAssertions softly) {
    // Parameter "softly" will not resolve
  }
}
```

**Comment by homberghp** [comment]
this might help: have an extension that allows wrapping any kind of AssertionException expression. This would allow any asserttion, custom or otherwise, including the mockito verifies etc, which is my current usecase.

**Comment by kriegfrj** [comment]
Thanks for this suggestion @homberghp. However, I don't think it is technically possible with just an extension, in the generic case. Most assertion frameworks throw exceptions when the assertion fails (typically some subclass of `AssertionError`) and this interrupts the normal flow of code. A generic extension can't catch that exception and then tell re-enter the test method from where the exception was thrown.

However, if you're specifically interested in combining Mockito verifications with AssertJ soft assertions, you should look at @fduminy's [AssertJ Mockito](https://github.com/fduminy/assertj-mockito), which allows you to set up both AssertJ and Mockito together with soft assertions. I've not used it myself (yet!) but I've had a good look at the code and it looks like it should do the job.
