### ISSUE TITLE
lazy withFailMessage /  overridingErrorMessage

### ISSUE THREAD

**Issue by noguespi** [joel-costigliola/assertj-core#1837]
#### Summary

junit provide a lazy fail message description by using a supplier. The supplier is called only if an error occurs, otherwise it is not called.

```java
        Assertions.assertTrue(true, () -> "I won't be called");
        Assertions.assertTrue(false, () -> "I will be called");
```
It is useful for at least two reason : 

- performance optimization if computing the custom error message is costly.
- getting error message may not be possible if there is not an error, however assertThat try to get the error message even if there is no error.

Suggestion, add the same capability to withFailMEssage or overridingErrorMessage, example : 

```java
        assertThat(response.isError())
            .withFailMessage(() -> "my error")
            .isFalse();
```

**Comment by Mincol** [comment]
Replacing withFailMessage() with as() cut time in one of mine test from 4 minutes 34 seconds to 46 seconds.

**Comment by joel-costigliola** [comment]
I'm ok adding this because it can be useful in some cases.
@Mincol just pointing out that `as()` and `withFailMessage()` have different purposes.

**Comment by Mincol** [comment]
For others and @joel-costigliola it does. But I wanted to point out how much real world usage of `withFailMessage()` can be costly. `as()` is not using lambdas.

So time gain must be in eager call to `format` within `withFailMessage()`

**Comment by Eveneko** [comment]
Can I work on it？I think it's a good idea to improve the performance in some cases. We can discuss further.

**Comment by joel-costigliola** [comment]
Would be great, thanks @Eveneko.

**Comment by Eveneko** [comment]
@Mincol Can you provide your test cases? Thank you very much!

**Comment by Mincol** [comment]
Unfortunately it is proprietary software, but I will try to provide equivalent test. ETA next week.

**Comment by Eveneko** [comment]
@Mincol Thx

**Comment by Mincol** [comment]
Starting work on this.

**Comment by joel-costigliola** [comment]
@Mincol please sync with @Eveneko who also wanted to work on this. You can do together if you want!
