### ISSUE TITLE
IntelliJ outputs assertion failure info twice

### ISSUE THREAD

**Issue by Skynet0** [joel-costigliola/assertj-core#1848]
#### Summary

I am working on IntelliJ 2019.3, with AssertJ 3.15 and Java 11.0.6, and running tests using Junit 5.6.0. When I run tests, IntelliJ outputs the expected / actual message to the console twice.

#### Example

```java
@Test
@Tag("demo")
public void testDuplicateDemoIntAssertJ() {
    int x = 5;
    org.assertj.core.api.Assertions.assertThat(x).isEqualTo(10);
}
```

Outputs
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <5>
to be equal to:
 <10>
but was not.
Expected :10
Actual   :5
<Click to see difference>
```

This behavior does not appear when using JUnit 4. Truth has similar duplication in JUnit 4 and 5, I've raised it at https://github.com/google/truth/issues/680.

**Comment by joel-costigliola** [comment]
Thanks for letting us know, I think this is an Intellij Idea issue as you suggested in https://github.com/google/truth/issues/680#issuecomment-617415943.

Here's eclipse output when running the test:
```
org.opentest4j.AssertionFailedError: 
Expecting:
 <5>
to be equal to:
 <10>
but was not.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.
...
```
