### ISSUE TITLE
Drop get() inside assertThat

### ISSUE THREAD

**Issue by j-maly** [joel-costigliola/assertj-core#186]
Hi,
this does not work: 
List<String> l = ...;
Condition<String> condition = ...;
assertThat(filter(l).having(condition)).isNotEmpty();

I have to call get first
assertThat(filter(l).having(condition).get()).isNotEmpty();

But that get() call looks a bit like noise to me, how about modifying assertThat to call get first when its parameter is a filter?

**Comment by joel-costigliola** [comment]
I think https://github.com/joel-costigliola/assertj-core/issues/302 is a better alternative.
I'm closing the issue but feel free to disagree and reopen it.
