### ISSUE TITLE
usingRecursiveFieldByFieldElementComparator and usingComparatorForType unexpected behavior

### ISSUE THREAD

**Issue by ofabricio** [joel-costigliola/assertj-core#1876]
#### Summary

I faced an unexpected behavior (for me) with `usingRecursiveFieldByFieldElementComparator` and `usingComparatorForType `.

I'd except them to go recursively through all fields and check each field value. But something seems to be checking for the hash/equals before doing so.

In the example bellow the test that `works()` uses `@lombok.Getter` which does not override hash/equals, the test that `fails()` uses `@lombok.Value` which does override.

If that's not a bug, It would be good to have something to add clarity to this issue.

#### Example

```java
package com.example.hi;

import com.example.hi.ExampleTest.Foo.Bar;
import com.example.hi.ExampleTest.One.Two;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Value;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.Comparator;
import java.util.List;
import java.util.Map;

import static java.util.Collections.singletonList;
import static org.assertj.core.api.Assertions.assertThat;

public class ExampleTest {

    Comparator<LocalDateTime> truncateSeconds = (a, exp) ->
        a.isAfter(exp.truncatedTo(ChronoUnit.SECONDS)) ? 0 : 1;

    @Test
    void works() {

        var a = new Foo(Map.of("one", singletonList(new Bar(LocalDateTime.now()))));
        var b = new Foo(Map.of("one", singletonList(new Bar(LocalDateTime.now()))));

        assertThat(singletonList(a))
            .usingRecursiveFieldByFieldElementComparator()
            .usingComparatorForType(truncateSeconds, LocalDateTime.class)
            .containsExactly(b);
    }

    @Test
    void fails() {

        var a = new One(Map.of("one", singletonList(new Two(LocalDateTime.now()))));
        var b = new One(Map.of("one", singletonList(new Two(LocalDateTime.now()))));

        assertThat(singletonList(a))
            .usingRecursiveFieldByFieldElementComparator()
            .usingComparatorForType(truncateSeconds, LocalDateTime.class)
            .containsExactly(b);
    }

    @Getter
    @AllArgsConstructor
    public static class Foo {

        Map<String, List<Bar>> values;

        @Getter
        @AllArgsConstructor
        public static class Bar {

            LocalDateTime date;
        }
    }

    @Value
    @AllArgsConstructor
    public static class One {

        Map<String, List<Two>> values;

        @Value
        @AllArgsConstructor
        public static class Two {

            LocalDateTime date;
        }
    }
}
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this with details @ofabricio! 
We will analyze this shortly.

**Comment by joel-costigliola** [comment]
@ofabricio the reason is `equals` is used when overridden in fields of the objects to compare recursively, this is stated in the javadoc (but likely not clearly enough):

> The recursive property/field comparison is **not** applied on fields having a custom equals implementation, i.e. the overridden equals method will be used instead of a field/property by field/property comparison.

The [new recursive comparison](https://assertj.github.io/doc/#assertj-core-recursive-comparison) offers much more flexibility, in our case you can [force ignoring overridden `equals`](https://assertj.github.io/doc/#assertj-core-recursive-comparison-ignoring-equals). One limitation thought is that it only exposes the `isEqualTo` assertion (so you can't use `contains` assertion for example).

Does that help?

**Comment by joel-costigliola** [comment]
BTW I have created https://github.com/joel-costigliola/assertj-core/issues/1881 to allow the new recursive comparison to be used like `usingRecursiveFieldByFieldElementComparator`

**Comment by ofabricio** [comment]
> the reason is equals is used when overridden in fields of the objects to compare recursively,

But does that make sense since it is called `FieldByField` and `Recursive` comparator?

If you suppose that the programmer overrides equals in such a way that it deals with comparing each field recursively, then we could just use `isEqualTo()` and there is no point in `usingRecursiveFieldByFieldElementComparator` to exist.

The combo `usingRecursiveFieldByFieldElementComparator` + `usingComparatorForType` is also meaningless.

This was my workflow:

1. I thought, well it should be a good idea to use a custom comparator for LocalDateTime because I don't want to mock `now()`. I'll just truncate seconds and consider acceptable if the time is within a minute. This will make my code simple.

2. I tried this and it failed:

```
assertThat(list)
    .usingComparatorForType(truncateSeconds, LocalDateTime.class)
    .containsExactly(b)
```

3. Then I thought, well, maybe because I need to compare field by field recursively. Then I tried:

```
assertThat(list)
    .usingRecursiveFieldByFieldElementComparator()
    .usingComparatorForType(truncateSeconds, LocalDateTime.class)
    .containsExactly(b)
```

And it failed too. So I got totally confuse. I had no more ideas on what to do, until I spent hours playing with other methods to figure out it is considering the equals.

That method doesn't do what it says it does.

> Does that help?

It doesn't help since I'm dealing with a list and not single objects. It would be cumbersome to deal with each element separately. It should be nice to deal with elements just like it is nice to deal with single objects. An option like #1881 looks promising. I'll try to give a few suggestions there.

**Comment by joel-costigliola** [comment]
> But does that make sense since it is called FieldByField and Recursive comparator?

yes, this goes recursively for each fields and compare them

> If you suppose that the programmer overrides equals in such a way that it deals with comparing each field recursively, then we could just use isEqualTo() and there is no point in usingRecursiveFieldByFieldElementComparator to exist.

Not if you have some types that don't override equals

> The combo usingRecursiveFieldByFieldElementComparator + usingComparatorForType is also meaningless.

Might not be as useful as you think, but this allowed you to compare `LocalDateTime` at the precision you wanted

> And it failed too. So I got totally confuse. I had no more ideas on what to do, until I spent hours playing with other methods to figure out it is considering the equals.

Sorry about that, designing recursive comparison is not straightforward (thus the new one).
Just curious if you have read the javadoc, it was mentioning the use of `equals`.

Finally #1881 should solve your issue provided you configure the [`RecursiveComparisonConfiguration`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/recursive/comparison/RecursiveComparisonConfiguration.html) and ignore all overridden equals

> If you say it could have a configuration to ignoreEquals I'd argue that should be default behavior

I have hesitated making it the default but decided not to as it a type as an overridden equals why not using it? after the authors of the class have decided that this should be the way to compare them.

If most of the users want this behaviour I might change it.

**Comment by joel-costigliola** [comment]
This should work now with:
```java
// static import RecursiveComparisonConfiguration.builder
RecursiveComparisonConfiguration configuration = builder().withIgnoreAllOverriddenEquals(true)
                                                          .withComparatorForType(truncateSeconds, LocalDateTime.class)
                                                          .build();
assertThat(list).usingRecursiveFieldByFieldElementComparator(configuration)
                .containsExactly(b);
```
