### ISSUE TITLE
Consider native consumption support for IteratorAssert

### ISSUE THREAD

**Issue by devinrsmith** [joel-costigliola/assertj-core#1877]
In some cases it is invalid to collect the contents of an iterator - the returned value must be consumed during iteration. This is a common pattern when dealing with ByteBuffer iterators returned from file or database operations (useful for avoiding excessive allocation).

As such, it would be nice if `IteratorAssert` was able to deal with these semantics by consuming and checking the iterator values during iteration: `assertThat(it).containsExactlyElementsOf(iterable)`.

The workaround for now is pretty simple:

```java
private static <T> void containsExactlyElementsOf(Iterator<T> it, Iterable<T> expected) {
    final Iterator<T> eit = expected.iterator();
    while (it.hasNext() && eit.hasNext()) {
        assertThat(it.next()).isEqualTo(eit.next());
    }
    assertThat(it).isExhausted();
    assertThat(eit).isExhausted();
}
```

**Comment by joel-costigliola** [comment]
I'm assuming you are using using a version older than 3.12.0,  as in that version `IteratorAssert` has been changed to only reflect pure `Iterator` assertions (before that it was exposing `Iterable` assertions by converting the iterator under test to a list.
See https://assertj.github.io/doc/#assertj-core-3.12.0-breaking-changes

You can not face this in newer versions as you would have to explicitly convert your iterator to an iterable to call `containsExactlyElementsOf`.

I'm not sure that would solve your underlying problem though.

**Comment by devinrsmith** [comment]
I'm on the latest  - I'm hoping that new methods can be added to `IteratorAssert` so that my workaround becomes unnecessary. (I agree that `IteratorAssert` should *not* extend `IterableAssert` 👍.)

**Comment by joel-costigliola** [comment]
We have moved away from iterable style assertions for iterators because some users were confused about the iterator being consumed, at the moment I'm not convinced to get back to that road again.

> In some cases it is invalid to collect the contents of an iterator 

Your workaround is consuming the iterator (partially but still), I'm not sure to understand your point.

**Comment by joel-costigliola** [comment]
Closing this issue but happy to reopen if convinced by further discussions.
