### ISSUE TITLE
There appears no way to add failures to SoftAssertions from multiple threads

### ISSUE THREAD

**Issue by unix-junkie** [joel-costigliola/assertj-core#1879]
#### Summary

Consider I need to collect multiple failures produced in multiple threads. Currently, `SoftAssertions` doesn't allow me to do so w/o extra synchronizers.

#### Example

For example, this code is broken because changes made to the `SoftAssertions` instance from other threads might not be visible from the main thread:

```java
        final SoftAssertions softly = new SoftAssertions();

        final ForkJoinPool forkJoinPool = ForkJoinPool.commonPool();
        forkJoinPool.execute(() -> {
            softly.assertThat("foo").hasToString("foo");
        });
        forkJoinPool.execute(() -> {
            softly.assertThat("bar").hasToString("bar");
        });

        softly.assertAll();
```

What is the best approach to solve the above problem?

Guarding `SoftAssertions` with a synchronized block wherever I'm accessing the instance doesn't seem like a good solution (especially from test readability standpoint).

Probably you could introduce something like `SynchronizedSoftAssertions` or least make the list of failures a _synchronized list_. At the same time, it's not clear how to guard the whole call chain like

```java
softly.assertThat("foo").hasToString("foo");
```

with a single lock.

**Comment by joel-costigliola** [comment]
A synchronized or concurrent list should be enough, do you want to contribute it @unix-junkie?

**Comment by unix-junkie** [comment]
@joel-costigliola: Pushed the simplest fix.

Please review. 

I can provide the complete thread-safe solution if necessary (will be slightly heavier).
