### ISSUE TITLE
Some APIs have no test

### ISSUE THREAD

**Issue by Sunt-ing** [joel-costigliola/assertj-core#1887]
#### Summary
When I run the coverage test, I find:
- in `AbstractUrlAssert`: `hasNoPath()` and `hasNoParameters()` have no test.
- in `AbstractUriAssert`:`hasNoPath()` has no test.

Actually, Intellij IDEA tells me that they are never used.

I am happy to raise this as a PR if this issue is considered valid.

**Comment by scordio** [comment]
Yes please, improving test coverage is always good!

This gap is also mentioned in the Sonar report: https://sonarcloud.io/component_measures?id=joel-costigliola_assertj-core&metric=new_lines_to_cover&view=list

**Comment by Sunt-ing** [comment]
OK, thanks! I think I may have to wait for my last PR being merged.

**Comment by Sunt-ing** [comment]
When I write tests for `haveNoPath()`, I am very confused. 

According to javadoc, these assertions succeed:

```java
assertThat(new URL("http://www.helloworld.org")).hasPath("");
assertThat(new URL("http://www.helloworld.org")).hasNoPath();

assertThat(new URI("http://www.helloworld.org")).hasPath("");
assertThat(new URI("mailto:java-net@java.sun.com")).hasNoPath();
```

But these assertions fail:

```java
assertThat(new URI("http://helloworld.org")).hasNoPath();  // empty path
```

This assertion throws an `IllegalArgumentException`:

```java
assertThat(new URL("http://helloworld.org/pages")).hasPath(null);
```



Well, I think this is a little confusing. I prefer to have `hasPath(null)`=`hasNoPath()`=`hasPath("")` both in `urls` and `uris`.
