### ISSUE TITLE
Performance regression in 3.16.0: assertThat(byte[]).containsExactly(byte[])

### ISSUE THREAD

**Issue by AlexLandau** [joel-costigliola/assertj-core#1898]
#### Summary

While upgrading our codebase from AssertJ 3.15.0 to 3.16.1, one of our tests hung until a 40 minute timeout expired. It turned out that this test was calling assertThat(byte[]).containsExactly(byte[]) on some byte arrays with 20 million elements.

It appears that this assertion had linear performance characteristics in 3.15.0, but quadratic performance in 3.16.0, specifically changing at commit 3dc400426359866bfef0c65c5e4cbd6d4eeaf9fb. For example, it now takes about two minutes to run this assertion on an array of size one million, vs. less than a second previously.

My current workaround is to just assert the truth of Arrays.equals().

#### Example

```java
  @Test
  public void testScaleRegression() {
    // Times taken at assertj-core-3.16.1:
    // 8k: 15 ms
    // 16k: 39 ms
    // 32k: 101 ms
    // 64k: 371 ms
    // 128k: 1616 ms
    // 256k: 7398 ms
    // 512k: 31654 ms
    // 1024k: 118472 ms

    // Times taken at assertj-core-3.15.0:
    // 8k: 4 ms
    // 16k: 8 ms
    // 32k: 14 ms
    // 64k: 25 ms
    // 128k: 44 ms
    // 256k: 92 ms
    // 512k: 166 ms
    // 1024k: 339 ms
    for (int length : Arrays.asList(8_000, 8_000, 8_000, 16_000, 32_000, 64_000, 128_000, 256_000, 512_000, 1_024_000)) {
      byte[] data = new byte[length];
      Arrays.fill(data, (byte) 0x42);
      byte[] data2 = new byte[length];
      Arrays.fill(data2, (byte) 0x42);
      System.out.println("Testing for length " + length + "...");
      long startTime2 = System.currentTimeMillis();
      assertThat(data).containsExactly(data2);
      System.out.println("Done testing " + length + ", took " + (System.currentTimeMillis() - startTime2) + " ms");
    }
  }
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this with details!
Will fix this for the next release 3.17.0 (not yet sure if we want to revert that commit yet)
