### ISSUE TITLE
Add hasElementSatisfying

### ISSUE THREAD

**Issue by trajano** [joel-costigliola/assertj-core#1899]
#### Summary

There's a hasOnlyOneElementSatisfying method already, I was wondering if there's an alternative that can be added where a collection `hasElementSatisfying`

#### Example

```java
                o -> assertThat(o.getBillingContracts())
                    .hasOnlyOneElementSatisfying(
                        c -> assertThat(c)
                            .hasFieldOrPropertyWithValue("name", "No Contract")
                    )

```

My workaround so far
```java
o -> assertThat(o.getBillingContracts())
                    .satisfies(
                        contracts -> 
                            assertThat(
                                contracts.stream().filter(
                                    contract -> contract.getName().equals("No Contract")
                                ).findAny()
                            ).isPresent());

 ```

**Comment by joel-costigliola** [comment]
If I understand correctly I believe you could use [anySatisfy](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractIterableAssert.html#anySatisfy(java.util.function.Consumer)), right?

**Comment by trajano** [comment]
Almost, I just want *one* instance of it though.  (which I know my workaround doesn't satisfy)

**Comment by joel-costigliola** [comment]
Not sure I fully understand, you want to check there is one and only one element satisfying the predicate?

**Comment by trajano** [comment]
I want to check there is one and only one element satisfying the predicate, BUT does not have to be the only element in the collection.

hasOnlyOneElementSatisfying checks that the element is the only one in the list (which seems off when I read it because the method does not convey that it should be the only element in the list)

**Comment by joel-costigliola** [comment]
I agree the `hasOnlyOneElementSatisfying` is confusing.

for your case simply filter + count:
```
assertThat(o.getBillingContracts())
    .filteredOn(contract -> contract.getName().equals("No Contract"))
    .hasSize(1); 
```

**Comment by trajano** [comment]
Thanks for the tip.  It would be good for single ones but I actually have more criteria so your original anySatisfy helps

```java
           .satisfies(
                o -> assertThat(o.getBillingContracts())
                    .anySatisfy(
                        contract -> assertThat(contract)
                            .hasFieldOrPropertyWithValue("name", "No Contract")
                            .hasFieldOrPropertyWithValue("organization", expectedOrg)
                            .satisfies(c -> assertThat(c.hasSchedules()).isFalse())
                    )
                    .anySatisfy(
                        contract -> assertThat(contract)
                            .hasFieldOrPropertyWithValue("name", "Monthly Payment Plan")
                            .hasFieldOrPropertyWithValue("organization", expectedOrg)
                            .satisfies(c -> assertThat(c.hasSchedules()).isTrue())
                    )
                    .isNotEmpty()
                    .hasSize(2)
            );
```

**Comment by joel-costigliola** [comment]
@trajano can I close this issue? do you need more help?
