### ISSUE TITLE
Allow to specify equals BiPredicate instead of Comparator in RecursiveComparisonConfiguration 

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1904]
#### Summary

RecursiveComparisonConfiguration allows to register comparators by type or fields but what is only needed is a simple true/false comparison  

#### Example

Instead of:
```java
registerComparatorForType((d1, d2) -> Math.abs(d1 - d2) <= 0.01 ? 0 : 1, Double.class)
```
we would simply specify:
```java
registerComparatorForType((d1, d2) -> Math.abs(d1 - d2) <= 0.01, Double.class)
```

**Comment by scordio** [comment]
I guess you are expecting a signature like:

```java
public <T> SELF registerComparatorForType(BiFunction<? super T, ? super T, Boolean> comparator, Class<T> type) {
  ...
}
```

What about having a different method name? The comparator term without a `java.util.Comparator` parameter could be confusing.

Is `registerEqualsForType` too aggressive?

**Comment by joel-costigliola** [comment]
Yes we would need another name `registerEqualsForType` looks fine to me.

 @scordio  should we deprecate `registerComparatorForType` to avoid too many options?
It want to keep accepting comparators we could simply have `registerEqualsForType` taking a `Comparator`

**Comment by scordio** [comment]
I would still keep the option to register comparators and I actually prefer `registerComparatorForType` instead of `registerEqualsForType` with a `Comparator` parameter.

My motivation to keep it is the user might want to reuse existing comparators (e.g., `String.CASE_INSENSITIVE_ORDER`).

I'm not sure if having both `registerEqualsForType` and `registerComparatorForType` would cause trouble internally, like which one would win if both are called?

Considering the following as possible implementation for `registerEqualsForType`:

```java
public <T> void registerEqualsForType(BiFunction<? super T, ? super T, Boolean> equals, Class<T> type) {
  Comparator<T> comparator = (o1, o2) -> equals.apply(o1, o2) ? 0 : 1;
  typeComparators.put(type, comparator);
}
```

the most recent call between `registerEqualsForType` and `registerComparatorForType` would win.

Or do you have something else in mind?

**Comment by joel-costigliola** [comment]
> I would still keep the option to register comparators and I actually prefer registerComparatorForType instead of registerEqualsForType with a Comparator parameter.

I want to keep that option too.

> I'm not sure if having both registerEqualsForType and registerComparatorForType would cause trouble internally, like which one would win if both are called?

I don't see it as a big issue, I believe users will unlikely register both a comparator and an equals bifunction for the same type and if they do it seems pretty clear to me that the latest call would win.

I guess the only point would be to keep both `registerComparatorForType` and `registerEqualsForType` in the API, if I had thought to this issue when redesigning the recursive API  I would had two overloaded `registerEqualsForType` method, one with a Comparator and another with a `BiFunction`.

Anyway, we should start by adding `registerEqualsForType`, your suggested implementation looks fine to me, I don't want to have a map of comparators and a map of BiFunction in the config but that's an implementation detail.

We can always decide later to introduce `registerEqualsForType(Comparator)` and deprecate `registerComparatorForType`.
