### ISSUE TITLE
ignoringFields() not working when nested object has lombok @Data annotation

### ISSUE THREAD

**Issue by BertLeonaers** [joel-costigliola/assertj-core#1912]
#### Summary
When comparing 2 object that use lombok @Data annotation to generate getters and setters, ignoringFields() does not work on a field inside a nested element

It works fine when I use @Getter and @Setter instead of @Data

#### Dog class

```java
import lombok.Data;

@Data
public class Dog {

    String name;
    Breed breed;
}
```
```java
import lombok.Data;

@Data
public class Breed {
    String name;
    boolean have;
}
```
```java
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class TestAssertj {

    @Test
    public void testLombok() {
        Dog dog1 = new Dog();
        Breed breed1 = new Breed();
        breed1.setName("Retriever");
        breed1.setHave(true);
        dog1.setBreed(breed1);

        Dog dog2 = new Dog();
        Breed breed2 = new Breed();
        breed2.setName("Retrievers");
        breed2.setHave(true);
        dog2.setBreed(breed2);

        assertThat(dog1).usingRecursiveComparison()
                .ignoringFields("breed.name")
                .isEqualTo(dog2);
    }

}
```
java.lang.AssertionError: 
Expecting:
  <Dog(name=null, breed=Breed(name=Retriever, have=true))>
to be equal to:
  <Dog(name=null, breed=Breed(name=Retrievers, have=true))>
when recursively comparing field by field, but found the following difference:

field/property 'breed' differ:
- actual value   : Breed(name=Retriever, have=true)
- expected value : Breed(name=Retrievers, have=true)

The recursive comparison was performed with this configuration:
- the following fields were ignored in the comparison: breed.name
- overridden equals methods were used in the comparison
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).

**Comment by joel-costigliola** [comment]
By default overridden equals method are used, if you force using equals with `ignoringAllOverriddenEquals` (see https://assertj.github.io/doc/#assertj-core-recursive-comparison-ignoring-equals) I think both cases will work, let me know the result.

Note that I'm going to change the default and not use overridden equals unless specified (https://github.com/joel-costigliola/assertj-core/issues/1906).

**Comment by BertLeonaers** [comment]
Thanks for the fast reply.
using ignoringAllOverriddenEquals did solve my problem.

```java
assertThat(dog1).usingRecursiveComparison()
                .ignoringFields("breed.name")
                .ignoringAllOverriddenEquals()
                .isEqualTo(dog2);
```

**Comment by joel-costigliola** [comment]
closing this issue then ;-)
