### ISSUE TITLE
singleElement for iterables

### ISSUE THREAD

**Issue by mgrafl** [joel-costigliola/assertj-core#1927]
#### Summary
Add a method ```hasSingleElementThat``` to the assertions API for iterables that checks whether the iterable ```hasSize(1)``` and then returns ```element(0)``` for further assertions on that element.

I have stumbled across this pattern several times, so I wonder whether such a convenience method would make sense in the API. 

#### Example

```java
assertThat(newArrayList("Yoda")).hasSingleElementThat().startsWith("Yo");
```

**Comment by joel-costigliola** [comment]
we have [hasOnlyOneElementSatisfying](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractIterableAssert.html#hasOnlyOneElementSatisfying(java.util.function.Consumer)) but this name was a mistake as it is highly confusing. Your suggestion works better, it would be an opportunity to deprecate `hasOnlyOneElementSatisfying`.

The thing that does not work in your example is the strongly typed assertion, although we know it is a `String` java generics don't allow to return `String` assertion after `hasSingleElementThat`,  you are limited to object assertions, fortunately they provide [`satisfies`](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractAssert.html#satisfies(java.util.function.Consumer)) so you can write:

```java
assertThat(list("Yoda")).hasSingleElementThat().satisfies(e -> e.startsWith( "Yo"));
```
Not too bad but I think the following approach would be even better, it is similar to [`first(InstanceOfAssertFactory)`](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractIterableAssert.html#first(org.assertj.core.api.InstanceOfAssertFactory)), we would introduce `singleElement`:
```java
assertThat(list("Yoda")).singleElement(as(InstanceOfAssertFactories.STRING)).startsWith( "Yo");

// better with InstanceOfAssertFactories static import 
assertThat(list("Yoda")).singleElement(as(STRING)).startsWith( "Yo");

// even without InstanceOfAssertFactory, it reads nicely
assertThat(list("Yoda")).singleElement().satisfies(e -> e.startsWith( "Yo"));
```

@mgrafl thoughts?

**Comment by mgrafl** [comment]
I didn't know about ```hasOnlyOneElementSatisfying```. (If I had, I probably wouldn't have raised the issue.) I agree that its name is not intuitive. 

I also prefer the name ```singleElement```. 
And since ```assertThat``` also accepts the ```assertClass``` as second argument, the following example would also work: 
```java
assertThat(list("Yoda"), StringAssert.class).singleElement().startsWith("Yo");
```

**Comment by joel-costigliola** [comment]
Sweet, I have renamed the issue
