### ISSUE TITLE
AbstractByteArrayAssert asString should construct a new String

### ISSUE THREAD

**Issue by pradeepsixer** [joel-costigliola/assertj-core#1940]
#### Summary
Currently, `AbstractByteArrayAssert#asString()` does not override `AbstractAssert#asString()`, so it defaults to `byte[].toString()` internally, and the value returned is the generic Object representation.

#### Example

```java
assertThat(base64Encode("something"))
        .decodedAsBase64()
        .asString()  // expecting "something", instead we get "[B@459b187a"
```

**Comment by joel-costigliola** [comment]
Good catch @pradeepsixer!
