### ISSUE TITLE
Consider adding an assertThatNoException method

### ISSUE THREAD

**Issue by philwebb** [joel-costigliola/assertj-core#1962]
#### Summary
The `assertThatExceptionOfType` method and related helpers (`assertThatNullPointerException`, `assertThatIllegalArgumentException`, `assertThatIOException` & `assertThatIllegalStateException`) provide a nice way to check that a specific exception has been thrown.

If, however, you want to check that an exception was not thrown you need to use `assertThatCode` and follow it with `doesNotThrowAnyException`. It would be really nice to have an `assertThatNoException` method, so that exception tests can consistently lead with the assertion.

#### Example

Current:
```java
assertThatIllegalArgumentException().isThrownBy(() -> new Foo(null, "bar"));
assertCode(() -> new Foo("foo", null)).doesNotThrowAnyException();
```

Wanted:
```java
assertThatIllegalArgumentException().isThrownBy(() -> new Foo(null, "bar"));
assertThatNoException().isThrownBy(() -> new Foo("foo", null));
```

**Comment by philwebb** [comment]
I'm happy to work on a PR if wanted.

**Comment by joel-costigliola** [comment]
Good idea! go for the PR @philwebb :)
