### ISSUE TITLE
Why are some methods like contain final?

### ISSUE THREAD

**Issue by rdehuyss** [joel-costigliola/assertj-core#1967]
#### Summary
I want to extend ListAssert and override the methods `contains`, `containsOnly`, `containsExactly`, ... However, I just found out that these methods are final :-(

Why is that? https://github.com/joel-costigliola/assertj-core/blob/main/src/main/java/org/assertj/core/api/ListAssert.java#L268

Reason to override and extend the ListAssert is related to #1966. Before comparing my objects, I was hoping to remove the Semaphore (as not important when being compared).

**Comment by filiphr** [comment]
The methods are final in order to avoid a warning for users using the API. If they aren't then `@SafeVarargs` does not work and users will get a warning saying:

>Possible heap pollution from parameterized vararg type T

You can extend from `FactoryBasedNavigableListAssert` instead

**Comment by joel-costigliola** [comment]
@filiphr is right, I just wished there was a way to get rid of this warning without making these methods final!
although I understand the rationale of having to make the methods `final`, I really think it was too much and  `@SafeVarargs` should have been sufficient.
