### ISSUE TITLE
Breaking change for 2D arrays in v3.17.0

### ISSUE THREAD

**Issue by Fryie** [joel-costigliola/assertj-core#1975]
#### Summary

After upgrading to 3.17.0 some assertions such as `hasSize` and `allMatch` are not available anymore for 2D arrays, although they were before.

This is not a huge issue, as `hasDimensions` etc. seem to be better matchers anyway, but this isn't indicated in the release notes as a breaking change, so in case anybody else is running into this problem, at least now they can maybe find this issue.

#### Example

(with Kotlin, since I don't remember Java lambda syntax right now)

```kotlin
assertThat(my2DArray).hasSize(2)
assertThat(my2DArray).allMatch { it.size == 3 }
```

does not work anymore,
```kotlin
assertThat(my2DArray).hasDimensions(2, 3)
```

does.

**Comment by scordio** [comment]
Thank you @Fryie, added as breaking change in [e22e4b2](https://github.com/assertj/doc/commit/e22e4b247454caaab7b5551492db504517222e20).
