### ISSUE TITLE
Object2DArrayAssert#isDeepEqualTo(...) uses reference comparison instead of content comparison

### ISSUE THREAD

**Issue by charphi** [joel-costigliola/assertj-core#1976]
In v3.17.0, Object2DArrayAssert#isDeepEqualTo(...) uses reference comparison instead of content comparison.
So, two arrays with same content may be seen as different by assertj.

At line 89, the comparison is done by ` if (actualSubArray[j] != expectedSubArray[j]) {`
but should be `if (!Objects.equals(actualSubArray[j], expectedSubArray[j]) {`

**Comment by scordio** [comment]
Good catch, thank you @charphi!
