### ISSUE TITLE
OSGi: Soft proxies not working on Java 9+

### ISSUE THREAD

**Issue by bjhargrave** [joel-costigliola/assertj-core#1979]
In https://github.com/joel-costigliola/assertj-core/pull/1968, I made a fix to better support custom assertions in OSGi bundles being used as soft assertions. This works fine on Java 8 but does nothing for Java 9+ due to the way AssertJ selects the ClassLoadingStrategy.

https://github.com/joel-costigliola/assertj-core/blob/d80cb5c8fc9d76ed6ca4361cc40e0e42d22b1cbc/src/main/java/org/assertj/core/api/ClassLoadingStrategyFactory.java#L36-L41

In Java 8, `ClassLoadingStrategy.Default.INJECTION` is used. The strategy respects the class loader specified in 

https://github.com/joel-costigliola/assertj-core/blob/d80cb5c8fc9d76ed6ca4361cc40e0e42d22b1cbc/src/main/java/org/assertj/core/api/SoftProxies.java#L204

But in Java 9+, `ClassLoadingStrategy.UsingLookup.of(PRIVATE_LOOKUP_IN.invoke(null, assertClass, LOOKUP))` is used. This strategy uses the `MethodHandles.Lookup.defineClass` method which only uses the class loader defining the assertClass. That is, this strategy _ignores_ the class loader passed to the `load` method above :-( So this means in Java 9+, the CompositeClassLoader is not used to define the proxy classes and they can then fail to define since certain types in AssertJ are not visible.

**Comment by bjhargrave** [comment]
I have a fix for this and will soon submit a PR.

**Comment by joel-costigliola** [comment]
@bjhargrave thanks, is it possible to craft a test for this? we are building AssertJ for different java versions in a our CI, that would have picked up the issue.

**Comment by bjhargrave** [comment]
> is it possible to craft a test for this?

Yes, I have the test in my PR to add OSGi integration tests:

https://github.com/joel-costigliola/assertj-core/pull/1982/files#diff-48b3faed78fbacd185940ede4736cb75

I am working on the fix for that PR build break. 

Would you prefer one PR with both commits vs 2 PRs? I am now leaning towards the one PR.

**Comment by bjhargrave** [comment]
> I am now leaning towards the one PR

I did this. #1980 now includes the commit to add OSGi integration testing as well as a test class for the soft proxy support for OSGi.

**Comment by joel-costigliola** [comment]
One PR is better as the changes are closely related.

**Comment by kriegfrj** [comment]
Hi @joel-costigliola , I can confirm that #1980 now contains all changes (the fix and the OSGi-aware integration test).
