### ISSUE TITLE
Possibility to use a usingComparator with isEqualToComparingFieldByField

### ISSUE THREAD

**Issue by kmoens** [joel-costigliola/assertj-core#198]
Currently when we use
```java
assertThat(x).usingComparator(comparator).isEqualToComparingFieldByField(y)
```

This does not use the comparator which we specified. We have a number of cases where we would prefer that we could use a comparator here. 

Especially in our database-related unit tests, we retrieve a java.sql.Date object from the database, while our comparison objects have a java.util.Date. For our asserts, it is sufficient that they point to the same point in time (i.e. getTime()) is equal, but the equals() contract does not allow this. Therefore a dedicated comparator is capable of resolving this, but does not work with the isEqualToComparingFieldByField() method.

**Comment by joel-costigliola** [comment]
fixed with #585.
