### ISSUE TITLE
Alternative method to .overridingErrorMessage()?

### ISSUE THREAD

**Issue by fge** [joel-costigliola/assertj-core#199]
Quite simple really; this method name is quite a mouthful.

Could we have .failingWith()?

**Comment by AlexBischof** [comment]
+1 for *withFailMessage* . At first i would have preferred *failingWithMessage* but that is inconsistent to the naming convention here.

Can i do the change?

**Comment by joel-costigliola** [comment]
you can !

**Comment by AlexBischof** [comment]
I have created a PR but we have to be very careful on this in the future because now it is not as clear as it should be. We now have the following methods:
 * as
 * withFailMessage
 * overridingErrorMessage
 * failWithMessage

In custom asserts now the following is possible ;)
```java
assertion.as("test context").overridingErrorMessage("my %d errors %s", 5, "!").withFailMessage("say what??").failWithMessage("%d %s", 5, "time");
```

**Comment by joel-costigliola** [comment]
`failWithMessage` is not a problem as it is not available for end users.
the remaining methods are ok, the only duplication will be `withFailMessage` and `overridingErrorMessage` ... we might deprecate the latter if users are with `withFailMessage`.

Anyway, I know API bloating is a problem with AssertJ but I have taken the option to enrich the API when users ask for it (most of the time)
