### ISSUE TITLE
StandardRepresentation is broken for Jackson object models

### ISSUE THREAD

**Issue by stevegutz** [joel-costigliola/assertj-core#1990]
#### Summary

I'm not sure if this is something the maintainers are concerned with, but upgrading from assertj `3.16.1` to `3.17.1` seems to have broken how `StandardRepresentation` represents [the `JsonNode` type](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/JsonNode.html). I think that this broke in https://github.com/joel-costigliola/assertj-core/commit/1fe35a246c917373dca4345137ca5d7044e14276 because `JsonNode` implements `Iterable<JsonNode>`.

The effect of these changes is that all object nodes are rendered as `[]` in the output.

#### Example

```java
@Test
public void simpleTest() {
  JsonNode a = JsonNodeFactory.instance.objectNode().put("a", 1);
  JsonNode b = JsonNodeFactory.instance.objectNode().put("b", 2);
  assertThat(a).isEqualTo(b);
}
```

##### 3.17.1 output
```
java.lang.AssertionError: 
Expecting:
 <"[[]] (ObjectNode@1dd02175)">
to be equal to:
 <"[[]] (ObjectNode@31206beb)">
but was not.
```

##### 3.16.1 output
```
org.junit.ComparisonFailure: 
Expected :{"b":2}
Actual   :{"a":1}
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this, we'll try to fix that.

**Comment by stevegutz** [comment]
Thanks for the quick fix! I'll definitely start advocating for JsonUnit, but we have a large code base and it's not feasible to move existing tests over unless they break. Thanks again!
