### ISSUE TITLE
Using Conditions to assert collections values

### ISSUE THREAD

**Issue by dmitry-treskunov** [joel-costigliola/assertj-core#205]
In hamcrest it is possible to use matcher inside of another matcher, e.g.

 ```java
assertThat(list, hasItem(lessThan(4)));
```

So it will be good to have analogue in AssertJ:

```
Map<String, Dog> dogByName;
assertThat(dogByName).contains(entry("mike", aWhiteDog())

public static Condition<Dog > aWhiteDog() {
    return new Condition<Dog>("white dog") {
      @Override
      public boolean matches(final Dog dog) {
        return dog.getColor().equals("white");
      }
    };
  }
```

The same for lists, sets and so on.. What do you think?

Probably, the same result can be achieved by using ```extracting()``` methods, but they are not type-safe.

**Comment by joel-costigliola** [comment]
This is addressed by #690.
