### ISSUE TITLE
Diff.diff to produce a more concise diff output

### ISSUE THREAD

**Issue by kriegfrj** [joel-costigliola/assertj-core#210]
The built-in text-based diff in internal.Diff can produce very verbose output for very simple changes. For example, consider comparing two Strings/text files:

String A: 1000 lines of text.
String B: An newline character followed by String A.

Diff.diff will output 1000 lines of error message to describe a single character difference. If the strings additionally differed on line 500 then it is likely that this difference would get lost in the message.

I stumbled into this issue when working on the [assertions generator](/joel-costigliola/assertj-assertions-generator). Though not essential, it would be nice if Diff.diff tried harder to produce a more concise representation of the actual differences (akin to Unix diff and other similar utilities).

**Comment by joel-costigliola** [comment]
Done !
