### ISSUE TITLE
Allow thread dump printing on assertion failure

### ISSUE THREAD

**Issue by Dexterity** [joel-costigliola/assertj-core#212]
Sometimes an assertion in test could fail in rare cases for example because of some multithreading issues in tested code. It would be much easier to debug such tests if they could provide a thread dump on assertion failure.

Example code that collects & prints thread dump can be found here:
http://crunchify.com/how-to-generate-java-thread-dump-programmatically/

For example assertion providing thread dump could be like:

```java
assertThat(...).withThreadDump().isTrue();
```

**Comment by joel-costigliola** [comment]
@Dexterity where do you want the thread dump to be printed syserr ? sysout ?

**Comment by Dexterity** [comment]
Usually we are printing exception stacktraces in syserr because they are describing the reason of error. Full thread dump also intended to describe the reason, so I think it would be better to print it in syserr too.
