### ISSUE TITLE
HasPropertyWithValue

### ISSUE THREAD

**Issue by EarthCitizen** [joel-costigliola/assertj-core#242]
I have looked and not found it in the API. I could be overlooking it, but it would be great to be able to do the following:

```Java
public class Foo {
	int amount;
	String name;
	List<String> items;
	
	public int getAmount() {...}
	
	public String getName() {...}
	
	public List<String> getItems() {...}
}
```

```Java
Foo foo = new Foo();
assertThat(foo).hasPropertyWithValue("amount", 5).hasPropertyWithValue("name", "Someone");
```

**Comment by PascalSchumacher** [comment]
I guess this can be closed, as https://github.com/joel-costigliola/assertj-core/commit/77ab46110a5a9d579cc428d7977d49ce1e40bc82 added #hasFieldOrPropertyWithValue

**Comment by joel-costigliola** [comment]
Indeed !
