### ISSUE TITLE
Use openbeans to support assertions that use properties reflection

### ISSUE THREAD

**Issue by lujop** [joel-costigliola/assertj-core#247]
If you use assertions like isEqualToComparingFieldByField in Android they always return true and fail silently because the ClassNotFound errors are silently catched.

This behaivour is very error prone and I lost some time looking on what was really happening. I think that best solution will be to change the usage on java.beans with openbeans or at least don't catch silently the exceptions or do an explicit check for java.beans availability

**Comment by joel-costigliola** [comment]
No feedback.

**Comment by nghamilton** [comment]
I believe it is due to use of java.beans.Introspector and other classes not included with Android - assertThat(x).isEqualToComparingFieldByField(Y) fails with class not found errors.

**Comment by joel-costigliola** [comment]
@nghamilton thanks for the feedback.

For everybody, AssertJ does not officially support Android but tries to do so, if a quick fix can solve some incompatibilities, fine, but if it needs some major piece of work, no.

**Comment by lujop** [comment]
And what about simply not silently catching ClassNotFound. It won't work but at least it will fail fast.
