### ISSUE TITLE
Primitive Value Approximation Assertion

### ISSUE THREAD

**Issue by JakeWharton** [joel-costigliola/assertj-core#248]
I have a bunch of code where I test timings and averages which can vary. Our tests allow variance since the underlying behavior is non-deterministic to exact values. Instead we apply a range of valid values, but this range loses the semantics of the value we are actually trying to assert. I'd like to propose an value approximation assertion which carries the correct readability semantics for what we are actually trying to test.

More concretely, we currently have code like this:
```java
foo.withWindow(1000/*ms*/).doSomething(10/*times*/);
assertThat(foo.getAverageWindow()).isBetween(990, 1010);
```
What I want it something like this:
```java
foo.withWindow(1000/*ms*/).doSomething(10/*times*/);
assertThat(foo.getAverageWindow()).isApproximately(1000, /*±*/10);
```
Thoughts?

The implementation would just delegate to `isBetween` with `value+variance` and `value-variance` but the semantics of the API are much nicer.

**Comment by SuperJugy** [comment]
Is there a way to add this to version 1.7?

**Comment by joel-costigliola** [comment]
create a PR as stated in https://github.com/joel-costigliola/assertj-core/issues/299#issuecomment-143882417

**Comment by joel-costigliola** [comment]
reopened waiting for a PR to get it merged in 1.x branch

**Comment by joel-costigliola** [comment]
closing it as we added Android compatibility in 2.x
