### ISSUE TITLE
Collection assertion improvement : formatting

### ISSUE THREAD

**Issue by grzesuav** [joel-costigliola/assertj-core#263]
Issue based on : https://groups.google.com/forum/?hl=pl#!topic/assertj/eoVf40zBYsU

I am using collections assertions (f.e. assertThat(someList).toContainsOnly(otherList)) but when assertion fails, it has non formatted message.

By non formatted message I mean that it looks like:
to contain only:
<[SomeObject[key='someValue', value='false'], SomeObject[key=othervalue', value='false'], SomeObject[key='yeAnotherValue', value='false'], SomeObject[key='superValue', value='true']]>

is would be helpful (improve readability )if following format could be possible:
to contain only :
<[SomeObject[key='someValue', value='false'], 
SomeObject[key=othervalue', value='false'], 
SomeObject[key='yeAnotherValue', value='false'], 
SomeObject[key='superValue', value='true']]>

**Comment by joel-costigliola** [comment]
I would also align the elements, ex: 
```
<[SomeObject[key='someValue', value='false'],
  SomeObject[key=othervalue', value='false'],
  SomeObject[key='yeAnotherValue', value='false'],
  SomeObject[key='superValue', value='true']]>
```

**Comment by joel-costigliola** [comment]
I think that printing elements on new lines should be the default

**Comment by AlexBischof** [comment]
I think that is a good idea but do we really need a non-default?

**Comment by joel-costigliola** [comment]
ok, let's just change the way we print collections/arrays.
