### ISSUE TITLE
Make an alternative to failBecauseExceptionWasNotThrown() which is not that much of a mouthful, please...

### ISSUE THREAD

**Issue by fge** [joel-costigliola/assertj-core#299]
This method name is overly long.

What about, in no particular order of preference:

* `shouldHaveThrown()`,
* `failIfNotThrown()`,
* or something along those lines?

Sure, one can extend Assertions, but it'd be nice if assertj provided a shorter name for that. The current method is **really** a mouthful.

**Comment by SuperJugy** [comment]
Hi, is version 1.7 no longer maintained? I like this nicer method but it is only now available for version 2 and 3. I work with Android libraries so I can't use the newer versions.

Thanks!

**Comment by joel-costigliola** [comment]
It's not maintained actively but I accept any PR and will release new 1.x versions when needed, so to be clear if you want something to included in 1.x, create a PR.

**Comment by SuperJugy** [comment]
I see, unfortunately I don't have much free time, But I'll see if I can get around to it. Thanks!

**Comment by joel-costigliola** [comment]
reopened to get it merged in 1.x branch

**Comment by joel-costigliola** [comment]
should not be needed if we introduce Java6Assertions in 2.x branch (#500)

**Comment by joel-costigliola** [comment]
Should be addressed by #521 by using `Java6Assertions`.
