### ISSUE TITLE
To be OS agnostic, replace \n by %n in error message

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#312]
This is a huge task, let's do this when we change an error message.

**Comment by FaustXVI** [comment]
I'm currently working on it on my branch if you want to take a look.
https://github.com/FaustXVI/assertj-core/tree/issue-312
I'm trying to to it all in one so it's allow me to see much of the code.

**Comment by joel-costigliola** [comment]
sweet ! :)

**Comment by FaustXVI** [comment]
Do we also want the tests to be os agnostic ?
If not, i did it with an ugly hack in util.Strings.
If yes, then I we'll have to call String.format for each tests right ?

**Comment by joel-costigliola** [comment]
Yes the tests should be OS agnostics.
Can you create a PR ? It's easier to see what you have changed.

**Comment by FaustXVI** [comment]
I disagree closing this issue, the tests are still os dependant.

**Comment by joel-costigliola** [comment]
What is missing ?

**Comment by FaustXVI** [comment]
The test code still use \n characters so they won't pass on a windows. Event if the production code is now OS agnostic, the build still is.
