### ISSUE TITLE
Add LocalDate assertions

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#313]
Use `LocalDateTime` assertions as a model.

**Comment by onacit** [comment]
@joel-costigliola  @fiery-phoenix
Do we already have following assertions? Or do we have any reason not to have?

```java
final LocalDate actual = LocalDate.now();
assertThat(actual).hasYear(2022);
assertThat(actual).hasMonth(Month.MARCH);
assertThat(actual).hasMonthValue(3);
assertThat(actual).hasDayOfMonth(1);
```

**Comment by joel-costigliola** [comment]
No specific reason but not having anyone asked for them, we can add them for sure.

**Comment by onacit** [comment]
@joel-costigliola [Issued](https://github.com/assertj/assertj-core/issues/2541), FYI.
