### ISSUE TITLE
SoftAssertions simplification

### ISSUE THREAD

**Issue by lpandzic** [joel-costigliola/assertj-core#332]
Continuation from https://github.com/joel-costigliola/assertj-core/pull/321.

With the BDD issue aside, SoftAssertions would surely benefit from a shorthand static factory method like:

```java
SoftAssertions.assertAll(softly -> {
    softly.assertThat(mansion.guests()).as("Living Guests").isEqualTo(7)
    softly.assertThat(mansion.kitchen()).as("Kitchen").isEqualTo("clean");
});
```

Thoughts?

**Comment by joel-costigliola** [comment]
if you want to avoid to have to call `assertAll`, you can use 
* `AutoCloseableSoftAssertions` 
* `JUnitSoftAssertions`

In your case, I would rather use `AutoCloseableSoftAssertions`.

**Comment by lpandzic** [comment]
Isn't it cleaner and simpler this way, even with an anonymous inner class?

**Comment by joel-costigliola** [comment]
I think that using try-with-resources is a lighter approach and it's java 7 compatible, I don't see much value this static method, but if more people ask for it, I'll reconsider.

For the time being, I'm closing this issue but feel free to reopen it if you find more people wanting it.

**Comment by lpandzic** [comment]
Anonymous inner classes are Java 6 compatible but ok, it makes sense since assertj is now on Java 7.
