### ISSUE TITLE
Defining code style for Introspection features

### ISSUE THREAD

**Issue by xgouchet** [joel-costigliola/assertj-core#338]
Multiple asserts use introspection, among others the isEqualToComparingFieldByField() method. 

This method expect that the fields be public, or accessible through a getter. First of all, the documentation should warn the user that only the JavaBeans conventions is supported. 

A common convention (especially among Android programmers) is to prefix member variables with a lowercase m. For instance, a field which would be named "foo" in JavaBeans would be named "mFoo". In both cases, the getter is named getFoo(). 

Problem is that the Introspection class only uses the JavaBean introspector which doesn't recognizes the second convention. 

It would be a great benefit to allow the use of a custom inspector, or adding support to other field naming conventions.

**Comment by joel-costigliola** [comment]
In 2.0, private fields are used in field by field comparison (this can be disabled but it's the default behaviour in 2.0). 

This should meet your need unless I'm mistaken, if so please close the issue.

2.0 is expected to be released in few weeks.

**Comment by xgouchet** [comment]
Indeed this will meet my needs, thanks a lot
