### ISSUE TITLE
File asserts

### ISSUE THREAD

**Issue by genmad** [joel-costigliola/assertj-core#343]
For me, when i do assertion on a file, it is important that the File/Directory itself on the filesystem is the same for expected and actual comparisons. So when I do something like assertThat(File).isEqualTo(otherFile) they should return true when they are pointing to the same file/directory.

please consider this example:

File expected = new File("tests");
File actual = new File("tests/../tests");
assertThat(expected.getCanonicalPath()).isEqualTo(actual.getCanonicalPath());
assertThat(expected).isEqualTo(actual);

while comparing the string representation there is no assertion error, but comparing the file representation there will be an error issued.

From my point of view there are 2 solutions possible, either compare allways the canonicalPath  or offer methods which tell you that they compare the canonical path for equality

**Comment by joel-costigliola** [comment]
`isEqualTo` compares objects according to their `equals` method, for the consistency's sake I won't change that but I'm ok to add a new comparison based on canonical path (or real path for `Path`).

I propose to name the assertion: `isEqualByComparingCanonicalPathTo` (I'm open to suggestion). 
I would also add `isEqualByComparingRealPathTo` for `Path`.

BTW in your example, you should switch `expected` and `actual` to get a relevant error message.

**Comment by joel-costigliola** [comment]
WDYT ?

**Comment by genmad** [comment]
hi, 
sorry for not replying.

I understand your point about isEqualTo being implemented like equals. 
On the other hand is the equals implementation the way we really need it? The equals implementation considers the object representation ( including the object address). But do we really care for the object address? 

If we implement it the way you propose, I guess we need to implement other methods which are today based on the isEqualTo implementation. I thought that I had another case where I had list<File> and wanted to do similar things.

**Comment by joel-costigliola** [comment]
I think it would be a bad thing to make `isEqualTo` not to use `equals`, it would be confusing for users if sometimes `isEqualTo` don't rely on `equals`.

An alternative solution is to use a specific comparator as shown [here](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#custom-comparison-strategy).

**Comment by genmad** [comment]
Your are right, that isEqualTo should use equals. ( By the way, why did you make the distinction between equals and isEqualTo?)

I like the alternative solution. No messing around with equals and keeping the backwars compatibility.

I'm all set with this solution. Now I guess, there is only need to provide an Comparator for files based on the canonical path (CanonicalPathFileComparator)

**Comment by joel-costigliola** [comment]
`equals` is the method from `Object`, it should not be used as an assertion method, it has been marked as deprecated to avoid users to accidentally use it in place of `isEqualTo`.

I'm closing this issue as it is addressed by `usingComparator`.
