### ISSUE TITLE
java.nio.file Assertions are going to break a lot of Android projects

### ISSUE THREAD

**Issue by emilesvt** [joel-costigliola/assertj-core#345]
We found by way of a few transitive dependencies (assertj-guava:1.2.0) when 2.0.0 was released on Friday a lot of our Android projects stopped working.  The File based assertions that were added within the last month aren't going to work on the Dalvik platform as those classes are not available.  This will preclude anyone using from assertj in their Android projects from ever moving the 2.x version.

**Comment by joel-costigliola** [comment]
Well, we can't be stuck to java 6 just because of Android.
Having said that, if there are some assertions you really need, we might just release another 1.x version including them.

**Comment by emilesvt** [comment]
We're not missing any assertions and JDK7 support is available for Android, it's just that Dalvik doesn't have all the classes available to it that you'd find in the JRE.  I was just throwing this out there so others were aware.

**Comment by Sarev0k** [comment]
I'm getting the following error when I try to use AssertJ 2.0 with Android:

        error: cannot access Path
                assertThat(“foo”).isEqualTo(“Bar”);
                ^
        class file for java.nio.file.Path not found
        1 error

**Comment by joel-costigliola** [comment]
The reason was given by @emilesvt previous comment.

**Comment by dlubarov** [comment]
> AssertJ Core 2.0 relies on Java 7.

I would tweak the release notes to make it clear that it relies on JRE 7 SE classes. It sounded to me like it relies on Java 7 language features, which wouldn't be a problem for most Android projects.

**Comment by joel-costigliola** [comment]
Will add that.

**Comment by joel-costigliola** [comment]
Done : http://joel-costigliola.github.io/assertj/assertj-core.html

**Comment by dlubarov** [comment]
Thanks!

**Comment by 1zaman** [comment]
> Done : http://joel-costigliola.github.io/assertj/assertj-core.html

That web page claims that the 2.x version should be suitable for Android.

> if there are some assertions you really need, we might just release another 1.x version including them.

The assertion that I was missing is `isEqualByComparingTo()` in `AbstractComparableAssert`.

**Comment by joel-costigliola** [comment]
Is it not ? (compatible with Android), note that you have to use `Java6Assertions` and yes it should be mentioned in the documentation but it is not (yet).

**Comment by joel-costigliola** [comment]
doc issue created  : https://github.com/joel-costigliola/assertj/issues/61

**Comment by 1zaman** [comment]
Using `Java6Assertions` fixes the issue, thanks!

**Comment by vanniktech** [comment]
@joel-costigliola would it be possible to backport `withFailMessage()` as well as `containsExactlyInAnyOrder` into 1.x?
