### ISSUE TITLE
Provide a P2 update site

### ISSUE THREAD

**Issue by rbioteau** [joel-costigliola/assertj-core#348]
It will be really cool to be able to retrieve assertj-core from a <b>p2 update site</b> in order to add it in a [RCP Target Platform](http://www.vogella.com/tutorials/EclipseTargetPlatform/article.html)

**Comment by joel-costigliola** [comment]
It should be possible in https://github.com/joel-costigliola/assertj project which is the project website.
I have created https://github.com/joel-costigliola/assertj/issues/17 to track that
A contribution would be welcomed.
I'm closing this issue since it has been moved to assertj site project.
