### ISSUE TITLE
Javadoc code example for common assertions

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#349]
ex : `isEqualTo`

**Comment by PascalSchumacher** [comment]
Sorry if I'm mistaken, but could this be a duplicate of https://github.com/joel-costigliola/assertj-core/issues/4 ?

**Comment by joel-costigliola** [comment]
It's a part of #4 which is too big so I decided to split it.

**Comment by PascalSchumacher** [comment]
As far as I can tell there is at least one example for each assertion method now. I guess this can be closed.

**Comment by joel-costigliola** [comment]
yes !
