### ISSUE TITLE
Add hasSameTimeAs(String dateAsString) assertion

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#352]
```
assertThat(Date date).hasSameTimeAs(String dateAsString)
```

**Comment by mkordas** [comment]
What date formats should be supported?

**Comment by joel-costigliola** [comment]
The parsing logic is already written (see `AbstractDateAssert.parse`), the implementation is straightforward, see `AbstractDateAssert.isAfter(String dateAsString)` as an example.

**Comment by mkordas** [comment]
OK, I'll take it - please assign me.
