### ISSUE TITLE
Easier flatExtracting usage

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#353]
For example, instead having to implements `Extractor<BasketBallPlayer, List<BasketBallPlayer>>`  to be able to call:
```java
// teamMatesExtractor() returns a new Extractor<BasketBallPlayer, List<BasketBallPlayer>>
assertThat(list(noah, james)).flatExtracting(teamMatesExtractor()).contains(irving, rose);
```
I just want to write (assuming `BasketBallPlayer` has a `teamMate` property):
```java
assertThat(list(noah, james)).flatExtracting("teamMates").contains(irving, rose);
```
or the type safe version:
```java
assertThat(list(noah, james)).flatExtracting("teamMates", BasketBallPlayer.class)
                             .contains(irving, rose);
```

**Comment by AlexBischof** [comment]
Implemented the non-typesafe variant but i have the feeling that it was too easy. Basically i was overloading AbstractIterableAssert.flatExtracting/AbstractObjectArrayAssert.flatExtracting and used internally Extractors.byName.

After a short feedback i would create also the typesyfe variant.

**Comment by joel-costigliola** [comment]
Thanks that was quick  ! :)

Can you create a PR ? It's just easier to comment code.
Can you check that you have the correct formatting preferences, there were so much diff due to reformatting that it is hard to see what has really changed.

From what I saw, we should (if possible) probably reuse the existing `flatExtracting` your code seems to duplicate it, I also don't understand the NPE.

**Comment by AlexBischof** [comment]
I have refactored and reformatted the code and created a PR. I also removed the exception wrapping which was a result of a manually created extractor of the test classes.

**Comment by joel-costigliola** [comment]
Thanks, integrated with few improvements.
