### ISSUE TITLE
Feature request: isEqualToIgnoringWhitespace assertion on String

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#355]
It could be something simillar to Hamcrest's `org.hamcrest.Matchers#equalToIgnoringWhiteSpace`.

From it's Javadoc:
>Creates a matcher of String that matches when the examined string is equal to the specified expectedString, when whitespace differences are (mostly) ignored. To be exact, the following whitespace rules are applied:
all leading and trailing whitespace of both the expectedString and the examined string are ignored
any remaining whitespace, appearing within either string, is collapsed to a single space before comparison

>For example:
`assertThat("   my\tfoo  bar ", equalToIgnoringWhiteSpace(" my  foo bar"))`

**Comment by joel-costigliola** [comment]
Agreed, with the same semantics as hamcrest to avoid confusing users.

**Comment by AlexBischof** [comment]
My commit should solve this issue but i am not able to get the test running. He fails always with "Joda" which i am not using.

No offense but the design of the CharSequenceAssertBaseTest is totally not understandable. Time to implement the issue <5min, time to get the test running >1h until now and still not running

**Comment by joel-costigliola** [comment]
PR please ! ;-)

**Comment by mkordas** [comment]
Thanks guys for fast response. I agree that semantics should be the same, but:
* we should add more documentation and define what is whitespace
* we should specify how it behaves with strings with Windows/Unix newline characters
* we should change `WhiteSpace` to `Whitespace` as it is used on http://en.wikipedia.org/wiki/Whitespace_character

**Comment by joel-costigliola** [comment]
The behaviour should be described in javadoc WITH code examples, I always find it easier to understand behaviour through examples.
