### ISSUE TITLE
assert matchers for java.net.URI/java.net.URL

### ISSUE THREAD

**Issue by tokuhirom** [joel-costigliola/assertj-core#356]
I want an assert matcher for java.net.UR[IL].

**Comment by joel-costigliola** [comment]
Ok, what assertions ?
Can you contribute ?

**Comment by tokuhirom** [comment]
e.g. `assertThat(url).hasSchemeEqualsTo("http").hasPathEquals("/path/to/foo")`.

**Comment by joel-costigliola** [comment]
Let's keep it simple and use: `assertThat(url).hasScheme("http").hasPath("/path/to/foo")`.

**Comment by AlexBischof** [comment]
The current design of my branch uses only UriAssert. Any URL's can be asserted via a convenience method in Assertions so that there is no code duplication. As a drawback the following test code would fail:

      AbstractUriAssert<?> assertions = Assertions.assertThat(url);
      assertThat(assertions.actual).isSameAs(url);

Thoughts?

**Comment by PascalSchumacher** [comment]
+1 for adding these assertions
