### ISSUE TITLE
Feature request: hasToString assertion on any Object

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#357]
It could be something similar to existing Hamcrest assertion `org.hamcrest.Matchers#hasToString(java.lang.String)`

From its Javadoc:
>Creates a matcher that matches any examined object whose toString method returns a value equalTo the specified string.

>For example:
`assertThat(true, hasToString("TRUE"))`

**Comment by joel-costigliola** [comment]
Agreed, it can be useful.

**Comment by AlexBischof** [comment]
hasToStringIgnoringCase
 too?

**Comment by joel-costigliola** [comment]
I would prefer to just have `hasToString` to avoid API bloating for no real needs, if users wants to make fancy assertions on `toString`they can use String assertions like `assertThat(object.toString()).startsWith`
