### ISSUE TITLE
Add OffsetTime and OffsetDateTime 

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#363]

**Comment by checketts** [comment]
With this work happening in the Java 8 branch will a new Java 8 release of AssertJ happen any time soon, or should I just build my own RC to begin using? I want to start using it and give feedback/pull requests.

**Comment by joel-costigliola** [comment]
It just happened :)
Feedback and PR always welcome

**Comment by AlexBischof** [comment]
What is the status here? Can i take it?

**Comment by joel-costigliola** [comment]
you can, thx.

**Comment by AlexBischof** [comment]
Ok, created PR for OffsetTime and looking now at OffsetDateTime.

**Comment by AlexBischof** [comment]
PR contains now assertion for OffsetDateTime, too.

**Comment by joel-costigliola** [comment]
Sweet, thanks, will have a look at it next week or so
