### ISSUE TITLE
Asserting for interfaces resulting in Ambiguous method error under Java 8

### ISSUE THREAD

**Issue by mariuszs** [joel-costigliola/assertj-core#365]
```java
import org.assertj.core.api.Assertions;

public class Ambiguous {

    public static void main(String... args) {
        Assertions.assertThat(caughtException());
    }

    public static <E extends Exception> E caughtException() {
        return null;
    }
}
```

Error message (for Java 8 only!):

    javac -source 1.8 Ambiguous.java  -classpath assertj-core-3.0.0.jar                                                                     
    Ambiguous.java:6: error: reference to assertThat is ambiguous
            Assertions.assertThat(caughtException());
                      ^
      both method assertThat(CharSequence) in Assertions and method assertThat(Throwable) in Assertions match
    1 error

Explanation:

http://stackoverflow.com/questions/29499847/ambiguous-method-in-java-8-why/29500086#29500086

Maybe we can change this API, deprecate conflicting methods and remove it in future releases?

**Comment by mariuszs** [comment]
title misspelled

**Comment by mariuszs** [comment]
title misspelled

**Comment by joel-costigliola** [comment]
Fixed I hope.
I have let other method `assertThat` that took interface or generic type extending interface.

**Comment by joel-costigliola** [comment]
Oh ... and thanks !

**Comment by joel-costigliola** [comment]
@mariuszs Can you give it a try ? I'm about to release 3.1.0 this week.

**Comment by mariuszs** [comment]
Nice :) Sorry for delay from my site.

This code works for me:

```java
import org.assertj.core.api.StrictAssertions;

public class Ambiguous {

    public static void main(String... args) {
        StrictAssertions.assertThat(caughtException());
    }

    public static <E extends Exception> E caughtException() {
        return null;
    }
}
```

**Comment by mariuszs** [comment]
This code works too:

```java
    @Test
    public void bdd() throws Exception {

        // given: an empty list
        List myList = new ArrayList();

        // when: we try to get the first element of the list
        when(() -> myList.get(1));

        // then: we expect an IndexOutOfBoundsException
        StrictAssertions.assertThat(caughtException())
                .isInstanceOf(IndexOutOfBoundsException.class)
                .hasMessage("Index: 1, Size: 0")
                .hasNoCause();
    }
```

Maybe we need also something like BDDStrictExceptions

**Comment by joel-costigliola** [comment]
sweet, thanks for the feedback
