### ISSUE TITLE
Feature request: doesNotStartWith and doesNotEndWith assertions on CharSequence

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#372]
Provide complementary assertions to:
* https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L471
* https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L445

**Comment by joel-costigliola** [comment]
I agree.
