### ISSUE TITLE
Use strict instead of lenient date parsing mode by default

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#374]
While parsing String representing the date, [setLenient(false)](http://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#setLenient(boolean)) mode should be used.

It solves some date parsing anomalies, such as allowing January 32nd to be interpreted as February first or even January -1st as December 31st. More examples can be found [here](http://stackoverflow.com/questions/7606387/what-is-the-use-of-lenient).

The commit message should say that it's a braking change so that when I do the release notes I won't forget it.

We need a way to set the parsing leniency so that users can switch to the old behaviour. The (new) default behaviour being not to be lenient.

##### Design question
* Should this be static and global AssertJ parameter? Then we need to add a method `setStrictDateParsing(boolean)` in Assertions delegating the real work to the same method in `AbstractDateAssert`.
* Otherwise we may add e.g. `usingLenientDateParsing()` to `AbstractDateAssert` to parse date leniently just for one particular assertion.

**Comment by joel-costigliola** [comment]
I don't think we need to set leniency per assertion, let's provide the global option only.

**Comment by mkordas** [comment]
OK - should it be global option per ClassLoader (`private static` field) or global option per Thread (`private static ThreadLocal<Boolean>` field)?

**Comment by joel-costigliola** [comment]
I don't think we need to store a field, we should simply update each `DEFAULT_DATE_FORMATS` in `AbstractDateAssert` to use the given leniency setting.

**Comment by mkordas** [comment]
1. We have two lists with date formats: `DEFAULT_DATE_FORMATS` and `userDateFormats`.
2. We can use two loops and change leniency for all formats, but what when a user will add new format after the leniency mode is changed? We either need to store that setting and reapply it or tell the users that all newly added formats are strict by default and static method needs to be invoked again to change the mode.

**Comment by joel-costigliola** [comment]
We should only change the `DEFAULT_DATE_FORMATS`, the user formats are users responsibility, we assume they know what they are doing (might not be always true but ... ).
Since a user can't add a default format `DEFAULT_DATE_FORMATS` we can avoid storing a field.

**Comment by mkordas** [comment]
All right, please review #375.
