### ISSUE TITLE
Add support for primitive Optional classes

### ISSUE THREAD

**Issue by jodastephen** [joel-costigliola/assertj-core#379]
The Java 8 release contains support for `Optional` (yay!). But it does not appear to have support for `OptionalInt`, `OptionalLong` or `OptionalDouble`. It would be great to have support for these.

See [our version](https://github.com/OpenGamma/OG-Commons/blob/master/modules/collect/src/test/java/com/opengamma/collect/OptionalDoubleAssert.java) for `OptionalDouble`.

**Comment by joel-costigliola** [comment]
Indeed they are missing.

When comparing double with a tolerance, we use `within` syntatic sugar to improve readability, following the same approach for `OptionalDouble` would give:
```java
assertThat(OptionalDouble.of(10.0)).isCloseTo(8.0, within(2.0));
```
Would you be happy with that ?

**Comment by jodastephen** [comment]
In our version (linked above) we have 

* isPresent()
* isEmpty()
* hasValue(double expected)
* hasValue(double expected, Offset<Double> tolerance)
* hasValue(double expected, double tolerance)

The method name `isCloseTo` with a tolerance seems fine to us.

**Comment by AlexBischof** [comment]
I would take it.

**Comment by joel-costigliola** [comment]
@AlexBischof to be clear for `OptionalDouble` value check, let's define these assertions: 

```java
assertThat(OptionalDouble.of(8.0)).hasValue(8.0);

// within is a helper method to create an Offset
assertThat(OptionalDouble.of(10.0)).hasValueCloseTo(8.0, within(2.0));
```

**Comment by AlexBischof** [comment]
Thanks for clarifying. 

Finally i have a PR-ready branch but wondering about the code duplication (e.g. OptionalXXXShouldBeEmpty, OptionalXXXShouldBePresent, AbstractOptionalXXXAssert etc.). 

It should be no problem to composite the error and AbstractOptionalXXXAssert classes. Is there anything i should keep in mind

**Comment by joel-costigliola** [comment]
You can add new methods to `OptionalShouldBeEmpty` for `OptionalInt`, `OptionalLong` or `OptionalDouble`, no need to create another class (don't forget to add the corresponding unit tests in `OptionalShouldBeEmpty_create_Test`).

ex:
```public static OptionalShouldBeEmpty shouldBeEmpty(OptionalInt optional)```

**Comment by joel-costigliola** [comment]
@AlexBischof what about your PR ? is it ready ?

**Comment by AlexBischof** [comment]
Basically it is ready. Still need to do the small refactoring above. I provide the PR tomorrow after my final check.

**Comment by AlexBischof** [comment]
PR created.

**Comment by joel-costigliola** [comment]
Done.
