### ISSUE TITLE
Feature request: isEqualToAnyOf assertion for all Objects

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#380]
In Hamcrest we can use the following assertion:
```java
assertThat(something, or(equalTo(first), equalTo(second));
```
It would be nice to have the following replacement in AssertJ:
```java
assertThat(something).isEqualToAnyOf(first, second);
```

**Comment by joel-costigliola** [comment]
This assertion already exists : `isIn`

Example : ` assertThat(frodo).isIn(sam, frodo, pippin);`
