### ISSUE TITLE
Extraction of nested field/property combination fails

### ISSUE THREAD

**Issue by a11n** [joel-costigliola/assertj-core#381]
Today I discovered that extraction of field/property combinations fails for `AbstractIterableAssert`. It either expects properties or fields. It seem to fail for altering combinations.

I depend on a class from a lib from Google, which has a public field `file` of type `File`. If I want to extract `file.name`, where name is a method (`File#getName()`), I get the following exception:
>org.assertj.core.util.introspection.IntrospectionError: 
>Can't find any field or property with name 'file.name'.
>Error when introspecting fields was :
>No getter for property 'file' in com.android.tools.lint.Warning 

Here is some example code to demonstrate the issue:
```java
List<Warning> warnings = lint.getWarnings();   
assertThat(warnings).extracting("file.name").containsExactly("AndroidManifest.xml");
```

By the way, it succeeds when I try `file.path`, cause `path`is a field of type `File`.

A look at assertj's `ByNameSingleExtractor` class seems to support my assumption (see line 48-52).

So my question is, if this is on purpose or if it is an issue?

Because when looking at other "path reflection" solutions, for instance at Apache's commons-lang, the resolution of nested properties always accepts anything, fields, getters, indexes, maps...

**Comment by joel-costigliola** [comment]
It's an issue, we should be able to extract any field/property combination.
Thanks for reporting this.

**Comment by a11n** [comment]
Thanks for confirmation. I'll try to make an according PR.

**Comment by a11n** [comment]
Ok, I've investigated the corresponding sources now. Before working on a pull request I want to check some aspects with you first.

As described above there is a "hard" distinction between properties (=getters) and fields. Two separate classes exist: `PropertySupport`and `FieldSupport`.

In order to have a generic support for nested property/field combinations there needs to be a sort of `CompositePropertyFieldSupport` which successively resolves nested elements. The most of the code of `PropertySupport` and `FieldSupport` could be reused for this... unfortunately the methods are mostly private and both classes are in different packages :-/ (my first idea was to make them package private, but this won`t work).

So my question is, why is FieldSupport in another package than PropertySupport?

Do you have any ideas yourself or any restrictions I should know of? Otherwise I would continue and propose a PR in the next couple of days.

Thanks in advance.

**Comment by joel-costigliola** [comment]
There is no real good reason just "historical" ones, we started with property support only and add later on field support. This part of the code definitely needs some refactoring love.
Feel free to move classes and make methods public if it is needed.
