### ISSUE TITLE
Feature request: isNotEqualToIgnoringCase assertion on CharSequence

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#392]
We have already [isEqualToIgnoringCase](https://github.com/joel-costigliola/assertj-core/blob/ca732b2d513984e086eface4aaafeb2af7b57555/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L262), but it would be nice to have corresponding `isNotEqualToIgnoringCase`.

**Comment by AlexBischof** [comment]
I have created a PR for this but i find a quite difficult to decide when to use *isNotEqualToIgnoringCase* instead of  *isNotEqualTo*.

**Comment by joel-costigliola** [comment]
You should use `isNotEqualToIgnoringCase` when you consider that uppercase/lowercase does not matter, said otherwise if you lowercase the String to compare, are they different ?

I agree it is no
