### ISSUE TITLE
Feature request: extend containsSequence assertions

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#393]
Right now it's only possible to do positive `containsSequence` assertion using varargs:
https://github.com/joel-costigliola/assertj-core/blob/ca732b2d513984e086eface4aaafeb2af7b57555/src/main/java/org/assertj/core/api/AbstractCharSequenceAssert.java#L365

Would be nice to have:
* assertion using `Iterable` as argument in addition to varargs
* negative assertion `doesNotContainSequence`

**Comment by joel-costigliola** [comment]
I agree.
