### ISSUE TITLE
Feature request: assertion to check that two comparable objects are equal

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#394]
Sample class:
```java
  class A implements Comparable<A> {
    @Override public int compareTo(A o) {
      return 0;
    }
  }
```
This assertion passes:
```java
    assertThat(new A().compareTo(new A())).isZero();
```
Would be nice to have more fluent assertion for that:
```java
    assertThat(new A()).equalsTo(new A());
```
`equalsTo` is just a guess. I was thinking also about `comparesTo`, `comparesAsEqualTo`. I'm open to other ideas.

**Comment by joel-costigliola** [comment]
Agreed, let's use `isEqualByComparingTo` as it already available for `BigDecimal` assertion.

**Comment by mkordas** [comment]
Great name, thanks. I'll prepare PR soon.

**Comment by mkordas** [comment]
Is it OK, to add `isEqualByComparingTo` to every comparable, also types like `Integer` or `Double`? If yes, then we could remove concept of `UnevenComparableAssert`. What do you think?

**Comment by joel-costigliola** [comment]
I agree, it was designed like this in fest-assert but I don't see any real value keeping it.

BTW, let's also add `isNotEqualByComparingTo` as part of this issue.
