### ISSUE TITLE
Comparison by value strategies should support mixed nested field/property

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#396]
Example: if comparison is done on `home.address.number` and `home` is a property and `address` a field the comparison fails as it is only able to get pure field or pure property values.  

Moreover the javadoc is wrong as now private field are supported.

**Comment by PascalSchumacher** [comment]
I took a look a this, but have not been able to reproduce the issue. This test passes:

```java
@Test
public void test() {
    assertThat(Arrays.asList(new Person())).usingElementComparatorOnFields("home.address.number").contains(new Person());
}

private static class Person {
    private Home home = new Home();
}

private static class Home {
    public Address getAddress() {
        return new Address();
    }
}

private static class Address {
    int number = 1;
}
```

What am I missing?

**Comment by PascalSchumacher** [comment]
@joel-costigliola Could you show me an example that should work but does not? Thanks!

**Comment by joel-costigliola** [comment]
I think this has been fixed as a side effect of the refactoring on property/field support.
the only thing to do is to add a test proving it (if it does not already exists).

Sorry for the waste of time !

**Comment by joel-costigliola** [comment]
Test added (8fd1a1fe82eb16f45db33727ce85769d10ca5fb2).
