### ISSUE TITLE
Feature Request: extracting method on objects

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#411]
What I would like to do:

```java
public class Person {
     String firstname, lastname;
     Address adress;
}

then(new Person()).extracting("firstname", "lastname").doesNotContainNull();
```

Maybe this is already possible?

**Comment by joel-costigliola** [comment]
No, `extracting` works for iterable and arrays.

I like the idea, good one.

**Comment by PascalSchumacher** [comment]
Thanks. :) 

I will try to provide a pull request for this.

**Comment by cciotti** [comment]
@PascalSchumacher - are you working on this? I need similar functionality and would take a crack at it if you're not in the middle of it.

**Comment by PascalSchumacher** [comment]
No, I'm not working on this, so feel free to take it on.

Am 26. September 2015 18:06:27 MESZ, schrieb Chris Ciotti <notifications@github.com>:

**Comment by cciotti** [comment]
Thanks, I'll take it

**Comment by PascalSchumacher** [comment]
@cciotti Are you still working on this? If not I may be able to give it a try.

**Comment by cciotti** [comment]
@PascalSchumacher - no I'm not. I didn't need the feature in my project.
