### ISSUE TITLE
Feature Request: compare objects of different types field/property by field/property

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#412]
```java
class Person {
	String firstname, lastname;

	public Person(String firstname, String lastname) {
		this.firstname = firstname;
		this.lastname = lastname;
	}
}

class PersonDAO {
	String firstname, lastname;
	Long id;

	public PersonDAO(String firstname, String lastname, Long id) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.id = id;
	}
}

Person person = new Person("John", "Doe");
PersonDAO personDAO = new PersonDAO("John", "Doe", 1L);
		
assertThat(person).isEqualToObjectOfOtherTypeComparingFieldByField(personDAO);
assertThat(personDAO).isEqualToObjectOfOtherTypeIgnoringGivenFields(person, "id");
```

Names of the assertion methods could probably be improved.

**Comment by joel-costigliola** [comment]
Maybe we should just relax the check on objects being of the same class in `isEqualToComparingFieldByField`, after all one might say that if you compare fields/properties the actual type is not really relevant.

**Comment by PascalSchumacher** [comment]
Actually I expected `isEqualToComparingFieldByField/isEqualToComparingOnlyGivenFields/ 	isEqualToIgnoringGivenFields/ isEqualToIgnoringNullFields` to work on objects of different classes. After I discovered that they do not I created this request.

I could try to provide a pull request for your preferred solution. (If you believe this feature to be a worthy addition to AssertJ.)

**Comment by joel-costigliola** [comment]
I think so.
Removing the call to `assertOtherTypeIsCompatibleWithActualClass` in `org.assertj.core.internal.Objects` should do the trick.

**Comment by PascalSchumacher** [comment]
Thank you very much for adding this! :)

**Comment by joel-costigliola** [comment]
My pleasure ! :)

**Comment by PascalSchumacher** [comment]
How can I use this enhancement?

```java
public class CompareObjectsOfDifferentClasses {

	private static class Person {
		String firstname, lastname;

		public Person(String firstname, String lastname) {
			this.firstname = firstname;
			this.lastname = lastname;
		}
	}

	private static class PersonDAO {
		String firstname, lastname;
		Long id;

		public PersonDAO(String firstname, String lastname, Long id) {
			this.firstname = firstname;
			this.lastname = lastname;
			this.id = id;
		}
	}

	@Test
	public void should_be_able_to_compare_Person_to_PersonDAO() {
		Person person = new Person("John", "Doe");
		PersonDAO personDAO = new PersonDAO("John", "Doe", 1L);
		
		assertThat(person).isEqualToComparingFieldByField(personDAO);
		
		assertThat(personDAO).isEqualToIgnoringGivenFields(person, "id");
	}
}
```
Still give me two compile errors when using current master:

> The method isEqualToComparingFieldByField(CompareObjectsOfDifferentClasses.Person) in the type AbstractObjectAssert<capture#1-
 of ?,CompareObjectsOfDifferentClasses.Person> is not applicable for the arguments (CompareObjectsOfDifferentClasses.PersonDAO)

>The method isEqualToIgnoringGivenFields(CompareObjectsOfDifferentClasses.PersonDAO, String...) in the type AbstractObjectAssert<capture#2-
 of ?,CompareObjectsOfDifferentClasses.PersonDAO> is not applicable for the arguments (CompareObjectsOfDifferentClasses.Person, String)

**Comment by joel-costigliola** [comment]
Ok, I screwed up the fix - only works if expected object inherits from actual type.
In your example, if you declare `person`  and `personDAO` as objects, it will work fine.

**Comment by joel-costigliola** [comment]
Fix fixed.

**Comment by kevdoran** [comment]
This is a super old issue, but I just want to say that this feature continues to be really useful, as does AssertJ in general. Thanks all!

**Comment by joel-costigliola** [comment]
Just for reference, here's how to do it in recent version https://assertj.github.io/doc/#assertj-core-recursive-comparison-strict
