### ISSUE TITLE
Feature Request: Add isCloseToPercentage to numbers

### ISSUE THREAD

**Issue by AlexBischof** [joel-costigliola/assertj-core#415]
In my current project i need to check values with an offset which is a percentage value. So i need to calculate the offset like this:

```java
        double actualSum = 101d;
        double expectedSum = 100d;
        //should differ only within 0.5 percent
        double percentage = 0.5d;

        double calculatedOffset = percentage * expectedSum / 100;
        assertThat(actualSum).isCloseTo(expectedSum, offset(calculatedOffset));
```
Can we create a convenience method to encapsulate that calculation so that it would look like this
```java
assertThat(actualSum).isCloseToPercentage(expectedSum, offset(0.5d));
```

**Comment by AlexBischof** [comment]
Having started with implementing this i think it is better to use it that way
```java
assertThat(9.0).isCloseTo(10.0, Percentage.percentage(0.5));
```

**Comment by joel-costigliola** [comment]
Ok but I suggest to use `withinPercentage` to be consistent with the existing API.

**Comment by AlexBischof** [comment]
I see that *isCloseTo* is only in *RealNumbers* which is not up to date anymore because every number has this method now. I would like to update this by pulling this method to *Numbers*. Therefore a refactoring of Numbers is needed.
```java
class Numbers<NUMBER extends Number & Comparable<NUMBER>>
```
@joel-costigliola Do you see any problems with that?

**Comment by AlexBischof** [comment]
I am almost finished so do you mean that way?

```java
assertThat(9.0).isCloseTo(10.0, Percentage.withinPercentage(0.5));
assertThat(9.0).isCloseTo(10.0, Assertions.withinPercentage(0.5));
```

**Comment by joel-costigliola** [comment]
Yes, `Assertions.withinPercentage` delegating to `Percentage.withinPercentage`

**Comment by joel-costigliola** [comment]
Just to be sure, if you want to express that actual is close to expected by less than 5%, you would write:

```java
assertThat(9.0).isCloseTo(10.0, withinPercentage(5));
```

right ?

**Comment by AlexBischof** [comment]
Yes. Basically it is just a convenience method so that the following is the same:
```java
assertThat(9.0).isCloseTo(10.0, offset(0.5));
assertThat(9.0).isCloseTo(10.0, offset(10.0*0.05));
```

**Comment by joel-costigliola** [comment]
:+1:
