### ISSUE TITLE
AbstractAssert.isSameAs() javadoc comment

### ISSUE THREAD

**Issue by gaganis** [joel-costigliola/assertj-core#418]
I am a new user of assertions in general and I came upon an issue while trying to use the isSameAs method. By reading the Javadoc I wasn't really sure what the method would do. I finally resorted to ready the source where I found that it does a reference check using ==. So I would have liked that this would be mentioned in the Javadoc.
maybe it could be changed to "Verifies that the actual value is the same as the given one. Equivalent to a == b"

Thanks
Giorgos

**Comment by joel-costigliola** [comment]
agreed, should have some code example too.

**Comment by joel-costigliola** [comment]
Actually on our todo list as part of : https://github.com/joel-costigliola/assertj-core/issues/349

**Comment by gaganis** [comment]
I am amazed by how fast this was has been resolved!
I am a bit disappointed through because I was planning to write/contribute it myself on the weekend and missed the opportunity.☺

Thanks a lot guys!

**Comment by joel-costigliola** [comment]
Don't be disappointed ! you can contribute to https://github.com/joel-costigliola/assertj-core/issues/349 :bowtie:  - it's a work in progress
