### ISSUE TITLE
Add "expected" value to AbstractIterableAssert.containsExactly assertion message

### ISSUE THREAD

**Issue by elygre** [joel-costigliola/assertj-core#423]
The AbstractIterableAssert message does not contain the expected value, only the actual value. This makes it harder to use in a parameterized setting, like the one below:

    // Verifies that searching for values returns only those values
    for (String storageType : Arrays.asList("FILE", "TEXT", "URL", "XML")) {
        List<String> storage = searchFor(storageType);
        assertThat(storage).containsExactly(storageType);
    }

The error message does not tell me which what I was looking for, but only what I got -- which of the four iterations failed?

    java.lang.AssertionError: 
    Actual and expected should have same size but actual size is:
     <2>
    while expected is:
     <1>
    Actual was:
    <["XML", "TEXT"]>

This can be contrasted with a simple `assertThat("hi").isEqualTo("ho")`:

    org.junit.ComparisonFailure: 
    Expected :"ho"
    Actual   :"hi"

It would be nice if the error message also included expected value:

    java.lang.AssertionError: 
    Actual and expected should have same size but actual size is:
     <2>
    while expected is:
     <1>
    Expected was:           <-- New
    <["TEXT"]>              <-- New
    Actual was:
    <["XML", "TEXT"]>

**Comment by joel-costigliola** [comment]
I definitely agree.
Thanks for taking the time to report this.
