### ISSUE TITLE
What has prevented SoftAssertions itself from implementing AutoCloseable?

### ISSUE THREAD

**Issue by fge** [joel-costigliola/assertj-core#434]
I love the new feature which appeared in 2.0.0 with AutoCloseableSoftAssertions; however I wonder why SoftAssertions itself wasn't extended to implement it and thus removing the need for a whole new class?

Was there a technical reason behind it?

**Comment by joel-costigliola** [comment]
That's a good point !

**Comment by AlexBischof** [comment]
The only technical reason i could imagine is for backward stability if someone has already used a *close* method with a different modifier.

```java
new SoftAssertions(){
    protected void close(){} //compile error
}
```

Combining these two classes would be a code quick win ;)

**Comment by Turbo87** [comment]
@fge @joel-costigliola see https://github.com/joel-costigliola/assertj-core/pull/235

**Comment by PascalSchumacher** [comment]
I guess the "you get this annoying compiler warning saying that your resource is not closed" argument is a valid reason and this can be closed?

**Comment by joel-costigliola** [comment]
yes, the warning is annoying.
