### ISSUE TITLE
Javadoc: Reduce/remove gap between "Example:" heading and example code

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#438]
It would be nice to reduce or remove the gap between the "Example:" heading and example code in the javadoc, so that the content assist in IDEs show more actual content.

E.g: https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractIterableAssert.html#containsOnly%28T...%29

**Comment by joel-costigliola** [comment]
Hmmm you don't syntax highlighting, I suspect `https` as this URL looks fine : http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractIterableAssert.html#contains%28T...%29

Maybe HTTPS prevents hightlight.js to be loaded ...

**Comment by PascalSchumacher** [comment]
Yes the highlighting works with HTTP.

Does highlighting work for you in Eclipse? For me it does not.

My complaint was, that without code highlighting the gap between the "Example:" heading and example code is very big: https://github.com/PascalSchumacher/stuff/blob/master/assertj-javadoc-example-margin.png and looks like wasted space.

With highlighting it looks o.k., so feel free to close this issue.

**Comment by joel-costigliola** [comment]
No, eclipse can't preserve syntax highlighting as it is done through javascript.

I might consider reducing the space so that it looks better in eclipse but I still want to keep the nice looking generated javadoc.

**Comment by joel-costigliola** [comment]
Best solution so far : 
* remove starting and ending in examples (lot of work but worth it!)
* increment padding in `hljs` class to 0.6em

**Comment by PascalSchumacher** [comment]
If there is anything I can help with I can create a pull request.

**Comment by joel-costigliola** [comment]
yep, have a look at what I did in assertj-guava (see this commit https://github.com/joel-costigliola/assertj-guava/commit/841ee1b60df12a59b5e7528901a07e9d18c0f618), you can generate the javadoc with maven and if you are happy with the result, we have to do the same for assertj-core, that is reformatting the code examples like in the mentionned commit.

**Comment by PascalSchumacher** [comment]
The javadoc examples of assertj-guava look much improved in Eclipse!

Thanks I lot. :)

I will create a pull request with the changes for assertj.

**Comment by joel-costigliola** [comment]
:+1:
