### ISSUE TITLE
Cannot assert Path content when using Jimfs file system.

### ISSUE THREAD

**Issue by bowmore** [joel-costigliola/assertj-core#439]
Jimfs is an in memory file system from google for testing purposes. Its implementation of java.nio.Path.toFile() throws an UnsupportedOperationException. This is actually completely legit (implementations are not required to support toFile() according to javadoc)

The assertion on a Path's contents, however, appears to use toFile() to get to the contents. So my assertion on this file fails.

<b>Path's assertions should not rely on java.nio.Path.toFile()</b>

<pre>
java.lang.UnsupportedOperationException
	at com.google.common.jimfs.JimfsPath.toFile(JimfsPath.java:397)
	at org.assertj.core.internal.Paths.assertHasContent(Paths.java:277)
	at org.assertj.core.api.AbstractPathAssert.hasContent(AbstractPathAssert.java:257)
    ...
</pre>

As a workaround I read the contents of the file myself, and use an assertion on String equality.

**Comment by joel-costigliola** [comment]
hmm ... sneaky one ! I have to agree, we should probably use Path URI to read the content.

**Comment by bowmore** [comment]
Use Path URI, or simply java.nio.Files.newInputStream(Path)

**Comment by bowmore** [comment]
Using Path URI may also not be a good idea. I've tried doing this using Jimfs and got : "unknown protocol: jimfs".
So better to use java.nio.Files.newInputStream(Path) I think.

**Comment by joel-costigliola** [comment]
Thanks Pascal !

**Comment by bowmore** [comment]
I'll give it a whirl after my holidays, in the mean time, thanks a lot!
