### ISSUE TITLE
assertions related to entries on AbstractMapAssert should support java.util.Map.Entry as arguments

### ISSUE THREAD

**Issue by sarod** [joel-costigliola/assertj-core#440]
Hi,

It seems to me that AbstractMapAssert would be more flexible if AbstractMapAssert.contains (and other assertions related to MapEntry) were taking java.util.Map.Entry as arguments instead of MapEntry.
For backward compatibility MapEntry would need to implement java.util.Map.Entry interface.

What do you think?

**Comment by PascalSchumacher** [comment]
@joel-costigliola Do you think this is a beneficial addition/change? (Looks easy, maybe I could come up with a pull request.)

**Comment by joel-costigliola** [comment]
I have tried to use `java.util.Map.Entry` instead of `MapEntry` few years ago while working on Fest assert but failed for a reason I can't remember, it is worth give it another try with backward compatibility in mind as @sarod mentioned.

**Comment by PascalSchumacher** [comment]
Thanks. I give it a try. Even if I fail I will learn useful things about assertj. :)

**Comment by joel-costigliola** [comment]
:+1:

**Comment by joel-costigliola** [comment]
Thanks Pascal.
