### ISSUE TITLE
assertThat(java.util.function.Supplier) does / does not return same value when called multiple times

### ISSUE THREAD

**Issue by elygre** [joel-costigliola/assertj-core#442]
Today I will write code such as

```
Object result1 = object.getInstance();
Object result2 = object.getInstance();
assertThat(result1).isNotSameAs(result2);
```

However, I'm trying to implement the following logic:

```
assertThat(object::getInstance).doesNotReturnSameInstanceWhenCalledMultipleTimes()
```

where "doesNotReturnSameInstanceWhenCalledMultipleTimes" is a terrible name, but the only one i could thing of immediately. Perhaps better minds can come up with better names :-)

**Comment by joel-costigliola** [comment]
My suggestions:
```
assertThat(supplier).alwaysSuppliesDistinctInstances();
// or
assertThat(supplier).suppliesDistinctInstances();

assertThat(supplier).alwaysSuppliesSameInstance();
```

**Comment by elygre** [comment]
The term "always" is a bit strong, perhaps -- how many times do you have to check before you know that "always" is true? I like the "distinct", though...

```
assertThat(supplier).suppliesDistinctInstances();
assertThat(supplier).suppliesSameInstance();
```

Or maybe use the word "repeatedly" to indicate that there is repetition involved, even though there is no guarantee for "always"?

```
assertThat(supplier).repeatedlySuppliesDistinctInstances();
assertThat(supplier).repeatedlySuppliesSameInstance();
```

**Comment by joel-costigliola** [comment]
I agree that we can't verify that a supplier always provide the same instance,  but how many times would need to check that for `repeatedlySuppliesSameInstance` ? 

Same thing for `suppliesDistinctInstances`, how many times do you need to check that supplied values are different ? 2 ? but what if the third values is the same as the 2nd ?

I think i is very important to provide unambiguous assertions, in the current state the proposed  assertions can't be included in AssertJ.

**Comment by joel-costigliola** [comment]
I'm closing this request as I don't see any unambiguous way to provide the requested assertions.
Feel free to add some comment and if we find a clean solution, I'll reopen the issue.
