### ISSUE TITLE
Fluent definition of assertions on elements of iterable (instead of using areXXX(Condition))

### ISSUE THREAD

**Issue by sarod** [joel-costigliola/assertj-core#449]
Hi,

AbstractIterableAssert.areXXX(Condition) are great but it is more heavy to define than standard assertj fluent assertion.

It would be great to be able to write something like 
```
Set<String> strings;
assertThat(strings).allElements().hasSameSizeAs("refString");

Set<File> files;
assertThat(files).allElements().canRead();
```

We would also probably need variations of allElements() to achieve assertions similar to what areAtLeastOne, areAtLeast... allow.

The problem is that Java type system is not powerful enough to express that the returned type (subclass of AbstractAssert) of allElements() is dependant on the type of the generic type of the iterable.

One dirty solution would be to have one method per AbstractAssert implementation and let the caller call the correct one depending on the datatype he knows he have.
Another possible solution would to have an optional parameter on assertThat() methods taking iterables that would allow to specify the AbstractAssert.class to use when working on elements if not provided ObjectAssert would be used.

I'm not sure it's reasonable to implement this because it would add a lot complexity.
In any case I wanted to create the issue to know what you think about this and if better ideas on how to implement this emerge.

**Comment by joel-costigliola** [comment]
No easy solution for this issue, the best we can do IMO is to add `allMatch(Predicate)`, example:
```java
assertThat(players).allMatch(p -> p.isRookie());
```
but that would be only available for Java 8.

**Comment by artjomkruglenkov** [comment]
I would like to support the idea of adding such a functionality.

**Comment by joel-costigliola** [comment]
allMatch added

**Comment by PascalSchumacher** [comment]
Another nice enhancement :smile:!
