### ISSUE TITLE
Provide more detailed documentation on creating custom assertions

### ISSUE THREAD

**Issue by pmkpublic** [joel-costigliola/assertj-core#458]
The github.io site provides great documentation for getting started on creating custom assertions.

However, I quickly found myself wanting/needing to go past what was documented there. I spent a lot of time digging through source code and trying to model what I was doing on it. 

This was often fun, but it took me longer than I want to admit to get everything working (assuming I have reached that point). I would have loved some documentation on the main things that got me looking at source:

1. Custom soft assertions.
2. Properly defining classes, fluent entry points, and soft entry points for custom assertions that have their own type hierarchy. 
    * For example, let's say I want to create assertions on classes that extend the class ```AbstractWidget```. Some of these classes only need assertions on properties that are defined on ```AbstractWidget```. Other classes need assertions on properties defined on the subclass. How do I define my classes and entry points for a generic ```WidgetAssert``` class, as well as for assert classes for specific subclasses? It took me quite a bit of trial and error to get this fully working (probably due to not reading source carefully enough), particularly with regard to soft assertions.

If this level of documentation seems appropriate and useful, I'd be happy to put together an initial draft based on what I've done.

**Comment by joel-costigliola** [comment]
That would be awesome ! the github.io site is actually editable (see http://joel-costigliola.github.io/assertj/assertj-help.html#assertj-build-site).
I'm closing this issue and creating new ones in assertj repo where assertj site resides.

**Comment by joel-costigliola** [comment]
I have created:
* https://github.com/joel-costigliola/assertj/issues/26
* https://github.com/joel-costigliola/assertj/issues/27

feel free to create additional issues.
