### ISSUE TITLE
OptionalAssert.contains() vs. OptionalIntAssert.hasValue()

### ISSUE THREAD

**Issue by Turbo87** [joel-costigliola/assertj-core#459]
There is an inconsistency in the naming of the content check methods of the `Optional` class and primitive `OptionalInt/Long/...` classes. Either both should be supported or we should decide on one and keep it consistent.

**Comment by joel-costigliola** [comment]
we can support both as `hasValue` was chosen in the first place, the number of optional assertions is low enough to support synonym assertions.

**Comment by joel-costigliola** [comment]
`contains` assertions added
