### ISSUE TITLE
CompletableFuture Assertions

### ISSUE THREAD

**Issue by Turbo87** [joel-costigliola/assertj-core#461]
Here is my work-in-progress proposal for [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) assertions. Feedback is very welcome.

----

# CompletableFuture Assertions

A `CompletableFuture` describes an asynchronous operation result that will eventually be fulfilled.

## Methods

- `isDone()` - the future has a result (exception or regular result)
- `isCompletedExceptionally()` - the future as an exceptional result
- `isCancelled()` - the future was cancelled and due to that has a `CancellationException` result
- `get()` waits for and returns the result, throws a `CancellationException` or throws the exceptional result wrapped in an `ExecutionException`

## States

The `CompletableFuture` class can be in four different states:

- not completed / "incomplete" (`!isDone()`)
- completed normally / "completed" (`isDone() && !isCompletedExceptionally()`)
- completed exceptionally  / "failed" (`isCompletedExceptionally()`)
- cancelled (`isCancelled()`)

Pseudo code to extract the state as an enum value:

```java
if (!isDone())
    return NOT_COMPLETED;
    
if (!isCompletedExceptionally())
    return COMPLETED;
    
if (!isCancelled())
    return FAILED;
    
return CANCELLED;
```

### isDone()

```java
assertThat(future).isDone();

// -> Expecting incomplete future to be done
```

### isNotDone()

```java
assertThat(future).isNotDone();

// -> Expecting future with result:
//        <40>
//    not to be done

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    not to be done

// -> Expecting cancelled future not to be done
```

### isCompletedExceptionally()

```java
assertThat(future).isCompletedExceptionally();

// -> Expecting incomplete future to have completed exceptionally

// -> Expecting future with result:
//        <40>
//    to have completed exceptionally
```

### isNotCompletedExceptionally()

```java
assertThat(future).isNotCompletedExceptionally();

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to not have completed exceptionally

// -> Expecting cancelled future to not have completed exceptionally
```

### isCancelled()

```java
assertThat(future).isCancelled();

// -> Expecting incomplete future to be cancelled

// -> Expecting future with result:
//        <40>
//    to be cancelled

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be cancelled
```

### isNotCancelled()

```java
assertThat(future).isNotCancelled();

// -> Expecting cancelled future not to be cancelled
```

----

The following assertions do no map directly to `CompletableFuture` methods.

### isCompleted()

```java
assertThat(future).isCompleted();

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed
```

### isNotCompleted()

```java
assertThat(future).isNotCompleted();

// -> Expecting future with result:
//        <40>
//    to not be completed
```

### isCompletedWith(T expected)

```java
assertThat(future).isCompletedWith("result");

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed

// -> org.junit.ComparisonFailure: 
//     Expected :"result"
//     Actual   :"different result"
```

### isCompletedMatching(Predicate<? super T> predicate)

```java
assertThat(future).isCompletedMatching(result -> result < 40);

// -> Expecting incomplete future to be completed

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to be completed

// -> Expecting cancelled future to be completed

// -> Expecting:
//       <50>
//     to match given predicate.
```

### hasFailed()

```java
assertThat(future).hasFailed();

// -> Expecting incomplete future to have failed

// -> Expecting future with result:
//        <40>
//    to have failed

// -> Expecting cancelled future to have failed
```

### hasNotFailed()

```java
assertThat(future).hasNotFailed();

// -> Expecting future with exception:
//        <java.lang.RuntimeException: some random error>
//    to not have failed
```

### hasFailedWithThrowableThat()

```java
assertThat(future).hasFailedWithThrowableThat()
    .isInstanceOf(IllegalArgumentException.class)
    .hasMessage("something");

// -> Expecting incomplete future to have failed

// -> Expecting future with result:
//        <40>
//    to have failed

// -> Expecting cancelled future to have failed

// -> Expecting:
//        <java.lang.RuntimeException: some random error>
//    to be an instance of:
//        <java.lang.IllegalArgumentException>
//    but was instance of:
//        <java.lang.RuntimeException>
```

**Comment by Turbo87** [comment]
https://github.com/nurkiewicz/async-retry/blob/master/src/test/java/com/nurkiewicz/asyncretry/AsyncRetryJobTest.java#L97-L106 is an example of test code that could be simplified with the above proposal.

```java
		assertThat(future.isCompletedExceptionally()).isTrue();

		try {
			future.get();
			failBecauseExceptionWasNotThrown(ExecutionException.class);
		} catch (ExecutionException e) {
			final Throwable cause = e.getCause();
			assertThat(cause).isInstanceOf(SocketException.class);
			assertThat(cause).hasMessage(DON_T_PANIC);
		}
```

would be simplified to:


```java
		assertThat(future)
                    .hasFailedWith(SocketException.class)
                    .hasMessage(DON_T_PANIC);
```

**Comment by joel-costigliola** [comment]
Nice one ! Will review it in the next weeks.

**Comment by Turbo87** [comment]
@joel-costigliola can I help in some way to speed up the process?

**Comment by joel-costigliola** [comment]
one thing : I'm planning to improve the javadoc by reducing the space around code examples (see https://github.com/joel-costigliola/assertj-core/issues/438) - it means that code examples should be formatted differently as described in the mentioned issue. 
Can you do that for this PR ?

**Comment by Turbo87** [comment]
@joel-costigliola I could, but please have a look at my comment at https://github.com/joel-costigliola/assertj-guava/commit/841ee1b60df12a59b5e7528901a07e9d18c0f618 first. I'm not sure if this is such a good idea.

**Comment by Turbo87** [comment]
@joel-costigliola done

**Comment by joel-costigliola** [comment]
integrated, thx.
