### ISSUE TITLE
OptionalAssert.contains does not use the specified comparator

### ISSUE THREAD

**Issue by lucasweb78** [joel-costigliola/assertj-core#463]
The following does not work

```java
assertThat(Optional.of(new DummyObject(value))).usingComparator(new FieldByFieldComparator()).contains(new DummyObject(value));
```

Looking at OptionalAssert it appears the contains does not look to see if a comparator was specified and instead relies on the actual objects equals method (line 105):

```java
if (!actual.get().equals(expectedValue)) throw failure(shouldContain(actual, expectedValue));
```

**Comment by joel-costigliola** [comment]
The comparator is used on `actual` and `expected` object that would be `Optional` in your case not the values contained in optionals.

**Comment by lucasweb78** [comment]
I assumed it would work in a similar to way to collections where you can specify the comparator to use when comparing the actual contents of a list to the expected contents of the list.

**Comment by joel-costigliola** [comment]
In that case, it would have been `usingElementComparator` which compares collection elements but it is only defined for `Iterable/array` assertions.

The easy solution is to get your value and use the proper comparator:
```java
assertThat(opt.get()).usingFieldByFieldComparator().isEqualTo(new DummyObject(value));
```
we can add support for `usingElementComparator` and if you feel strongly about it, you can even contribute it ! ;-)

**Comment by lucasweb78** [comment]
My bad, I confused usingComparator with usingElementComparator. 

The approach you recommend above is a good work around but it would be nice to have the assertion return a useful error message if ```opt.get``` is empty instead of throwing a ```NoSuchElementException```. I could always do a ```ifPresent``` check as as a separate assert first but it would be nice to assert ''ifPresent``` and validate the value in a single statement.

I'll take a look at the code and see what needs to be done. One question, does it make sense to use the ```usingElementComparator``` syntax for Optional as it is consistent or given Optional as a value and not elements would ```usingValueComparator``` make more sense?

**Comment by joel-costigliola** [comment]
`usingValueComparator` would make more sense, I think it would be less confusing for people than `usingElementComparator`.

**Comment by joel-costigliola** [comment]
Integrated, thanks.
