### ISSUE TITLE
assertThat is ambiguous for generics in java 8

### ISSUE THREAD

**Issue by mgrebler** [joel-costigliola/assertj-core#469]
If the first argument of assertThat is a generic that cannot be inferred, compilation fails with: 

reference to assertThat is ambiguous 
both method assertThat (java.lang.CharSequence) in org.assertj.core.api.Assertions and method <T>assertThat(org.assertj.core.api.AssertProvider<T>) in org.assertj.core.api.Assertions match

The code snippet below demonstrates the error:

```java
package com.example.assertj;

import static org.assertj.core.api.Assertions.*;

import org.assertj.core.api.Assertions;
import org.junit.Test;

public class AssertjTest {

    public static <T> T returnGeneric() {
        return (T) new Object();
    }

    @Test
    public void failsToCompileWithJava8(){
        assertThat(returnGeneric()).isEqualTo("foo");
    }
}

```

This was done using assertj-core 3.1.0

Workaround is to explicitly cast. e.g.

```java
        assertThat((Object) returnGeneric()).isEqualTo("foo");
```

Is this something that can be fixed within assertj, or is there no way to avoid the explicit cast?

**Comment by joel-costigliola** [comment]
Can you give a try to `StrictAssertions` instead of `Assertions` ?

**Comment by mgrebler** [comment]
Same with StrictAssertions:

reference to assertThat is ambiguous
  both method assertThat(java.util.OptionalDouble) in org.assertj.core.api.StrictAssertions and method <T>assertThat(java.util.Optional<T>) in org.assertj.core.api.StrictAssertions match

**Comment by joel-costigliola** [comment]
I'm actually not sure this can be fixed, Java 8 is much stricter about generics.

This issue reminds me of https://github.com/joel-costigliola/assertj-core/issues/365 and http://stackoverflow.com/questions/29499847/ambiguous-method-in-java-8-why/29500086#29500086.

**Comment by joel-costigliola** [comment]
I'm closing this as I don't think there is a solution for that.
Feel free to prove me wrong and I'll gladly reopen this issue.
