### ISSUE TITLE
Iterable contains with String

### ISSUE THREAD

**Issue by drumonii** [joel-costigliola/assertj-core#471]
Been looking over the docs for a while on this but haven't found anything. Say I have a List of String:
```
List<String> strings = new ArrayList<>();
strings.add("I am a String");
strings.add("I am part of a List");
```
and I want to see if if the `List` of String contains a value:
```
assertThat(strings).contains("am");
```
But this will fail because `iterableContains()` of `StandardComparisonStrategy` uses the `areEqual` method which essentially uses the Object's `equals()`. Whereas a true String contains searches for a value in the String.
```
java.lang.AssertionError: 
Expecting:
 <["I am a String", "I am part of a List"]>
to contain:
 <["am"]>
but could not find:
 <["am"]>
```
So I'm not sure how to do a proper String contains check without calling the `toString` method after the `assertThat`.

**Comment by joel-costigliola** [comment]
That's normal, your assertion compares list elements with the given value (using `equals` method), it's a `List.contains` rather than  `String.contains`:
```java
// succeeds if strings list contains an element equals to "am"
assertThat(strings).contains("am");
```
What do you want to **exactly** ? checking that at least one of the String in strings contains "am" ?

**Comment by drumonii** [comment]
Ah right `List.contains`... thanks. But since the `List` has Strings, I thought perhaps the String's `contains` would be used instead. I misinterpreted the assertion. 
But yes, in my simple example, I want to check to see if each String in the `List` contains "am".

**Comment by joel-costigliola** [comment]
You can write a [Condition](http://joel-costigliola.github.io/assertj/assertj-core-conditions.html), and use `are` or `have` to check that it applies on all elements.

**Comment by drumonii** [comment]
Thanks have it working with a `Condition` in case someone else is wondering. 
```
       Condition<String> am = new Condition<String>() {
            private String am = "am";
            @Override
            public boolean matches(String value) {
                return value.contains(am);
            }
        };
        List<String> strings = new ArrayList<>();
        strings.add("I am a String");
        strings.add("I am part of a List");
        assertThat(strings).have(am);
```
But seems like a lot of effort to have a simple `contains` assertion check on a String. What you think?

**Comment by joel-costigliola** [comment]
That's where Hamcrest is better than AssertJ : it already has a bunch of matchers.

Otherwise if you use Java 8, there is special support for writing condition using `Predicate` : 
http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.0.0-condition-predicate-support

**Comment by drumonii** [comment]
The Java 8 support for writing a `Condition` with a `Predicate` is really nice. The equivalent to my last example would be:
```
assertThat(strings).have(new Condition<>(str -> str.contains("am"), "am"));
``` 
I'll go ahead and mark this as closed. Thanks!

**Comment by joel-costigliola** [comment]
:+1:
