### ISSUE TITLE
Question : How can I customize the error/success report ?

### ISSUE THREAD

**Issue by agoncal** [joel-costigliola/assertj-core#474]
Hi,

I'm trying to twist AssertJ so I can use its API for health check tooling. Basically, I want to check several technical components (JVM, filesystem, operating system, application server...) and at the end, report to the administrator, which components are ok or not. This is how it could look like : 

```
    assertThat(JVM.version()).as("Checking JVM Version").startsWith("1.7");
    assertThat(JVM.freeMemory()).as("Checking JVM Free Memory").isGreaterThan(1000);
```

I use SoftAssertions so I can execute all the tests and know which ones have failed. But I have several features I don't know how to implement : 

1) I need to know which tests have failed, but also, which tests have passed. For health check, you need to show the administrator all the tests, the ones that have failed but also the ones that have passed. Is there a way to do this ?
2) At the end, I need to "display" the report (success and failed tests) is a readable way to the administrator (XML + XSLT so I can get different formats such as HTML, XML and text). Is there a way to customize the output ?

I've started creating some custom asserts and custom SoftAssertions, but I'm a bit lost. 

Any ideas ?

Thanks

**Comment by joel-costigliola** [comment]
Hey Antonio,

Good to see you are trying AssertJ :)

You can override any error message with `overridingErrorMessage` and give a test description with `as(String description, Object... args)`, the test description appears before the error message between `[]`.

Example: 
```java
@Test
public void chained_soft_assertions_example() {
  String name = "Michael Jordan";
  SoftAssertions softly = new SoftAssertions();
  softly.assertThat(name)
        .as("checking start")
        .overridingErrorMessage("starts error")
        .startsWith("Mike");
  softly.assertThat(name)
        .as("checking content")
        .overridingErrorMessage("contains error")
        .contains("Lakers");
  softly.assertThat(name) // error message not overridden
        .as("checking end")
        .endsWith("Bolton");
  try {
    softly.assertAll();
  } catch (SoftAssertionError softAssertionError) {
    List<String> errors = softAssertionError.getErrors();
    System.out.println(errors);
  }
}
```` 
The errors looks like:
```
[[checking start] starts error, [checking content] contains error, [checking end] 
Expecting:
 <"Michael Jordan">
to end with:
 <"Bolton">
]
``` 

Trying to answer your questions : 
* you can find which tests have failed in the returned errors using test descriptions but you have to give "unique" test description
* you can't know from `SoftAssertionError` which tests have succeeded, just which the failing ones (if you follow the previous point)
* there is no XML error report but you can probably play with the returned errors to do whatever you want
* you can change the error message but you will loose assertj error message

AssertJ focuses on assertion but not on test suite reports, this is a concern left for JUnit or TestNG.

Hope it helps or at least clarify what is currently possible

Cheers

**Comment by agoncal** [comment]
Yes, I've realized that AssertJ is not about reporting but yes, about asserting (nice framework BTW ;o)

I'm actually hacking the JUnit APIs (e.g. org.junit.runner.notification.RunListener) so I can customize the report.
