### ISSUE TITLE
AbstractPathAssert should extend AbstractComparableAssert

### ISSUE THREAD

**Issue by david-bakin** [joel-costigliola/assertj-core#477]
`java.nio.file.Path` implements [`Comparable<Path>`](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#compareTo(java.nio.file.Path)) so ... `AbstractPathAssert` ought to extend `AbstractComparableAssert` to get `isEqualByComparingTo` etc.

**Comment by joel-costigliola** [comment]
good point !
