### ISSUE TITLE
Context-sensitive diff engine for unordered collections

### ISSUE THREAD

**Issue by cowwoc** [joel-costigliola/assertj-core#479]
It looks like we need to provide a different the DIFF engine for Maps than for normal text comparison. When invoking `assertThat(firstMap).isEqualTo(secondMap)` and the condition is false, the DIFF engine will highlight the wrong difference.

The map contents differ but instead of highlighting the actual difference, the DIFF engine seems to trip over the fact that the key iteration order is different between the two maps.

Meaning, given two HashMaps (where the key iteration order is undefined and not important):

```
A: {key1: value1, key2: value2}
B: {key2: value1, key1: value1}
```

I am expecting the DIFF engine to highlight the fact that `key2` is mapped to a different value. Instead, the DIFF engine highlights the fact that `A` starts with `key1` whereas `B` starts with `key2`.

In the meantime, is there a way to disable the DIFF engine for a specific `assertThat()` as a workaround?

**Comment by cowwoc** [comment]
I stand corrected. I was misreading the output. The DIFF is correct, but still kind of useful. It is flagging almost the entire String representation as a change. Given:

```
		Map<String, Integer> expected = ImmutableMap.<String, Integer>builder().
			put("a", 1).
			put("b", 2).
			build();
		Map<String, Integer> actual = ImmutableMap.<String, Integer>builder().
			put("b", 1).
			put("a", 1).
			build();
		assertThat(expected).isEqualTo(actual);
```

The output is:

```
expected:<{"[b"=1, "a"=1]}> but was:<{"[a"=1, "b"=2]}>
```

I am expecting either:
```
expected:<{"b"=[1], "a"=1]}> but was:<{"a"=1, "b"=[2]}>
```

or:

```
expected:<{"a"=1, "b"=[1]}> but was:<{"a"=1, "b"=[2]}>
```

Meaning, either retain the same ordering but highlight the value change, or reorder the keys and then run a simple text diff.

**Comment by joel-costigliola** [comment]
I haven't reproduced the problem ut I think it comes from JUnit not AssertJ ... under the hood AssertJ is returning  the AssertionError built using JUnit.
Try without AssertJ to see if you reproduce the behavior.

**Comment by cowwoc** [comment]
@joel-costigliola Who is constructing the diff message? JUnit or AssertJ? I was under the impression that JUnit does the comparison while AssertJ constructs the diff.

**Comment by joel-costigliola** [comment]
In case of assertion failure when using `isEqualTo`, AssertJ first tries to build a `ComparisonFailure` with JUnit if JUnit is available in the classpath, if not it just build the error itself - the code called for that is [newAssertionError](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/error/ShouldBeEqual.java#L106).

**Comment by cowwoc** [comment]
@joel-costigliola Just confirmed that the message in question is generated by AssertJ, not JUnit. The message is generated by `ShouldBeEqual.msgArgs()`.

**Comment by joel-costigliola** [comment]
The diff is done by JUnit, AssertJ format actual and expected and gives them to JUnit.
It turns out that AssertJ format the map exactly as Guava does in your example, AssertJ just format the map according to the map entrySet() order.

AssertJ could indeed do a smarter comparison by overriding `isEqualTo` and creating a `MapShouldBeEqual` error that would do the diff.

Want to try contributing that ?

**Comment by cowwoc** [comment]
Please excuse me, but I prefer to limit my contribution to "thinking out loud" for now. So here goes:

The easiest way to resolve this seems to be to sort the map keys prior to passing it to JUnit. Normally I wouldn't be in favor of reordering elements behind the user's back but in this case (unordered keys) it seems like the easiest and most readable solution.

So, first question: how do we detect whether the keys are ordered?

One thought that comes to mind is invoking `spliterator().characteristics()` and checking whether it contains `ORDERED`. If it does not, then we can sort the keys. Otherwise, we leave them as is.

Do you agree?

**Comment by joel-costigliola** [comment]
No problem if you don't want to contribute, I was suggesting that as it is a minor issues and I have plenty of priority work to do.

I would rather only show the difference, what was missing and what was not expected - like in `containsOnly` assertion.
`spliterator().characteristics()` can't be used for assertj-core 2.x since it does not rely on java 8.

**Comment by gabga** [comment]
Hi,
I am interested in doing this task. Since this would be my first contribution to an open source product, I may be annoying you with questions. So, please bear with me :)

**Comment by joel-costigliola** [comment]
@gabga don't worry, I will help :)

**Comment by gabga** [comment]
Hi,

First question: 

While reading the CONTRIBUTING.md I saw that you have a branch for each supported Java version. I guess that this improvement should be introduced in all of the three branches. Do you have any recommended approach to do this or should I do as I am pleased?

**Comment by joel-costigliola** [comment]
Good question, just focus on the 2.x branch as this java 7 compatible (I don't maintain actively the 1.x branch, I only do releases and let users introduce or backport feature through PR), then I usually merge the 2.x branch into master (version 3.x for java 8) et voila !

**Comment by gabga** [comment]
Hi,

I have now created a solution for map comparison (I am not quite finished yet) but some of the soft assertion tests are failing. 

I have solved the highlighting problem by modifying the string representation of the expected and actual (those are the ones printed out when the assert is failing) but it seems to mess up the JUnit error message for some reason. And soft assertions are simply collecting the JUnit error messages, which get completely wrong. 

E.g. the output with soft assertions is:

    org.assertj.core.api.SoftAssertionError: 
    The following assertion failed:
    1) expected:<{"[d"=3, "b"=2], "a"=1}> but was:<{"[b"=2, ["c"=3]], "a"=1}>

and with regular assertions it looks like:

    org.junit.ComparisonFailure: 
    Expected :{"d"=3, "b"=2, "a"=1}
    Actual   :{"b"=2, ["c"=3], "a"=1}

Any ideas what to do?

**Comment by joel-costigliola** [comment]
@gabga  can you create a PR so that I can review the code and help ? thanks

**Comment by gabga** [comment]
OK, I'll just clean up the code first.

**Comment by joel-costigliola** [comment]
Done, thanks @gabga !
