### ISSUE TITLE
assertHasBinaryContent only works for the default filesystem

### ISSUE THREAD

**Issue by openCage** [joel-costigliola/assertj-core#483]
assertHasBinaryContent uses path.toFile which only works on the default filesystem.
Files.readAllBytes works on all FileSystems

**Comment by joel-costigliola** [comment]
Already fixed in `Paths`, available in 2.2.0 released ... today :)
https://github.com/joel-costigliola/assertj-core/commit/cba1f870e41815fbf85497510d8744c1a3b6ef58#diff-3873c6cde4c1944bd8d80381846beca8

**Comment by openCage** [comment]
great
and 3.x?

**Comment by joel-costigliola** [comment]
in 3.2.0 which I will release in 2/3 weeks
