### ISSUE TITLE
Exctract on JSONObject

### ISSUE THREAD

**Issue by falkoner** [joel-costigliola/assertj-core#484]
Hi. 
As per https://github.com/joel-costigliola/assertj-core/issues/258 I should be able to extract values by keys in Map objects. 

I'm wondering now if I can do something with the same level of convenience with JSONObjects as well, since they behave to some extent in a very similar way.

Assuming I have following JSON Array of JSON Objects:
```
JSONArray symbolList;

// [{"symbol":"AAPL","companyName":"Apple Inc"},{"symbol":"AA","companyName":"Alcoa Inc."},{"symbol":"AAL","companyName":"American Airlines Group Inc."},{"symbol":"AAP","companyName":"Advance Auto Parts Inc."}]
```
I'd like to iterate (which AssertJ does) and verify extracting values by key name:
```
assertThat(symbolList).extracting("symbol").contains("AAPL");
```

Currently it results in following exception:
```
(org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'symbol'.
Error when introspecting fields was :
- No getter for property 'symbol' in org.json.simple.JSONObject 
Error when introspecting properties was :
- Unable to obtain the value of the field <'symbol'> from <{"symbol":"AAPL","companyName":"Apple Inc"}>)
```

Is there any way to make it work given the fact that getting the value is like that:
```
        JSONObject symbolObject = (JSONObject) symbolList.get(1);
        String symbol = (String) symbolObject.get("symbol");
        assertThat(symbol).contains("AAPL");
```

Note: I'm using com.googlecode.json-simple 1.1.1 now to work with JSON.

In general I would also reconsider decision on https://github.com/joel-costigliola/assertj-core/issues/75 What's currently recommended way/library to work with AssertJ and JSON objects?

**Comment by joel-costigliola** [comment]
there is one problem for that : assertj-core does not use any dependencies so it can't know JSONObjects.

You can try to use an [extractor](https://github.com/joel-costigliola/assertj-core/blob/c530ea5737586b8ffe04059ea7a04a8c12f79fa4/src/main/java/org/assertj/core/api/iterable/Extractor.java) (specially handy with java 8 lambdas) that implements the logic of extracting the data you need to check.

**Comment by falkoner** [comment]
Thanks, @joel-costigliola 
So just to confirm that I'm on the right path - I should use the ByMapKeyExtractor.java class as template, but use JSONObject instead of Map<K, V>, right? Here is the reference to this class: https://github.com/joel-costigliola/assertj-core/commit/2dcc837e841dafeb6da6902756e880c5971555dd

Do you have any recommended pattern to build out and organize a library like the one for https://github.com/joel-costigliola/assertj-core/issues/75 to keep all the extractors etc in place for json-simple object? I anticipate that I'll have to create quite a number of them eventually.

**Comment by joel-costigliola** [comment]
You are in the right track with `ByMapKeyExtractor`.

Regarding the JSON assertion module, follow what has been done for [assertj-guava](https://github.com/joel-costigliola/assertj-guava).

cheers

**Comment by joel-costigliola** [comment]
I'm closing this issue as it can't be solved in assertj-core.
Feel free to add comments if you need additional help.
