### ISSUE TITLE
Backport assertThatThrownBy() to v1.x for Android

### ISSUE THREAD

**Issue by Turbo87** [joel-costigliola/assertj-core#486]
I am currently working on some Android code and wanted to use `assertThatThrownBy()` but realized that it wasn't available. Is v1.x still a valid target to allow its use with Android code? Would it make sense to backport that feature?

**Comment by joel-costigliola** [comment]
yes 1.x is Android compatible but I'm not maintaining this branch actively, having said that I will release new versions for new contributions specific to this version.

**Comment by Turbo87** [comment]
okay. I might have a look at it when I have a bit of free time.

**Comment by joel-costigliola** [comment]
@Turbo87 do you reckon that #500 would make assertj 2.x android compatible ? 
In that case no need to backport anything ! Would be great.

**Comment by Turbo87** [comment]
oh, awesome, I didn't see that. if that really works I'm fine with closing this PR.

**Comment by joel-costigliola** [comment]
Is that something that you could test ? As I have never done Android app I don;t have an easy of testing that Assertj is Android compatible (moreover I'm pretty busy these days).

**Comment by Turbo87** [comment]
yeah, I think I could do that. in theory we just need to compile a jar file from the PR branch, use that in the android project and see if it runs properly. I'll get back to you once I've found the time to test it.

**Comment by joel-costigliola** [comment]
:+1:

**Comment by joel-costigliola** [comment]
should be addressed by https://github.com/joel-costigliola/assertj-core/pull/521
