### ISSUE TITLE
Cleanup branch names

### ISSUE THREAD

**Issue by Turbo87** [joel-costigliola/assertj-core#488]
It seems that there are currently three main branches, all with a different naming scheme:

- `1.7.1` for AssertJ v1.x (Java 6 and Android)
- `master` for AssertJ v2.x (Java 7)
- `java-8` for AssertJ v3.x (Java 8)

I would like to propose switching to a more consistent naming scheme:

- `v1.x` for AssertJ v1.x (Java 6 and Android)
- `v2.x` for AssertJ v2.x (Java 7)
- `master` for AssertJ v3.x and the current main development version (Java 8)

**Comment by joel-costigliola** [comment]
Yep, good idea, I will name them slightly differently 
- `1.x` for AssertJ v1.x (Java 6 and Android)
- `2.x` for AssertJ v2.x (Java 7)
- `master` for AssertJ v3.x and the current

**Comment by joel-costigliola** [comment]
done

**Comment by Turbo87** [comment]
:+1:
