### ISSUE TITLE
Provide hasToString Assertion

### ISSUE THREAD

**Issue by sadentc** [joel-costigliola/assertj-core#490]
#482 introduced the ability to verify equals and hashcoode, can we also get the ability to veriify the existence of toString method and verify its content?

**Comment by mkordas** [comment]
It's already implemented in #357.

**Comment by joel-costigliola** [comment]
Available in 2.1.0 and 3.1.0 : http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.1.0-hasToString

**Comment by sadentc** [comment]
excellent!!!
