### ISSUE TITLE
Question about assertj

### ISSUE THREAD

**Issue by eroyDivX** [joel-costigliola/assertj-core#494]
I just have a question about assertj, and I could not find where else to ask this. My apologies for posting this as an issue.

I am new to assertj, and I need to know if it is capable of launching a windows executable file for an application that is using Java 8 (swing). Can it launch the .exe for the application under test, or can it only launch a .jar?

Thank you
Erika

**Comment by joel-costigliola** [comment]
Hi Erika,
Not sure I understand the question but if your goal is to test a swing application you should have a lookt at Assertj Swing : http://joel-costigliola.github.io/assertj/assertj-swing.html

Hope it helps.

**Comment by eroyDivX** [comment]
Hi there,
Thank you for your reply. Sorry, I am a newbie!

Yes, my goal is to create automation tests for a swing application using
Eclipse IDE. However, I need to be able to automate launching of the
application itself which happens to be a windows desktop application. Is
that possible with Assertj Swing?


Thanks,
Erika

**Comment by joel-costigliola** [comment]
As I'm not the AssertJ Swing component leader, I don't know.
You should ask the question directly to assertj-swing team, just create an issue in https://github.com/joel-costigliola/assertj-swing.

I'm closing this one as it is not related to assertj-core.

Cheers
