### ISSUE TITLE
Add offset support to float/double arrays check methods

### ISSUE THREAD

**Issue by victor-zelinskiy** [joel-costigliola/assertj-core#505]
Please add offset support to float/double arrays check, like you did with one double value check, without this I can't contains check double arrays, I get errors like this:
java.lang.AssertionError: 
Expecting:
  <[7.199999999999999,
    3.5999999999999996,
    -12.0,
    30.599999999999998,
    0.30000000000000004]>
to contain exactly (and in same order):
  <[7.2, 3.6, -12.0, 30.6, 0.3]>

**Comment by joel-costigliola** [comment]
I'm ok with the idea but I have trouble finding a good API, i.e. how would you name the assertion ? 

This type of use case are nicely handled with an element comparator:
```java
@Test
public void comparing_array_of_real_numbers() {
  Comparator<Double> closeToComparator = new Comparator<Double>() {
    @Override
    public int compare(Double o1, Double o2) {
      return Math.abs(o1.doubleValue() - o2.doubleValue()) < 0.001 ? 0 : -1;
    }
  };
  assertThat(new double[] { 7.2, 3.6, -12.0 }).usingElementComparator(closeToComparator)
                                              .containsExactly(7.2000001, 3.5999999, -12.000001);
}
```

**Comment by zilidev** [comment]
Why not just keep current names but add overloaded versions with offset argument, it's a good practice to use offset wherever is a double comparison, for example starndart jUnit assert library even don't have methods to check double arrays without offset, they have only method org.junit.Assert.assertArrayEquals(double[] expecteds, double[] actuals, double delta)
I'd like to see somthing like this in your library. Btw thank you for AssertJ library, it is very useful.

**Comment by joel-costigliola** [comment]
fair enough, but won't be able to change assertions using varargs, will look like:
```java
assertThat(new double[] { 1.0, 2.0 }).containsExactly(new double[] { 0.999, 2.001 }, 0.001);
```

**Comment by nbogdan** [comment]
Hi, I've been trying to work on this. (it looked like good practice for a beginner). For containsExactly I've obtained:

```java
public S containsExactly(double[] values, double precision) {
    usingElementComparator(getComparatorWithPrecision(precision));
    arrays.assertContainsExactly(info, actual, values);
    return myself;
  }
```

But it seems to fail the tests with the actual array being seen as empty. Any suggestions?

**Comment by PascalSchumacher** [comment]
I think this issues should not be closed yet, because the requested offset support for float arrays is not implemented yet. What do you think?

**Comment by PascalSchumacher** [comment]
@joel-costigliola I will try to create a pull request for float arrays similar to you did for double arrays with a032e9d858f394089dd6460da1cbfd114fdef6ea

**Comment by joel-costigliola** [comment]
@PascalSchumacher that would be fantastic ! I still have to add a nice `toString()` method for double comparator but that's a minor thing.

**Comment by PascalSchumacher** [comment]
I already did most of the work required for the pull request, I should be able to finish it tomorrow.

It's great that 2.3.0 will be released in the near future. :)

**Comment by joel-costigliola** [comment]
:+1:  :smiley:
