### ISSUE TITLE
Add 'isNotEqualToIgnoringWhitespace' assertion

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#514]
There is `isEqualToIgnoringCase`/`isNotEqualToIgnoringCase` pair, but `isEqualToIgnoringWhitespace` doesn't have corresponding `isNotEqualToIgnoringWhitespace`. Missing assertion should be added.

**Comment by kryger** [comment]
What situation could this be useful in? Can you give an example of a pair of strings that are not equal ONLY if ignoring whitespace? This would imply that they are equal if whitespace *is* taken into account, and by definition trimming whitespace wouldn't change the outcome of the comparison.

**Comment by mkordas** [comment]
@kryger 
My understanding of this assertion is that it would pass if strings are not equal even if all whitespaces are removed.

Example:
```java
assertThat("word").isNotEqualTo("    word    \t\r\n"); // pass - strings contain the same word, but difference is in whitespace
assertThat("word").isNotEqualTo("    word    \t\r\n"); // fail - strings are the same if whitespaces are not taken into account
```
To sum up, this is just stronger version of `isNotEqualTo`. And IMO negative assertions should be as strong as possible, so it may be useful in some contexts.

**Comment by joel-costigliola** [comment]
if someone needs it, I'm ok to add it.

**Comment by joel-costigliola** [comment]
Integrated in 2.x and soonish in master.
