### ISSUE TITLE
Feature request: possibility to unextract value or chain assertions

### ISSUE THREAD

**Issue by cajar1988** [joel-costigliola/assertj-core#517]
Let's look at sample test code:
```
//given
PersonService personService = new PersonService();
//when
List<Person> persons = personService.fetchAll();
//then
assertThat(persons)
	.extracting(Person::getFirstName).isNotNull();
assertThat(persons)
	.extracting(Person::getLastName).isNotNull();
assertThat(persons)
	.extracting(Person::getAddress).isNotNull();
```
As you can see, I have three assertions: first name, last name and address should not be null. Due to API limitations `assertThat(...)` need to be repeated three times. It would be nice, if I could write something like that:
```
assertThat(persons)
	.extracting(Person::getFirstName).isNotNull()
	.extracting(Person::getLastName).isNotNull()
	.extracting(Person::getAddress).isNotNull();
``` 
Or even something like that:
```
assertThat(persons)
	.extracting(Person::getFirstName).isNotNull().unextract()
	.extracting(Person::getLastName).isNotNull().unextract()
	.extracting(Person::getAddress).isNotNull();
``` 

Another issue, is about chaining assertions with `or`, `and`, etc.
```
assertThat(persons)
	.extracting(Person::getFirstName).isNotNull().and()
	.extracting(Person::getLastName).isNotNull().and()
	.extracting(Person::getAddress).isNotNull();
``` 

These two topics are related, because both of them resolves my issue.
I'm not sure how the API should look like finally, also I'm not sure if I described it well enough, but I hope you get the point.

**Comment by joel-costigliola** [comment]
If I understand correctly, what you want is to check multiple things on each Person in the list, which can be done using `Condition` in a `are`/`have` assertion, something like
```java
assertThat(persons).are(personCondition)
```
example from assertj-example project:
```java
Condition<String> fairyTale = new Condition<String>(s -> s.startsWith("Once upon a time"), "a %s tale", "fairy");
String littleRedCap = "Once upon a time there was a dear little girl ...";
String cindirella = "Once upon a time there was a ...";
assertThat(asList(littleRedCap, cindirella)).are(fairyTale);
```

Also notice your assertion example always succeed because `extracting` returns a `List`
```java
// should probably use contains assertion instead of isNotNull
assertThat(persons)
    .extracting(Person::getFirstName).isNotNull();
```

Hope it helps

**Comment by joel-costigliola** [comment]
Closing the issue as "won't fix".
