### ISSUE TITLE
Feature request: single collection element assertions

### ISSUE THREAD

**Issue by fbiville** [joel-costigliola/assertj-core#518]
I often end up writing this kind of thing:

```java
Collection<MyItem> results = /*...*/;
assertThat(results).hasSize(1);
MyItem myItem = results.iterator.next();
assertThat(myItem)./* and then: MyItem assertions */;
```

This is verbose and alas too repetitive.
What would be nice (wouldn't there be type erasure):

```java
Collection<MyItem> results = /*...*/;
assertThat(results)
    .hasOnlyOneElement()
    ./* and then: MyItem assertions */;
```

Instead of waiting for generics reification that may or may not come to Java 9, there could be an API such as:

```java
Collection<MyItem> results = /*...*/;
assertThat(results)
    .hasOnlyOneElement(new TypeToken<MyItem>() {})
    ./* and then: MyItem assertions */;
```

More on TypeToken [here](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/reflect/TypeToken.html).

While this is far from being ideal, this brings a much nicer and more fluent API for such a common usecase.

WDYT?

**Comment by joel-costigliola** [comment]
Single element collection assertion would be a nice thing to have indeed !
Unfortunately I see two problems : 
* assertj-core does not have dependencies, thus guava is not available 
* even if Guava was available, I think it is too much work to get the unique element assertion started

Ideally I would have something like:
```java
Collection<String> results = /*...*/;
assertThat(results).uniqueElement().startsWith("foo");
```
Which is possible but can only return Object assertion, not very useful ... 

Other possible approaches 

What about these other approaches:

Option 1 : use a `Predicate`

```java
assertThat(jedis).hasOnlyOneElementMatching(jedi -> jedi.name.equals("Yo! da"), "check name");
// with default check description == given
assertThat(jedis).hasOnlyOneElementMatching(jedi -> jedi.name.equals("Yo! da"));
```
The first assertion fails with the following error message
```
Expecting:
  <Jedi[id=1, name='Yoda', age=800]>
to match "check name" predicate.
```
The second fails too with `given` replacing `"check name"` in the error message.

Option 2 : use a `Consumer` to let user use `assertThat` in the lambda

```java
assertThat(jedis).hasOnlyOneElementSatisfying(jedi ->  {
      assertThat(jedi.name).isEqualTo("Yoda");
      assertThat(jedi.age).isEqualTo(800);
    });
```
In that case no check description needed as we get the failed assertion error message (if any).

Option 3 : ship with both options ;-)

**Comment by fbiville** [comment]
Before answering in details, I TypeToken is just an example, I'm not suggesting AssertJ should depend on Guava ;-)
One can implement a similar utility.

**Comment by PascalSchumacher** [comment]
I think the first option is to limited.

The second option is more verbose, but gives access to the full power of assertjs assertions.

I think:
```java
List<Jedi> jedis = Arrays.asList(new Jedi("Yoda", "red"));
        
assertThat(jedis).hasOnlyOneElementSatisfying(jedi -> assertThat(jedi.getName()).startsWith("Y").endsWith("oda"));
```
is more readable that the current solution:
```java
List<Jedi> jedis = Arrays.asList(new Jedi("Yoda", "red"));

assertThat(jedis).hasSize(1);
assertThat(jedis.get(0).getName()).startsWith("Y").endsWith("oda");
```
Implementing this option for iterables and object arrays does not take much effort, but the effort is high if support for every type of primitive array is required.
