### ISSUE TITLE
Cannot resolve symbol 'Assertions'

### ISSUE THREAD

**Issue by theluxury** [joel-costigliola/assertj-core#520]
Installed via Maven, 

    import static org.assertj.core.api.*; 
works fine, but 

    import static org.assertj.core.api.Assertions.*; 
raises a Cannot resolve symbol 'Assertions' error. Using Java 1.8 with version 3.2.0

**Comment by joel-costigliola** [comment]
Just tested, it runs fine, can you provide a full test case ?

**Comment by theluxury** [comment]
What exactly do you mean test case?

**Comment by joel-costigliola** [comment]
A unit test to reproduce the problem along with the proper environment description.
it can be a simple maven project containing a single test.

**Comment by theluxury** [comment]
[Here](https://github.com/theluxury/epi-java) is the github repo for my project. The java class in question is Problem_5_4.java at https://github.com/theluxury/epi-java/blob/master/src/main/java/Problem_5_4.java. It doesn't actually have any methods form your api since 

    import static org.assertj.core.api.Assertions.*; 
raises the error. Please let me know if this is too much or not enough info.

**Comment by joel-costigliola** [comment]
what are you importing it if you don't use it ? 
my guess is your IDE compiler settings raise an error for unused import.

**Comment by theluxury** [comment]
Well I was tried using it but didn't since I couldn't import it, heh. I updated it with a version that has an

    assertThat("aaa").contains('a');
and am getting the error 

    Cannot resolve method assertThat(java.lang.String)

**Comment by joel-costigliola** [comment]
You don't use maven properly, one can't use test dependencies in `src/main/java`, either move your tests to `src/test/java` or get rid of `<scope>test</scope>` when declaring assertj dependency.
