### ISSUE TITLE
Provide feedback/contribute to Open Test Alliance Initiative

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#524]
I guess it would be good for assertj to provide feedback to the Open Test Alliance Initiative planed by JUnit.

See https://github.com/junit-team/junit-lambda/issues/12 and https://github.com/junit-team/junit-lambda/tree/master/open-test-alliance for details.

**Comment by joel-costigliola** [comment]
I have already been contacted by Sam Brannen and Johannes Link ;)

**Comment by PascalSchumacher** [comment]
I suspected this, but creating a issue is cheap and also notifies people watching the repo. :)

**Comment by joel-costigliola** [comment]
:+1:
