### ISSUE TITLE
ContainsSequence fails when given multiples of the same string

### ISSUE THREAD

**Issue by pmacklin** [joel-costigliola/assertj-core#544]
I was writing a unit test for some string joiner logic and came across this. If you try to test the same string present in multiple places in one sequence, the order checker logic is fooled.

Simple example:

```
final String delimiter = "-";
final String actual = "a,b,c";
assertThat(actual).containsSequence("a", delimiter, "b", delimiter, "c");
```

This will throw the following:
> java.lang.AssertionError: 
> Expecting:
>   <"a-b-c">
> to contain the following CharSequences in this order:
>   <["a", "-", "b", "-", "c"]>
> but <"-"> was found before <"b">

The problem is in `org.assertj.core.internal.Strings#assertContainsSequence`
```
      for (int i = 1; i < values.length; i++) {
        if (strActual.indexOf(values[i - 1].toString()) > strActual.indexOf(values[i].toString())) {
          throw failures.failure(info, shouldContainSequence(actual, values, i - 1, comparisonStrategy));
        }
      }
```

Where checking the second "-" results in the `indexOf("b")` returning 2 and `indexOf("-")` returning 1.

This is ultimately pretty minor, as it can be easily worked around for joiner-based logic with an exact `isEqualTo` assertion instead of the sequence assertion. However, it does seem like a deviation from the documented description for `containsSequence`, which makes no mention of duplicate strings in the values.

Anyways, love the project, great work! I hope to have some free time this week and maybe I'll come up with a patch.

**Comment by joel-costigliola** [comment]
A bug indeed, thanks for reporting this.

**Comment by joel-costigliola** [comment]
Fixed.
