### ISSUE TITLE
Assertion to check that a map contains all entries of another map

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#545]
I think it would be nice to have an Assertion to check that a map contains all entries of another map. What do you think?

**Comment by joel-costigliola** [comment]
I agree.

**Comment by PascalSchumacher** [comment]
added in https://github.com/joel-costigliola/assertj-core/commit/cb22c0e9bd94f6f872c8cfdc9c688e7cd0af0a88
