### ISSUE TITLE
Assertion equivalent of Guava ImmutableMap.of(K k1, V v1, K k2, V v2)... to check that map contains entries

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#546]
Of course there is already `public S contains(MapEntry<? extends K, ? extends V>... entries)`, but in my opinion `public S contains(K k1, V v1, K k2, V v2)` etc. would be even more convenient.

What do you think?

**Comment by joel-costigliola** [comment]
I'm not a big fan of having so many parameters but why not if you think it can be useful.

**Comment by PascalSchumacher** [comment]
Also the usage of this version would be less readable than the MapEntry one, so let's close this for now.
