### ISSUE TITLE
Add support for null values to BigDecimalComparator

### ISSUE THREAD

**Issue by sg-ad** [joel-costigliola/assertj-core#547]
Hi,

In a test, I have a need to verify the parameters passed to a mock.  Some of these parameters are BigDecimal values, but the parameter can be null.  Using an `ArgumentCaptor`, I can easily get the list of values that were passed.  If I want to verify the content, I'd like to use a `BigDecimalComparator`, but it doesn't tolerate `null` values.  For example, this fails with a `NullPointerException`:

```java
List<BigDecimal> values = new ArrayList<>();
values.add(BigDecimal.valueOf(1.0));
values.add(null);
values.add(null);
values.add(BigDecimal.valueOf(1.23));

assertThat(values)
	.usingElementComparator(new BigDecimalComparator())
	.containsExactly(BigDecimal.ONE, null, null, BigDecimal.valueOf(1.230));
```

While it's easy to wrap it into a `NullComparator` like this `Comparator.nullsFirst(new BigDecimalComparator))`, I think that a simple enhancement to the `BigDecimalComparator` would allow this case to be supported.  If you agree, I can submit a PR.

**Comment by joel-costigliola** [comment]
I agree :)

**Comment by joel-costigliola** [comment]
Fixed.
BTW you could have directly used `BigDecimalComparator.BIG_DECIMAL_COMPARATOR` instead of creating a new one.

**Comment by sg-ad** [comment]
Thanks!  (Sorry, I didn't get to submit a PR in time and that you had to do the work! :/ )
Happy New Year!

**Comment by joel-costigliola** [comment]
No problem, it was not lot of work
