### ISSUE TITLE
containsExactlyInAnyOrder

### ISSUE THREAD

**Issue by lpandzic** [joel-costigliola/assertj-core#572]
In IterableAssertions there is one feature I have found to be missing.
Assert that the Iterable contains exactly the given elements, but in any order. Best name I could find for this method is `containsExactlyInAnyOrder`.
For example:
```java
Object first = new Object();
Object second = new Object();
Object third = new Object();
List<?> objects = Stream.of(first, first, second, third).collect(Collectors.toList());
```
Usage example:
`assertThat(objects).containsExactlyInAnyOrder(first, second, third, first)`.

**Comment by joel-costigliola** [comment]
that's what `containsOnly` does :)

**Comment by lpandzic** [comment]
Yes, I don't want the second one to pass.
I need to assert over all the elements, including duplicates, but without order.

**Comment by joel-costigliola** [comment]
ok, I like the name, it's consistent with the other assertions.

**Comment by Sean-PAN2014** [comment]
It would be nicer to overload this method taking iterable as parameter.

**Comment by PascalSchumacher** [comment]
@Sean-PAN2014 No sure I understand you correctly, but you can use `containsExactlyInAnyOrder` to check iterables: http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractIterableAssert.html#containsExactlyInAnyOrder(ELEMENT...)

**Comment by filiphr** [comment]
@PascalSchumacher I think what @XinYang-Pan thought is to have the following:

```java
// an Iterable is used in the example but it would also work with an array
Iterable<Ring> elvesRings = newArrayList(vilya, nenya, narya, vilya);
Iterable<Ring> elvesRingsSomeMissing = newArrayList(vilya, nenya, narya);
Iterable<Ring> elvesRingsDifferentOrder = newArrayList(nenya, narya, vilya, vilya);

 // assertion will pass
 assertThat(elvesRings).containsExactlyInAnyOrder(elvesRingsDifferentOrder);

 // assertion will fail as vilya is contained twice in elvesRings.
 assertThat(elvesRings).containsExactlyInAnyOrder(elvesRingsSomeMissing);
```

Should I open a new issue for this one?

Btw. This is something that I would need as well

**Comment by XinYang-Pan** [comment]
@filiphr yeah, that's exactly what I mean.

**Comment by joel-costigliola** [comment]
@filiphr @XinYang-Pan https://github.com/joel-costigliola/assertj-core/issues/1009
