### ISSUE TITLE
2.3.0 DefaultToString does not work for Android

### ISSUE THREAD

**Issue by Bananeweizen** [joel-costigliola/assertj-core#579]
2.3.0 can be used with Android again, thanks to the new Java6Assertions entry point. However, after migration one of my tests still fails at runtime:

assertThat(myPojo).isEqualToComparingFieldByField(myReference);

        java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/Path;
        at org.assertj.core.presentation.DefaultToString.toStringOf(DefaultToString.java:49)

Looking at the DefaultToString implementation, we find an "instanceof Path", which does not work for Android testing due to the Path class not existing in the android.jar.

**Comment by joel-costigliola** [comment]
Thanks for reporting this - we don't have android tests to verify the actual compatibility.

**Comment by joel-costigliola** [comment]
I have removed the use of `Path` in `DefaultToString`, this fix is gonna be shipped in 3.3.0 and later on 2.4.0 - you might be interested in trying 3.3.0 (released soon) since it will contain `Java6Assertions`.

I'm closing the issue but feel free to reopen it or add a comment to ask it to be reopened.

**Comment by joel-costigliola** [comment]
If you want, I can cut a bugfix release (2.3.1) including this fix but I would like to be sure it properly addresses android compatibility, could you check that for me ? If you can, just build the current 2.x branch (a simple `mvn install` will do), if you don't have time that's ok, I'll just ship the fix in 2.4.0.

**Comment by Bananeweizen** [comment]
I'll try to check this evening after work.

**Comment by Bananeweizen** [comment]
Test results:

3.3.0 does not work with Android for me. The Android dx tool complains about wrong magic packets during compilations. Sounds reasonable, as it only understands Java 7 bytecode (AFAIK), and AssertJ 3.x is probably compiled using Java 8. I've not investigated further if something can be done here, as I'm also not fully into all the details of the Android tooling.

2.3.1-SNAPSHOT works well for me and fixes the original problem. Thanks.
