### ISSUE TITLE
Add a way to use Comparator for certain type fields for AbstractObjectAssert.isEqualToComparingOnlyGivenFields();

### ISSUE THREAD

**Issue by cornerpocket407** [joel-costigliola/assertj-core#585]
Currently when calling:
```
assertThat(actual).isEqualToComparingFieldByField(expected)
```

There's no way of using certain Comparators for certain datatype fields. For example, for BigDecimal fields, I'd like set the precision and scale.

**Comment by joel-costigliola** [comment]
For the time being, the way to go is to use your own `Comparator` (on actual).

I know comparing certain type is a problem and people  want to register a specific comparator but I haven't found a nice API to introduce it, any ideas welcome !

**Comment by PascalSchumacher** [comment]
Well it's hardly innovative, but what about adding something like `usingComparatorForFieldsOfType(Comparator, Class)` to `AbstractObjectAssert`, that would allow:

```java
assertThat(john).usingComparatorForFieldsOfType(comperator, BigDecimal.class).isEqualToComparingFieldByField(mark);
```
I guess you would mostly use this for `float/double/BigDecimal`. AssertJ already has `ComparatorFactory#doubleComparatorWithPrecision` and `ComparatorFactory#floatComparatorWithPrecision` maybe there should also be `ComparatorFactory#bigDecimalWithPrecision`?

Another idea would be to also add `usingOffsetForFieldsOfType(Comparator, Class)` to `AbstractObjectAssert`, that would allow:

```java
assertThat(john).usingOffsetForFieldsOfType(withPrecision(0.5), Double.class).isEqualToComparingFieldByField(mark));
```

**Comment by joel-costigliola** [comment]
I have had a similar idea but I'm not fond of it for two reasons : 
- it does not deal with two different attributes of the same type requiring to be compared with different precisions
- it's a little bit heavy (to my taste at least)

I would rather do something like:
```java
FieldComparator heightComparator =  new FieldComparator("height", withPrecision(0.5));
FieldComparator weightComparator =  new FieldComparator("weight", withPrecision(0.1));
```

```java
// isEqualToComparingFieldByField(Object expected, FieldComparator... fieldComparators);
assertThat(john).isEqualToComparingFieldByField(mark, heightComparator, weightComparator);
```
or

```java
assertThat(john).usingFieldComparators(heightComparator, weightComparator)
                .isEqualToComparingFieldByField(mark);
```

**Comment by PascalSchumacher** [comment]
Hi Joel,

not sure what you mean by heavy? Care to explain further?

I guess `comparingFieldByField` is mostly used if there are are a lot of fields to compare, so I think it's best not to require spelling out every field.

As `withPrecision` returns an `Offset` it's limited to numbers, I think using a `Comparator` would make this more generally useful.

Cheers,
Pascal

**Comment by cornerpocket407** [comment]
@joel-costigliola I feel the field name fits more inside ```assertThat()``` fluent API rather than outside in the comparator.

I like @PascalSchumacher's proposal. And perhaps for more granular control, something along the lines of (don't focus too much on method naming):
```
assertThat(john).usingComparatorForField(comparator1, "height").usingComparatorForField(comparator2, "weight").isEqualToComparingFieldByField(mark);
```

**Comment by joel-costigliola** [comment]
@PascalSchumacher `usingOffsetForFieldsOfType` seems "heavy" to me but that's only my opinion.

I quite like @cornerpocket407 proposal, I would slightly modify it to:

```java
assertThat(john).usingComparatorForField("height", comparator1)
                .usingComparatorForField("weight", comparator2)
                .isEqualToComparingFieldByField(mark);
```
the only downside is the repetition of `usingComparatorForField` that was avoided with `usingFieldComparators`

**Comment by cornerpocket407** [comment]
@joel-costigliola What about having the method you mentioned right above as well as  also:
```
assertThat(john).usingComparatorForFields("height", "weight", comparator1)
```

for cases where the same comparator should be used?

**Comment by joel-costigliola** [comment]
@cornerpocket407 it would better to invert the parameters to be able to use varargs for fields but it makes the code a little bit less readable.

**Comment by cornerpocket407** [comment]
Agreed (can vargs even be in the first param?). So you like the idea of the two methods?

**Comment by joel-costigliola** [comment]
No varargs needs to be the last parameter.

I like this one, not sure which other you are talking about:
```java
assertThat(john).usingComparatorForFields(comparator, "height", "weight")
                .isEqualToComparingFieldByField(mark);
```

As @PascalSchumacher mentioned, we might also provide a comparator per type to avoid listing all the fields, something like 
```java
assertThat(john).usingComparatorForType(Double, doubleComparator)
                .isEqualToComparingFieldByField(mark);
```
A field comparator would take precedence over a type one.

**Comment by PascalSchumacher** [comment]
Something like:
```java
assertThat(john).usingComparatorForType(Double.class, doubleComparator).isEqualToComparingFieldByField(mark);
```

was also requested/suggested in https://github.com/joel-costigliola/assertj-core/issues/198

**Comment by PascalSchumacher** [comment]
BTW I have started to work on a pull request for the `usingComparatorForFields` part.

**Comment by DevDik** [comment]
Is there a way possible where we can compare some fields but not all of the two objects using isEqualToComparingFieldByField ()

**Comment by PascalSchumacher** [comment]
@DevDik You can use `isEqualToIgnoringGivenFields` or `isEqualToComparingOnlyGivenFields` see:
http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractObjectAssert.html#isEqualToIgnoringGivenFields(java.lang.Object,%20java.lang.String...) 
http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractObjectAssert.html#isEqualToIgnoringGivenFields(java.lang.Object,%20java.lang.String...)

**Comment by DevDik** [comment]
@PascalSchumacher Thanks for the answer. But is there also a way of comparing two different objects where name of 1 field is different in both, or one Object has an extra parameter.

**Comment by joel-costigliola** [comment]
No, how AssertJ would know how to compare field 1 in object A with field 2 in object B ?

**Comment by filiphr** [comment]
@DevDik if you would like to compare different objects I would suggest to have a look at https://github.com/mapstruct/mapstruct which can help you map one object to another and then use the same object for assertions with AssertJ
