### ISSUE TITLE
Export *.internal and *.util packages for ability to create custom assertions in a OSGi environment

### ISSUE THREAD

**Issue by aaschmid** [joel-costigliola/assertj-core#588]
Hi @joel-costigliola,

thanks for this great assertion framework. I would like to create custom assertions in an OSGi environment and reuse e.g. ```org.assertj.core.internal.Iterables```. Unfortunately, this package is marked as private, see 

```
Private-Package: org.assertj.core.internal,org.assertj.core.util
```

Can you change this or is there a reason against it?

**Comment by joel-costigliola** [comment]
Which version are you using ? In  2.3.0 and 3.3.0, I changed the pom.xml to export everything, cf 

```xml
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>2.5.3</version>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Export-Package>
              org.assertj.core.*
            </Export-Package>
            <Bundle-RequiredExecutionEnvironment>JavaSE-1.8</Bundle-RequiredExecutionEnvironment>
            <_removeheaders>Bnd-LastModified</_removeheaders>
          </instructions>
        </configuration>
      </plugin>
```

I surprised to see see private packages in the generated manifest :( I don't know where if I misconfigured the `maven-bundle-plugin` or if it's a bug.

On the principle, I don't  have any reason against exposing everything but be aware that internal classes may change (I try not to but if needed I'll do it).

**Comment by aaschmid** [comment]
Hi @joel-costigliola, that was quick, great. Currently we are using 2.2.0 (java 7) but are very flexible about the version :-)
And I am fine with the changes at least in ```*.internal``` packages. If this would harm something, we can at least stick with the old version some days until time for the upgrade is ...

Do you have a clue when you are able to release the next version?

**Comment by PascalSchumacher** [comment]
@aaschmid Can you give 2.3.0 a try? It's already released and `org.assertj.core.internal` should be exported (as far as I understand): https://github.com/joel-costigliola/assertj-core/commit/b45abcbdfe4cffb99f4f0812d8f7a09b056c5e35

**Comment by aaschmid** [comment]
@joel-costigliola Oh sorry, so I got your answer wrong.
@PascalSchumacher thanks for the hint
And sorry for not trying the newest version before opening this issue!

**Comment by joel-costigliola** [comment]
@aaschmid  No pb.
