### ISSUE TITLE
Add an assertion to check that list has at least/at most 'x' elements

### ISSUE THREAD

**Issue by vanta** [joel-costigliola/assertj-core#589]
Currently there is only a method to check concrete size of collection. It would be helpful to be able to assert for minimal/maximal size of list that one is interested in.

**Comment by joel-costigliola** [comment]
I would just get the size of the collection and use `isBetween` assertion, WDYT ?

**Comment by vanta** [comment]
Of course, it can be done this way, but with such approach hasSize() method
so it's not needed :) I always though that assertJ goal is to simplify
devs' lifes by allowing to assert in method chainging.

On Wed, Jan 20, 2016 at 7:17 AM, Joel Costigliola <notifications@github.com>
wrote:

> I would just get the size of the collection and use isBetween assertion,
> WDYT ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joel-costigliola/assertj-core/issues/589#issuecomment-173107237>
> .
>



-- 
Krzysztof Wolny

**Comment by joel-costigliola** [comment]
ok, would you be happy with `hasSizeBetween()` ? :)

**Comment by vanta** [comment]
I would :)

On Wed, Jan 20, 2016 at 8:58 AM, Joel Costigliola <notifications@github.com>
wrote:

> ok, would you be happy with hasSizeBetween() ? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joel-costigliola/assertj-core/issues/589#issuecomment-173122395>
> .
>



-- 
Krzysztof Wolny

**Comment by joel-costigliola** [comment]
Fixed with #301.
