### ISSUE TITLE
SoftProxies package access hinders custom collectors

### ISSUE THREAD

**Issue by MWFNexient** [joel-costigliola/assertj-core#598]
Wrote a custom SoftAssertion collector, but hit a snag while trying to access the `proxies` field inherited from AbstractStandardSoftAssertions and AbstractSoftAssertions. The field is protected, but SoftProxies's methods are package-private, meaning any custom collectors either need to have the same package (org.assertj.core.api) or use reflection to access either errorsCollected() or the collector field.

I don't know if this if this clashes with #339 or not.

**Comment by joel-costigliola** [comment]
I can make these methods protected but I'm not guaranteeing backward compatibility on them although this part of the code is pretty stable.

**Comment by MWFNexient** [comment]
After thinking about it, what would need to happen would be the methods being public. SoftProxies can be final, because we only need to extend AbstractStandardSoftAssertions which contains the proxies field. However, SoftProxies is package-private itself, so the class would need to be public without package spoofing.

An alternative would be to add to AbstractStandardSoftAssertions a protected method that returns a List<Throwable> of proxies.errorsCollected(), which only adds a protected access point, rather than alter SoftProxies.

**Comment by joel-costigliola** [comment]
I tend to prefer the second solution as it exposes less of the internal of soft assertions but if you need `SoftProxies` and `errorsCollected` to be public, I can live with that.

I'll fix this issue with the second solution unless you prefer the other option or want to do a contribution ;-)

**Comment by MWFNexient** [comment]
For what I'm working on, I just need the List<Throwable> ^^ And I'd be happy to do the leg work. I'll fork and do a pull request.

**Comment by MWFNexient** [comment]
I have to be honest. I don't know where exactly I should put tests for these.

**Comment by joel-costigliola** [comment]
I would write a dummy custom SoftAssertion collector from an "external" package to check that it is now possible to do so but feel free to ignore me if you find it too much work (as long as nothing was broken with the changes, I'm happy with it).

**Comment by MWFNexient** [comment]
Read ya. As soon as my VPN stops being foolish (it's blocking google.com of all things!) I can work on that.

**Comment by joel-costigliola** [comment]
Integrated, thanks
