### ISSUE TITLE
instanceOf assertion does not work properly with java.util.Iterator

### ISSUE THREAD

**Issue by Blahord** [joel-costigliola/assertj-core#603]
I was testing the concrete class of an java.util.Iterator by
```
java.util.Iterator<Integer> javaIterator = asJavaUtilIterator(list.iterator());
assertThat(javaIterator).isInstanceOf(ReducibleJavaIterator.class);
```
But that test fails with:

```
java.lang.AssertionError: 
Expecting:
 <[1, 2, 3, 4, 5, 6]>
to be an instance of:
 <com.github.blahord.betterrcollections.compatibility.ReducibleJavaIterator>
but was instance of:
 <org.assertj.core.api.IterableAssert.LazyIteratorToIterableWrapper>
```
even `javaIterator` is an instance of the class `ReducibleJavaIterator` as the Debugger tells me.

Screenshot:
http://s11.postimg.org/3ms9kz8rn/Screenshot_20160130_125326.png

**Comment by Blahord** [comment]
Can by workarounden with:
```
assertThat(javaIterator.getClass()).isEqualTo(ReducibleJavaIterator.class);
```

**Comment by Blahord** [comment]
Example test:
```
public void testIteratorInstanceOf() throws Exception {

    class MyIterator implements java.util.Iterator<Integer> {
        @Override
        public boolean hasNext() {
            return false;
        }

        @Override
        public Integer next() {
            throw new java.util.NoSuchElementException();
        }
    }

    assertThat(new MyIterator()).isInstanceOf(MyIterator.class);
}
```

**Comment by joel-costigliola** [comment]
The thing is that we wrap the given iterator in a lazy one (`LazyIteratorToIterableWrapper`) to avoid consuming it when the assertions does not need to do so, so what you pass to `actual(Iterator)` is transformed thus the error.

Your workaround is the right way to test the class.

We should mention the sneaky behavior of `actual(Iterator)` in the javadoc as the beahviour you experienced is "by design".

Sorry for the lack of documentation

**Comment by Blahord** [comment]
The workaround has a problem: I can only check for the exact class, not for any superclass.
For Lists and Sets i can do 'assertThat(list).isInstanceOf(MyList.class)' So i feels unnatural, if i can't do that for Iterators. Is there a technical reason, why on Iterators it behaves different?

**Comment by joel-costigliola** [comment]
As (badly ?) explained before, the technical reason is a design choice to avoid consuming the given iterator when not needed.

**Comment by joel-costigliola** [comment]
you can use this assertion in the meantime:

```java
assertThat(javaIterator instanceof ReducibleJavaIterator.class).isTrue();
```

**Comment by joel-costigliola** [comment]
Fixed along with all related `instanceOf` assertions
