### ISSUE TITLE
Should the java-8 branch be deleted?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#608]
As master is now java-8, the presence of a java-8 branch can confuse people e.g. a recent pull-request (https://github.com/joel-costigliola/assertj-core/pull/605) was created for the java-8 branch. Therefore I believe it's better to delete this branch.

What do you think?

**Comment by joel-costigliola** [comment]
You're right, I will delete it

**Comment by joel-costigliola** [comment]
done

**Comment by PascalSchumacher** [comment]
Thanks!
