### ISSUE TITLE
Optional hasValue assertion error should display actual values

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#609]

**Comment by pivovarit** [comment]
Is this issue about getting rid of "Optional[]" content wrapping or about more general case of generating a human readable string representations of objects?

**Comment by joel-costigliola** [comment]
I remember having a problem at work with the assertion error message not showing the actual value but I can't reproduce it ... mmmh.

I'll double monday at work but on my computer everything is fine.

sorry for having wasting your  time :(

**Comment by pivovarit** [comment]
Well, this code is actually useful anyway. I will provide some additional test to show it

**Comment by pivovarit** [comment]
`"%nExpecting %s to contain a value but was empty."`

Is this the case you were referring to?

**Comment by joel-costigliola** [comment]
No, the optional being empty there is no value to display. 

Your PR makes the error message confusing IMO, the message will look like : 
`Expecting 20 to contain 10` which does not make sense as 20 is not a value container.

Why do you think it is useful, I might miss something there.

**Comment by pivovarit** [comment]
Well, obviously you are right, I would need to revert to previous state, but I was referring to situations where you are testing contents of an Optional for some value and an optional instance is empty.

`String errorMessage = shouldContain(Optional.empty(), 10).create();`

It produces a message:

`Expecting:
  <Optional.empty>
to contain:
  <10>
but did not."`

but... we already have a defined message for an empty Optional case! So why not make it like:
`Expecting Optional to contain:
  <10>
but was empty."`

If you think it's fine I can prepare a separate PR containing only that change

**Comment by joel-costigliola** [comment]
I like your suggestion, a separate PR would be nice indeed.
Thanks !

**Comment by pivovarit** [comment]
I will prepare it in a few minutes :)

**Comment by joel-costigliola** [comment]
:+1:

**Comment by pivovarit** [comment]
Do you want a separate test case for an every type of Optional?

**Comment by joel-costigliola** [comment]
yes.

**Comment by pivovarit** [comment]
I'm on it!

**Comment by pivovarit** [comment]
#629 here it is :) if you find the case illustrating this issue, let me know

**Comment by joel-costigliola** [comment]
Closing as I can't remember :( or reproduce the issue.
