### ISSUE TITLE
"isEqualToComparingFieldByField" doesn't perform deep comparison

### ISSUE THREAD

**Issue by xp-vit** [joel-costigliola/assertj-core#612]
In case if object under assert has some complex types as fields (POJOs) and POJO field is equal, but is different instance "AssertionError" is generated. I Think we need to implement "isEqualToComparingDeepFieldByField" assertion method and compare fields recursively.

**Comment by PascalSchumacher** [comment]
Thanks for reporting, there is already a issue for this: https://github.com/joel-costigliola/assertj-core/issues/178

Sadly a really satisfying implementation of this is not easy. :(

**Comment by xp-vit** [comment]
Yes, I understand that it's complicated task and I see that you already started some implementation.
https://github.com/PascalSchumacher/assertj-core/commit/ed99b5d45610b6952dafb9cf6c353beabb30fe9a
Is there any particular problems you faced? Is there anything I can do to help finishing this feature?

**Comment by PascalSchumacher** [comment]
There is a bit of discussion of the problems of https://github.com/PascalSchumacher/assertj-core/commit/ed99b5d45610b6952dafb9cf6c353beabb30fe9a in the pull request https://github.com/joel-costigliola/assertj-core/pull/515.

The main problem was, that I did not see how make the pull request support all the features users expect of assertj:

- display the path to the difference
- comparison using properties (not only fields)
- ...

Any ideas how to solve this would be great. If you come up with a completely different solution that would also be great. :)

**Comment by xp-vit** [comment]
Can you please provide your definition of property?

**Comment by PascalSchumacher** [comment]
A public method called `getX`/`isX` which returns a value.

**Comment by xp-vit** [comment]
Does this mean that there is possibility that there is no corresponding field X in class for `getX/isX`?

**Comment by PascalSchumacher** [comment]
@xp-vit Sorry, I was wrong. There needs to be a corresponding field X.

Because this:

```java 
@Test
public void test() {
    assertThat(new Person()).isEqualToComparingFieldByField(new Person());
}

public static class Person {
    
    public String getId() {
        return UUID.randomUUID().toString();
    }
}
```
succeeds, but this fails:
```java 
@Test
public void test() {
    assertThat(new Person()).isEqualToComparingFieldByField(new Person());
}

public static class Person {
    
    private String id;
    
    public String getId() {
        return UUID.randomUUID().toString();
    }
}
```

**Comment by xp-vit** [comment]
So, from my perspective we need to test (compare) only fields, ignoring getters.

Algorithm should be following:
1. iterate through fields and check if field has equals overridden:
2a. TRUE: check using "equals" method.
2b. FALSE: go to point #1.

What do you think?

**Comment by PascalSchumacher** [comment]
That was what my pull request was doing as far as I remember.

As @joel-costigliola said in the comments the getter should be tried first e.g. by using  `org.assertj.core.util.introspection.PropertyOrFieldSupport#getSimpleValue`

Also the current "path" should to be stored to display a good error message if there is a difference. A further requirement is to make the algorithm terminate even if there is a bi-directional relationship (circle) between objects.

**Comment by PascalSchumacher** [comment]
@xp-vit Thanks for reminding me of this. :)

I took another look at https://github.com/joel-costigliola/assertj-core/pull/515 and have started to extend it. I believe I might be able to make it fulfill all requirements, but of course this will take time.

**Comment by PascalSchumacher** [comment]
I believe I have now solved the problems of #515, but of course there is still a lot of polishing left to do.

**Comment by xp-vit** [comment]
@PascalSchumacher  Please push your code to github and I will be able to help you testing and writing unit tests.

**Comment by PascalSchumacher** [comment]
@xp-vit I pushed the changes to  #515, but the code is still really unfinished and volatile (a mess).

**Comment by PascalSchumacher** [comment]
@xp-vit I submitted a cleaned-up and rebased version of #515 as #615

**Comment by joel-costigliola** [comment]
Done
