### ISSUE TITLE
Add .within(timeSpan) feature

### ISSUE THREAD

**Issue by slobokot** [joel-costigliola/assertj-core#614]
I would like to have assertion like
assertThat(file).within(30, SECONDS).exists()

The assertion should succeed as soon as file appears on disk. Or fail if file hasn't been created during 30 sec.

This may sound fragile, but it would greatly help in dealing with legacy code where there is no option to change production code.

**Comment by szpak** [comment]
Long time ago I wanted to add it to (then) FEST-Assert, even did it (FEST-475), but it was a maintenance hell. Some time later, when Java 8 arrived I implemented AssertJ support in Awaitility, which makes it trivial to use:

```
await().until(() -> assertThat(file).exists());
```

See my [blog post](https://solidsoft.wordpress.com/2014/04/29/using-assertj-and-awaitility-together-thanks-to-java-8-and-lambdas/) for more details. IMHO there is no need to add that feature to AssertJ itself.

**Comment by slobokot** [comment]
Awaitility solves the issue.
