### ISSUE TITLE
Javadoc has no "since" tags

### ISSUE THREAD

**Issue by bannmann-incub8** [joel-costigliola/assertj-core#635]
A google search led me to [containsExactlyInAnyOrder](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractIterableAssert.html#containsExactlyInAnyOrder%28T...%29) and I used it in my project, which uses AssertJ 2.3.0.

However, my compiler told me later that this method doesn't exist. I found out that it was only added in version 2.4.0.

Please, please add "since" Javadoc tags (at least) for new methods, so people have a chance to find out which features they can use and which not.

**Comment by joel-costigliola** [comment]
You are right but I also think that people should use the latest versions as they usually are backward compatible ( what the benefit of using an old version ?) if they do `since` tag have less value.

**Comment by bannmann-incub8** [comment]
Right, people should always use the latest versions. However, you can't always change your dependency freely, and you certainly don't do it every day:

- When I encountered this issue, the new version was two days old. The AssertJ dependency is defined in our corporate framework and as a policy to avoid clutter, we usually don't change inherited dependencies in product that use it. So using new AssertJ would have meant creating a new framework release and switching the product to use it, which was out of the scope of the task I was working on.

Anyway, even without dramatic problems or elaborate explanations, having "since" tags is just good practice inside the Java ecosystem.

**Comment by PascalSchumacher** [comment]
I guess this can be closed, as we added `@since` tags for the 2.5.0/3.5.0 releases.

**Comment by PascalSchumacher** [comment]
@joel-costigliola Please close this issue. Thanks!

**Comment by joel-costigliola** [comment]
Thanks for the ~~kick in the butt~~ gentle reminder :)
