### ISSUE TITLE
Better support comparing lists / iterable objects

### ISSUE THREAD

**Issue by sta-szek** [joel-costigliola/assertj-core#636]
There is new feature in 3.4.0 version:
`assertThat(...).isEqualToComparingFieldByFieldRecursively(...)`

but comparing lists is still poor, because we have to use equals(...) method when comparing two objects - it is used by default?

We would like to have methods like:

```
assertThat(<some iterable>).containsExactlyElementsOf(<some iterable>) - already provided.
assertThat(<some iterable>).containsExactlyElementsOfComparingFieldByField(<some iterable>) - really missing
assertThat(<some iterable>).containsExactlyElementsOfComparingFieldByFieldRecursively(<some iterable>) - missing too 
```

As suggested by @PascalSchumacher we can use:
```
assertThat((Object) Arrays.asList("a", "c")).isEqualToComparingFieldByFieldRecursively(Arrays.asList("a", "c"));
assertThat((Object) Arrays.asList("a", "c")).isEqualToComparingFieldByField(Arrays.asList("a", "c"));
```

But this approach works only for identical Lists - internal state of lists such as private fields other than compared objects will be compared too.

**Comment by PascalSchumacher** [comment]
Just noticed that a field by field comparison of elements can already be done like this:

```java
  public static class Bean {
    int i;
    
    public Bean(int i) {
      this.i = i;
    }
  }
  
  @Test
  public void test() {
    assertThat(Arrays.asList(new Bean(1), new Bean(2))).usingFieldByFieldElementComparator().containsExactly(new Bean(1), new Bean(2));
  }
```

so we are just missing a `usingFieldByFieldElementRecursivelyComparator()` method.

**Comment by PascalSchumacher** [comment]
@sta-szek I can give implementing the `usingFieldByFieldElementRecursivelyComparator()` method a try, or would you like to do it?

**Comment by sta-szek** [comment]
If you don't mind I can give a try :)

**Comment by PascalSchumacher** [comment]
You a welcome to give it a try. :)

The feature should added to `AbstractObjectArrayAssert` as well as to `AbstractIterableAssert` I think.

If you any questions @joel-costigliola and I are there to help. :)

**Comment by joel-costigliola** [comment]
@sta-szek you're welcome to contribute :)
I would simply rename the method to `usingRecursiveFieldByFieldElementComparator`

**Comment by PascalSchumacher** [comment]
@sta-szek Are you still working on this? If you are not I could give it a try.

**Comment by sta-szek** [comment]
Ok, sorry for the confusion, but currently I am working on another tester-library, so I don't have time for this right now.
It would be nice If you could implement this solution.
Next time I'll try to help you :)

PS the eclipse formatter is really poor (I use IntelliJ, which has much more options) and when I import eclipse formatter, intellij overrides some options, but the rest is unmodified, so importing eclipse formatter to intellij is not good solution.
There is eclipse formatter plugin for intellij, but if you use it you lost a lot of helpful formatting options, which I think, should be used in every project.

My recommendation is to use intellij instead of eclipse, but of course I dont push you :smiley:
