### ISSUE TITLE
Use default Float and Double comparators for field by field comparison in #usingFieldByFieldElementComparator?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#637]
Related to: https://github.com/joel-costigliola/assertj-core/commit/d251f2c22ee6aecfb1cf9d81066e0247dc34e47b

I guess `usingFieldByFieldElementComparator` should also use the default comparators instead of comparing exact values?

What do you think?

**Comment by joel-costigliola** [comment]
I haven't done that because of potential breaking changes for code relying in the current behaviour but we might reconsider this to make the different comparisons consistent.

**Comment by PascalSchumacher** [comment]
@joel-costigliola Just as I wanted to ask about this, I see that you added it to the `2.9.0` milestone two days ago.  😄 👍

**Comment by joel-costigliola** [comment]
Done in 65c3487a0aa8ff83f25d4c84084c4e67a03f1922

**Comment by PascalSchumacher** [comment]
Thanks! 😃
