### ISSUE TITLE
add a NavigationListAssert<T,EA> extends ListAssert<T> for easier navigation through generated Assert models

### ISSUE THREAD

**Issue by jstrachan** [joel-costigliola/assertj-core#641]
this is an implementation class used to provide generated navigation methods through generated Assert classes. 

For background see this whole thread for https://github.com/joel-costigliola/assertj-assertions-generator/issues/67

In particular for [here's an example navigating through lists](https://github.com/joel-costigliola/assertj-assertions-generator/issues/67#issuecomment-208756239)

So these classes are really intended to be reused by folks generating assertion classes using navigable list properties.

PR on its way shortly...

**Comment by jstrachan** [comment]
BTW I also added a little assertThat(list, assertFactory) method https://github.com/jstrachan/assertj-core/blob/7b1d079edeb5ac984cebbed77a65025718ee7673/src/test/java/org/assertj/core/navigation/ListNavigation_Test.java#L41-L46

so in Java 8 style notation you could do...
```
List<Vehicle> vehicles = ...;
listAssert = assertThat(vehicles, (vehicle) -> assertThat(vehicle));
```
which would create a NavigationListAssert that knows how to create assertions on the element (a vehicle) so that you could do chained assertions like...
```
assertThat(vehicles, (vehicle) -> assertThat(vehicle)).first().brand().isEqualTo("Audi");
```
etc.

Though really the main use case of NavigationListAssert is really for inside the generated Assert classes for iterable properties/fields

**Comment by joel-costigliola** [comment]
I need to look into this thoroughly, I'll get back to you soonish. 
I like the idea but I find this syntax not super clear :
```assertThat(vehicles, (vehicle) -> assertThat(vehicle));``` 
I'm not saying I have a better solution though.

**Comment by joel-costigliola** [comment]
Just specifying the assert class might be enough, which would give a lighter syntax (but would require reflexion to build the assert instance), I'll give it a try and see how it goes :
```java
assertThat(vehicles, VehicleAssert.class);
```

**Comment by joel-costigliola** [comment]
I have succeeded in making `NavigationListAssert` with a class instead of an `AssertFactory`, it can be used like that:
```java
List<String> list =  newArrayList("one", "two", "three");    
assertThat(list, StringAssert.class).first().startsWith("o");
```
It requires though few lines of ugly reflection code to handle the case where you want to build an `ObjectAssert`, for example if the value to test is a `Car` trying to build an `ObjectAssert` by refelction fails as there is no `ObjectAssert` constructor taking a car.

The comment I made on the syntax can be addressed with a method reference:
```
assertThat(vehicles, Assertions::assertThat);
``` 
Not as readable as passing the assert class IMO but providing a  `AssertFactory` is probably more flexible than relying on some reflection code.

@jstrachan  Any thoughts ?

**Comment by joel-costigliola** [comment]
I'm gonna support both `AssertFactory` and class based `NavigationListAssert`, ex:

```java
@Test
public void should_navigate_to_list_elements_and_perform_specific_string_assertions() {
  List<String> list = newArrayList("one", "two", "three");
  // navigation gives StringAssert
  assertThat(list, StringAssert.class).first().startsWith("o");
  assertThat(list, StringAssert.class).last().endsWith("ee");
  assertThat(list, StringAssert.class).element(1).contains("w");
  assertThat2(list).first().isEqualTo("one");
}

@Test
public void should_use_ObjectAssert_by_default() {
  List<String> list = newArrayList("one", "two", "three");
  // navigateion gives ObjectAssert
  assertThat2(list).first().isEqualTo("one");
  assertThat2(list).last().isEqualTo("three");
  assertThat2(list).element(1).isEqualTo("two");
}
```

**Comment by jstrachan** [comment]
Thanks, that all looks great! I agree both approaches have their merits. The AssertFactory suits code generation with the generator while the reflection case is really handy when folks are working on existing models that don't have a generator

**Comment by joel-costigliola** [comment]
Done
