### ISSUE TITLE
add a Java 8 lamdba interface for chaining assertions easier?

### ISSUE THREAD

**Issue by jstrachan** [joel-costigliola/assertj-core#643]
so imagine you've some generated assertion classes which are deeply nested like discussed [here](https://github.com/joel-costigliola/assertj-assertions-generator/issues/67) so you have some assertions like...
```java
assertThat(foo).bar().whatnot().cheese().isNotNull(); 
assertThat(foo).bar().whatnot().beer().isEqualTo("Stella");
assertThat(foo).bar().whatnot().wine().isEqualTo("Shiraz");
```
there's some duplication. Now our IDEs can refactor those expressions to variables...
```java
WhatnotAssert whatnot = assertThat(foo).bar().whatnot();
whatnot.cheese().isNotNull(); 
whatnot.beer().isEqualTo("Stella");
whatnot.wine().isEqualTo("Shiraz");
```
but I wonder if Java 8 lambdas could be used to make an XPath like variable/predicate chain via a single new method on AbstractAssert?
```java
assertThat(foo).bar().whatnot().with(whatnot -> {
  whatnot.cheese().isNotNull(); 
  whatnot.beer().isEqualTo("Stella");
  whatnot.wine().isEqualTo("Shiraz");
});
```
The nice thing is the type inference to avoid the noise of the actual types of the assert classes; so the code feels cleaner yet is nice and DRY.

Not 100% sure on the name of the function; used `with` could be `assert` or something? Basically it just invokes the lamda with the current assertion object really ;).

Thoughts? Happy to submit a PR you think its a good idea

**Comment by jstrachan** [comment]
Actually a corollary to that is it might be handy to add a foreach method to NavigationListAssert to be able to add assertions to all elements in a list:
```java
assertThat(foo).bar().vehicles().foreach(vehicle -> vehicle.brand().isNotNull());
```

**Comment by joel-costigliola** [comment]
We have something alike to verify [multiple assertions for  `Optional` values](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.3.0-hasValueSatisfying), to be consistent I would use: 
```java
assertThat(whatnot).satisfies(whatnot -> {
  whatnot.cheese().isNotNull(); 
  whatnot.beer().isEqualTo("Stella");
  whatnot.wine().isEqualTo("Shiraz");
});
```
