### ISSUE TITLE
Specify multiple single value extractors in flatExtracting

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#644]
For the time being, to extract multiple values and combine them before performing assertions we have to do something like this: 
```java
// ch type is TolkienCharacter
assertThat(fellowshipOfTheRing).flatExtracting(ch -> asList(input.getName(), ch.getAge()))
                               .contains(33 ,"Frodo", "Legolas", 1000);
```
It would be nice to simply specify the list of extractors (Java 8) :
```java
assertThat(fellowshipOfTheRing).flatExtracting(TolkienCharacter::getName, 
                                               TolkienCharacter::getAge))
                               .contains(33 ,"Frodo", "Legolas", 1000);
```
or with properties names (Java 7) : 
```java
assertThat(fellowshipOfTheRing).flatExtracting("name", "age"))
                               .contains(33 ,"Frodo", "Legolas", 1000);
```

**Comment by PascalSchumacher** [comment]
I already have working prototype for the multiple extractor function method. I will clean it up and submit a pull requests.

**Comment by PascalSchumacher** [comment]
Just noticed that the prototype was not really working. It was expecting all collections to contain objects of the same type.

When I tried to make it work for untyped objects, there is a conflict between:

`public <V> ListAssert<V> flatExtracting(Extractor<? super T, ? extends Collection<V>> extractor)`

` public final ListAssert<Object> flatExtracting(Function<Object, ? extends Collection<Object>>... extractors)`

so it does not seem to be possible to make this work (unless I'm missing something).

**Comment by joel-costigliola** [comment]
I think what we want is :
```java 
public ListAssert<Object> flatExtracting(Function<Object, Object>... extractors)
// or
public ListAssert<Object> flatExtracting(Extractor<Object, Object>... extractors)
```
and not:
```java 
public ListAssert<Object> flatExtracting(Function<Object, ? extends Collection<Object>>... extractors)
```
the reason being that each extractor extracts one value, combine them in a list and flatten it. 
conceptually it is converting a list of single value extractors to one multi value extractor, like [allAsList](http://google.github.io/guava/releases/19.0/api/docs/com/google/common/util/concurrent/Futures.html#allAsList%28java.lang.Iterable%29) in guava's future.

I'm not sure whether we would need to use wildcard or not, e.g:
```java 
public ListAssert<Object> flatExtracting(Extractor<? super Object, ? extends Object>... extractors)
```

**Comment by PascalSchumacher** [comment]
I do not understand. If we want to extract a single value why use `flatExtracting`? The existing method `public <V> ListAssert<V> flatExtracting(Extractor<? super T, ? extends Collection<V>> extractor)` does not extract single values. For extracting single values is the `extracting` method. Or I'm I missing something?

Anyway:
```java
public ListAssert<Object> flatExtracting(Function<Object, Object>... extractors)
public ListAssert<Object> flatExtracting(Extractor<Object, Object>... extractors)
public ListAssert<Object> flatExtracting(Extractor<? super Object, ? extends Object>... extractors)
```
each cause a compile time conflict with existing method:
```java
public <V> ListAssert<V> flatExtracting(Extractor<? super T, ? extends Collection<V>> extractor)
```

**Comment by joel-costigliola** [comment]
We want to extract multiple single values as in:
```java
assertThat(fellowshipOfTheRing).flatExtracting(TolkienCharacter::getName, 
                                               TolkienCharacter::getAge))
                               .contains(33 ,"Frodo", "Legolas", 1000);
```
We combine them in a list si that our users don't have to do it manually as in: 
```java
// ch type is TolkienCharacter
assertThat(fellowshipOfTheRing).flatExtracting(ch -> asList(input.getName(), ch.getAge()))
                               .contains(33 ,"Frodo", "Legolas", 1000);
```
@PascalSchumacher does it make sense to you ?

**Comment by PascalSchumacher** [comment]
Sure, thanks for explaining. :)

**Comment by joel-costigliola** [comment]
Done for 2.5.0 by specifying extractors by name and 3.5.0 by specifying extractors as lambdas.
