### ISSUE TITLE
Feature request: every string in List<String> matches to a pattern

### ISSUE THREAD

**Issue by Aleks-Ya** [joel-costigliola/assertj-core#652]
#### Summary
I haven't found convinient way to assert that each string in List<String> matches to a pattern.
#### Real life use case or example
Tryed these:
```        
    @Test
    public void stringIterableMatchesPattern() {
        Iterable<String> strings = Arrays.asList("a", "b");
        Pattern pattern = Pattern.compile("[ab]");

        // compile error
        assertThat(strings).matches(pattern); 

        //runtime error (cast List to String)
        assertThat(strings).asString().matches(pattern); 

        //works, but non-iformative error message (no info about pattern)
        assertThat(strings).allMatch(string -> pattern.matcher(string).matches());

        //works, print info about pattern, but too long
        assertThat(strings).as("Pattern: %s", pattern).allMatch(string -> pattern.matcher(string).matches());
    }
```
#### Java 8 specific ?
NO 

Can you suggest the best way to do this assert?
Version: assertj-core-3.4.1

**Comment by Aleks-Ya** [comment]
#518

**Comment by joel-costigliola** [comment]
The last one is the way to go, I don't think it is that long ... 

Unfortunately, there is no way to reuse existing typed assertions (like String) on a `List<String>` because Java generics limitations (I would be thrilled to be proven wrong though).

Another way of writing your assertions is: 
```java
strings.forEach(string -> assertThat(string).matches(pattern));
```

**Comment by Aleks-Ya** [comment]
Your assertion is suitable. Thanks!
