### ISSUE TITLE
Allow to check result of last soft assertion

### ISSUE THREAD

**Issue by fduminy** [joel-costigliola/assertj-core#653]
#### Summary
I would like to be able to check the result of the last soft assertion.

#### Real life use case or example
```java
Person person = ...
SoftAssertion soft = new SoftAssertions();
if (soft.assertThat(person.getAddress()).isNotNull().wasSuccess()) {
    soft.assertThat(person.getAddress().getStreet()).isNotNull();
}
```

Actual workaround is :
```java
soft.assertThat(person.getAddress()).isNotNull();
if (person.getAddress() != null) {
    soft.assertThat(person.getAddress().getStreet()).isNotNull();
}
```
but for more complex assertion, I must also write the equivalent boolean expression for the ```if``` statement.

The implementation is easy and need to set a flag to ```false``` at begin of ```ErrorCollector.intercept``` and, on failure, set the flag to ```true```.

#### Java 8 specific ?
NO

**Comment by joel-costigliola** [comment]
Yeah, I see that it can be useful. 

@fduminy would you be keen to contribute a fix for this issue ?

**Comment by fduminy** [comment]
@joel-costigliola I will

**Comment by fduminy** [comment]
@joel-costigliola Will that feature be integrated into the 1.x branch (I assume it will be in the master branch) ?
... probably at release time

**Comment by joel-costigliola** [comment]
Not in 1.x, I don't maintain it actively but everything that goes in 2.x ends up in master, that's the most efficient way I have found to get 2.x and 3.x in sync (3.x = 2.x + java 8 specific stuff)
