### ISSUE TITLE
IterableAssert should override isSameAs and isNotSameAs to unroll the actual instance.

### ISSUE THREAD

**Issue by nickstolwijk** [joel-costigliola/assertj-core#655]
#### Summary
IterableAssert  does not override the methods to unroll the actual instance.

#### Real life use case or example
    @Test
    public void testIterator() {
        Iterator<String> iterator = new ArrayList<String>().iterator();
        assertThat(iterator).isSameAs(iterator);
    }

leads to: 
java.lang.AssertionError: 
Expecting:
 <java.util.ArrayList$Itr@a4300e>
and actual:
 <[]>
to refer to the same object
	at TestIterator.testIterator(TestIterator.java:xx)

#### Java 8 specific ?

NO 

The PR addressing this issue if any must be based on the `master` if the issue Java 8 specific, use otherwise the `2.x` branch.

**Comment by joel-costigliola** [comment]
Good catch, the lazy iterator "ugly" stuff sometimes bites us.

**Comment by nickstolwijk** [comment]
I have created a pull request with a fix and tests.
