### ISSUE TITLE
Support for java 8 Predicates

### ISSUE THREAD

**Issue by sta-szek** [joel-costigliola/assertj-core#658]
#### Summary
It would be nice to have support for java 8 predicates.
Assertions should allow for testing them instead of testing everyone separetly.

#### Real life use case / example
Good:
```
//given
acceptedValues = Lists.newArrayList("a","b")

//when
final Predicate<String> predicate = Predicate.create(acceptedValues);

//then
assertThat(predicate).accepts("a")
                     .accepts("b")
                     .doesNotAccept("c")
                     .accepts(Lists.newArrayList("a","b"))
                     .doesNotAccept(Lists.newArrayList("c","d"));
```

Not good:
```
//given
acceptedValues = Lists.newArrayList("a","b")

//when
final Predicate<String> predicate = Predicate.create(acceptedValues);
boolean result1 = predicate.test("a");
boolean result2 = predicate.test("b");
boolean result3 = predicate.test("c");
boolean result4 = predicate.test("d");

//then
assertThat(result1).isTrue();
assertThat(result2).isTrue();
assertThat(result3).isFalse();
assertThat(result4).isFalse();
```
#### Java 8 specific ?
YES

**Comment by joel-costigliola** [comment]
Good idea, I would just use `matches` instead of `accepts` and `matchAll` for collection/array.

**Comment by filiphr** [comment]
@joel-costigliola I am willing to work on this if no one is. I already have some idea about how to do it.

I just have one question, do we also need the other predicates (```IntPredicate```, ```LongPredicate```, ```DoublePredicate```).

**Comment by joel-costigliola** [comment]
@filiphr that would be great ! regarding your question I would say yes (we have the same thing with `Optional`).

**Comment by joel-costigliola** [comment]
@filiphr do you prefer `assertThat(predicate).accepts("a")` or `assertThat(predicate).matches("a")` ?
I'm having second thoughts and contradict my previous comment) as it is correct to say that a value matches a predicate but not the other way around.

**Comment by filiphr** [comment]
@joel-costigliola I think that accepts is more suitable in this situation. You are correct.

**Comment by joel-costigliola** [comment]
`accepts` accepted then :)

**Comment by filiphr** [comment]
While doing the changes to ```accepts``` something else came to my mind. Regarding the error factories, I am reusing some which were already there, like ```ShouldMatch```, and I am also reusing the ```Iterables#assertAllMatch``` is that acceptable?

**Comment by joel-costigliola** [comment]
No, I think this will be confusing, if you assert that the predicate should accept a value and it does not then the problem is on the predicate not the value, I would use a message like:
```
Expecting given predicate to accept <value> but did not.
```
where given is replaced by predicate description when provided.
Feel free to suggest a better error message ...

**Comment by filiphr** [comment]
I will modify the error messages so it is better to understand. Will probably do something in the ```Iterables``` as the logic is the same for the assertion

**Comment by joel-costigliola** [comment]
:+1:

**Comment by jangalinski** [comment]
Nice feature. I know discussion is over, but I just have to add my two c:

I am used to the FunctionalInterfaces, so "accept" to automatically indicates a Consumer. Working with predicates I would expect "tests" (and doesNotTest).

**Comment by joel-costigliola** [comment]
well if you write `assertThat(predicate).test("a")` it is not clear that it means `assertThat(predicate).testToTrue("a")` as `predicate.test("a")` can return true or false.

`assertThat(predicate).evaluateToTrue("a")` would be closer to the java api wording but a little bit too long to my taste.

**Comment by sta-szek** [comment]
or according to predicate's 'test' method it could be:
`assertThat(predicate).passes("a")`
`assertThat(predicate).passesOn("a")`
`assertThat(predicate).willPass("a")`
`assertThat(predicate).isPassing("a")` ?

**Comment by joel-costigliola** [comment]
I kind of like ` assertThat(predicate).isTrueFor("a")` but I still have a slight preference for `accepts`.

**Comment by jangalinski** [comment]
+1 for "isTrueFor"
