### ISSUE TITLE
Support to test infinite Iterators and Iterables

### ISSUE THREAD

**Issue by DanielGronau** [joel-costigliola/assertj-core#661]
#### Summary

It seems AssertJ doesn't handle infinite data structures well, which leads to "hanging" tests (probably when trying to determine the size of the data structure).

#### Real life use case / example

I tried to test an implementation of a cyclic iterator using assertThat(myIterator).startsWith(1,2,3,1,2,3), which hangs.
 
#### Java 8 specific ?

NO

**Comment by joel-costigliola** [comment]
AssertJ converts the iterator to a `List` as soon as it needs to be consumed, for example to check its size but in the case of `startsWith`, we should not perform the conversion as it is necessary.
