### ISSUE TITLE
Allow casting an AbstractObjectAssert<Super> to AbstractObjectAssert<Child>

### ISSUE THREAD

**Issue by anuraaga** [joel-costigliola/assertj-core#662]
#### Summary

When asserting on APIs that return a base class you know the type of, it can be useful to be able to cast the object under assertion fluently for more type-safety. This should probably be an asType, similar to asString and asList, though it would be conceivable for isInstanceOf to do this conversion too.

#### Real life use case / example

```java
class Animal {
  String getName();
}

class Cat extends Animal {
  String getMeow();
}

assertThat(zooService.getCurrentPet()).asType(Cat.class).extracting(Cat::getMeow).contains("purr");
```

#### Java 8 specific ?

YES (not so useful without lambdas for type-safety)

If the issue Java 8 specific, the Pull Request must be based on the `master`, otherwise the `2.x` branch must be used.

**Comment by joel-costigliola** [comment]
Yeah ... why not although I'm not totally convinced it adds lot of value since you already do:
```java
assertThat(zooService.getCurrentPet()).extracting("meow").contains("purr");
```
The only drawback is that it is not typesafe or refactoring friendly, but on the other hand it's more concise.

**Comment by igormukhin** [comment]
That one would be good. 

I am currently in need of such `castTo` or `asType` method:

```java

class BooleanConverter implements Converter {
    public Object convertToDataValue(Object objectValue) {
        // magic...
    }
}

class BooleanConverterTest {
    private BooleanConverter sut = new BooleanConverter();

    @Test
    public testConvertToDataValue() {
        assertThat(sut.convertToDataValue("Y")).castTo(Boolean.class).isTrue();
    }
}
```

You can also do so that `isInstanceOf` would return the assert for the type.

**Comment by joel-costigliola** [comment]
@igormukhin is https://github.com/joel-costigliola/assertj-core/issues/683 what you are looking for ?

**Comment by igormukhin** [comment]
@joel-costigliola yes, thanks!

**Comment by joel-costigliola** [comment]
closing this issue then
