### ISSUE TITLE
Have AbstractThrowableAssert extend AbstractObjectAssert?

### ISSUE THREAD

**Issue by anuraaga** [joel-costigliola/assertj-core#663]
#### Summary
Currently, it is only possible to assert on the message and cause of a throwable. As many custom exceptions have fields that we'd like to verify it'd be useful to have AbstractObjectAssert's assertions available.

#### Real life use case / example
```java
assertThatThrownBy(() -> callService()).hasFieldOrPropertyWithValue("status", Status.ILLEGAL_ARGUMENT);
```

If combined with #662, can be even more type-safe

```java
assertThatThrownBy(() -> callService()).asType(MyException.class).extracting(MyException::getStatus).isEqualTo(OK);
```

#### Java 8 specific ?

NO 

If the issue Java 8 specific, the Pull Request must be based on the `master`, otherwise the `2.x` branch must be used.

**Comment by joel-costigliola** [comment]
I agree we could have done that.
