### ISSUE TITLE
assertj.org website is down?

### ISSUE THREAD

**Issue by hoangtranwork** [joel-costigliola/assertj-core#664]
I cannot access the assertj.org website, is it just me having that issue or the website is down?

**Comment by joel-costigliola** [comment]
Long story short : use http://joel-costigliola.github.io/assertj/

Long story long : I was living in France when I registered assertj.org, I
now live in New Zealand and renewing the domain from NZ was ridiculously
expensive, so I did not renew it but I'm gonna buy the domain again from NZ
...

sorry guys !

**Comment by joel-costigliola** [comment]
closing this issue and creating this https://github.com/joel-costigliola/assertj/issues/51
