### ISSUE TITLE
JavaDoc of AbstractObjectArrayAssert.containsExactlyInAnyOrder(...) is an erroneous copy

### ISSUE THREAD

**Issue by selo-ecube** [joel-costigliola/assertj-core#667]
The JavaDoc of org.assertj.core.api.AbstractObjectArrayAssert.containsExactlyInAnyOrder(T... values) seems to be a copy of org.assertj.core.api.AbstractObjectArrayAssert.containsExactlyElementsOf(Iterable<? extends T> iterable) and does not fit the name and body of the method.

**Comment by joel-costigliola** [comment]
@selo-ecube thanks for taking the time to report it.
@PascalSchumacher selo-ecube thanks for taking the time to fix it.
