### ISSUE TITLE
Methods within normal and BDD Asertions

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#671]
#### Summary
This is more like a question then a problem. I was having a look at the ```BDDAssertions``` and ```Assertions```, also the soft types. Is the general idea that all of the ```assertThat``` from the ```Assertions``` exist as ```then``` method in ```BDDAssertions```?

If yes then I would propose some way of guaranteeing this, by either always generating the ```BDDAssertions``` from the ```Assertions```, or by creating a test that would test all the methods from the ```Assertions```. 

Additionally about the methods between the soft assertions and the assertions are not consistent.

#### Example

I did a small analysis on the (2.x branch) and there are some difference between the methods:

Assertions|BDDAssertions
---|---
public static <K, V> MapAssert<K, V> assertThat|public static <K, V> AbstractMapAssert<K, V> then
public static <T> T assertThat(final AssertProvider<T> component)| missing
public static <T extends AssertDelegateTarget> T assertThat(T assertion)| missing
public static AbstractPathAssert<?> assertThat(Path actual)| missing

#### Java 8 specific ?

NO

**Comment by joel-costigliola** [comment]
That would be great indeed.

Thanks for the analysis, I'll fix that right away.

**Comment by filiphr** [comment]
I also noticed that the soft assertions use the implemented classes of the assertions, is there some reason for this?

I am asking since I can also make a test which checks if the ```BDDAssertions``` have the same methods as the ```AbstractBDDSoftAssertions```. If you say yes, then we need to decide how to fix it. Should we always return our own implementations of the ```Abstract*Assert``` or the abstract ones. If we return the abstract we would introduce breaking changes. This same thing applies for the difference in the ```MapAssert``` vs the ```AbstractMapAssert```, and the methods in the ```Assertions``` vs the ```AbstractSoftAssertions```

**Comment by joel-costigliola** [comment]
Soft assertions could actually return AbstractXXXAssert classes but need to proxy the concrete class (CGLIB needs a concrete class to instantiate to be able to create a proxy).

**Comment by filiphr** [comment]
If it is ok to return the ```AbstractXXXAssert``` then I will do that. Shortly I would create a pull request with the test I have in mind and also the "fixes" for the test

**Comment by filiphr** [comment]
@joel-costigliola Do you think that we could somehow use something from the assertj-assertions-generator to generate the different ```Assertions``` classes. 

Maybe if we add Annotations to the different ```Assert``` classes we can generate the Assertions. I am thinking in this direction, since with something like this one would only need to write a new asserter add the appropriate information in the ```Annotation``` and everything will be synced

**Comment by joel-costigliola** [comment]
It's ok as long as we don't add any compile/runtime dependencies to assertj-core, another option to consider is [JavaPoet](https://github.com/square/javapoet) to generate java source.

**Comment by PascalSchumacher** [comment]
I guess this can be closed, as the missing methods (and tests to prevent this in the future) were added in 2.5.0/3.5.0.

**Comment by PascalSchumacher** [comment]
@joel-costigliola Please close this issue. Thanks!

**Comment by joel-costigliola** [comment]
Closed, thanks.
