### ISSUE TITLE
Support registering custom fieldname/type comparators for element fields when comparing iterables/arrays

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#676]
as suggested by @joel-costigliola in https://github.com/joel-costigliola/assertj-core/pull/645#issuecomment-223801634 :

>[...] [I] realized that there is no support for registering specific field/type comparators (as mentioned in the existing javadoc), for completion and consistency we should add it.

>Adding `usingComparatorElementForType` and `usingComparatorForElementField` methods in `AbstractIterableAssert` and using the registered comparators in `FieldByFieldComparator` should solve this problem I believe .

**Comment by PascalSchumacher** [comment]
I'm not sure the names make it clear enough that the comparators are not used for the elements itself, what about something like `usingComparatorForElementFieldsWithType` and `usingComparatorForElementFieldsWithName`?

**Comment by joel-costigliola** [comment]
I like `usingComparatorForElementFieldsWithType` and `usingComparatorForElementFieldsWithName` better than my suggestions, let's use them :)

**Comment by joel-costigliola** [comment]
@PascalSchumacher I let this one for you when you have time (no hurry).
