### ISSUE TITLE
Feature suggestion: hasNoNullFields and hasNoNullFieldsIgnoring

### ISSUE THREAD

**Issue by jhannes** [joel-costigliola/assertj-core#680]
#### Summary

I find that I often use assertj in combination with property-based testing. This is super-useful for things like database mappings. See example below.

The neat thing currently is that this captures the situation where I add a field to my domain object, but forget to add a mapping for the same field, since I'm using isEqualToIgnoringGivenFields.

However, it does not capture the situation where I also forget to populate the new field in my test data creator. hasNoNullFields could remedy this.

#### Example

```java
            Product product = testData.sampleProduct();
            repository.save(product);
            assertThat(repository.find(product.getId()))
                    .isEqualToIgnoringGivenFields(product, "updatedAt");

           // with suggested feature improvement
            assertThat(repository.find(product.getId()))
                    .hasNoNullFieldsIgnoring("optionalName")
                    .isEqualToIgnoringGivenFields(product, "updatedAt");
```

#### Java 8 specific ?

* NO

**Comment by joel-costigliola** [comment]
Hi Johannes,

Would these assertions strictly consider fields but not properties ? 
I'm also guessing it should be able to read private fields, right ?

I find `hasNoNullFieldsExcept` to be a better name than `hasNoNullFieldsIgnoring` and also assume it takes a vararg, WDYT  ?

**Comment by jhannes** [comment]
My inspiration was `.isEqualToIgnoringGivenFields` and friends, so `hasNoNullFields` should remind of these.

I think it makes most sense to use `Objects.getDeclaredFieldsIncludingInherited` (just like `isEqualToIgnoringGivenFields` does) to determine the fields to use.

I agree that `hasNoNullFieldsExcept` is a better name. I suggested `hasNoNullFieldsIgnoring` to remind of `isEqualToIgnoringGivenFields`, but on closer consideration, your suggestion is a much clearer name.
