### ISSUE TITLE
Allow working with the type previously checked through isInstanceOf(…)

### ISSUE THREAD

**Issue by olivergierke** [joel-costigliola/assertj-core#683]
#### Summary

When writing assertions against instances of `Object`, I frequently find myself asserting the actual object type first, and then casting to that type to add further assertions:

```java
Object object = …;

assertThat(object).isInstanceOf(Foo.class);

Foo foo = (Foo) object;

assertThat(foo).…
```

It would be cool if the instanceOf check returned an assertion for the type I just asserted to:

#### Example

```java
assertThat(object).isInstanceOf(String.class).contains("bar");
```

**Comment by joel-costigliola** [comment]
That  would be a nice thing to have indeed, I'm not sure it is technically feasible to with generic type erasure but I'll give it a try anyway.

In the meantime, in case your object is a `String`, there is an `asString()` that combines checking the object is an instance of a String a return `StringAssert` (same with `List`).

**Comment by olivergierke** [comment]
The `String` was just an example :). In my case I am actually using a complex type. Maybe introducing a new method for exactly that purpose is a better way (also not to break existing code)?

**Comment by joel-costigliola** [comment]
I know it was an example :)

Thinking out loud, we could introduce a method like `<ASSERT> toAssert(ASSERT assertionClass)` to support that but it is a bit ugly.

**Comment by olivergierke** [comment]
No need to hurry! Maybe just leave the ticket flying around for a bit and see if others chime in and have ideas.

**Comment by joel-costigliola** [comment]
No hurry indeed, I have put it for 2.6.0 which is not the next release (2.5.0) to have time to think about it.

**Comment by lbilger** [comment]
I think this is really hitting the limits of Java ;)

Two ideas come to mind:
First idea:
```java
assertThat(typeChecked(object, String.class)).contains("bar");
```
```java
public static <T> T typeChecked(Object object, Class<T> expectedClass) {
    assertThat(object).isInstanceOf(expectedClass);
    return (T) object;
}
```
This would make use of the existing overloads of ```assertThat```. Might be hard to integrate this with soft assertions, though.

Second idea:
```java
assertThat(object).isInstanceOf(String.class).satisfies(string-> assertThat(string).contains("bar"));
```
Where ```isInstanceOf```could return an ```AbstractObjectAssert``` of the expected type. Even simpler, but probably less readable, would be:
```java
assertThat(object).isInstanceOfAndSatifies(String.class, string-> assertThat(string).contains("bar"));

**Comment by olivergierke** [comment]
I like the

```java
assertThat(object).isInstanceOf(String.class).satisfies(string -> …);
```

idea.

**Comment by joel-costigliola** [comment]
in 3.5.0 release (which is 2.5.0 + Java 8 specific features) coming this month, we have added `satisfies` feature, see https://github.com/joel-costigliola/assertj-core/issues/643#issuecomment-210687011, it will be pushed in master soonish.

**Comment by dorzey** [comment]
If we change `isInstanceOf` to the below:
```java
public <X> X isInstanceOf(Class<X> type) {
    objects.assertIsInstanceOf(info, actual, type);
    return type.cast(actual);
}
```
would that be sufficient to get it working with `satisfies`?

**Comment by lbilger** [comment]
This would return an instance of X itself, which would require another ``assertThat`` around the call. But if ``isInstanceOf`` returned an ``ObjectAssert<X>``, it should work. Something like:
```java
public <X> AbstractObjectAssert<?, X> isInstanceOf(Class<X> type) {
    objects.assertIsInstanceOf(info, actual, type);
    return assertThat(type.cast(actual));
}
```

**Comment by olivergierke** [comment]
@lbilger — That's basically was I was looking for 🙃.

**Comment by joel-costigliola** [comment]
As @lbilger said, his suggestion is not addressing the initial issue :
```java
// does not compile because isInstanceOf returns AbstractObjectAssert not StringAssert.
assertThat(object).isInstanceOf(String.class).contains("bar");
```

I'm gonna continue trying things although my gut feeling is that you need to pass the assert type as a parameter of `isInstanceOf` in order to chain type specific assertions.

**Comment by joel-costigliola** [comment]
Got something working by introducing ... 
```java
// (naming of the method might change)
public <ASSERT> ASSERT assertWith(Class<ASSERT> type) {
  try {
    return (ASSERT) type.getConstructor(actual.getClass()).newInstance(actual);
  } catch (Exception e) {
    throw new RuntimeException("Fail to switch to " + type.getSimpleName() + " assertions", e);
  }
}
```
... one can write: 
```java
Object object = "foo";
assertThat(object).assertWith(StringAssert.class).contains("oo")
```

Another solution would be to add methods like `asString` for every type AssertJ has assertions for, each method would check the instance type and convert to the proper assert type. This will add a bunch of methods to `AbstractAssert` but they will be easy to discover since they all follow the pattern `asTYPE`, concretely if the object under test is a `Date` you would just to write 

```java
Object object = new Date();
assertThat(object).asDate().hasYear(2016);
```

Comments welcome ;-)

**Comment by joel-costigliola** [comment]
Fixed by adding all possible `asXXX` methods.

**Comment by olivergierke** [comment]
To be completely honest, I think the API is not really nice as it requires you to have all potential possibilities implemented explicitly. As indicated above, I think the requirement never was to get hold of a typed {{Assert}} in the first place (or by that wanting to pass the assert type), but only API to get access to the object under test *as the type I just validated against*, so that I can create additional assertions myself:

```java
assertThat(object).isInstanceOf(String.class).satisfying(string -> { // string is a String here
  assertThat(string).… // <- I happily create the typed assertion myself here
})
```

I see all the support implemented for the types you know of, but what if I come around with an `Optional` or something that implements `Iterable`. There's no `as…`-method I could call then, right? Feels a bit like we were throwing out the baby with the bathwater here?

**Comment by joel-costigliola** [comment]
I missed the main point, fair enough ...  
I'll keep the `asXXX` methods as they are handy for AssertJ known types and will add the type aware `satisfying` if this is technically possible (not so sure yet):
```java
 assertThat(object).isInstanceOf(String.class).satisfying
``` 
otherwise I'll go for:
```java
assertThat(object).isInstanceOfSatifying(String.class, string-> assertThat(string).contains("bar"));
```
which I'm pretty sure is possible.

**Comment by joel-costigliola** [comment]
I have reverted the `asXXX` method to avoid bloating the API and added in `isInstanceOfSatifying` https://github.com/joel-costigliola/assertj-core/commit/baa10e7e7a67d09fabc2f0f20a919d8e0c30b40f.

Hope this is the right one this time !

**Comment by olivergierke** [comment]
There's no right or wrong here :). But a big thanks for taking the feedback into account! 👍
