### ISSUE TITLE
Problems with SoftAssertions and java.util.Optional

### ISSUE THREAD

**Issue by lbilger** [joel-costigliola/assertj-core#687]
#### Summary
Testing for Optional containing a given value fails with SoftAssertions if the Optional is empty. The call to ```AbstractOptionalAssert.contains``` will check for ```Optional.isPresent```, but the thrown Exception is captured and execution flow continues to call ```Optional.get```, which causes a NoSuchElementException, interrupting the test and hiding any previous assertion errors.
Easy fix would be to add an extra ```isPresent``` check, but this seems to be a more general problem as Issue #447 shows.

#### Example

```java
        SoftAssertions softly = new SoftAssertions();
        softly.assertThat(Optional.empty()).contains("Foo");
        softly.assertAll();
```

#### Java 8 specific ?
YES

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Fixed by rethrowing `AssertionError` from nested assertion calls (in this commit https://github.com/joel-costigliola/assertj-core/commit/0988c941582dc4c702e4ab64eef564e22eb585c6).
