### ISSUE TITLE
Provide assertion for Java8 predicates

### ISSUE THREAD

**Issue by jangalinski** [joel-costigliola/assertj-core#689]
#### Summary

I want to simply assert the behavior of a predicate  without evaluating it first

#### Example

```java
// given some Predicate

Predicate<String> startsWithA = s -> s.startsWith("a");
 
// instead of
assertThat(startsWithA.test("abc")).isTrue();

// I want to write
assertThat(startsWithA).isTrueFor("abc");

```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

Remark: looks like a minor change and I would be happy tp provide the PR. Just let me know what you think (or if this is already possible somehow and I missed it).

**Comment by filiphr** [comment]
This is already implemented. See #658.

It should come out in the next release.

**Comment by jangalinski** [comment]
Cool, thanks. cloning this one then.
