### ISSUE TITLE
Add MapAssert#hasEntrySatisfying(K, Condition<V>)

### ISSUE THREAD

**Issue by valery1707** [joel-costigliola/assertj-core#690]
#### Summary
I want to add methods to simplify check map values.
Similar to #70 and #205, but I have working code for PR.

#### Example

```java
assertThat(map)
    .hasEntry("key1", allOf(isNotNull, isContains("value"), someCreatedCondition))
    .hasEntry("key1", v -> {
        assertThat(v)
            .isNotNull()
            .contains("value")
            .is(someCreatedCondition);
    });
```

#### Java 8 specific ?
* `hasEntry(K, Condition<? super V>)` - NO
* `hasEntrySatisfying(K, Consumer<? super V>)` - YES

I will create two PR, but need I create two issues?

**Comment by joel-costigliola** [comment]
Yes, create two issues as one is only for 2.x version (the non java 8 specific).

I would also use `hasEntrySatisfying` for both assertions.

Thanks !

**Comment by joel-costigliola** [comment]
The PR for `hasEntrySatisfying(K, Consumer<? super V>)` should be on `master`.
The PR for `hasEntrySatisfying(K, Condition<? super V>)` should be on the `2.x` branch.

**Comment by valery1707** [comment]
Description for Java 8 specific method moved to #691

**Comment by valery1707** [comment]
@joel-costigliola, I created both PR

**Comment by valery1707** [comment]
@joel-costigliola, what about #692 and #693

**Comment by joel-costigliola** [comment]
I will review them as part of 2.6.0 / 3.6.0 releases, I'm focused on
releasing 2.5.0/3.5.0 right now.

cheers

**Comment by joel-costigliola** [comment]
Integrated thanks !
