### ISSUE TITLE
spike java-power-assert 

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#694]
#### Summary

https://github.com/jkschneider/java-power-assert offers nice error messages, let's try to use it in AssertJ. 

This issue is only a spike, don't replace all AssertJ error messages.

If the spike is conclusive then we need to identify which messages can be improved.
#### Java 8 specific ?
- NO  : Pull Request must be based on `2.x` branch

**Comment by dorzey** [comment]
I've spikes adding AssertJ support to java-power-assert.  I've raised an issue - https://github.com/jkschneider/java-power-assert/issues/6.

**Comment by PascalSchumacher** [comment]
While I like groovy power assert a lot, java-power assert has the serious limitation, that it can not be used in eclipse.

The project also seems pretty dead (almost 1,5 years since the last commit).

**Comment by joel-costigliola** [comment]
Let's reopen this issue if something happens
