### ISSUE TITLE
SoftAssertions: Add #fail(String) method.

### ISSUE THREAD

**Issue by caugner** [joel-costigliola/assertj-core#699]
#### Summary

JUnit has a `#fail(String)` method in order to make a test fail independently from a specific object (which `assertThat(...)` requires). In general, such a `#fail(String)` method can be used for complex assertions or whenever a sophisticated failure message is required. This would be useful to have in AssertJ, especially in combination with `SoftAssertions` that report several failures at once.

#### Example

```java
Collection<Acme> acmes = ...;
SoftAssertions softly = new SoftAssertions();
for (Acme acme : acmes) {
  boolean matches = matchesComplexConditionThatIsSpecificToThisTest(acme);
  if (!matches) {
    softly.fail("Doesn't match complex condition: " + acme);
  }
}
softly.assertAll();
```

As of 3.5.0, the following would be possible, but I think it's less clear and adds too much noise:  
```java
softly.assertThat(matches).as(acme + " matches complex condition.").isTrue();
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I'm not totally convinced, I could argue that replacing an `if` statement that takes 3 lines by a single line does not add noise but actually reduces it.

**Comment by caugner** [comment]
I get your point, but wouldn't you agree that those 3 lines are easier to read than the single line?

Let me try to convince you with another example:

```java
SoftAssertions softly = new SoftAssertions();
Collection<Acme> = createOneInconsistentAcmePerType();
AcmeRepository repo = ...;

for (Acme acme : acmes) {
  try {
    repo.save(acme);
    softly.fail("Repo should deny inconsistent Acme of type " + acme.getType());
  } catch (InconsistentAcmeException e) (
    // All good.
    softly.assertThat(e).hasKey("InconsistentAcmeException_" + acme.getType());
  }
}

softly.assertAll();
```

Do I have any alternative to test the missing exception case with AssertJ?

This would work, but is even worse than the previous example:

```java
softly.assertThat(false)
      .as("Repo should deny inconsistent Acme of type " + acme.getType())
      .isTrue();
```

**Comment by joel-costigliola** [comment]
Ok, I'm convinced now :)

**Comment by caugner** [comment]
@joel-costigliola I'm happy to hear that. Let me see if I can figure out where it should go…

My guess would be to add two methods `#fail(String)` and possibly `#fail(String, Throwable)` (for the sake of consistency) to [AbstractSoftAssertions](https://github.com/joel-costigliola/assertj-core/blob/2.x/src/main/java/org/assertj/core/api/AbstractSoftAssertions.java) (in the 2.x branch) which could then

- call the corresponding method in [Fail](https://github.com/joel-costigliola/assertj-core/blob/2.x/src/main/java/org/assertj/core/api/Fail.java),
- catch the resulting exception, and 
- pass it via [SoftProxies](https://github.com/joel-costigliola/assertj-core/blob/2.x/src/main/java/org/assertj/core/api/SoftProxies.java) to the [ErrorCollector](https://github.com/joel-costigliola/assertj-core/blob/2.x/src/main/java/org/assertj/core/api/ErrorCollector.java).

**Comment by joel-costigliola** [comment]
I believe you are on the right track, don't forget to call `lastResult.setSuccess(false)`, we need to think about  `setSuccess` implementation as calling `resolvingOutermostErrorCollectorProxyNestedCall` might not be relevant since nothing is proxied when calling directly `Fail`.

Some unit tests need to be added to verify that `AbstractSoftAssertions#wasSuccess()` behaviour is correct.

**Comment by caugner** [comment]
For the sake of consistency and completeness (with `Fail`), I also added

* `#failBecauseExceptionWasNotThrown(Class<? extends Throwable> throwableClass)` and
* `#shouldHaveThrown(Class<? extends Throwable> throwableClass)`.

Some users may be accustomed to these and therefore should also find them in SoftAssertions. Also, while *shouldHaveThrown* is more concise, *failBecauseExceptionWasNotThrown* is easier discoverable, i.e. both have their justification.

**Comment by joel-costigliola** [comment]
done.
