### ISSUE TITLE
Rename Date assertions isWithinXXX to hasXXXFieldEqualTo

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#7]
I think that `isWithinXXX` assertions is not a great name (yes it was my idea ...), I come up with a clearer name (I hope), let's see that with an example:

Before:
```java 
assertThat(myBirthday).isWithinMinute(27);
```
Options 1: 
```java 
assertThat(myBirthday).hasMinuteFieldEqualTo(27);
```
Options 2:
```java 
assertThat(myBirthday).hasMinute(27);
```

**Comment by AlexBischof** [comment]
What's the status here?

**Comment by joel-costigliola** [comment]
looking for feedback/option ...

**Comment by PascalSchumacher** [comment]
I would prefer `assertThat(myBirthday).hasMinute(27);`, but maybe `assertThat(myBirthday).hasMinuteEqualTo(27);` is more consistent with existing assertions?

**Comment by joel-costigliola** [comment]
ok, let's go for  `assertThat(myBirthday).hasMinute(27);` as it is shorter than the other options

**Comment by AlexBischof** [comment]
Since this is an API change, how do i handle that in my PR?
