### ISSUE TITLE
Multimap isNotEqualTo() possible problem

### ISSUE THREAD

**Issue by pivovarit** [joel-costigliola/assertj-core#706]
I encountered some specific problem and I am not sure if this is the desired behaviour.
Please have a look at the following code example. In my case it fails, BUT if I replace mmap1's type it starts to pass.

    @Test
    public void givenMultimaps_whenVerifyingContent_thenCorrect() throws Exception {
        final Multimap<Integer, String> mmap1 = ArrayListMultimap.create();
        mmap1.put(1, "one");
        mmap1.put(1, "1");
        mmap1.put(2, "two");
        mmap1.put(2, "2");

        final Multimap<Integer, String> mmap1_clone = Multimaps.newListMultimap(new HashMap<>(), ArrayList::new);
        mmap1_clone.put(1, "one");
        mmap1_clone.put(1, "1");
        mmap1_clone.put(2, "two");
        mmap1_clone.put(2, "2");

        assertThat(mmap1)
                .isNotEqualTo(mmap1_clone);
    }

and changed code:

    @Test
    public void givenMultimaps_whenVerifyingContent_thenCorrect() throws Exception {
        final Multimap<Integer, String> mmap1 = Multimaps.newMultimap(new HashMap<>(), Sets::newHashSet);
        mmap1.put(1, "one");
        mmap1.put(1, "1");
        mmap1.put(2, "two");
        mmap1.put(2, "2");

        final Multimap<Integer, String> mmap1_clone = Multimaps.newListMultimap(new HashMap<>(), ArrayList::new);
        mmap1_clone.put(1, "one");
        mmap1_clone.put(1, "1");
        mmap1_clone.put(2, "two");
        mmap1_clone.put(2, "2");

        assertThat(mmap1)
                .isNotEqualTo(mmap1_clone);
    }

**Comment by PascalSchumacher** [comment]
Hi Grzegorz,

thanks for reporting.

I think this is a not assertj problem. Assertj-core knows nothing about `Multimap`s, it just use the `equals` implementation of the `Multimap` objects to determine equality.  `Mulitmap` then uses `com.google.common.collect.Multimaps#equalsImpl` which uses `multimap.asMap().equals(that.asMap())` to determine equality.

What do you want to test for?

If you want to check that the multimaps are different objects you can use `assertThat(mmap1).isNotSameAs(mmap1_clone)`.

If you want to check that the multimaps are of different types you can use `assertThat(mmap1).doesNotHaveSameClassAs(mmap1_clone)`.

**Comment by joel-costigliola** [comment]
In addition to @PascalSchumacher comment, if you want to compare `Multimap` content, you can use AssertJ Guava and specifically [hasSameEntriesAs](http://joel-costigliola.github.io/assertj/guava/api/org/assertj/guava/api/MultimapAssert.html#hasSameEntriesAs-com.google.common.collect.Multimap-).

See http://joel-costigliola.github.io/assertj/assertj-guava.html for a quick start.

**Comment by joel-costigliola** [comment]
I'm closing this issue as it is not related to assertj-core but feel free to continue the discussion if you need more help or have more questions.

**Comment by pivovarit** [comment]
Ok, everything clear :) thanks
