### ISSUE TITLE
Provide support to assert Dictionary<K,V> objects

### ISSUE THREAD

**Issue by cvgaviao** [joel-costigliola/assertj-core#713]
#### Summary

Currently is possible to make a lot of assertions on Map<K,V> objects and its entries, but it is not for Dictionary<K,V> objects.
besides JDK do not recommends its use, an OSGi based projects uses it everywhere since its part of the OSGi core API (because it handles concurrency very well).

So I would like to have the possibility to assert key and values from a Dictionary<K,V> object.

**Comment by joel-costigliola** [comment]
According to the javadoc `Dictionary` is obsolete, I won't spend time writing assertions but you can contribute it and I will be glad to accept it.

**Comment by cvgaviao** [comment]
well, I know that javadoc says it is obsolete. I don't like to use it either. but I'm sure that they won't never, ever remove it from java core... and also pretty sure that OSGi API won't change since its multi-thread nature and old code support...
Will take a look when I have a time... btw, is there any wiki/doc showing the necessary steps (classes/methods) required?

**Comment by joel-costigliola** [comment]
just look at map assertions, might be a good idea to convert the dictionnary to a map and use map assertions directly.

**Comment by PascalSchumacher** [comment]
Closing this a `Dictionary` is obsolete and no pull request was supplied.

**Comment by chronodm** [comment]
In case anyone happens across this, it's fairly trivial in Java 9 to convert a `Dictionary` to a (not very efficient) `Map` (which you can then do map assertions on):

```java
      Dictionary<String, String> dict = new Hashtable<>();
      Map<String, String> wrapper = new AbstractMap<>() {
        @Override
        public Set<Entry<String, String>> entrySet() {
          return StreamSupport.stream(
            Spliterators.spliteratorUnknownSize(
              dict.keys().asIterator(),
              Spliterator.ORDERED
            ),
            false
          ).map(k -> Map.entry(k, dict.get(k)))
            .collect(Collectors.toSet());
        }
      };
```
