### ISSUE TITLE
Field comparison not ignoring static fields

### ISSUE THREAD

**Issue by mikezx6r** [joel-costigliola/assertj-core#723]
#### Summary
Similar to #590, but this time for statics. 
A static element won't ever be a field, so it shouldn't be comparing them.

Field has an isStatic() method to simplify this

**Comment by joel-costigliola** [comment]
Thanks for reporting this.

**Comment by mikezx6r** [comment]
And I've submitted a pull request, so no one else needs to investigate it.

**Comment by joel-costigliola** [comment]
:+1: 
pretty busy these days but I have planned it for the next release.

**Comment by joel-costigliola** [comment]
done.
