### ISSUE TITLE
Add integer-based overloads to ByteArrayAssert

### ISSUE THREAD

**Issue by elygre** [joel-costigliola/assertj-core#729]
#### Summary
ByteArrayAssert has a number of methods that take byte-parameters. However, since there is no byte-constant in java, you will have to cast each and every parameter value.

It would be useful to have integer-overloads of these methods.

#### Example

The first example does not work. The two next ones are workarounds.

```java
// Verify the magic number of a pdf-file by checking four first bytes
assertThat(fileContent).startsWith(0x25, 0x50, 0x44, 0x46);

// Java does not have byte constants, and ByteArrayAssert does not support integers, but...
assertThat(fileContent).startsWith((byte) 0x25, (byte) 0x50, (byte) 0x44, (byte) 0x46);
assertThat(fileContent).startsWith(new byte[] { 0x25, 0x50, 0x44, 0x46 });
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
I'm currently working on a pull request with this feature.

**Comment by joel-costigliola** [comment]
Done
