### ISSUE TITLE
Avoid casting when assert field on base type single objects

### ISSUE THREAD

**Issue by tomaszszlek** [joel-costigliola/assertj-core#730]
#### Summary
Hi,
I have proposal of some improvement regarding field assertions on single object.
Now when some type is not known we can do following assert:

#### Example

```java
assertThat(throwable).isInstanceOf(MyException.class);
assertThat(((MyException) throwable).getErrorCode())
		.isEqualTo(someCode);
```

what do you think to add feature which would avoid to cast explicitly ?, for example:

```java
assertThat(throwable).isInstanceOf(MyException.class).extracting("errorCode").isEqualTo(someCode);
```

It could work in similar way as 'extract' for collections.

Thanks,
Tomek

**Comment by joel-costigliola** [comment]
is your feature covered by https://github.com/joel-costigliola/assertj-core/issues/683 ?

**Comment by tomaszszlek** [comment]
Yes it is. I am sorry but didn't notice that similar task is already created. Anyway what do you think about implement my proposition as well as it could be handy and considered as some kind of shortcut of #683 solution ? For example we could do following : 
`
assertThat(throwable).extracting("errorCode").isEqualTo(someCode);
`

**Comment by joel-costigliola** [comment]
hey, no pb.

I guess having `extracting` on `Object` assertion makes sense to avoid casting your object and to have access to private fields.

**Comment by tomaszszlek** [comment]
Hey, 

thanks, I see that `assertThat(Throwable actual)` doesn't have such extracting method while abstract `assertThat(T actual)` has it already so adding this feature will make these two consistent :)

**Comment by joel-costigliola** [comment]
`extracting` already exist for `Object` indeed :flushed:.

the good news for you is that it is also available for `Throwable` assertions since 2.5.0/3.5.0 (#663) so I guess you are not using 2.5.0/3.5.0, right ?

**Comment by tomaszszlek** [comment]
oh ok, you are right, I am using 3.3.0. So it looks like we can close this ticket ? :)
My bad actually as I didn't check the latest 3.5.* version ;)

**Comment by joel-costigliola** [comment]
closed :)
