### ISSUE TITLE
Add a pluggable strategy for how to handle #equals

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#734]
>A pluggable strategy for how to handle Equals would be ideal. I have JAXB generated classes that I would like to compare so I cannot introduce equals methods into them as the files are generated. Being able to add a custom equals like I am able to do with compare.

requested by derekbassett in https://github.com/joel-costigliola/assertj-core/issues/646

**Comment by joel-costigliola** [comment]
Does `usingComparatorForType` and `usingComparatorForFields` along with `isEqualToComparingFieldByField` address this concern ? If not what can we add/improve ?

**Comment by PascalSchumacher** [comment]
I guess it does.

**Comment by derekbassett** [comment]
Sorry I just received this.
No it does not because it requires if I am checking any deep objects I can't control what I am doing to make equals.  You have this capability with compare and passing in a Comparator.  I don't understand why this would be difficult for Equals.

**Comment by joel-costigliola** [comment]
@derekbassett  I'm not sure I understand your answer, what it is that you are not controling ? can you clarify ? An example would help.

**Comment by derekbassett** [comment]
Yes give me tomorrow and I will write one up.

**Comment by joel-costigliola** [comment]
:+1:
