### ISSUE TITLE
Illegal Map comparison when using `isEqualToComparingFieldByFieldRecursively` 

### ISSUE THREAD

**Issue by acc15** [joel-costigliola/assertj-core#737]
#### Summary

Map comparison is broken when using `isEqualToComparingFieldByFieldRecursively` 

May be i misunderstand this feature, but i think that Map's (and any java Collection) must be handled by `equals` without comparing them field-by-field, at least this is common behavior which everybody will expect - imho.
#### Example

``` java
class A {
    Map<Integer, Boolean> map;
}

@Test
void test1() {
    A a = new A(), b = new A();
    a.map = new HashMap<>();
    a.map.put(1, true);

    b.map = new TreeMap<>();
    b.map.put(1, true);

    assertThat(a).isEqualToComparingFieldByFieldRecursively(b);
}
```

Produces this output:

```
Path to difference:  <map>
- expected: <{1=true}>
- actual  : <{1=true}>
```

**Comment by joel-costigliola** [comment]
The library that is used for recursive comparison comes from https://github.com/jdereg/java-util, it does compare collection and maps by their content, it is not using their `equals` method.

Is that a desired behaviour ? I think so as the recursive comparison is about content, the javadoc should be improved to make this clear. Would that work for you ?

You can use [`usingComparatorForType(comparator, type)`](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.4.0-usingComparatorForType) if you need to introduce a specific comparison strategy.

**Comment by acc15** [comment]
I've tried  `usingComparatorForType(comparator, type)` and `usingComparatorForFields(comparator, fields)` without success - its just ignores this.

**Comment by acc15** [comment]
Oh, i've take a look at difference detection code..

org.assertj.core.internal.DeepDifference

      if (key1 instanceof SortedMap) {
        if (!(key2 instanceof SortedMap)) {
          differences.add(new Difference(currentPath, key1, key2));
          continue;
        }
      } else if (key2 instanceof SortedMap) {
        differences.add(new Difference(currentPath, key1, key2));
        continue;
      }

      if (key1 instanceof Map) {
        if (!(key2 instanceof Map)) {
          differences.add(new Difference(currentPath, key1, key2));
          continue;
        }
      } else if (key2 instanceof Map) {
        differences.add(new Difference(currentPath, key1, key2));
        continue;
      }


It's makes a difference between `SortedMap` and `Map`. As i understand this is by design but why and for what?

**Comment by joel-costigliola** [comment]
This code comes from https://github.com/jdereg/java-util, my guess is that if you have a sorted map you want to take the order into account but it should be able to compare the content of a sorted map and a regular one, I consider this is a bug then.

We will also check `usingComparatorForType` behaviour, should work.

**Comment by PascalSchumacher** [comment]
Yes `SortedMap`s are only considered equal if they both have the same elements in the same order. The `instanceof` checks are just a performance optimization. 

Taking this into consideration I do not think it makes sense to compare a sorted to a unsorted map (at least if one map contains more that one element).

**Comment by PascalSchumacher** [comment]
https://github.com/joel-costigliola/assertj-core/pull/764 makes it possible to use a custom comparator for a concrete collection or map type. 

Adding support for registering a comparator for an interface like `Map` that is then used for all classes implementing it would be a lot more work. The simple check in https://github.com/joel-costigliola/assertj-core/blob/ff021db1c1cbe02b24998228d5659f5eca00d0a6/src/main/java/org/assertj/core/internal/DeepDifference.java#L305 would have to be significantly extended.

**Comment by acc15** [comment]
> Taking this into consideration I do not think it makes sense to compare a sorted to a unsorted map (at least if one map contains more that one element).

Well, may be...

But i think that comparison must be consistent with `equals`, which doesnt take any order into account at all (if you compare two TreeMap's with different Comparators but same elements - equals will return true)

**Comment by joel-costigliola** [comment]
I haven't made up my mind on what the proper behaviour should be, for the time being I think it should compare map content as the recursive comparison is about content.

**Comment by joel-costigliola** [comment]
My thoughts on this one have changed a bit, I tend to think that the actual behavior is ok (I now agree with @PascalSchumacher comment).

If we were to allow comparing sorted and unsorted maps then for the sake of consistency we should also comparing set and sorted set, and why not list vs set. Basically `isEqualToComparingFieldByFieldRecursively` is expecting fields of actual and expected to have the same type.

What we could do instead is to improve the error message for two unequal fields wit the same string representation by adding the field's type.

**Comment by joel-costigliola** [comment]
Error message has been improved and now show differences more accurately when standard fields description happened to be the same, in the given example that gives:
```
Path to difference: <map>
- expected: <{1=true} (TreeMap@4ce)>
- actual  : <{1=true} (HashMap@4ce)>
```
The type and hash code have been added to disambiguate the fields description when their default representation was identical.

**Comment by acc15** [comment]
> Basically isEqualToComparingFieldByFieldRecursively is expecting fields of actual and expected to have the same type.

Ok. Then following test must fail: 

    interface XAble {
        int getX();
    }
    
    class A implements XAble {
        final int x;
    
        public A(int x) {
            this.x = x;
        }
    
        public int getX() {
            return x;
        }
    }
    
    class B implements XAble {
        final int x;
    
        public B(int x) {
            this.x = x;
        }
    
        public int getX() {
            return x;
        }
    }
    
    class C {
    
        final XAble v;
    
        public C(XAble v) {
            this.v = v;
        }
    
        public XAble getV() {
            return v;
        }
    }
    
    public class IsEqualToComparingFieldByFieldRecursively {
    
        @Test
        public void testIsEqualToComparingFieldByFieldRecursively() throws Exception {
            final C c1 = new C(new A(15));
            final C c2 = new C(new B(15));
            assertThat(c1).isEqualToComparingFieldByFieldRecursively(c2);
        }
    }

But it doesnt... Passed
