### ISSUE TITLE
isCloseTo doesn't work with arrays

### ISSUE THREAD

**Issue by lukehutch** [joel-costigliola/assertj-core#738]
#### Summary
```
double[] x = ...;
double[] y = ...;
// This doesn't compile:
assertThat(x).isCloseTo(y);
```

#### Example
Without this, you get errors like:

```
org.junit.ComparisonFailure: expected:<...0.5, 0.5, 0.75, 0.25[, 0.75, 0.25]]>
    but was:<...0.5, 0.5, 0.75, 0.25[000000000000006, 0.75, 0.25000000000000006]]>
```

#### Java 8 specific ?
* NO

**Comment by joel-costigliola** [comment]
There is indeed no `isCloseTo` for arrays of numbers.

I'm curious: how would you define `isCloseTo` mean for arrays ?

**Comment by lukehutch** [comment]
I would expect the semantics to work element-wise, the same way that the regular isCloseTo works for scalars. (You could define other metrics to measure similarity between matrices, e.g. an L_2 norm, but I think the element-wise max difference makes the most sense as a sane default.) i.e. the assertion would fail if there was a difference in any given element position of greater than a specified epsilon. The assertion would also fail if the arrays were of different sizes.

It probably makes sense to provide support for at least 1D, 2D and 3D  matrices.

**Comment by joel-costigliola** [comment]
That makes sense, do you want to contribute ? (that's ok if you can't)

**Comment by lukehutch** [comment]
I figured why not, I'll give this a shot. I just spent the last 45 minutes setting up an AssertJ Eclipse project and figuring out how to write this, then I realized that containsExactly with a precision argument already does this exact thing. It's probably not ideal to duplicate the API for containsExactly in the form of isCloseTo. What do you think?

As an aside, it would make it much easier to hack on AssertJ if you check in the Eclipse project files/dirs (.project, .classpath, .settings) into GitHub. Then Eclipse can immediately find the existing project from the git URL, set it up automatically with Maven and with the correct classpath for running tests, etc.

**Comment by PascalSchumacher** [comment]
@joel-costigliola I guess this can be closed?

**Comment by joel-costigliola** [comment]
Sorry I did not remember `containsExactly` already supported that (facepalm)

The API is already big enough to avoid adding duplicate unless I have a very good case.

I have added the eclipse project files (but it's easy to import the project in eclipse in you have a maven plugin).

**Comment by lukehutch** [comment]
All good, thanks!
