### ISSUE TITLE
[java8] assertThat is ambiguous for Comparable

### ISSUE THREAD

**Issue by grzechol** [joel-costigliola/assertj-core#745]
#### Summary
Custom assertion for class implementing Comparable causes compilation errors under Java 8. This happens only when Comparable class is parametrized. Tested with assertj-core 3.5.2

#### Example

```java
public class MyClass<T> implements Comparable<MyClass<T>> {
    @Override
    public int compareTo(MyClass<T> o) {
        return 0;
    }
}
public class MyClassAssert extends AbstractAssert<MyClassAssert, MyClass<?>> {
    public MyClassAssert(MyClass<?> actual) {
        super(actual, MyClassAssert.class);
    }
}
public class MyAssert extends org.assertj.core.api.Assertions {
    public static MyClassAssert assertThat(MyClass<?> myClass) {
        return new MyClassAssert(myClass);
    }
}

import static MyAssert.assertThat;
public class MyClassTest {
    public static void test() {
        assertThat("abc").isEqualTo("abc");
        MyClass<String> myObj = new MyClass<>();
        assertThat(myObj).isEqualTo(myObj);
    }

```
[ERROR] MyClassTest.java:[6,9] reference to assertThat is ambiguous
[ERROR] both method assertThat(MyClass<?>) in MyAssert and method <T>assertThat(T) in org.assertj.core.api.Assertions match

#### Java 8 specific ?
YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
I know Java 8 is stricter than Java 7 concerning generics, gut feeling is this is the same as https://github.com/joel-costigliola/assertj-core/issues/365 but I haven't fully analysed the problem.

**Comment by filiphr** [comment]
@grzechol did you writ the asserter by yourself or was it written by the generator? If you replace

``` java
public class MyAssert extends org.assertj.core.api.Assertions {
    public static MyClassAssert assertThat(MyClass<?> myClass) {
        return new MyClassAssert(myClass);
    }
}
```

With:
``` java
public class MyAssert extends org.assertj.core.api.Assertions {
    public <T> static MyClassAssert assertThat(MyClass<T> myClass) {
        return new MyClassAssert(myClass);
    }
}
```

**Comment by joel-costigliola** [comment]
@filiphr thanks for the investigation !
@grzechol clising this issue but I'll be happy to reopen it if you find it should.
