### ISSUE TITLE
Add extractingValue() for `Optional` assertions

### ISSUE THREAD

**Issue by mkobit** [joel-costigliola/assertj-core#748]
#### Summary

It looks like this is already available in [`assertj-guava`](https://github.com/joel-costigliola/assertj-guava/blob/master/src/main/java/org/assertj/guava/api/OptionalAssert.java#L137).

Would like to see the same functionality available for Java 8 `Optional`s.
#### Example

``` java
final Path myPath = Paths.get("myPath");
assertThat(myPath).isPresent()
                               .extractingValue()
                               .endsWith(Paths.get("myPath"));
```
#### Java 8 specific ?
- YES : create Pull Request from the `master` branch

**Comment by mkobit** [comment]
This seems like it would be easy to implement, but I'd like to get your thoughts on the right direction for the API for `Optional` with current differences between the:

- [Guava `OptionalAssert`](https://github.com/joel-costigliola/assertj-guava/blob/master/src/main/java/org/assertj/guava/api/OptionalAssert.java)
- [Core `OptionalAssert`](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/OptionalAssert.java)

**Comment by joel-costigliola** [comment]
@mkobit due to Java generic limitations it is not possible to chain specific type assertions, only Object assertions, in your example it means you can't chain the `endsWith` call . 
Is the feature still valuable without specific type assertions ?

**Comment by mkobit** [comment]
That's a bummer.

I don't think the feature would be that valuable then because the fluent chaining is the valuable part.

Can you think of a different way to achieve similar functionality?

**Comment by joel-costigliola** [comment]
there are two ways : 

1 / 
pass the assert type as a generic parameter : `extractingValue(T)`  where `T` is `StringAssert` to get `String` assertions, not elegant IMO as users need to know the assert types.

2 / 
add a bunch of methods like `extractingXXX()` where XXX is the value type, ex `extractingString()`, problem is it bloats the API and is not generic, it does not work with your custom assert type.

**Comment by joel-costigliola** [comment]
Closing this issue until we have an acceptable way of implementing it.
