### ISSUE TITLE
Add map(…) and flatMap(…) to OptionalAssert 

### ISSUE THREAD

**Issue by olivergierke** [joel-costigliola/assertj-core#751]
#### Summary

If you're dealing with `Optional`s whose values return `Optional`s, you end u with a lot of nesting. It would be cool if these could be flattened out like this:

#### Example

```java
Optiona<Foo> foo = Optional.of(foo);

assertThat(foo).hasValueSatisfying(it -> {
  assertThat(it.methodReturningAnOptional()).hasValueSatisfying(inner -> {
    assertThat(inner.methodReturningNoOptional()).isEqualTo(reference);
  }
}
```

Note, how you constantly have to nest expressions and also rewrap the values obtained from the method call into new asserts.

It would be cool if one could rather write this instead:

```java
assertThat(foo)
  .flatMap(it -> it.methodReturningAnOptional())
  .map(it -> it.methodReturningNoOptional())
  .isEqualTo(reference);
```

I currently have this custom assert class in my code to achieve this:

```java
public class OptionalAssert<T> extends AbstractAssert<OptionalAssert<T>, Optional<T>> {

  public OptionalAssert(Optional<T> actual) {
    super(actual, OptionalAssert.class);
  }

  public static <T> OptionalAssert<T> optionalAssertThat(Optional<T> optional) {
    return new OptionalAssert<T>(optional);
  }

  public <S> OptionalAssert<S> flatMap(Function<T, Optional<S>> function) {

    Assertions.assertThat(actual).isPresent();

    return optionalAssertThat(actual.flatMap(function));
  }

  public <S> AbstractObjectAssert<?, S> map(Function<T, S> function) {

    Assertions.assertThat(actual).isPresent();

    return Assertions.assertThat(actual.map(function).orElseThrow(() -> new IllegalStateException()));
  }
}
```

I guess that can be improved to report good error messages in case of a flat map step producing an empty `Optional`, but it does the trick for me now.

**Comment by olivergierke** [comment]
Oh, and the reason I rather want to map and flat map on the assertions is that it would allow to find out which mapping step produced the empty `Optional`, whereas when mapping on the `Optional` directly, that information is lost.

**Comment by joel-costigliola** [comment]
Good idea, `map` and `flatMap` will add more functional/fluent style to assertions which is nice.

**Comment by joel-costigliola** [comment]
@olivergierke the current implementation does not fail if `map` or `flatMap` produce an empty `Optional`, this is left to the user to check for that (chaining with `contains` assertion for example).

**Comment by joel-costigliola** [comment]
I'm closing the issue but might reopen it if needed.
