### ISSUE TITLE
Is Bean Validation Possible using Fluent assertion??

### ISSUE THREAD

**Issue by DevDik** [joel-costigliola/assertj-core#753]
#### Summary
Hi All,

I do not know whether it is very relevant question but is it possible to test bean validations.?

I have some bean validations on method input parameters in my class. Is it possible to unit test those validations. I tried searching few links but could not find something relevant to my class/method. 

Any lead/help on the same please...

#### Example

```java7

        @GET
	@Path("/{id}")
	@Produces(MediaType.APPLICATION_JSON)
	
	public MyClass getValue(
			@PathParam("id") @Pattern(regexp = "someRegex" message = "PatternValidationError") @NotNull(message = "NullValidationError") @Length(min = 9, max = 34, message = "LengthValidationError") String id) throws MyException {

//some code

}

I basically want to test @Pattern, @Null and @Length. 

```

**Comment by DevDik** [comment]
@joel-costigliola  @PascalSchumacher : Can you guys suggest something...:)

**Comment by joel-costigliola** [comment]
There is no support for bean validation, what I would do is test your method with different parameter values and check that it fails as expected by your validation rules.

**Comment by DevDik** [comment]
Thanks for the reply...I did find another way for doing this. Although, it would be great if can implement this within fluent assertions... :)

**Comment by onacit** [comment]
FYI, I wrote a small extension for Bean-Validation.
https://github.com/jinahya/assertj-bean-validation/tree/sketch

```java
assertBean(object).isValid();
assertThat(bean(object)).isValid();
```
