### ISSUE TITLE
ObjectArrayAssert: Allow extracting single value using Function

### ISSUE THREAD

**Issue by caugner** [joel-costigliola/assertj-core#755]
#### Summary

It should be possible to extract a single value in an [`ObjectArrayAssert`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1648-L1652) using a `Function`.

So far, there is only [`AbstractObjectArrayAssert#extracting(Function<T, ?>...)`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1704-L1716) which returns a `ObjectArrayAssert<Tuple>`, even if only one `Function` is given.

There are two solutions for this:
1. Change signature of [`AbstractObjectArrayAssert#extracting(Extractor<? super T, U>)`](https://github.com/joel-costigliola/assertj-core/blob/fe84371353fa3f74ea574e04a9480c986f77e6fb/src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java#L1648-L1652) to `AbstractObjectArrayAssert#extracting(Function<T, U>)`.
2. Add `AbstractObjectArrayAssert#extracting(Function<T, U>)`.

_Note_: For this, the [`FieldOrPropertiesExtractor`](https://github.com/joel-costigliola/assertj-core/blob/ff021db1c1cbe02b24998228d5659f5eca00d0a6/src/main/java/org/assertj/core/groups/FieldsOrPropertiesExtractor.java#L36) probably needs to be extended to support `Function`s.
#### Example

``` java
// Note: unchecked(Function<T,R>) wraps a Function and effectively removes exceptions 
// from its signature by wrapping these exceptions in a RuntimeException.

MimeMessage[] messages = fetchReceivedMessages(); // Fetches messages from GreenMail.

assertThat(messages)
  .as("Received messages")
  .hasSize(2)

  .extracting(unchecked(message -> (MimeMultipart) message.getContent())
  .as("Content of message")
  .isNotNull()

  .extracting(unchecked(content -> content.getBodyPart(0))
  .as("First body part of message")
  .isNotNull()

  .extracting(unchecked(body -> (String) body.getContent()))
  .as("Body of messages")
  .isNotNull()
  .allMatch(body -> body.contains("Powered by AssertJ.")); // Description requires #756
```
#### Java 8 specific ?
- YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
Well there is another variant `extracting(Extractor<? super T, U> extractor)` which allows to pass a lambda:

```java
TolkienCharacter[] fellowshipOfTheRingArray = fellowshipOfTheRing.toArray(new TolkienCharacter[0]);

assertThat(fellowshipOfTheRingArray).extracting(TolkienCharacter::getName)
                                    .contains("Boromir", "Sam", "Legolas");
```

Except for using JDK type, why would we add another variant using a `Function` ?

**Comment by caugner** [comment]
> Except for using JDK type, what would be the value of adding a variant using a Function ?

So basically my problem was that I needed to extract values using methods that (potentially) throw Exceptions, in this case:
* `javax.mail.internet.MimeMessage#getContent() throws IOException, MessagingException`,
* `javax.mail.internet.MimeMultipart#getBodyPart(int) throws MessagingException` and 
* `javax.mail.Part#getContent() throws IOException, MessagingException`.

This means, I couldn't just write:
```java
.extracting(message -> (MimeMultipart) message.getContent())
```
Rather, I had to catch the Exception(s):

```java
.extracting(message -> {
    try {
      return (MimeMultipart) message.getContent();
    } catch (IOException | MessagingException e) {
      throw new RuntimeException(e);
    }
  })
```

As this isn't really readable, I could have extracted this into to a `wrap` method (which I didn't have at hand back then):
```java
static <T, R, E extends Exception> Extractor<T, R> wrap(ThrowingFunction<T, R, E> function) {
	return new Extractor<T, R>() {

		@Override
		public R extract(T input) {
			try {
				return function.apply(input);
			} catch (Exception e) {
				throw new RuntimeException(e);
			}
		}
	};
}

@FunctionalInterface
public interface ThrowingFunction<T, R, E extends Exception> {
	R apply(T argument) throws E;
}
```

Then I can write:
```java
.extracting(wrap(message -> (MimeMultipart) message.getContent()))
```

Ultimately, to make a long story short: to solve this "problem" conveniently, maybe there could be a variant of the `Extractor<F, T>` interface that allows the `#extract(F input)` method to throw an Exception which could be caught e.g. in the `extracting(Extractor<? super T, U> extractor)` implementation?

```java
// org.assertj.core.api.iterable.Extractor
public interface ThrowingExtractor<F, T, E extends Exception> {
  T extract(F input) throws E;
}

// org.assertj.core.api.AbstractObjectArrayAssert
  public <U, E extends Exception> ObjectArrayAssert<U> extracting(ThrowingExtractor<? super T, U, E> extractor) {
    U[] extracted = FieldsOrPropertiesExtractor.extract(actual, extractor);

    return new ObjectArrayAssert<>(extracted);
}

// org.assertj.core.groups.FieldsOrPropertiesExtractor
  public static <F, T, E extends Exception> T[] extract(F[] objects, ThrowingExtractor<? super F, T, E> extractor) {    
    List<T> result = extract(newArrayList(objects), extractor);
    return toArray(result);
  }

  public static <F, T, E extends Exception> List<T> extract(Iterable<? extends F> objects, ThrowingExtractor<? super F, T, E> extractor) {
    List<T> result = Lists.newArrayList();
    
    for (F object : objects) {
      try {
        final T newValue = extractor.extract(object);
        result.add(newValue);
      } catch (Exception e) {
        throw new RemoteException(e);
      }
    }
    
    return result;
  }
```

Then I could finally write:
```java
.extracting(message -> (MimeMultipart) message.getContent())
```

**Comment by joel-costigliola** [comment]
I agree that would be handy, I like writing code in a functional style and I have been regularly bothered by checked exceptions

**Comment by scordio** [comment]
Hi @caugner, I came across https://github.com/assertj/assertj/issues/755#issuecomment-261728955 during the analysis of #1499, and I have a question for you 🙂 Some time has passed since then, let's see if I'm too optimistic...

Do you remember why you proposed the `E extends Exception` type parameter for `ThrowingExtractor`, instead of just having `Exception` in the method signature? E.g.:

```java
T extract(F input) throws Exception;
```

**Comment by caugner** [comment]
I haven't written Java in almost 10 years, but my idea might have been to only catch Exceptions of that type `E`, although I'm not sure if that's actually possible?

**Comment by scordio** [comment]
First and foremost, thanks for taking the time to answer, and so quickly!

Looking at the current implementation, I don't think the `apply` [implementation](https://github.com/assertj/assertj/blob/3441f4b32ca80ef3e95b3b4902dfe519820c1510/assertj-core/src/main/java/org/assertj/core/api/iterable/ThrowingExtractor.java#L35-L41) reflects that intention, and I'm also unsure if there is any way to achieve it.

For the use cases we intend to support, declaring `Exception` or even `Throwable` on the method signature should be enough. That's likely what we'll do to solve #1499.

Thanks again!
