### ISSUE TITLE
RFC: Allow SoftAssertions in chained assertions

### ISSUE THREAD

**Issue by caugner** [joel-costigliola/assertj-core#757]
#### Summary

It should be possible to use `SoftAssertions` in chained assertions, that is a way to continue assertion checking beyond the first failure in a chain of assertions and to propagate more than one failure to the `SoftAssertions` object.

So far, only the first failure in a chain of assertions will propagate to the `SoftAssertions` object.

There are two approaches for this:
1. Provide a method `AbstractAssert#collect()` that doesn't take any parameter, but activates a "soft mode" for all following assertions in the chain, so that all these assertions are checked and all failures are collected.
2. Provide a method `AbstractAssert#softly(Function<...>)` where the `Function` takes the current and provides another (possibly different) `Assert` object and all assertions in there are collected.
#### Example

(_Note_: Let `assertThat(email)` return an instance of `EmailAssert` that extends `AbstractAssert`.)

For approach 1:

``` java
softly.assertThat(email)
  .collect()
  .hasFrom("sender@example.com")
  .hasTo("recipient@example.com")
  .hasSubject("Message from Sender to Recipient")
```

For approach 2:

``` java
softly.assertThat(email)
  .softly(assertThatEmail -> assertThatEmail
    .hasFrom("sender@example.com")
    .hasTo("recipient@example.com")
    .hasSubject("Message from Sender to Recipient")
  )
```

In general, this could be rewritten as follows:

``` java
softly.assertThat(email).hasFrom("sender@example.com");
softly.assertThat(email).hasTo("sender@example.com");
softly.assertThat(email).hasSubject("sender@example.com");
```

However, this workaround is no longer applicable when `#extracting(...)` is used.
#### Java 8 specific ?
- Approach 1: NO  : create Pull Request from the `2.x` branch
- Approach 2: YES : create Pull Request from the `master` branch

**Comment by filiphr** [comment]
@caugner I think that your workaround is not applicable to `#extracting(...)` because those methods create a new instance of an `Assert` which is no longer wrapped in a proxy.

**Comment by joel-costigliola** [comment]
Ideally that should work out of the box, I would be ok for approach 1 but I don't like approach 2, it is too verbose.

A spike is needed to see if we can support this out of the box without introducing `collect()`.

**Comment by filiphr** [comment]
In order to support this out of the box, I think that we need to wrap the assertions themselves into a proxy and not the asserters. If the internals are wrapped, then the chaining can continue.

**Comment by fiery-phoenix** [comment]
Below test seems to work on trunk (code is available at [):](https://github.com/fiery-phoenix/assertj-core/blob/dfa55cc30bbd6ab55fc2bbeea2c24d87949155d2/src/test/java/org/assertj/core/temp/ChainedSoftAssertionTest.java), though I might have misunderstood the problem.

`  
  @Test
  public void should_work_with_chained_assertions() {
    Email email = new Email("from@example.com", "to@example.com", "Message from Sender to Recipient");

    softly.assertThat(email)
      .hasFrom("sender@example.com")
      .hasTo("recipient@example.com")
      .hasSubject("Message from Sender to Recipient")
      .extracting("from", "to")
      .contains("sender@example.com")
      .hasAtLeastOneElementOfType(String.class)
      .doesNotContain("to@example.com");

    try {
      softly.assertAll();
      shouldHaveThrown(SoftAssertionError.class);
    } catch (SoftAssertionError e) {
      assertThat(e.getErrors()).hasSize(4);
    }
  }
`

**Comment by caugner** [comment]
> Below test seems to work on trunk (...), though I might have misunderstood the problem.

Thank you very much, your test works fine for me as well. Unfortunately, I cannot reproduce why I had the impression that it doesn't work, so I'll close this issue. Sorry for the trouble!

**Comment by fiery-phoenix** [comment]
No trouble at all, glad that it worked for you as well :)
