### ISSUE TITLE
usingComparatorForType is not used with registered type's subclasses

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#758]
#### Summary

`usingComparatorForType` should work with registered type subclasses too.

http://stackoverflow.com/questions/39490785/using-assertj-usingcomparatorfortype-method-with-inheritance

**Comment by filiphr** [comment]
@joel-costigliola, I have one idea how this can be done. I am working on a PR right now and wanted to consult with you. I was thinking to add an internal custom map or some other wrapper over a map which when doing the get will return either the direct `comparator` (if there is a key for this in the map), or will return the first `comparator` for which the key is assignable.

There are 2 ways, that I thought of, for this to be done:
* We extend Map directly and make sure that we change the internals everywhere (when creating the map) 
* We add a wrapper and make the internals use this wrapper (`OnFieldsComparator`, `RecursiveFieldByFieldComparator`, `IgnoringFieldsComparator`, `FieldByFieldComparator`) the ones I mention have the map in the constructor. This would be a breaking change for someone that is using the `internal` package. I think that with the second approach it would be easier not to make a mistake in the future.

**Comment by joel-costigliola** [comment]
I would definitely prefer the second option, just to be sure we are on the same page, instead of using a `Map<Class<?>, Comparator<?>>` we would have a class whose job will be to store comparators and give the most relevant one, my first ideas for naming this class are `TypeComparators` or `TypeComparatorRegistry`.

**Comment by filiphr** [comment]
Yes this is my idea exactly. Using a class to store comparators giving the most relevant one, we'll need to specify what most relevant is though. Should it be by insertion order, should we go up the inheritance chain (class and interface) to find the most relevant one or something else. 

The naming sounds really good. To me `TypeComparators` sounds better, `TypeComparatorRegistry` for me looks like some `Registry` for the entire framework, not for one class.

I'll start on the second option and will do a PR.

**Comment by joel-costigliola** [comment]
Relevance should be on inheritance chain, the closer the better.

**Comment by PascalSchumacher** [comment]
Another important question is what should happen if the there are two comparators with the same distance in the inheritance chain.

**Comment by joel-costigliola** [comment]
True but I would not expect users to register many comparators with the same priority very frequently, if that happens we should use the insertion order, anyway users can always register one for the exact type to solve the ambiguity.

**Comment by filiphr** [comment]
@PascalSchumacher, the current implementation of the `TypeComparators` goes up the class inheritance first, and then checks the interfaces. The order of the interfaces in the `implements` and/or `extends` is maintained. What would be the same distance in the inheritance chain? There is always some order even for the interfaces.

For example:
``` java
interface I1 {}
interface I2 {}
interface I3 extends I1, I2 {}
class A implements I2 {}
class B extends A implements I1 {}
class C extends B implements I3 {}
```

If a comparator for `A` is provided then that comparator is returned for `C` and `B`. If a comparator for `I1` and `I2`, then we have:
* For `C` -> the one for `I1`
* For `B` -> the one for `I1`
* For `C` -> the one for `I2`

**Comment by PascalSchumacher** [comment]
@filiphr E.g. if a class implements two interfaces and there is a comparator for each interfaces. Then the distance to both is the same. But I guess the case is very unlikely.

**Comment by filiphr** [comment]
@PascalSchumacher in the PR the [`Class.getInterfaces`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getInterfaces--) is used. So that order is taken into consideration and not the insertion order of the comparators.
