### ISSUE TITLE
StackOverflowError in StandardRepresentation

### ISSUE THREAD

**Issue by trustin** [joel-costigliola/assertj-core#762]
#### Summary

`StandardRepresentation.toStringOf(CompletableFuture)` can trigger a `StackOverflowError` when AssertJ tries to stringify a future whose result is itself.

`toStringOf(CompletableFuture)` should not try to recurse if the result of `CompletableFuture.join()` is itself (or any `CompletableFuture`?)

#### Example

```java
CompletableFuture f = new CompletableFuture();
f.complete(f);
new StandardRepresentation().toStringOf(f); // will throw a StackOverflowError.
```

#### Java 8 specific ?

I guess no, but I tried it only on Java 8.

**Comment by joel-costigliola** [comment]
Good catch ! will be fixed in the next 3.x release

**Comment by trustin** [comment]
@joel-costigliola Thanks a lot!
