### ISSUE TITLE
assertThatExceptionOfType/assertThatThrownBy does not allow the description

### ISSUE THREAD

**Issue by luengnat** [joel-costigliola/assertj-core#763]
#### Summary

assertThatExceptionOfType/assertThatThrownBy does not allow the error description to be specified.
#### Example

``` java

Assertions.assertThatThrownBy(() -> throw new Exception())
.describeAs("should give this error message");

```

The above example does not give the expected error message.
#### Java 8 specific ?
- YES : create Pull Request from the `master` branch
- NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
With the current implementation it is not possible to specify the assertion description as `assertThatThrownBy` fail directly if no exception is thrown, can you confirm this is what you would like to have ? 

To support that, we would need to introduce a second parameter : `assertThatThrownBy(lamda, "assertion description")`.

**Comment by PascalSchumacher** [comment]
@luengnat It would be nice if you could answer Joels question. Thanks in advance!

**Comment by joel-costigliola** [comment]
`assertThatExceptionOfType ` supports description since 363c756d39401e3c53f5140b7a190c8ec233218a, I'm adding `assertThatThrownBy(lambda, "assertion description")` even though it is possible to use `assertThatCode` to achieve the same result.
