### ISSUE TITLE
Cannot modify maxLengthForSingleLineDescription

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#768]
While adding more tests for the `StandardRepresentation` I realized that the `maxLengthForSingleLineDescription` cannot be set, because the the check was wrong. 

I have already made a fix for it together with some new tests that provide more coverage to the `StandardRepresentation`. The fix is in filiphr/assertj-core@4485bd2. Will provide a PR once #767 is merged (I am using the new AbstractBaseRepresentationTest)

**Comment by joel-costigliola** [comment]
fixed with https://github.com/joel-costigliola/assertj-core/pull/767

**Comment by filiphr** [comment]
@joel-costigliola great. There are some more tests in my branch, do you want me to make a PR with them?

**Comment by joel-costigliola** [comment]
would be great ! :+1:

**Comment by filiphr** [comment]
@joel-costigliola done, see PR #776
