### ISSUE TITLE
Extraction of nested field/property combination fails

### ISSUE THREAD

**Issue by dipak-pawar** [joel-costigliola/assertj-core#769]
#### Summary
Getting exception when calling `class.simplename, class.typename` on extraction even class has getSimpleName, getTypeName methods.

Exception ==>        
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'simplename'.
Error when introspecting properties was :
- No getter for property 'simplename' in java.lang.Class 
Error when introspecting fields was :
- Unable to obtain the value of the field <'simplename'> from <class java.lang.String>

#### Example
```java
List<String> list = new ArrayList<>();
 list.add("foo");
 list.add("bar");
 assertThat(list).hasSize(2).extracting("class.simplename").contains("String" , "String");
```

#### Java 8 specific ?
No
* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Hi @dipak-pawar 

You need to respect property name case, it works with `class.simpleName`.

Regards

**Comment by dipak-pawar** [comment]
hey @joel-costigliola , It works thanks.
