### ISSUE TITLE
`contains` check on a Collection<? extends Base> gives compiler error

### ISSUE THREAD

**Issue by igormukhin** [joel-costigliola/assertj-core#772]
#### Summary

The example below gives a compiler error. 

But if you do a simple `list.contains(new ContreteBase())`, the program compiles. May be because the method is defined as List.contains(Object o) and not List.contains(E o).

Is there solution for that assertion case in AssertJ already?
#### Example

``` java
public class GenericsHell {

    void aMethod() {
        List<? extends Base> list = new ArrayList<>();

        // Error:(17, 37) java: The method contains(capture#1-of ? extends Base...) in the type org.assertj.core.api.AbstractIterableAssert<capture#2-of ?,java.util.List<? extends capture#1-of ? extends Base>,capture#1-of ? extends Base,org.assertj.core.api.ObjectAssert<capture#1-of ? extends Base>> is not applicable for the arguments (ContreteBase)
        Assertions.assertThat(list).contains(new ContreteBase());
    }

}

interface Base {
}

class ContreteBase implements Base {
}
```

**Comment by joel-costigliola** [comment]
I think the only solution would be to use `Object` instead of the generic type in `contains`, this has been done for `isEqualTo` but not for any collection assertions, for the time being there is no plan to make collection assertions to take `Object` type parameter (I'm opened to change this if a majority of users wants it).

Anyway, the not-so-nice workaround is to cast your collection to a `List<Base>` or `List<Object>`.

**Comment by igormukhin** [comment]
@joel-costigliola Yes, you need to cast it to `List<Base>` and suppress the warning for the unchecked operation. Ok, let's see if others need it.

**Comment by hadadil** [comment]
+1

**Comment by joel-costigliola** [comment]
So far I feel most of the users expect generics assertions.
Anyone, feel free to comment on this to prove me wrong.

**Comment by chkpnt** [comment]
I'm new to `AssertJ`, so sorry for the question: Is the cast to `List<Base>` outside of AssertJ still the only option, or is there now a better or an AssertJ-way to narrow down the wildcard?
