### ISSUE TITLE
Expand Optional assertion api to include Conditions

### ISSUE THREAD

**Issue by at-alexb** [joel-costigliola/assertj-core#774]
#### Summary

The existing `Optional` assertion api includes `hasValue` and `hasValueSatisfying`. It would be nice to expand it to include `Condition`s.

This second method does allow a lamba or method reference (e.g. `Condition::matches`) to be written that asserts `Condition`s against the optional value, but I think not needing to do this is more readable.

#### Example

Assumes a method `jsonProperty` that returns a `Condition` checking a particular value in some JSON.

```java
Optional<JSON> json = maybeCreateSomeJson();
assertThat(json).hasValue(jsonProperty("$.property", "value"));
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
I agree but not with `hasValue`, I would use `matches` instead.

**Comment by filiphr** [comment]
There is already the `matches` method that accepts the actual object being asserted. So in this case the `Predicate<Optional<T>>`. So theoretically if the method `jsonProperty("$.property", "value")` returns a predicate it will work.

Or maybe having a method `matches(T)` would be preferred?

**Comment by joel-costigliola** [comment]
The thing with `Condition` is that you can combine them (predicate too but they offer less possibilities) and they can hold a description but other than that you are right.

@at-alexb thoughts ?

**Comment by at-alexb** [comment]
@filiphr assertj also already has an API for making `Optional` assertions, so we're using our `Condition` method with that at the moment like this:

`assertThat(json).hasValueSatisfying(jsonProperty("$.property", "value")::matches);`

It feels a little bit more indirect to read and write versus having a method that directly accepts a `Condition` and as @joel-costigliola mentions, the other advantage `Condition`s would have here is the description they come with. 

E.g. here we pass through the selection string so that test failures describe the mismatching property directly when the test fails.

**Comment by at-alexb** [comment]
Actually,  maybe `matches` isn't quite the right name? Perhaps the method should be `hasValueMatching` so it follows the naming of the other methods that automatically 'unwrap' the `Optional`?

**Comment by joel-costigliola** [comment]
yeah, I'm not too happy with `matches`, I'm thinking to keep `hasValueSatisfying` but with a `Condition` parameter (obviously).

**Comment by fiery-phoenix** [comment]
If method extractingValue() was present, it would be possible to write smth like:

assertThat(Optional.of("something")).extractingValue().is(passingCondition);
assertThat(Optional.of("something")).extractingValue().isNot(notPassingCondition);
assertThat(Optional.of("something")).extractingValue().satisfies(s -> {
      assertThat(s).isEqualTo("something")
                   .startsWith("some")
                   .endsWith("thing");
    }); // AbstractOptionalAssert#hasValueSatisfying(Consumer<T> requirement) could have been removed

what do you think?

**Comment by joel-costigliola** [comment]
That could work, it requires two method calls instead of one though.

**Comment by fiery-phoenix** [comment]
Actually, that is why I was asking for an opinion :)

**Comment by joel-costigliola** [comment]
I'm also reluctant to add `extractingValue` because you can't chain type specific assertions after it.

**Comment by fiery-phoenix** [comment]
Yes, generics have their limitations... Ok, will create a pull request with overloaded `hasValueSatisfying`, and will leave a comment about extractingValue() as a food for thought, as I still prefer reusing existing functionality.
