### ISSUE TITLE
assertThatExceptionOfType does not show stack trace when unexpected exception thrown

### ISSUE THREAD

**Issue by hatchy** [joel-costigliola/assertj-core#791]
#### Summary
The ```assertThatExceptionOfType``` does not show the stack trace of an unexpected exception.  

In the example output below it is difficult to see what threw the ```UnsupportedOperationException``` and diagnose the problem.

#### Example

```java
java.lang.AssertionError: 
Expecting:
 <java.lang.UnsupportedOperationException>
to be an instance of:
 <java.lang.IllegalArgumentException>
but was instance of:
 <java.lang.UnsupportedOperationException>
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Can you give an example of a more helpful error message ?

**Comment by hatchy** [comment]
I was thinking about two possible approaches.

Having the stack trace as a separate message at the end:
```java
java.lang.AssertionError: 
Expecting:
 <java.lang.UnsupportedOperationException>
to be an instance of:
 <java.lang.IllegalArgumentException>
but was instance of:
 <java.lang.UnsupportedOperationException>
full stack trace:
 <java.lang.UnsupportedOperationException
	at mu.app.MyClass.myMethod(MyClass.java:52)
	at mu.app.MyClass.callingMethod(MyClass.java:143)
  ...>
```

Or, replacing ```but was instance of:``` with ```but was:``` and printing the full stack trace.
```java
java.lang.AssertionError: 
Expecting:
 <java.lang.UnsupportedOperationException>
to be an instance of:
 <java.lang.IllegalArgumentException>
but was:
 <java.lang.UnsupportedOperationException
	at mu.app.MyClass.myMethod(MyClass.java:52)
	at mu.app.MyClass.callingMethod(MyClass.java:143)
  ...>
```

Let me know your thoughts.

**Comment by joel-costigliola** [comment]
I'll go for the second option, the exception type is not repeated

**Comment by hatchy** [comment]
Thanks for the quick response! 👍
