### ISSUE TITLE
String.matches() fails on strings with parenthesis or brackets

### ISSUE THREAD

**Issue by fnl** [joel-costigliola/assertj-core#793]
#### Summary

See title; The below example fails using `org.assertj:assertj-core:3.5.2`; Similar, if using square or curly brackets.

#### Example

```java
    @Test
    public void example() {
        assertThat("this(string)here").matches("this(string)here");
    }
```

#### Java 8 specific ?

(I'm using Java 8)

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by ptemplier** [comment]
The regexp is invalid and needs escaping like this

```
    @Test
    public void example() {
        assertThat("this(string)here").matches("this[(]string[)]here");
        assertThat("this(string)here").matches("this\\(string\\)here");
    }
```

**Comment by joel-costigliola** [comment]
Thanks @ptemplier for the answer !

**Comment by fnl** [comment]
Thanks for clarifying! Hope I didn't just miss that hint about escaping in the docs...
