### ISSUE TITLE
add isCloseTo assertion for Java 8 java.time.* types

### ISSUE THREAD

**Issue by xak2000** [joel-costigliola/assertj-core#796]
#### Summary

Add `isCloseTo` assertion for java 8 `java.time.*` types the [same way](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/AbstractDateAssert.java#L2155) as for `java.util.Date`.

Preferably for all types of [java.time](http://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) package.

Most important types are:

- [ ] Instant
- [ ] LocalDate
- [ ] LocalDateTime
- [ ] LocalTime
- [ ] ZonedDateTime

#### Example

```java
Instant instant1 = Instant.now();
Instant instant2 = Instant.now();
assertThat(instant1).isCloseTo(instant2, 100); // 100 ms
```

Instead of:
```java
assertThat(instant1.toEpochMilli()).isCloseTo(instant2.toEpochMilli(), within(100L));
```
which also is not null-safe.

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
agreed.

**Comment by PascalSchumacher** [comment]
Thanks to @fiery-phoenix pull request which added this for all  `java.time.*` classes supported by AssertJ I think this can be closed. `Instant` is no supported yet, but this should be a different issue I think.

**Comment by joel-costigliola** [comment]
agreed : https://github.com/joel-costigliola/assertj-core/issues/903
