### ISSUE TITLE
filteredOn(Predicate) is not working on IterableAssert

### ISSUE THREAD

**Issue by lmalgras** [joel-costigliola/assertj-core#808]
#### Summary
Using method filteredOn(Predicate) on an instance of IterableAssert results in `java.lang.ClassCastException: org.assertj.core.api.ListAssert cannot be cast to org.assertj.core.api.IterableAssert`

#### Example
I have replaced List<Employee> by Set<Employee> on the javadoc example :
```java
Employee yoda   = new Employee(1L, new Name("Yoda"), 800);
Employee obiwan = new Employee(2L, new Name("Obiwan"), 800);
Employee luke   = new Employee(3L, new Name("Luke", "Skywalker"), 26);

Set<Employee> employees = newHashSet(yoda, luke, obiwan);

assertThat(employees).filteredOn(employee -> employee.getAge() > 100)
            .containsOnly(yoda, obiwan);
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this, it's a (stupid) bug, the return type of `filteredOn` should have been `AbstractListAssert`

**Comment by joel-costigliola** [comment]
To be clear this only works for `List` at the moment.

**Comment by joel-costigliola** [comment]
Fixed
