### ISSUE TITLE
Support for BigIntegers similar to BigDecimal?

### ISSUE THREAD

**Issue by toddobryan** [joel-costigliola/assertj-core#811]
Is there any reason `BigInteger`s don't have similar support to `BigDecimal`s? I just replaced all my `int`s in a project with `BigInteger`s (because of serialization/deserialization issues) and wrote some code to support `BigInteger` asserts that take `int`s, `long`s, and `String`s as the argument of `isEqualTo`. I'd be happy to donate my code back to the project, but want to make sure it's something people would want before I ask for permission to contribute at work.

**Comment by joel-costigliola** [comment]
The only reason is that no one requested it but it would be a welcome addition.

**Comment by PascalSchumacher** [comment]
@toddobryan Any updates?

**Comment by PascalSchumacher** [comment]
@joel-costigliola merged the pull request by @epeee

Thanks!
