### ISSUE TITLE
Improve error message for "optional.containsInstanceOf(clazz)"

### ISSUE THREAD

**Issue by elygre** [joel-costigliola/assertj-core#812]
#### Summary

The error message for OptionalAssert.containsInstanceOf() is less descriptive than the similar message for AbstractAssert.isInstanceOf. Pull request is in the works.

#### Example

Before change:

```java
Expecting Optional to contain a value of type Number.
at ...
```

After change:

```java
Expecting:
 <Optional>
to contain a value that is an instance of:
 <class java.lang.Number>
but did contain instance of:
 <class java.lang.String>
at ...
```

Existing isInstanceOf-message:

```java
Expecting:
 <"StringValue">
to be an instance of:
 <java.lang.Number>
but was instance of:
 <java.lang.String>
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Agreed !
