### ISSUE TITLE
NPE when describedAs(null)

### ISSUE THREAD

**Issue by juddgaddie** [joel-costigliola/assertj-core#815]
#### Summary
I would not expect this to throw an NPE.
The assertion is clearly valid the describedAs just provides additional information, in this case none.

A possible work around could be to implement a custom Description but syntactically this is ugly.

#### Example

```java
String someReturnedFailureMessage = null;
assertThat(1).describedAs(someReturnedFailureMessage).isEqualTo(1);
```

For comparison with JUnit Assert, does not throw an NPE:
```java
String someReturnedFailureMessage = null;
Assert.assertThat(someReturnedFailureMessage , 1, is(1));
```

**Comment by joel-costigliola** [comment]
I fail to see a use case for a null description, you could use `as(String description, Object... args)` like `as("%s", descThatCanBeNull)`.

**Comment by PascalSchumacher** [comment]
I guess this can be closed?

**Comment by juddgaddie** [comment]
I still think it shouldn't throw an NPE, but if people think otherwise than close the issue.

**Comment by joel-costigliola** [comment]
@juddgaddie rethinking of it, we could replace a null description by an empty String, is this what you expect ?

**Comment by juddgaddie** [comment]
As I showed in the first 2 code snippets I expect Assertj to not throw an NPE when a null description is passed in. Just like JUnit Assert. I'm not sure what you mean by "we could replace null description by an empty String" do you mean after it is passed in to describedAs?

**Comment by joel-costigliola** [comment]
to treat it as `assertThat(1).describedAs("")`
