### ISSUE TITLE
flatExtracting should support a Function

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#817]
#### Example

```

        assertThat(  logger.getAllLoggingEvents() )
            .extracting( LoggingEvent::getArguments )
            .flatExtracting( input -> input )
            .allMatch( Predicate.isEqual( "1" ) );
```

should be writeable as

```        
assertThat(  logger.getAllLoggingEvents() )
            .extracting( LoggingEvent::getArguments )
            .flatExtracting( Function.identity() )
            .allMatch( Predicate.isEqual( "1" ) );
```

or perhaps better

```
assertThat(  logger.getAllLoggingEvents() )
            .extracting( LoggingEvent::getArguments )
            .flatExtracting()
            .allMatch( Predicate.isEqual( "1" ) );
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
@xenoterracide  is there something preventing you to write :
```java
assertThat(logger.getAllLoggingEvents()).flatExtracting(LoggingEvent::getArguments)
                                        .allMatch(Predicate.isEqual( "1" ));
```

**Comment by xenoterracide** [comment]
huh, for some reason I hadn't considered doing it that way... just upgraded from 2.5 since spring platform is still on that... some of these methods seem less obvious coming from java 8 (extracting vs map), and hamcrest (I spent a ton of time looking for some way to do `everyItem` from hamcrest, and found `allMatch` only in 3.x. 

only other issue I noticed that if my `Predicate.isEquals( 1 )` it will fail in a way that makes the issue less obvious. Could potentially make a separate issue, or can close.

```
Expecting all elements of:
  <["1", "1", "1", "1", "1"]>
to match given predicate but this element did not:
  <"1">
```

just some comments

**Comment by joel-costigliola** [comment]
The `allMatch` error message will be improved, it should report all elements not matching the predicate (https://github.com/joel-costigliola/assertj-core/issues/816), is that what you were thinking of ?

**Comment by joel-costigliola** [comment]
Note that you can pass a predicate description to `allMatch` to improve the error message, ex 
```java
List<TolkienCharacter> hobbits = newArrayList(frodo, sam, pippin, sauron);
assertThat(hobbits).allMatch(character -> character.getRace() == HOBBIT, "hobbit");
```
error message
```
java.lang.AssertionError: 
Expecting all elements of:
  <[Frodo 33 years old Hobbit,
    Sam 38 years old Hobbit,
    Pippin 28 years old Hobbit,
    Sauron 50000 years old Maia]>
to match 'hobbit' predicate but this element did not:
  <Sauron 50000 years old Maia>
```

**Comment by xenoterracide** [comment]
no, it's not that it's more about the quoting, in both causes it says `"1"` but the reason the second one fails is that you're comparing a string to an integer, but nothing about the output implies that I'm looking at an integer. I'm thinking that primitives (or things that autobox) should not have quotes. Message would be

```
Expecting all elements of:
  <["1", "1", "1", "1", "1"]>
to match given predicate but this element did not:
  <1>
```

**Comment by xenoterracide** [comment]
wait... reading that now, seems stupid because it doesn't know what the predicate is... so never mind...

though, the `everyItem` syntax it could... but seems like an overkill addition.
