### ISSUE TITLE
Add isEqualToNormalizingNewlines assertion

### ISSUE THREAD

**Issue by mkordas** [joel-costigliola/assertj-core#818]
#### Summary

Sometimes it is useful to compare two strings and ignore os-specific newline differences to make test passing both on Windows and Linux. It would be enough to perform `.replaceAll("\\r\\n", "\n")` on both assertion arguments and then delegating to `isEqualTo`.

#### Example

```java
// pass
assertThat("a\r\nb").isEqualToNormalizingNewlines("a\nb")
assertThat("\n").isEqualToNormalizingNewlines("\r\n")

// fail
assertThat("\n").isEqualToNormalizingNewlines("")
assertThat("\r").isEqualToNormalizingNewlines("\n")
assertThat("a").isEqualToNormalizingNewlines("a\n")
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Yep, why not.

**Comment by xenoterracide** [comment]
Personally, I would prefer that the `isEqual` show the newlines as their escaped characters, as well as tabs and non breaking spaces, so that when white space differed you could more easily discern why.

I would also suggest that doing the substitution likely means a bug in the code caused by not using the line separator http://stackoverflow.com/a/10937340/206466, which can be used in `String.format( "%n")`, or directly.

**Comment by joel-costigliola** [comment]
@xenoterracide That is an interesting improvements, I would only show whitespace/newline character as escaped when the difference is only about them, I have created https://github.com/joel-costigliola/assertj-core/issues/854 to track this improvement.

**Comment by joel-costigliola** [comment]
@mkordas I think @xenoterracide has a point on code not using the line separator being a bug, do you have an example in mind where it would be a valid use case ?

**Comment by mkordas** [comment]
@joel-costigliola even if you use system line separator in your code, the newline characters of the files on the disk depend on Git's `core.autocrlf` setting. You may end up with a test that works under one setting and fails with other. And there are many usages when it doesn't matter if you print either `\n` or `\r\n`, as both display fine e.g. in console.
