### ISSUE TITLE
FieldByFieldRecursively comparator does not properly use comparatorForType when comparing Sets

### ISSUE THREAD

**Issue by lbilger** [joel-costigliola/assertj-core#841]
#### Summary
Consider the test case in the example below. The last assertion fails though it should succeed. I have debugged the issue and it seems to boil down to an issue in ```org.assertj.core.internal.DeepDifference#compareUnorderedCollection```. The method uses a hashCode created using the ```deepHashCode``` method, which does not consider the ```comparatorByPropertyOrField```or ```comparatorByType``` maps.
Two BigDecimals with same value but different scale are not equal and have different hash codes, but compareTo returns 0 for them. Thus, a comparison using the hash code will fail, while a comparison using a BigDecimal::compareTo comparator will succeed.

#### Example

```java
@Test
public void bigDecimal() {
	BigDecimal value1 = BigDecimal.valueOf(100);
	BigDecimal value2 = value1.setScale(2);

	assertThat(value1).isNotEqualTo(value2);
	assertThat(value1.hashCode()).isNotEqualTo(value2.hashCode());
	assertThat(value1).isEqualByComparingTo(value2);
	
	class Foo {
		private final BigDecimal value;

		Foo(BigDecimal value) {
			this.value = value;
		}

		BigDecimal getValue() {
			return value;
		}
	}

	Foo foo1 = new Foo(value1);
	Foo foo2 = new Foo(value2);

	assertThat(foo1)
			.usingComparatorForType(BigDecimal::compareTo, BigDecimal.class)
			.isEqualToComparingFieldByFieldRecursively(foo2);

	class Bar {
		private final Set<Foo> foos;

		Bar(Set<Foo> foos) {
			this.foos = foos;
		}

		Set<Foo> getFoos() {
			return foos;
		}
	}

	assertThat(new Bar(singleton(foo1)))
			.usingComparatorForType(BigDecimal::compareTo, BigDecimal.class)
			.isEqualToComparingFieldByFieldRecursively(new Bar(singleton(foo2)));
}
```

#### Java 8 specific ?
Example is Java 8 specific but the problem should be the same in older versions.

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
Thanks for reporting.

My understanding is that `deepHashCode` is a performance optimization. When support for `comparatorBy*` was added to `isEqualToComparingFieldByFieldRecursively` we missed that this optimization can no longer be used (at least in the current form). :(

**Comment by joel-costigliola** [comment]
@lbilger thanks for the analysis.
