### ISSUE TITLE
version higher than 2.6.0 doesn't work in Android (unSupportedOperationException)

### ISSUE THREAD

**Issue by DavidBcn** [joel-costigliola/assertj-core#852]
#### Summary
I have been using this library for a while in Android development, the other day I wanted to upgrade to use the latest version and I am getting `unSupportedOperationException` with no more information (even with /.gradlew --debug --stacktrace and --info).

2.6.0 and lower versions work but with 3.0.0 and higher it is showing the exception.

I am using:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by joel-costigliola** [comment]
We don't officially support Android, we are only trying to do our best effort for 2.x to be Android compatible but nothing on the 3.x side.

**Comment by DavidBcn** [comment]
thank you, joel to reply! 
how about putting this information in the main page?

**Comment by joel-costigliola** [comment]
It is already in http://joel-costigliola.github.io/assertj/assertj-core.html which is the main assertj-core page ;-) 
Have you given a try to `Java6Assertions` ? It is an entry point that should give only java 6 (thus android compatible) assertions.

**Comment by PascalSchumacher** [comment]
@DavidBcn Did using `org.assertj.core.api.Java6Assertions` as an entry point (instead of ``org.assertj.core.api.Assertions`) work for you? Can this issue be closed?
