### ISSUE TITLE
extracting().isEqualTo() not the same as property access

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#853]
#### Example

```
        IdentifiedUserDetails userDetails = (IdentifiedUserDetails) details;
        assertThat( userDetails.getId() )
            .as( "%s has same id as %s", userDetails, credentials )
            .isEqualTo( credentials.getUser().getId() );
```
is not the same as

```
        IdentifiedUserDetails userDetails = (IdentifiedUserDetails) details;
        assertThat( userDetails )
            .extracting( Identified::getId  )
            .as( "%s has same id as %s", userDetails, credentials )
            .isEqualTo( credentials.getUser().getId() );
```

output is

```
Expected :694ced57-6a66-43ae-8c36-9c2456ad3c15
Actual   :[694ced57-6a66-43ae-8c36-9c2456ad3c15]
```

seems extracting always returns a collection regardless of what it started out as. Perhaps providing a map method... also you can infer both sides of the map. see Java 8's Stream.map function signature. This type of inference has been available for a while (I think java 5, but maybe 6 or 7)

```
    <R> Stream<R> map(Function<? super T, ? extends R> var1);
```

extracting could behave in the same way using the function to determine the return type.

**Comment by joaodelgado** [comment]
Why was this issue marked as invalid? I'm running into the same issue and finding the current API a bit confusing.

`extracting` behaves differently on collections than on single objects, which I don't find very intuitive.

Take the example below:

```java
 IdentifiedUserDetails userDetails = (IdentifiedUserDetails) details;
 assertThat( userDetails )
            .extracting( Identified::getId  )
            .containsExactly( credentials.getUser().getId() );

 assertThat( singletonList(userDetails) )
            .extracting( Identified::getId  )
            .contains( credentials.getUser().getId() );
```

This test would pass.
The call to `extracting` always returns a list, regardless of the original _thing_ being compared.

This makes it difficult to chain assertions. I would like to be able to do something like:

```java
 assertThat( userDetails )
            .isNotNull()
            .extracting( Identified::getId  )
            .isNotNegative();
```

**Comment by joel-costigliola** [comment]
`extracting` on Object was meant to extract multiple properties and putting them in a list, maybe we should provide a single property extraction but I'm not sure it is that useful since one can simply call the property getter within `assertThat`  (you can't do that with chaining from the original object assertion though).

Your last suggestion is something that comes up regularly but is not possible due to java generics limitations, I mean by that `extracting` in your example can not return the assertions specific to the extracted value, it is defaulted to Object assertions.
