### ISSUE TITLE
Suggested Improvements for AbstractAssert.failWithMessage(...)

### ISSUE THREAD

**Issue by Gubbel** [joel-costigliola/assertj-core#873]
### Summary
Currently, the error messages generated in custom assertions via `failWithMessage()` are less clear compared to similar messages from built in assertions.

	MyTuple actual = new MyTuple(new int[] { 1, 2, 3 });
	assertThat(actual).hasValue1("");

This test fails with the following stack trace:
```
java.lang.AssertionError: Expected the first value of <FailWithMessageImprovements$MyTuple@6d21714c> to be <> but was <[I@108c4c35>
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:111)
	at FailWithMessageImprovements$MyTupleAssert.hasValue1(FailWithMessageImprovements.java:43)
	at FailWithMessageImprovements.customAssert(FailWithMessageImprovements.java:12)
```

While a built in assertion:

	MyTuple actual = new MyTuple(new int[] { 1, 2, 3 });
	assertThat(actual.getValue1()).isSameAs(""); // 

fails with
```
java.lang.AssertionError: 
Expecting:
 <"">
and actual:
 <[1, 2, 3]>
to refer to the same object
	at FailWithMessageImprovements.builtInAssert(FailWithMessageImprovements.java:24)
```

In the message from my (trivial) custom assert
- it's unclear what the values of `actual` and `expected` are
- the stack trace contains elements from AssertJ and my assert

### Suggestions

1. ~~Add an alternative to `failWithMessage()`, that uses the same formatting as AssertJ (i.e. the same behavior as before #320, but as opt-in).
The custom assert could have pre-formatted the values via `Representation.toStringOf(Object)`, but I think creating asserts should be as convenient as possible.~~
Never mind, I found `throwAssertionError(ErrorMessageFactory)`, which is exactly what I need.
2. Also filter the error stack trace in `failWithMessage()`, exactly like `Failures.failure()`.
3. Extend this filtering by also removing elements of the current assert class.

I could contribute this, if you agree with my suggestions.

### Example

	public static class MyTuple {
		// ...

		public Object getValue1() {
			return value1;
		}
	}

	public static class MyTupleAssert extends AbstractObjectAssert<MyTupleAssert, MyTuple> {
		// ...

		public MyTupleAssert hasValue1(Object expected) {
			isNotNull();

			if (!Objects.equals(actual.getValue1(), expected)) {
				failWithMessage("Expected the first value of <%s> to be <%s> but was <%s>", actual, expected, actual.getValue1());
			}

			return this;
		}
	}

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
What would a better error message ? 
Both actual and expected values are displayed according to their String representation, I'm not sure what  additional information you want to get, hashCode ?, do you want to display actual first ? 

Ok to filter the stack trace.

**Comment by Gubbel** [comment]
I would prefer formatting the values with the assert's representation. But I'll just use `throwAssertionError(ErrorMessageFactory)` instead in cases like that.

**Comment by PascalSchumacher** [comment]
Joel merged the pull request, so I'm closing this. Thanks for reporting and for the pull request! 👍
