### ISSUE TITLE
Pretty print of asserted objects

### ISSUE THREAD

**Issue by pablisco** [joel-costigliola/assertj-core#879]
#### Summary

I thought it would be interesting if we could have pretty printing of the objects when there is an error (instead of the default toString). This could allow for custom rendering of the objects. For instance:

```java

ComplexObject object = ....

assertThat(object).usingPrinter(new ObjectPrinter<ComplexObject> {
  public String print(ComplexObject object) {
    return "{", object.getKey() + ", " + object.getValue() + "}";
  }
}).isNotNull();
```
Also, could have one that uses reflexion to work out the pretty print:
```java
assertThat(object).usingReflectionPrinter().isNotNull();
```

Is this feature or similar currently possible? If not I'll create a PR.

**Comment by PascalSchumacher** [comment]
You can archive this by registering a custom `Representation`, see:

http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.5.0-registerFormatterForType

and:

https://github.com/joel-costigliola/assertj-examples/blob/fe8a97d37359f238c0965230e0aaa883dcb71337/assertions-examples/src/test/java/org/assertj/examples/RepresentationExamples.java

for more information and examples.

**Comment by pablisco** [comment]
That's very interesting. Thanks :)

What version of AssertJ is that on?

**Comment by PascalSchumacher** [comment]
3.5.0+
