### ISSUE TITLE
Extracting of properties implemented by default interface method broken in 3.6.0 (regression from 3.5.2)

### ISSUE THREAD

**Issue by adammichalik** [joel-costigliola/assertj-core#880]
#### Summary
When a class implements an interface that has a `getXxx()` method with default implementation, `extracting("xxx")` fails with

```
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'name'.
Error when introspecting properties was :
- No getter for property 'name' in [...] 
Error when introspecting fields was :
- Unable to obtain the value of the field <'name'> from <...@d70c109>
```

This used to work in 3.5.2.

#### Example

```java
import java.util.Arrays;
import java.util.List;

import org.junit.Test;

import static org.assertj.core.api.Assertions.*;

public class DefaultPropertyTest {
    @Test
    public void hasDefaultName() {
        List<Person> people = Arrays.asList(new Person());

        assertThat(people).extracting("name").containsOnly("John Doe");
    }
}

class Person implements DefaultName {

}

interface DefaultName {
    default String getName() {
        return "John Doe";
    }
}
```

#### Java 8 specific ?
YES (interface default methods)

**Comment by joel-costigliola** [comment]
Thanks for reporting this.

**Comment by PascalSchumacher** [comment]
I caused this regression with https://github.com/joel-costigliola/assertj-core/commit/b996e82a86a19b40e80ee0741a5ace56145228b1

Sorry everybody. :(

**Comment by joel-costigliola** [comment]
@PascalSchumacher the main issue for me was the lack of tests with default methods, that would have caught the regression, hopefully we have great users and we now are aware of that.

@adammichalik is it a blocking issue for you ? said otherwise can you wait for 3.7.0 to be released or do you want a bugfix release ?

**Comment by adammichalik** [comment]
@joel-costigliola I can stick to 3.5.2 for now, no rush. Thanks for fixing it!

**Comment by Xaerxess** [comment]
@joel-costigliola I'd really appreciate 3.6.x release with this bugfix sooner than 3.7.0.

**Comment by joel-costigliola** [comment]
@Xaerxess we can do that.

**Comment by joel-costigliola** [comment]
@Xaerxess  @adammichalik  Fixed in 3.6.2 which is available in maven central repo.

**Comment by Xaerxess** [comment]
Thanks!

**Comment by adammichalik** [comment]
Thanks, I checked it and works fine in 3.6.2!
