### ISSUE TITLE
Timestamp and Date equals are not symmetric.

### ISSUE THREAD

**Issue by mjeffrey** [joel-costigliola/assertj-core#881]
#### Summary
When making tests with hibernate and using the assertIsEqualToComparingFieldByFieldRecursively to compare the entity returned from Hibernate with the expected entity, there are problems with unexpected failures with Dates. 
While the input field is a java.util.Date the resulting value is java.sql.Timestamp and the equals() methods are not symmetric, so the objects ae not considered equal.
See http://stackoverflow.com/questions/8929242/compare-date-object-with-a-timestamp-in-java

#### Example

The following will be written as a date but be returned as a Timestamp.
```java
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on")
    private Date createdOn;

```

#### Java 8 specific ?
It is not java8 specific and it is a small fix, I will make a pull request for this.
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I haven't yet given a lot of thought, I usually tend not to override Java behavior.

**Comment by PascalSchumacher** [comment]
I know from personal experience that the non-symmetry between the equals methods of these classes is annoying. This is a design error, but I do not think assert-j should hide it, especially not by changing the comparison for all objects as suggested in #882.

**Comment by joel-costigliola** [comment]
@mjeffrey As @PascalSchumacher mentioned AssertJ is not here to address JDK mistakes in order not to surprise users, having said that your issue can be addressed by registering a "symmetric" Date comparator as in: 

```java
@Test
public void should_be_able_to_use_a_date_comparator_for_timestamp() {

  JediMaster yoda1 = new JediMaster("Yoda", new Jedi("luke", "Green"));
  yoda1.dateOfBirth = new Timestamp(1000L);
  JediMaster yoda2 = new JediMaster("Yoda", new Jedi("luke", "Green"));
  yoda2.dateOfBirth = new Date(1000L);

  // use a date comparator to compare either Date or Timestamp
  assertThat(yoda1).usingComparatorForType(SYMMETRIC_DATE_COMPARATOR, Date.class)
                   .isEqualToComparingFieldByField(yoda2);
  assertThat(yoda2).usingComparatorForType(SYMMETRIC_DATE_COMPARATOR, Date.class)
                   .isEqualToComparingFieldByField(yoda1);
}
```
It is probably not the most elegant solution but at least it makes it cleat that a special comparator is needed to compare a timestamp with a date.

I have pushed a commit to make `usingComparatorForType` more flexible and allow using a Date comparator for timestamp type, ie `.usingComparatorForType(SYMMETRIC_DATE_COMPARATOR, Timestamp.class)` but the snippet of code above does not need it.
