### ISSUE TITLE
test class/method field visibility

### ISSUE THREAD

**Issue by xenoterracide** [joel-costigliola/assertj-core#888]
#### Summary

because I tend to write libraries, I've noticed that sometimes I take the IDE's suggestion of "may be package private" on something that should be a public class/method whatever. Below I've included the first API that comes to mind, but I'm sure there are others.

#### Example

```
    @Test
    public void test() {
        assertThat( My.class ).isPublic().hasPublicMethods( "getFoo", "getBar" );
        assertThat( Constants.class ).isPublic().hasPublicFields( "FOO", "BAR" );

    }
```

alternatively (would lead to less method explosion)

```
    @Test
    public void test() {
        assertThat( My.class ).isPublic().hasMethods( "getFoo", "getBar" ).withModifer(Modifier::isPublic);

    }
```

also worth noting  that hasDeclaredFields/hasFields don't seem to pick up static fields (not surprising)

**Comment by joel-costigliola** [comment]
We can definitely add these assertions, we could also add ones for less less visible fields/methods although I think they won't be used so much but for the sake of completeness we probably should.

**Comment by xenoterracide** [comment]
right, well that does make the "withModifier" (or some similar API sort of interesting), that way you don't have the method explosion for each modifier, however up to you.

**Comment by joel-costigliola** [comment]
Closing this issue as we have added:

- `isPublic()` 
- `isProtected()`
- `hasMethods(String... methodNames)`
- `hasDeclaredMethods(String... methodNames)`
- `hasPublicMethods(String... methodNames)`
- `hasDeclaredPublicMethods(String... methodNames)`

**Comment by joel-costigliola** [comment]
I'm thinking to change the added assertions to:  
- `hasMethods(String... methodNames)` : check public accessible methods
- `hasDeclaredMethods(String... methodNames)` :  check declared methods (includes non public ones)
I want to do so to be consistent with the fields assertions
- `hasFields(String... fieldNames)` : check public accessible fields
- `hasDeclaredFields(String... fieldNames)` :  check declared fields (includes non public ones)

@xenoterracide I think that should cover your expectations, right ?
