### ISSUE TITLE
Add anySatisfy for Iterable / array

### ISSUE THREAD

**Issue by hughwphamill** [joel-costigliola/assertj-core#889]
#### Summary
Allow to verify a bunch of assertions for any elements of an Iterable much like satifies.

Very similar to #711 except that it would pass if any element passes all of the assertions

#### Example

```java
assertThat(myIcelanderFriends).extracting(Person::getAddress)
                              .anySatisfy(a -> {
                                  assertThat(a.getCountry()).isEqualTo("Iceland");
                                  assertThat(a.getPhoneContryCode()).isEqualTo("+354");
                                  assertThat(a.getSurname()).endsWith("son");
                              });
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch

**Comment by joel-costigliola** [comment]
Good idea, we will add that.

**Comment by epeee** [comment]
We can close this one since the pr is integrated, isn't it?

**Comment by joel-costigliola** [comment]
yes !

**Comment by hughwphamill** [comment]
Super, thanks for the speedy turnaround!
