### ISSUE TITLE
Improve android support?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#897]
New android version support some java 8 feature like lambda expressions and streams (https://developer.android.com/guide/platform/j8-jack.html), but `java.nio.file.Path` and the `java.time` are still not supported.

What about renaming Java6XAssertions to AndroidXAssertions and adding streams etc. to the 3.x versions?

**Comment by joel-costigliola** [comment]
I agree but would keep `Java6XAssertions` and mark them deprecated.

**Comment by PascalSchumacher** [comment]
Support for the `java.nio.file` and `java.time` packages was added in Android API Level 26 (Android 8).

Therefore I'm closing this issue.
