### ISSUE TITLE
Enhancement request on isEqualToComparingFieldByFieldRecursively

### ISSUE THREAD

**Issue by QEcoderS** [joel-costigliola/assertj-core#913]
Hi, I need to compare the response object field by field recursively using isEqualToComparingFieldByFieldRecursively. But it can't ignore the fields that are null in my expected object. Is it possible to provide an enhancement of isEqualToComparingFieldByFieldRecursively skipping null values in expected object or help in achieving the same.

Thanks,
Shuba.

assertThat(expectedObj).isEqualToComparingFieldByFieldRecursively(responseObj);

SIMPLE EXAMPLE
expectedObj
-------------
{
 "FirstName": "SHUBA"
 "LastName": "RAJA"
}

responseObj
-------------
{
 "FirstName": "SHUBA"
"MiddleName" : "INBA"
 "LastName": "RAJA"
}

In my case the assert fails as MiddleName is Null in the expected obj... since I have too many fields and complex sub objects, I want to provide limited fields in my expectedObj and validate them against the response.

Please help

**Comment by joel-costigliola** [comment]
I'm ok to add this feature but not changing the behavior `isEqualToComparingFieldByFieldRecursively` as it is a breaking change.

The challenge here is to find a way to specify that `null` fields are to be ignored in comparison, the straigtforward solution is to add `isEqualToComparingFieldByFieldRecursivelyIgnoringNullFields` but the name is really long, I'd like to see if we could find a lighter way to support this feature.

**Comment by QEcoderS** [comment]
Thank you very much Joel! for the quick response. Looking forward to this feature at the earliest.
Just a small thought to avoid long name, can we have an overloaded method with an additional argument - bool ignoreNullFields.

Kind Regards,
Shuba.

**Comment by joel-costigliola** [comment]
Good idea, we will probably use an enum for extensibility.

**Comment by pierrefevrier** [comment]
+1 I need this feature :)

**Comment by pierrefevrier** [comment]
One question about `ComparingFieldByField`: is-it possible to compare `FieldByField` with `Collection.contains()` ?

**Comment by joel-costigliola** [comment]
@pierrefevrier can you give an example and move that to another issue if it is not related to the current issue ?

**Comment by PascalSchumacher** [comment]
@pierrefevrier there is currently no way to use FieldByField etc. comparison for map entries/values.

**Comment by derekm** [comment]
See also my feature request #982, wanting "OnlyGivenFields" and "IgnoringGivenFields" forms of isEqualToComparingFieldByFieldRecursively.

**Comment by joel-costigliola** [comment]
@QEcoderS , @pierrefevrier, @derekm I have closed in favor of https://github.com/joel-costigliola/assertj-core/issues/1002 which I would like to have your opinion on.
