### ISSUE TITLE
assertThat(-0.).isZero() fails

### ISSUE THREAD

**Issue by stonio** [joel-costigliola/assertj-core#919]
#### Summary

Tested with: AssertJ 2.6.0 ; Java 7

Expression `assertThat(-0.).isZero();` fails. Can we reconsider this?

#### Example

```java
final double d = -0.;

assertThat(d).isZero(); // fails

assertThat(d).isCloseTo(0, within(0.)); // workaround
```

#### Java 8 specific ?
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I agree.
the issues comes from AssertJ converting `double` to `Double`. It turns out that with `Double` positive zero is not equal to negative  zero as explained in 
http://stackoverflow.com/questions/14771328/java-signed-zero-and-boxing.

**Comment by joel-costigliola** [comment]
That also applies to `float`

**Comment by joel-costigliola** [comment]
Fixed.

**Comment by onacit** [comment]
I have reached here with an issue seems related this issue. It seems that wrapper class doesn't work for NEGATIVE zeros.

```java
    {
      final int POSITIVE_ZERO_BITS = 0b0__00000000__00000000_00000000_0000_000;
      assert POSITIVE_ZERO_BITS == 0;
      final int NEGATIVE_ZERO_BITS = 0b1__00000000__00000000_00000000_0000_000;
      assert NEGATIVE_ZERO_BITS == Integer.MIN_VALUE;
      final float POSITIVE_ZERO = Float.intBitsToFloat(POSITIVE_ZERO_BITS);
      final float NEGATIVE_ZERO = Float.intBitsToFloat(NEGATIVE_ZERO_BITS);
      assert POSITIVE_ZERO == +.0f;
      assert POSITIVE_ZERO == -.0f;
      assert NEGATIVE_ZERO == +.0f;
      assert NEGATIVE_ZERO == -.0f;
      assertThat(POSITIVE_ZERO).isZero();
      assertThat(Float.valueOf(POSITIVE_ZERO)).isZero();
      assertThat(NEGATIVE_ZERO).isZero();
      //assertThat(Float.valueOf(NEGATIVE_ZERO)).isZero();
      assertThrows(org.opentest4j.AssertionFailedError.class, () -> assertThat(Float.valueOf(NEGATIVE_ZERO)).isZero());
    }
    {
      final long POSITIVE_ZERO_BITS = 0b0__00000000_000__00000000_00000000_00000000_00000000_00000000_00000000_0000L;
      assert POSITIVE_ZERO_BITS == 0L;
      final long NEGATIVE_ZERO_BITS = 0b1__00000000_000__00000000_00000000_00000000_00000000_00000000_00000000_0000L;
      assert NEGATIVE_ZERO_BITS == Long.MIN_VALUE;
      final double POSITIVE_ZERO = Double.longBitsToDouble(POSITIVE_ZERO_BITS);
      final double NEGATIVE_ZERO = Double.longBitsToDouble(NEGATIVE_ZERO_BITS);
      assert POSITIVE_ZERO == +.0d;
      assert POSITIVE_ZERO == -.0d;
      assert NEGATIVE_ZERO == +.0d;
      assert NEGATIVE_ZERO == -.0d;
      assertThat(POSITIVE_ZERO).isZero();
      assertThat(Double.valueOf(POSITIVE_ZERO)).isZero();
      assertThat(NEGATIVE_ZERO).isZero();
      assertThat(Double.valueOf(NEGATIVE_ZERO)).isZero();
      assertThrows(org.opentest4j.AssertionFailedError.class, () -> assertThat(Double.valueOf(NEGATIVE_ZERO)).isZero());
    }
```

**Comment by onacit** [comment]
@joel-costigliola Just calling. Thanks.

**Comment by onacit** [comment]
@joel-costigliola Shouldn't this issue be re-opened?

**Comment by scordio** [comment]
@onacit if I am not mistaken, the issue is only for boxed values. According to @joel-costigliola's comment:

> It turns out that with `Double` positive zero is not equal to negative zero as explained in
> http://stackoverflow.com/questions/14771328/java-signed-zero-and-boxing.
> 
> We will keep the existing behavior for `Double` but we will fix it for `double`.

which is in line with the JDK behavior.

Or did I miss something?

**Comment by onacit** [comment]
@scordio You're not mistaken at all, I believe, yet it's pulling me with a new point of view.

Currently,
`Abstract(Double|Float)Assert#assertIsPrimitiveZero()` methods compare `(double|float)Value()` with `0.0`.
Which seems work with both negative|positive zero values.

And `(Doubles|Floats)#zero()` methods returns `0.0d`, `0.0f`, respectively.

I'm curious when clients call a method so called `isZero()`, I would believe that the `actual` should be verified as a value which considered _zero_ regardless of positivity or negativity?.

But verifies only those three conditions.

* negative primitive zero: `-.0(f|d)`
* positive primitive zero: `+.0(f|d)`
* a wrapper type of `+.0(f|d)` using `Object#equals` method.

I don't understand why both negativity and positivity pulled out of wrapper case.

```java
    assertThat(new Double(+.0d)).isZero();
    assertThat(new Double(-.0d)).isZero(); // Why not verifies? Isn't it zero?
```

Thanks.
