### ISSUE TITLE
assertion description is forgotten after using extracting

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#920]
#### Summary

After using `extracting` the assertion information (including the description) is forgotten as a new assertion is created to check the extracted values

#### Example

```java
assertThat(fellowshipOfTheRing).as("check names") 
                               .extracting("name")  
                               .contains(sauron);   
```
(obviously) fails as expected but `check names` does not appear in the error message.

**Comment by fiery-phoenix** [comment]
If to rewrite example as:

    assertThat(fellowshipOfTheRing).extracting("name")
                                   .as("check names")
                                   .contains(sauron);

it works as expected and for me it looks more logical to use `#as("check names")` after extracting names.

But I think improvement is useful. Should sub-assert `#as(...)` method just override the one got from basic assert?

**Comment by joel-costigliola** [comment]
@fiery-phoenix point taken, #918 is valuable, let's try to see if it is possible to combine this and #918 without confusing users.

**Comment by PascalSchumacher** [comment]
This was fixed in https://github.com/joel-costigliola/assertj-core/commit/09c084f6c09e49727c60f0cc7fe1ceaeaf5646c2 and https://github.com/joel-costigliola/assertj-core/commit/7365f84e829a939980b9978836e5e550013f2946
