### ISSUE TITLE
AssertionMatcher proposal

### ISSUE THREAD

**Issue by SpOOnman** [joel-costigliola/assertj-core#926]
#### Summary

I have a proposal to add a generic Hamcrest Matcher implementation that would fit assertj library:

```java
    public abstract class AssertionMatcher<T> extends BaseMatcher<T> {
        private AssertionError lastError;

        @Override
        public boolean matches(Object argument) {
            T actual = (T) argument;
            try {
                assertion(actual);
                return true;
            } catch (AssertionError e) {
                lastError = e;
                return false;
            }
        }

        public abstract void assertion(T actual) throws AssertionError;

        @Override
        public void describeTo(Description description) {
            //Describe lastError and its stacktrace
        }
    }
```

Advantages as I see it:

- don't create complex boolean expressions inside matches method
- override only assertion method
- inside assertion method use assertj default, custom or any other assertions that throw AssertionError
- failure description is provided with detailed description get from assertion and with a stacktrace that points exactly to line where assertion has failed.

#### Example

Basic usage is simple, for example with Mockito library:

```java
    verify(customerRepository).save(argThat(new AssertionMatcher<Customer>() {
            @Override
            public void assertion(Customer actual) throws AssertionError {
                assertThat(actual).hasName("Tom")
                    .hasAge(30);
            }
    }));
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

I this this proposal has generic use case and fits well with assertj library. Please review it and if you agree I would provide a PR.

**Comment by joel-costigliola** [comment]
If I understand you correctly you want to integrate AssertJ assertions into Hamcrest matcher so that you can reuse some AssertJ assertions where an Hamcrest matcher is required.

If that is the case then yes I agree it can be useful.

We also have the other way around https://github.com/joel-costigliola/assertj-core/pull/570 (not integrated yet) that allows to reuse Hamcrest matcher as AssertJ.

**Comment by SpOOnman** [comment]
Yes, I want to reuse my custom AssertJ assertions - that was exactly my intension.

That's great. I'll provide a PR then!
