### ISSUE TITLE
Java 9 reflection changes

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-core#928]
Java 9 is much more restrictive concerning reflective access to non-public fields/methods. For example `setAccessible` called by `org.assertj.core.util.introspectionFieldUtils#readField` on a private field fails with:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private transient long java.util.Date.fastTime accessible: module java.base does not "opens java.util" to unnamed module @66b72664
```

This means that assertj methods which use reflection on non-public fields/methods will fail/behave differently. For example the `isEqualTo*Fields` methods.

**Comment by PascalSchumacher** [comment]
It still works if the user opens all required packages for assertj, e.g. `--add-opens java.base/java.util=ALL-UNNAMED` (ALL-UNNAMED can be replaced with the assertj module name once there is one).

For example `DeepDifference_Test` fails on java 9, but runs with these args:

```
mvn -Dtest=DeepDifference_Test test -DargLine="--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.math=ALL-UNNAMED"
```

**Comment by PascalSchumacher** [comment]
According to http://mail.openjdk.java.net/pipermail/jigsaw-dev/2017-March/011763.html --permit-illegal-access in a future version of jdk9 will simplify granting access.

**Comment by joel-costigliola** [comment]
If I understand correctly we are going to get screwed in Java 10 ?

**Comment by PascalSchumacher** [comment]
Users who like to use assertj features using reflection on private stuff will have to do some setup to allow assertj access. On java 9 they can use `--permit-illegal-access`, on java 10 they will have to do some more work by opening up individual modules. Does not look to bad to me.

**Comment by joel-costigliola** [comment]
I think this solves the issue : https://www.theregister.co.uk/2017/05/12/oracle_loses_jpms_vote/ ...

**Comment by sormuras** [comment]
Copied comment from https://github.com/junit-team/junit5/issues/1063 by @AlanBateman

> In the case of AssertJ then it looks like it has a re-packaged cglib that is hacking into ClassLoader.defineClass. They need to be steered towards using java.lang.invoke.MethodHandles.Lookup.defineClass instead.

So. If you re-package a cglib version that uses method handles... no screw in Java 10 or 18.3.

**Comment by PascalSchumacher** [comment]
But sadly there is no such version of cglib yet. 

Assertj `3.8.0/2.8.0` already use the latest release of cglib (`3.2.5`).

Of course we will happily update once a cglib version is released.

**Comment by filiphr** [comment]
I think that an alternative would be to remove cglib and switch to [Byte Buddy](http://bytebuddy.net/#/) as far as I know they are java 9 compatible and they are used a lot in large projects (Hibernate, Spring, Mockito that I know of). I think that it doesn't need to be shaded as well, but I am not sure.

**Comment by joel-costigliola** [comment]
That could be something interesting to try, I'm not a big fan cglib and if we can remove shading then that would be awesone.

**Comment by PascalSchumacher** [comment]
Byte Buddy is better supported than cglib, so plus +1 for a switch.

I took a look at this a year or so ago, but I'm not very knowledgeable in this area, so I did not get very far.

I believe the shading of cglib was done to keep assertj without any dependencies and to avoid conficts with other dependencies using different versions of cglib. Maybe Byte Buddy has better compatiblity between versions, but Byte Buddy is also heavily developed and not all versions are comptable with each other. Therefore Byte Buddy does not really solve the shading problem imho.

**Comment by joel-costigliola** [comment]
yeah, I don't think we can avoid shading since assertj-core has a no dependency policy .

**Comment by joel-costigliola** [comment]
@PascalSchumacher what is the status of this issue now that we have moved to byte buddy ?

**Comment by PascalSchumacher** [comment]
The issue is not related to cglib/byte-buddy. It is about AssertJ features which use reflection e.g. `comparingFieldByField`, `comparingFieldByFieldRecursive`.

As there haven't been any related user questions (that I'm aware of) I guess we can close it for now.

What do you think?

**Comment by joel-costigliola** [comment]
We can close it after adding an entry in the [FAQ/Help](http://joel-costigliola.github.io/assertj/assertj-core.html#help) website section.

**Comment by joel-costigliola** [comment]
useful https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-BA521187-60FD-4CA5-B998-58A1D05587BC

**Comment by joel-costigliola** [comment]
The best explanation of Reflectively Accessing Internal APIs With `--add-opens`: https://blog.codefx.org/java/five-command-line-options-to-hack-the-java-9-module-system/#Reflectively-Accessing-Internal-APIs-With--add-opens

**Comment by joel-costigliola** [comment]
documented : http://joel-costigliola.github.io/assertj/assertj-core.html#java9-reflection-error
