### ISSUE TITLE
Files.newTemporaryFile() is not unique when called multiple times.

### ISSUE THREAD

**Issue by DavidOpDeBeeck** [joel-costigliola/assertj-core#929]
#### Summary

When calling `Files.newTemporaryFile()` multiple times in close proximity of each other the filenames could be the same. This could result in a failing test and the following error `a file was found with the same path`.

This could be resolved by calling `Files.newFile(String path)`, but one would expect that `Files.newTemporaryFile()` would be unique each time it is called.

#### Current

```java
  public static File newTemporaryFile() {
    String tempFileName = concat(valueOf(System.currentTimeMillis()), ".txt");
    return newFile(concat(temporaryFolderPath(), tempFileName));
  }
```
#### Proposed
```java
  public static File newTemporaryFile() {
    String tempFileName = concat(UUID.randomUUID().toString(), ".txt");
    return newFile(concat(temporaryFolderPath(), tempFileName));
  }
```

**Comment by joel-costigliola** [comment]
Fair enough but `Files` is not part of AssertJ API I don't recommend to use it as it can be changed any time.

**Comment by PascalSchumacher** [comment]
@joel-costigliola If the method is not part of the API, maybe we should remove it, as it is not used inside AssertJ. Only a single method of `Files` is used by AssertJ (and only one time).

**Comment by PascalSchumacher** [comment]
@joel-costigliola Any comments on this?

**Comment by joel-costigliola** [comment]
Will integrate it this we.

**Comment by joel-costigliola** [comment]
Actually already integrated last month !
