### ISSUE TITLE
Condition subclass "satisfies" and/or "matches" as well as "is" and "has"?

### ISSUE THREAD

**Issue by Mrodent** [joel-costigliola/assertj-core#938]
#### Summary

I did a search here but the suggestion doesn't seem to have been made.  When you create your own Condition class (fantastically versatile feature BTW), you can use either "is" or "has".  And, cleverly, the failure message uses the chosen verb.  Could you not let people use one or two other verbs, particularly "satisfies"?  A minor point, no doubt, but would improve readability.

#### Example

```java
<add example here>
```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I'm sympathetic to the idea, can you tell me:
- How would you choose to use `satisfies` over `has/is` ?
- What the error message would look like ?

**Comment by Mrodent** [comment]
See class below: it inspects a String which, to pass the test, must contain HTML with at least one `<SPAN>` , and all its SPANs must have a "class" attribute the value of which must contain the String (i.e. the class) "fg[xxx]_colour".  The constructor determines the "xxx" ("red", "green", etc.).

If it fails you get "Expected "...." to **have**...", so I've deliberately tailored the toString method to make sense using this verb: "to have... at least one SPAN and to apply, etc."

But it might be slightly less contorted in this case and in others where you can say "Expected .... to satisfy" [succinct description of the condition which should have been met].

It seems (to me) kind of logical, given the name of the class Condition, that you might want to talk about a condition not being **satisfied**.

```
public class HTMLStringWithForegroundColourDirectiveForSpans extends Condition<String> {
	private String htmlFragment;
	
	private String fgColour;
	
	public HTMLStringWithForegroundColourDirectiveForSpans( String colour ){
		fgColour = colour;
	}
	

	@Override
	public boolean matches( String htmlFragment ) {
		this.htmlFragment = htmlFragment; 
		
		Document jsoupDoc = Jsoup.parse( htmlFragment );
		ForegroundColourCheckingNodeVisitor fGCheckingNV = new ForegroundColourCheckingNodeVisitor( fgColour );
		NodeTraversor nt = new NodeTraversor(fGCheckingNV);
		nt.traverse( jsoupDoc );
		// for this node to "match" it must contain at least one "SPAN" element, and no "SPAN" element which 
		// does NOT have class "fgcolour_[colour]"
		return  fGCheckingNV.foundAtLeastOneSpanElement && ! fGCheckingNV.nonColourSpanFound;
	}
	
	@Override
	public String toString(){
		return String.format( "at least one SPAN and to apply \"fgcolour_%s\" class to its SPAN(s): |%s|", fgColour, htmlFragment );
	}

}

class ForegroundColourCheckingNodeVisitor implements NodeVisitor {
	
	boolean foundAtLeastOneSpanElement = false;

	boolean nonColourSpanFound = false;
	
	private String fgColour;
	
	ForegroundColourCheckingNodeVisitor( String colour ){
		fgColour = colour;
	}

        // blah blah implementation of this NodeVisitor class

```

**Comment by joel-costigliola** [comment]
Summary of what needs to be done:

- add `public SELF satisfies(Condition<? super ACTUAL> condition)` to `ExtensionPoints`
- add `assertSatifies` to `Conditions`
- add a `ShouldSatisfy` error class
