### ISSUE TITLE
Using Conditions to assert maps entries/keys/values

### ISSUE THREAD

**Issue by Mishail** [joel-costigliola/assertj-core#944]
I wonder if it makes sense to make a next step from #205 and #690 and add more methods to `MapAssert`. 

Like:
```java
hasEntry(Condition<? super E> entryCondition)
hasValue(Condition<? super V> valueCondition)
hasKey(Condition<? super K> keyCondition)
```
and their negative counterparts.

**Comment by joel-costigliola** [comment]
the first one already exists : http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractMapAssert.html#hasEntrySatisfying-K-org.assertj.core.api.Condition-

I'm ok to add the other if you can give me a real life use case.

**Comment by Mishail** [comment]
> the first one already exists

That's not quite true. I have to know the key in order to use that method. But I'm talking about more general approach where I have some _criteria_ for an entry, which may or may not include a specific key.

A real life use case. I was trying to create a test case today where I had to check if a map didn't have a value which satisfied some predicate.

The only way to do that now is something like:

```
Assertions.assertThat(map.values()).areNot(new Condition<>(s -> ..., "desc"))

//or use `doNotHave`
```

The only problem with that approach, is if assertion fails I'll get `map.values()` in a error message, and not the map itself.

Hamcrest does have matchers like the ones from the description

**Comment by joel-costigliola** [comment]
You are right about the API.

I would use a different syntax:
```java
hasEntrySatisfying(Condition<? super E> entryCondition)
hasValueSatisfying(Condition<? super V> valueCondition)
hasKeySatisfying(Condition<? super K> keyCondition)
```

**Comment by Mishail** [comment]
I'm fine with any naming as long as it provides the functionality 👍
