### ISSUE TITLE
Enhanced SoftAssert suport

### ISSUE THREAD

**Issue by SergeyPirogov** [joel-costigliola/assertj-core#948]
Will be useful to have enhanced version of soft assert:

JUnit 5 provided new version for softAssertions:

```java
 Address adress = new Adress();
 assertAll("address",
            () -> assertEquals("John", address.getFirstName()),
            () -> assertEquals("User", address.getLastName()));
```

Can we achieve the same?

**Comment by joel-costigliola** [comment]
Have you given a try to [JUnitSoftAssertions](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#JUnitSoftAssertions) ? 

What is it in `assertAll` that you don't find in soft assertions ?
I see one advantage of AssertJ soft assertions in that you don't need lambdas which are a bit noisy in `assertAll`.

Basically I'm not yet convinced ;-)

**Comment by PascalSchumacher** [comment]
@SergeyPirogov Any update on this? Or can we close this issue?

**Comment by SergeyPirogov** [comment]
@PascalSchumacher I found an alternative in assertj documantation
