### ISSUE TITLE
Assert that a class has exactly (declared) fields

### ISSUE THREAD

**Issue by filiphr** [joel-costigliola/assertj-core#953]
#### Summary

Currently `AbstractClassAssert#hasFields()` and `AbstractClassAssert#hasDeclaredFields()` check only that the passed fields exist. It would be good to have an assertion that asserts that a class has exactly the specified (declared) fields.

The signature can of course be discussed, I am more interested in the functionality :)

#### Example

```java
class MyClass {
   public String fieldOne;
   public String fieldTwo;
   private String fieldThree;
}

//pass
assertThat(MyClass.class).hasFieldsExactly("fieldOne", "fieldTwo");
assertThat(MyClass.class).hasDeclaredFieldsExactly("fieldOne", "fieldTwo", "fieldThree");

//fail
assertThat(MyClass.class).hasFieldsExactly("fieldOne");
assertThat(MyClass.class).hasDeclaredFieldsExactly("fieldOne", "fieldThree");
```

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Ok with that but just putting `Exactly` after `has`, ex `hasExactlyFields`

**Comment by joel-costigliola** [comment]
I'm currently integrating the PR but I'm gonna rename the assertions `hasOnlyFields` and `hasOnlyDeclaredFields` to be consistent with iterable assertions where `containsExactly` checks the order of the given elements whereas `containsOnly` does not.

**Comment by joel-costigliola** [comment]
I also a minor bug in the error message use (`shouldHaveExactlyDeclaredFields`) where actual fields where passed instead of expected ones. I discovered that is by adding some examples in assert-examples, making them fail and looking at the error message. Adding examples puts you in the user's shoes - always a good thing.

**Comment by filiphr** [comment]
@joel-costigliola thanks for integrating it. I have no problem with the renaming of the assertions. I can do that as well if you want to. I have no problem in updating my PR. 

Sorry for the bug...

**Comment by joel-costigliola** [comment]
@filiphr I will finish the work, it's not much, thanks for the PR, always appreciated.

**Comment by filiphr** [comment]
@joel-costigliola no problem, glad I could help :)
