### ISSUE TITLE
Feature Request: AbstractIterableAssert.containsAny

### ISSUE THREAD

**Issue by lbilger** [joel-costigliola/assertj-core#954]
#### Summary
I couldn't find an easy way to assert that an Iterable contains any of a given set of values.

#### Example

```java
		// passes:
		assertThat(Arrays.asList("foo")).containsAny("foo", "bar");
		assertThat(Arrays.asList("bar")).containsAny("foo", "bar");
		assertThat(Arrays.asList("foo", "bazz")).containsAny("foo", "bar");
		
		// fails:
		assertThat(Arrays.asList("bazz")).containsAny("foo", "bar");
```

#### Java 8 specific ?
No
* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
Indeed there is no easy way of doing this, a condition is the simplest option.

I would simply rename the assertion to `containsAnyOf`.
