### ISSUE TITLE
doesNotHaveElementsOfType

### ISSUE THREAD

**Issue by mg6maciej** [joel-costigliola/assertj-core#962]
#### Summary

Similiar to https://github.com/joel-costigliola/assertj-core/issues/202, I suggest adding `doesNotHaveElementsOfType(Class<*>)`

#### Example

```kotlin
assertThat(list).doesNotHaveElementsOfType(MyClass::class.java)
```

#### Java 8 specific ?

NO

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
yep, does it come from a real life use case  ?

**Comment by mg6maciej** [comment]
I have used `doNotHave` as a workaround in my code.
```
assertThat(/**/).doNotHave(Condition(Predicate { it is MoveByTrain }, "MoveByTrain")) 
assertThat(/**/).doNotHave(Condition(Predicate { it is MoveByRoad || it is MoveBySea }, "MoveByRoad or MoveBySea"))
assertThat(/**/).doNotHave(Condition(Predicate { it is Trade }, "Trade")) 
```
but I would prefer to have:
```
assertThat(/**/).doesNotHaveElementsOfType(MoveByTrain::class.java)
assertThat(/**/)
        .doesNotHaveElementsOfType(MoveByRoad::class.java)
        .doesNotHaveElementsOfType(MoveBySea::class.java)
assertThat(/**/).doesNotHaveElementsOfType(Trade::class.java)
```
with better error output. `doNotHave`'s error is weird in case of just checking type.

Maybe there is a function I could use, but I just didn't find?

**Comment by joel-costigliola** [comment]
We will rename that to `doesNotHaveAnyElementsOfType` to be consistent with `doesNotContainAnyElementsOf`.
