### ISSUE TITLE
Introduce @Beta annotation

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#964]
#### Summary

The idea is to warn users that the feature may change in the future.

**Comment by PascalSchumacher** [comment]
added with https://github.com/joel-costigliola/assertj-core/commit/60afa15204e18269a7abbfd279418b67cbfdf05a

**Comment by filiphr** [comment]
Good idea with the annotation. It leaves you more space to evolve features.

Might be worthwhile looking into https://github.com/apiguardian-team/apiguardian. It's what the JUnit team is using for the JUnit 5 APIs

**Comment by joel-costigliola** [comment]
@filiphr I had a look at apiguardian, I decided to go a simpler way but if the need arises we will be moving towards an apiguardian like annotation.

**Comment by filiphr** [comment]
Sorry didn't know that you had a look at it. 

I think apiguardian would be more interesting once there is some tooling and support from IDEs out there.
