### ISSUE TITLE
New join condition which will check all condition even if one fail

### ISSUE THREAD

**Issue by gauee** [joel-costigliola/assertj-core#967]
#### Summary
Sometimes we would like examine the object under multiple condition. To avoid code duplicates I would like to have a group of conditions which should be match for my test case. I think that beneficial will be to use the join condition which will check all of my condition and as a description in fail case show only the descriptions of condition which in real failed.

#### Example
```java
assertThat(createRqCaptor.getValue())
                .has(allOf(
                        new Condition<>(rq -> rq.getRaw(), "CreateRq have to set the raw on true"),
                        new Condition<>(rq -> 1000 == rq.getTtlMillis(), "CreateRq have to set the ttlMillis"),
                        new Condition<>(rq -> "testKey".equals(rq.getKey()), "CreateRq have to set the same object key")
                ));
```
```
Expecting:
 <CreateRq[key=testKey,ttlMillis=1000,data=Data[stringData=<null>,byteData=<null>,anyData=<null>],objectType=<null>,raw=false,version=<null>]>
to have:
 <all of:<[CreateRq have to set the raw on true]>>

```

Are you interested in such solution? If yes, I will prepare a pull request with such additional condition.

**Comment by joel-costigliola** [comment]
Would using [satisfies](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractAssert.html#satisfies-java.util.function.Consumer-) be a good match for what you need ?

```java
// second constructor parameter is the light saber color
Jedi yoda = new Jedi("Yoda", "Green");
Jedi luke = new Jedi("Luke Skywalker", "Green");

Consumer<Jedi> jediRequirements = jedi -> {
  assertThat(jedi.getLightSaberColor()).isEqualTo("Green");
  assertThat(jedi.getName()).doesNotContain("Dark");
};

// assertions succeed:
assertThat(yoda).satisfies(jediRequirements);
assertThat(luke).satisfies(jediRequirements);
```

**Comment by gauee** [comment]
Please correct me if I am wrong but this is still asserts lazy. I do not have much experience with satisfies.
My point is to have such mechanism to perform the eager asserts with appropriate assertError message.
Let me present what I expecting exactly:
```java
        Consumer<Jedi> jediRequirements = jedi -> {
            assertThat(jedi.getLightSaberColor()).isEqualTo("Green");
            assertThat(jedi.getName()).doesNotContain("Dark");
        };

        assertThat(new Jedi("Dark jedi", "Red")).satisfies(jediRequirements);
```

returns:
`org.junit.ComparisonFailure: 
Expected :"Green"
Actual   :"Red"`

expected:
`org.junit.ComparisonFailure: 
Expected :"Green"
Actual   :"Red"`
`java.lang.AssertionError: 
Expecting:
 <"Dark jedi">
not to contain:
 <"Dark"> `

**Comment by joel-costigliola** [comment]
Sorry I did not get your point, if you want to gather all errors and mot fail at the first one, you can use [soft assertions](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#soft-assertions).

**Comment by gauee** [comment]
Oh yeah! This is what I am looking for.
Thank you very much!
