### ISSUE TITLE
Java 9 and shading cglib

### ISSUE THREAD

**Issue by sormuras** [joel-costigliola/assertj-core#968]
#### Summary

The JUnit 5 team is test-driving on Java 9 the coming days (and weeks).

Our current build fails because of a "NoClassDefFoundError" pointing to the shaded **cglib** in AssertJ 3.6.2. 

We had a similar problem with the Gradle Shadow Plugin using an out-dated ASM version to move/shade entities. It was related to https://bugs.openjdk.java.net/browse/JDK-8174868

#### Log

```java
  JUnit Jupiter:ExceptionHandlingTests:checkedExceptionInTestMethodIsRegistered()
    MethodSource [className = 'org.junit.jupiter.engine.ExceptionHandlingTests', methodName = 'checkedExceptionInTestMethodIsRegistered', methodParameterTypes = '']
    => java.lang.NoClassDefFoundError: Could not initialize class org.assertj.core.internal.cglib.proxy.Enhancer
```
https://travis-ci.org/junit-team/junit5/builds/219055181#L952

#### Solution?

Update Shade plugin you use to shade cglib and asm?

I'll try to generate a better stacktrace to pin-point the underlying error causing initialization of class `org.assertj.core.internal.cglib.proxy.Enhancer` to fail.

**Comment by joel-costigliola** [comment]
@sormuras thanks for reporting this, @PascalSchumacher has spiked using Java 9 in AssertJ, he might have more feedback than me on the subject.
We have upgraded in master cglib to 3.2.5 and asm to 5.2 which I believe are the latest versions, @sormuras  would you mind giving a try with it (you need to build AssertJ, a simple `mvn install` should be enough to do so).
@PascalSchumacher  can  you help @sormuras ?

**Comment by joel-costigliola** [comment]
BTW, we are planning to release the next version of AssertJ 3.7.0 at the end of the month.

**Comment by sormuras** [comment]
Used jitpack.io to build your core "master-SNAPSHOT" artifact. Let's see what happens: https://travis-ci.org/junit-team/junit5/builds/219085282

3.7.0 soon sounds great!

**Comment by PascalSchumacher** [comment]
I think it has the same cause (https://github.com/cglib/cglib/issues/94) as https://github.com/joel-costigliola/assertj-core/issues/927 which was fixed by updating to cglib `3.2.5`.

**Comment by joel-costigliola** [comment]
I guess we can close this one then, @sormuras ?

**Comment by sormuras** [comment]
Sure. Looking forward to switch the dependency to AssertJ 3.7.0, soon.
