### ISSUE TITLE
Add Checks.checkThat() returning boolean

### ISSUE THREAD

**Issue by diogoko** [joel-costigliola/assertj-core#972]
#### Summary

Many of the assertions are useful outside the scope of testing. I propose a new `Checks` class with a signature similar to the current `Assertions` class.

#### Example

```java
import static org.assertj.core.api.Checks.checkThat;

if (checkThat("test", a -> a.doesNotContain("A"))) {
    ...
}
```

#### Possible implementation

```java
public static boolean checkThat(String actual, Consumer<AbstractCharSequenceAssert> callback) {
    try {
        callback.accept(assertThat(actual));
        return true;
    } catch (AssertionError e) {
        return false;
    }
}
```

**Comment by joel-costigliola** [comment]
I need to give it some thoughts as AssertJ was intended for testing but it is an interesting suggestion.

**Comment by filiphr** [comment]
@joel-costigliola as an additional idea for thought would be that this can be used well with Mockito's own [ArgumentMatcher](https://github.com/mockito/mockito/blob/c8f07c70a2e2be4714b4fc6a1a7f6e8b473b3bac/src/main/java/org/mockito/ArgumentMatcher.java) and will still be used for testing purposes :). One can benefit a lot from the power of the AssertJ assertions when doing verification. I know at least me personally would have benefited from it in the last few weeks :).

**Comment by joel-costigliola** [comment]
fair enough, I'm ok to add this.

**Comment by filiphr** [comment]
By the way I saw that in the new release 2.7.0 / 3.7.0 there will be Hamcrest [`AssertionMatcher`](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/matcher/AssertionMatcher.java).

**Comment by joel-costigliola** [comment]
I'm trying to find a better name, I don't find natural for `checkThat` to return a boolean (if the check fails I kinda expect an exception to be raided as in [guava preconditions](https://github.com/google/guava/wiki/PreconditionsExplained).

I haven't got any great naming ideas yet ...

**Comment by diogoko** [comment]
The best alternative I could find until now was `testThat`. Maybe `evaluate` or `eval` or `evaluateIf`.

**Comment by TheRealMarnes** [comment]
Isn't it better to use hamcrest for such things? It's specifically designed to be a matching library, in test and production code. Adding a non-test usage paradigm to assertj feels like feature creep IMO, especially with assertj and hamcrest offering 99% the same assertions anyway. Hamcrest is also built on smply returning a boolean, instead of first throwing an Error and then having to catch it right away again, which is kind of a code smell. As a user of both I got the feeling assertj uses hamcrest for most of its assertions anyway, though I may be wrong there.

**Comment by filiphr** [comment]
>As a user of both I got the feeling assertj uses hamcrest for most of its assertions anyway, though I may be wrong there.

You are completely wrong here (I don't mean it in a rude way). AssertJ has it's own way of doing the checks and uses 0 Hamcrest assertions internally.

In my opinion a big plus and advantage of AssertJ is it's fluent style of asserting. With Hamcrest you need to know what you want to do, with AssertJ you get autocomplete support based on the type you are asserting out of the box.

One reason why a support for something like this in AssertJ is in https://github.com/joel-costigliola/assertj-core/issues/972#issuecomment-293828281. It can help quite a lot with doing more complex Mockito matchers for example. And of course still in the context of testing, I don't mean for production usage. With it's current implementation AssertJ is not intended for use in production code.

**Comment by TheRealMarnes** [comment]
@filiphr I see, fair enough.

**Comment by JosephYao** [comment]
For mockito, I just created a simple helper method as below to use any assertJ method as an ArgumentMatcher.

```java
    public static <T> T should(Consumer<T> assertion) {
        return argThat(argument -> {
            assertion.accept(argument);
            return true;
        });
    }
```

And, here is a sample test using this helper.
```java
    @Test
    public void no_exist_order_should_insert() {
        OrderModel model = mock(OrderModel.class);
        OrderController orderController = new OrderController(model);

        orderController.save(new Order() {{
            setId(91);
            setAmount(100);
        }});

        verify(model).save(
                should(order -> assertThat(order).isEqualToComparingFieldByField(new Order() {{
                    setId(91);
                    setAmount(100);
                }})));
    }
```

So, I suggest this as a simple alternative to creating all those "testThat" methods. Just my 2 cents.

**Comment by joel-costigliola** [comment]
@JosephYao the method `should` depends on Mockito right? 
If that is the case it can't be added as AssertJ policy is not to depend on anything.

**Comment by JosephYao** [comment]
Yes, you're right. As I suggested, the method should is quite easy to implement in any code base. So, no need to add anything to AssertJ then.
