### ISSUE TITLE
suggestion: catch two common mistakes

### ISSUE THREAD

**Issue by alokmenghrajani** [joel-costigliola/assertj-core#979]
#### Summary
I have noticed two common mistakes people make when using Assertj. Both these mistakes can be caught using static analysis, but it wouldn't hurt if the library caught them at runtime.

The first mistake is to call `.equals` instead of `.isEqualTo`. The second mistake is to write code such as `assertThat(some boolean expression)` and forgetting the `isTrue()` call.

In AbstractAssert, the code could maintain a boolean flag checking if the object has been "consumed" by one of the `isFoo` methods. In the destructor, the code could check the flag and throw an exception.

What do you think?

**Comment by joel-costigliola** [comment]
`equals` is deprecated on Assert objects.
the second problem is trickier, we have a [findbugs rule](http://joel-costigliola.github.io/assertj/assertj-core.html#faq-incorrect-api-usage) to detect that but if you have a better solution I'm happy to hear it.

**Comment by joel-costigliola** [comment]
@alokmenghrajani any thoughts ?

**Comment by filiphr** [comment]
For the second problem something like a JUnit Rule (I don't know the alternative for TestNG) could work. The only thing is that all the assert methods will need to register themselves that they have been invoked (or have some sort of spy that will track the called methods), the registrations can be done in the constructor of the root assert.

**Comment by alokmenghrajani** [comment]
The findbugs rule works for me on some codebases. I noticed it didn't catch things in travis, I'll setup a test repo and share a concrete example.

The JUnit Rule approach seems like a good idea. The overhead of having every assert method register itself sounds like it would be something minimal.

**Comment by alokmenghrajani** [comment]
https://github.com/alokmenghrajani/assertj-test shows a repo where `mvn test findbugs:check` doesn't run findbugs on the test files. It catches any issues in `App.java`, but not `AppTest.java`. Any idea why?

**Comment by PascalSchumacher** [comment]
@alokmenghrajani The findbugs check was added in assert-j 2.5.0/3.5.0 (additional checks will be done in 2.7.0/3.7.0 see: https://github.com/joel-costigliola/assertj-core/issues/914 https://github.com/joel-costigliola/assertj-core/commit/ff53cee098dc2f421bea0aae58875ab991f185a1), but you example project uses 3.0.0.

**Comment by alokmenghrajani** [comment]
I poked around a little with finalizers and JUnit, and I couldn't find any way to write an object that can fail the current test. Throwing an exception in the finalizer doesn't seem to do anything. Hooking into JUnit using a RunListener requires having the current JUnitCore object.

Findbugs works great with the caveat that it needs to be setup right :)

Feel free to close this task unless you can think of some clever way to do this at runtime?

**Comment by filiphr** [comment]
With JUnit [`@Rule`](http://junit.org/junit4/javadoc/4.12/org/junit/Rule.html) you can do what you are trying to do. Have a look at the [`ExpectedException`](https://github.com/joel-costigliola/assertj-core/blob/master/src/test/java/org/assertj/core/test/ExpectedException.java) from assertj.

**Comment by PascalSchumacher** [comment]
As this problem is easily solved by using static code analysis tools, I'm closing this issue.
