### ISSUE TITLE
Force usage of recursive comparator for a given type

### ISSUE THREAD

**Issue by ylegat** [joel-costigliola/assertj-core#980]
#### Summary
Hello !

I know that the call to _usingRecursiveFieldByFieldElementComparator_ does not use the recursive comparator on objects having a custom _equals_ method. I also know that it is possible to specify a custom comparator of a given type. So here is my question : is there a way to force the usage of the recursive comparator internally used by AssertJ for attributes of a given type ?

#### Example
A case where this can be useful :
* let _Child_ a type having a _Date_ attribute and implementing _equals_;
* let _Parent_ a type having a _Child_ attribute as well as some other attributes;
* let a _Date_ comparator, _dateComparatorIgnoringMillis_, that is comparing two dates ignoring milliseconds;

If we want to compare two instances of _Parent_ and disregard the millisecond precision of the date, we are kind of blocked. With the following assertion, _dateComparatorIgnoringMillis_ will not be used:
```java
assertThat(parent)
.usingComparatorForElementFieldsWithType(dateComparatorIgnoringMillis, Date.class)
.usingRecursiveFieldByFieldElementComparator()
.isEqualTo(new Parent(new Child(aDate)));
```

Of course, there is the possibility to use the _extract_ feature in order to write an assertion on the child directly, but it is not very convenient as it requires to first compare the _Parent_ instances ignoring their child and then compare their children.

**Comment by joel-costigliola** [comment]
You can try [`usingComparatorForFields`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectAssert.html#usingComparatorForFields-java.util.Comparator-java.lang.String...-) for the parent date.

**Comment by ylegat** [comment]
Well, maybe I did not understood your answer but that's the issue : the date field is in _Child_, not _Parent_ ; and that's way it would be nice to say "use your recursive comparator for the child field", given that this recursive comparator has been configured to use a dedicated comparator for dates.

**Comment by PascalSchumacher** [comment]
I think the best you can do at the moment is this (not tested and not really advisable, as it uses assertj internal classes):

```java
TypeComparators typeComparators = new TypeComparators();
typeComparators.put(Date.class, dateComparatorIgnoringMillis);
assertThat(parent)
    .usingComparatorForElementFieldsWithType(
         new RecursiveFieldByFieldComparator(Collections.EMPTY_MAP, typeComparators), Child.class)
    .isEqualToComparingFieldByFieldRecursively(new Parent(new Child(aDate)));
```

**Comment by ylegat** [comment]
Haha actually this is already my workaround :)

**Comment by ylegat** [comment]
I just wanted to be sure that there was no other solution. Ok I'll try to work on a better way to do it by submitting a pull request when I have some time. Thanks !

**Comment by joel-costigliola** [comment]
Sorry I did not understand the problem.
I would try register a `Child` comparator that deals with comparing Child's date appropriately, I'm not completely sure it will work but that is worth trying.

**Comment by PascalSchumacher** [comment]
A possible method name for this feature could be `usingRecursiveFieldByFieldComparisonForTypes(class...)`.

E.g.:
``` java
assertThat(parent)
  .usingRecursiveFieldByFieldComparisonForTypes(Child.class)
  .usingComparatorForType(Date.class, dateComparatorIgnoringMillis)
  .isEqualToComparingFieldByFieldRecursively(new Parent(new Child(aDate)));
```

**Comment by ylegat** [comment]
@joel-costigliola , unfortunately in my real case scenario I've got a lot of classes containing dates that I want to compare with the same custom comparator. So it would be more convenient to just relay on the field by field comparator, properly set with a custom comparator for the Date type, instead of declaring for each class a custom comparator. In this regard, @PascalSchumacher proposal is closer to what I have in mind.

**Comment by joel-costigliola** [comment]
I need to think more about it but I like @PascalSchumacher suggestion.

**Comment by ylegat** [comment]
@joel-costigliola, do you think I can help and work on a pull request on that matter ? Or is the topic related to a more global refactoring you have in mind (I'm thinking of what you said about #982) ?

**Comment by joel-costigliola** [comment]
closing this in favor of #1002
