### ISSUE TITLE
`ComparingOnlyGivenFields` & `IgnoringGivenFields` forms of `isEqualToComparingFieldByFieldRecursively()`

### ISSUE THREAD

**Issue by derekm** [joel-costigliola/assertj-core#982]
I would like to whitelist or blacklist fields when using `isEqualToComparingFieldByFieldRecursively`.

**Comment by joel-costigliola** [comment]
Good idea. 

At this point I think we should try to isolate an API for recursive comparison that is clearly separated from the other assertions, for example if we introduce `comparingOnlyFields` and `excludingFields` for object assertions but it only makes sense for recursive comparison, not the other object assertions, it's making the object assertions API more difficult to use.

**Comment by joel-costigliola** [comment]
@derekm, @ylegat I have closed in favor of https://github.com/joel-costigliola/assertj-core/issues/1002 which I would like to have your opinion on.
