### ISSUE TITLE
"contains" feature in AssertJ not showing the right results (Actual comes under Expecting, and Expected comes under Actual)

### ISSUE THREAD

**Issue by JaspalAujla** [joel-costigliola/assertj-core#983]
#### Summary
contains feature in AssertJ not showing the right result.
Content which should reflect in "Expecting" is displaying under "to contain", however the content which should reflect in "to contain" is displaying under "Expecting"

#### Example
```java
assertThat(actual).contains(expected);
```

Please refer below image for more clarification. I have written 2 tests. 1st test is with "isEqualTo" which is showing right results. However, 2nd test is with "contains" which is showing wrong results:

![assertj_issue](https://cloud.githubusercontent.com/assets/17103120/25731190/4b69890a-3198-11e7-8112-c7dfc4631113.PNG)

**Comment by joel-costigliola** [comment]
The `contains` checks whether the actual String content includes/contains the given expected String, in that regard the error is relevant, in your example `"actual text"` does not contain `"expected text"` and thus the `contains` assertion fails.

The javadoc shows some code examples:
```java
 assertThat("Gandalf the grey").contains("alf");
 assertThat("Gandalf the grey").contains("alf", "grey");
```

Does that make sense ? 

See also `contains `See https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#contains-java.lang.CharSequence-

**Comment by JaspalAujla** [comment]
Your explanation is absolutely fine.

But the point is, under Expecting tag, the expected text should come, not actual.
For example:
Expecting<"expected text">
if you would have Expecting <"actual text"> that is wrong.
Expecting mean what we are expecting, we can not display actual in it.

We can display it like below as well, same like "isEqualTo"
expected <"expected text"> but contains <"actual text">

**Comment by joel-costigliola** [comment]
I disagree, `expecting` is used in the sense of expecting something (actual) to fulfill some condition, like "I'm expecting my teenager son to come back before 11pm".

If it was `expected` you would have a point but it is `Expecting`.

I also find `expected <"expected text"> but contains <"actual text">` to be confusing.

**Comment by JaspalAujla** [comment]
Let's take your example:
Expecting <"my teenager son to come back before 11pm"> so, this is what you are expecting, not actual.
Actual would be what the actual output contains:
contains <"my teenager son to come back before 11pm"> here test will pass
contains <"my teenager son to come back before 10pm"> here test will fail
contains <"my teenager son to come back before 9pm"> here test will fail

Moreover, to make the library consistent, you have to manage consistency:
It is so confusing that at 1 side (isEqualTo) where Expected means what is expected, and at another side (contains) where Expecting means what is actual.
For example:
According to you, below is right in the case of "isEqualTo" but wrong in the case of "contains"
expected <"expected text"> but was <"actual text">
Expecting <"expected text"> but contains <"actual text">

So, in the case of "contains" you prefer:
Expecting <"actual text"> but contains <"expected text">

Finally, in a nutshell, a library (AssertJ) user should have to keep in mind that when he/she will use "isEqualTo" then expected means "expected" and when he/she use "contains" then Expecting means "actual".

Hope, you would understand what I want to explain.

**Comment by joel-costigliola** [comment]
Sorry I don't really understand, to me it is like you are saying that `expected` and `expecting` means the same thing but it's not.

I do not prefer `Expecting <"actual text"> but contains <"expected text">` that is not what AssertJ returns moreover it does not make sense grammatically, I prefer `Expecting <"actual text"> to contain <"expected text"> ` where `Expecting` is the word that starts describing the expectation that was not met.

**Comment by JaspalAujla** [comment]
I understand your explanation, but in this way you are taking your implementations away from testing frameworks JUnit or TestNG.
I also understand the way you want to manage your outcomes in grammatically understandable English. But, if you want to prefer this way then you have to implement it every where.

I noticed, in the case of "isEqualTo", you are using ComparisonFailure from junit:
expected:<"[expected] text"> but was:<"[actual] text">

However, for other type of comparisons you designed your outputs. Consequently, your output structure is inconsistent in terms of "isEqualsTo" and other comparisons, which creates confusion.

Additionally, when we talk about testing world, software testing or ISTQB syllabus, Testers, Developers and Business Analyst have a mind set about "Expected/Expecting" keyword that is only what we are expecting or want to see as an output.

That is why the way you are using "Expecting" keyword to show actual outcome is really confusing.

**Comment by joel-costigliola** [comment]
To answer your different points:

- AssertJ (and previously Fest Assert) were created because of the poor assertions support in JUnit and to less extent TestNG, your argument about AssertJ implementations being away from these frameworks is not compelling to me.
- Since `isEqualTo` error message is built from JUnit's ComparisonFailure, I can't change it.
- As for the ISTQB thing, can you point me where they are recommending `Expected` over `Expecting` or whatever assertions recommendations ?

So sum up, I note the inconsistency in the error messages but I'm still not convinced it is a problem, if more users complain about `Expecting` style in error messages, I will consider changing them.

**Comment by JaspalAujla** [comment]
I am not saying that ISTQB "recommending Expected over Expecting or whatever assertions recommendations". I just wanted to explain how Developer, Tester and BA taking Expected word in first impression, and as Expecting looks similar to this, which creates confusion.

FYI, I know some professionals even my colleagues who find different ways to see the results (outcomes) according to what the want to see, but not prefer to report their concern to library owner.
For example, 1 of my colleagues suggested me below:
![assertjoverriding](https://cloud.githubusercontent.com/assets/17103120/25876456/8a0a7430-3571-11e7-819a-160f565cd97e.png)

Sorry, if I am wasting your much time. But it is just a discussion.

If you prefer then please close this issue. Your explanation is also acceptable.

**Comment by joel-costigliola** [comment]
I'm going to close this issue as I'm not convinced to move away from `Expecting` style message.
Having said that, we are always keen to improve error messages so if the `reformatTableResults` is really better than the default error message, I would be happy to use it, feel free to open a new issue for that if relevant.
