### ISSUE TITLE
Double.NaN isCloseTo always true

### ISSUE THREAD

**Issue by gn6996** [joel-costigliola/assertj-core#984]
#### Summary

AssertJ (3.6.2) returns true, if checking double is close to NaN. 
[StackOverflow](http://stackoverflow.com/questions/43848512/double-nan-iscloseto-double-value-returns-true)
#### Example

```java
assertThat(Double.NaN).isCloseTo(0.007, Percentage.withPercentage(0.1));
```

**Comment by PascalSchumacher** [comment]
Thanks for reporting this bug also occurs in 2.7.0/3.7.0!

**Comment by joel-costigliola** [comment]
Good catch ! Thanks for reporting it.

**Comment by joel-costigliola** [comment]
We will do a bugfix release in the next weeks to address that.

**Comment by PascalSchumacher** [comment]
I have started to work on a pull request for this. Looks like there are also bugs related to `Double.NEGATIVE_INFINITY` and `Double.POSITIVE_INFINITY`.

**Comment by PascalSchumacher** [comment]
@gn6996 AssertJ versions 2.8.0 / 3.8.0 with the fix for this have just been released. :smile:
