### ISSUE TITLE
isBetween for Instant - works in AssertJ 3.6.2, broken in 3.7.0

### ISSUE THREAD

**Issue by chbrehm** [joel-costigliola/assertj-core#986]
#### Summary
Updating AssertJ Core from 3.6.2 to 3.7.0 broke compilation of my project. It turns out I used "isBetween" assertions for java.time.Instant. That works in 3.6.2 because Instant is Comparable, and "isBetween" is provided in AbstractComparableAssert. After updating to 3.7.0 however, AbstractInstantAssert is used for Instant, which doesn't provide "isBetween".

#### Example

```java
Instant timestamp = ...;
Assertions.assertThat(timestamp).isBetween(Instant.now().minusSeconds(1), Instant.now());
```
The example compiles with AssertJ Core 3.6.2, but doesn't compile with 3.7.0.

#### Java 8 specific ?

No

**Comment by joel-costigliola** [comment]
Thanks for reporting this ! We will fix that quickly and do a bugfix release in the next weeks.

**Comment by joel-costigliola** [comment]
We will add `isBetween` and `isStrictlyBetween` to all temporal assertions

**Comment by joel-costigliola** [comment]
Fixed in https://github.com/joel-costigliola/assertj-core/commit/5d51ca9dfd36d9c1d885e08a5f592cc9c90a0682.

**Comment by PascalSchumacher** [comment]
@chbrehm AssertJ 3.8.0 which added `isBetween` and `isStrictlyBetween` to all temporal assertions was just released. :smile:

**Comment by chbrehm** [comment]
Thanks for the quick fix and the feedback.
