### ISSUE TITLE
Comparables instance should not be shared

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#991]
`Comparables.instance()` returns the same  instance which is used in a few places,  this is not good as `Comparables` is stateful (you can set the comparisonStrategy) .

**Comment by joel-costigliola** [comment]
Same applies for `Objects`

**Comment by PascalSchumacher** [comment]
If I'm not mistaken it is not possible to change the comparison strategy of the `instance`, but you can construct other instances with different comparison strategies. So for code simplicity it would be good remove it anyway.

There are also other classes similar to `Comparables` and `Objects` e.g. `Longs`, `Integers`...
