### ISSUE TITLE
Warning:(34, 17) java: unchecked method invocation: method assertThat in class org.assertj.core.api.Assertions is applied to given types   required: java.util.List<? extends ELEMENT>   found: java.util.List

### ISSUE THREAD

**Issue by jschneider** [joel-costigliola/assertj-core#993]
Problematic code:

      List<? extends String> strings = Arrays.asList("a", "b", "c");
      assertThat(strings).hasSize(3 );

When compiling that code, I get a warning:

Warning:(34, 17) java: unchecked method invocation: method assertThat in class org.assertj.core.api.Assertions is applied to given types
  required: java.util.List<? extends ELEMENT>
  found: java.util.List

IntelliJ Idea is also warning me about that code. Is there a way to work around that issue?

**Comment by joel-costigliola** [comment]
I was not able to reproduce this either from eclipse or maven either in 2.7.0 or 3.7.0.
Can you give more information about your environment ?

Mine:
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T07:39:06+12:00)
Maven home: /home/joel/prog/apache-maven-3.5.0
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: /home/joel/prog/java/jdk1.8.0_112/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-77-generic", arch: "amd64", family: "unix"
```

**Comment by PascalSchumacher** [comment]
I guess @jschneider wasn't using `2.7.0` /  `3.7.0` but an older version. Otherwise please reopen. Thanks!

**Comment by velzganesh** [comment]
I am also able to reproduce this issue.
![image](https://user-images.githubusercontent.com/5512477/28925099-7e0510b6-7881-11e7-9442-8e25e2e8d2ac.png)

In addition to this warning, getting error on performing a check as below:
assertThat(List<Animal>).contains(new Dog()); //where Animal is an Interface implemented by Dog

**Comment by velzganesh** [comment]
Reproducible on both Eclipse and IntelliJ

![image](https://user-images.githubusercontent.com/5512477/28926403-506fd718-7885-11e7-9071-9b59070e4c99.png)

**Comment by joel-costigliola** [comment]
@velzganesh  I still can't reproduce it with the your Animal / Dog suggestion: 

![image](https://user-images.githubusercontent.com/382613/28966710-d8548610-796b-11e7-80db-330f66660fe5.png)

**Comment by jschneider** [comment]
Okay guys, I have created a repository to reproduce this issue: https://github.com/jschneider/assertj-core-issue-993
Unfortunately I can no longer get the compiler warning. Don't ask me why...

Now it is just IntelliJ IDEA that is warning me. The inspection that produces the warning can be found under:
- Java - Compiler issues - Unchecked warning.

But since the compiler is not warning me, it might be a false positive?

**Comment by joel-costigliola** [comment]
@jschneider I'll give a try to your repo to see how it goes.
