### ISSUE TITLE
Feature Request: hasSameHashCodeAs

### ISSUE THREAD

**Issue by Riggs333** [joel-costigliola/assertj-core#995]
#### Summary

Provide a (shortcut) way to assert that the hashCode of two objects are equal.

#### Example

An alternative way to write
```java
        assertThat("foo".hashCode()).isEqualTo("foo".hashCode());
```

could be
```java
        assertThat("foo").hasSameHashCodeAs("foo");
```

While this example uses `String` it should work with any type of object, as every `Object` has a `hashCode`.

#### Java 8 specific ?

NO

**Comment by joel-costigliola** [comment]
Good idea, do you want to contribute it ?

**Comment by Riggs333** [comment]
Yeah, sure. :-) I would be honoured.
But I need a little time.
Will try to get something done until the end of the week.

**Comment by joel-costigliola** [comment]
@Riggs333 take your time, no pressure here, we have no timetable for 2.9.0 yet.
